### ISSUE TITLE
TreeTable: invoking column sort causes null pointer exception

### ISSUE THREAD

**Issue by lbbishop** [primefaces/primefaces#10060]
### Describe the bug

Clicking a sortable column in PrimeFaces TreeTable causes NPE:
```
Apr 24, 2023 8:15:52 AM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.NullPointerException: Cannot invoke "org.primefaces.model.TreeNode.getRowKey()" because the return value of "org.primefaces.model.TreeNode.getParent()" is null
java.lang.NullPointerException: Cannot invoke "org.primefaces.model.TreeNode.getRowKey()" because the return value of "org.primefaces.model.TreeNode.getParent()" is null
        at org.primefaces.component.treetable.TreeTableRenderer.encodeNode(TreeTableRenderer.java:528)
        at org.primefaces.component.treetable.TreeTableRenderer.encodeNodeChildren(TreeTableRenderer.java:847)
        at org.primefaces.component.treetable.TreeTableRenderer.encodeNodeChildren(TreeTableRenderer.java:834)
        at org.primefaces.component.treetable.TreeTableRenderer.encodeTbody(TreeTableRenderer.java:514)
        at org.primefaces.component.treetable.feature.SortFeature.encode(SortFeature.java:110)
        at org.primefaces.component.treetable.TreeTableRenderer.encodeEnd(TreeTableRenderer.java:118)
```

Reproducer is provided.

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/11305279/primefaces-test.zip)

### Expected behavior

Clicking sortable column should sort nodes based on sort criteria.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.0

### Theme

NA

### JSF implementation

Mojarra

### JSF version

4.0.0

### Java version

17

**Comment by melloware** [comment]
Looks like it might be a Mojarra issue.

`mvn clean jetty:run -Pmojarra40` **FAILS**

`mvn clean jetty:run -Pmyfaces40` **PASSES**

**Comment by melloware** [comment]
Even with MyFaces 4.0 its kinda slow to react but does end up sorting.

**Comment by melloware** [comment]
Its also strange its not happening on the Showcase because your code looks identical to the Showcase?

**Comment by lbbishop** [comment]
It happens using every template (ultima etc.) demo application on the primefaces site.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
