### ISSUE TITLE
p:repeat component may cause random exception if var has the same name on two components

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1031]
Hi, i dont know how this happend, or how i can reproduce it but it did, after i tried the new p:repeat component

(using p repeat to iterate trough a collection, in this case it is not inside a different tag)

```

<p:repeat var="item" value="#{.............items}">
            ........
        </p:repeat>

```

then somewhere deeper in the tree the same var name is used is used 

```
<p:dataTable value="#{.......other class...items}" var="item">
......
</p:dataTable>

```

```
The class 'x.x.x.x.x.ClassOfFirstItemCollection' does not have the property 'propertyOfSecondCollection'.
    at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111)

```

So it seems that item still is referencing the first collection.

After reverting to ui:repeat for the first, the error doesnt happen again

In case i find out something new i will post it

**Comment by kukel** [comment]
maybe that is one of the other 'reversed' problems with ui:repeat and PF is doing it 'correctly' (EL has no 'scoping' afaik)

**Comment by cnsgithub** [comment]
I was able to create a MWE to reproduce the issue. Multiple things have to be done in Order to reproduce.
- Having a p:outputPanel around the second place where var is used (here a dataTable)
- Using the var item inside a "rendered" attribute
- Calling an action
- Removing the p:outputPanel 'fixes' the issue. However it would still be nice to know why it happens

XHTML

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:p="http://primefaces.org/ui" xmlns:pm="http://primefaces.org/mobile" xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:head>
        <title>TestPage</title>
    </h:head>
    <h:body>
        <p:repeat var="item" value="#{issueBean1031.list1}">
                #{item.prop1}
        </p:repeat>

        <p:outputPanel id="content" layout="block">

                <p:dataTable id="dt-id" value="#{issueBean1031.list2}" var="item">
                    <p:column rendered="#{item.prop2 == 'f'}">
                        #{item.prop2}
                    </p:column>
                </p:dataTable>

            <p:commandButton value="Action!" action="#{issueBean1031.doSomething()}" update="content" />

         </p:outputPanel>

    </h:body>
</html>




```

Java-Stuff, 2 Classes to make two different collections and the bean

```
 public class IClass1 {
    private String prop1;
    public IClass1(String name){
        this.prop1 = name;
    }
    public String getProp1() {
        return prop1;
    }
    public void setProp1(String prop1) {
        this.prop1 = prop1;
    }
}
public class IClass2 {
    private String prop2;
    public IClass2(String name){
        this.prop2 = name;
    }
    public String getProp2() {
        return prop2;
    }
    public void setProp2(String prop2) {
        this.prop2 = prop2;
    }

}

```

```
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;


@ManagedBean(name="issueBean1031")
@SessionScoped
public class Issue1031Bean {

    public Issue1031Bean(){
        list1 = new ArrayList<>();
        list1.add(new IClass1("a"));
        list1.add(new IClass1("b"));
        list1.add(new IClass1("c"));
        list1.add(new IClass1("d"));
        list1.add(new IClass1("e"));


        list2 = new ArrayList<>();
        list2.add(new IClass2("f"));
        list2.add(new IClass2("g"));
        list2.add(new IClass2("h"));
        list2.add(new IClass2("i"));
        list2.add(new IClass2("j"));

    }

    List<IClass1> list1;
    List<IClass2> list2;


    public List<IClass1> getList1() {
        return list1;
    }
    public void setList1(List<IClass1> list1) {
        this.list1 = list1;
    }
    public List<IClass2> getList2() {
        return list2;
    }
    public void setList2(List<IClass2> list2) {
        this.list2 = list2;
    }

    public void doSomething() {
         System.out.println("test");
    }

}


```

```
Error Rendering View[/issue1031.xhtml]: javax.el.PropertyNotFoundException: /issue1031.xhtml @16,51 rendered="#{item.prop2 == 'f'}": The class 'de.test.primefaces.issue1031.IClass1' does not have the property 'prop2'.
    at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111)

```

**Comment by kukel** [comment]
This works with a ui:repeat?

**Comment by wsaca** [comment]
PF 6: datatable doesn't work inside an **ui:repeat** or **p:repeat**. When you use ajax is working, but if you try to process the form that is containing the datatable with a commandButton then the values are always set to null.

**Comment by tandraschko** [comment]
does it work with ui:repeat?

**Comment by tandraschko** [comment]
updated our forked p:repeat. If it's still not working, it should be fixed in Mojarra first.
