### ISSUE TITLE
DataTable: Regression(PF 12->13) - LazyDataModel throws ClassCastException

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#10587]
### Describe the bug

This bug has similar symptoms with #7737
Regression from 12.0.0 -> 13.0.0
I believe that if the model object is non-existent, which it is in this case, a default ListDataModel is returned and causes this exception

```
jakarta.servlet.ServletException: class jakarta.faces.model.ListDataModel cannot be cast to class org.primefaces.model.LazyDataModel (jakarta.faces.model.ListDataModel is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @74ae7b8d; org.primefaces.model.LazyDataModel is in unnamed module of loader org.glassfish.web.loader.WebappClassLoader @26b3fdc9)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:709)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1554)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessToExtension(FacesViewsForwardingFilter.java:187)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:144)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:130)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:86)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:166)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassCastException: class jakarta.faces.model.ListDataModel cannot be cast to class org.primefaces.model.LazyDataModel (jakarta.faces.model.ListDataModel is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @74ae7b8d; org.primefaces.model.LazyDataModel is in unnamed module of loader org.glassfish.web.loader.WebappClassLoader @26b3fdc9)
	at org.primefaces.component.datatable.DataTable.getLazyDataModel(DataTable.java:1209)
	at org.primefaces.component.datatable.DataTable.loadLazyDataIfEnabled(DataTable.java:477)
	at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:126)
	at org.primefaces.component.datatable.DataTableRenderer.render(DataTableRenderer.java:103)
	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:96)
	at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:586)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1442)
	at jakarta.faces.render.Renderer.encodeChildren(Renderer.java:146)
	at jakarta.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:557)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1435)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1438)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1438)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:162)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:166)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
	... 40 more
```

### Reproducer

URL: https://github.com/flowlogix/flowlogix/tree/cbd650d608569732e999e5dc6241f8c4e5e3cb20/jakarta-ee/jee-examples

Deploy the app, go to path http://localhost:8080/ex/view-users

Exception appears

### Expected behavior

Works with 12, should work with PF 13 as well

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

Any

### JSF implementation

Mojarra

### JSF version

Payara 6.2023.8

### Java version

17, 20

### Browser(s)

Any

**Comment by Rapster** [comment]
It should be fixed in the latest snapshot, can you give it try please?

**Comment by lprimak** [comment]
You are correct! This issue is fixed in 14-SNAPSHOT currently.
