### ISSUE TITLE
DataTable: with SummaryRow - Nullpointer on paginate

### ISSUE THREAD

**Issue by fjvasconcellos** [primefaces/primefaces#1060]
Error stacktrace

```
at org.primefaces.component.datatable.DataTableRenderer.isInSameGroup(DataTableRenderer.java:1279) [primefaces-5.2.jar:5.2]
    at org.primefaces.component.datatable.DataTableRenderer.encodeRows(DataTableRenderer.java:880) [primefaces-5.2.jar:5.2]
    at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:825) [primefaces-5.2.jar:5.2]
    at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:788) [primefaces-5.2.jar:5.2]
    at org.primefaces.component.datatable.feature.PageFeature.encode(PageFeature.java:36) [primefaces-5.2.jar:5.2]
    at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:78) [primefaces-5.2.jar:5.2]
```

My DataTable has 6 results and show 4 in a page.
When paginate the error happens because the variable "nextGroupByData" is null.

**Comment by kukel** [comment]
Use the forum please and create a GOOD working minimal code example!!!

**Comment by tandraschko** [comment]
No example -> invalid.
If the problem still persists with the current trunk version, please create new issue with a fully runnable and small sample bean+xhtml.
