### ISSUE TITLE
TabView: swipe on mobile enabled but fails on last item

### ISSUE THREAD

**Issue by zeppelinux** [primefaces/primefaces#10628]
### Describe the bug

https://www.primefaces.org/showcase/ui/panel/tabView.xhtml - load on mobile and swipe several times to the left (reaching post last element).

Also not obvious way to disable the swipe.

Note, this is not normal mobile browser swipe - it doesn't have to start from the right edge of the screen.

### Reproducer

https://www.primefaces.org/showcase/ui/panel/tabView.xhtml

### Expected behavior

Not sure, but it doesn't crash.

### PrimeFaces edition

Community

### PrimeFaces version

13

### Theme

default

### JSF implementation

MyFaces

### JSF version

2.2+

### Java version

17

**Comment by zeppelinux** [comment]
``When TabView (PF13)  is swiped left on mobile it crashes with:
java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:678)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at org.primefaces.component.tabview.TabView.queueEvent(TabView.java:119)
at org.primefaces.behavior.ajax.AjaxBehaviorRenderer.decode(AjaxBehaviorRenderer.java:55)
at jakarta.faces.component.behavior.ClientBehaviorBase.decode(ClientBehaviorBase.java:58)
at org.primefaces.util.ComponentUtils.decodeBehaviors(ComponentUtils.java:261)
at org.primefaces.renderkit.CoreRenderer.decodeBehaviors(CoreRenderer.java:638)
at org.primefaces.component.tabview.TabViewRenderer.decode(TabViewRenderer.java:58)
at jakarta.faces.component.UIComponentBase.decode(UIComponentBase.java:450)
at org.primefaces.component.api.UITabPanel.processDecodes(UITabPanel.java:1076)
``

**Comment by FlipWarthog** [comment]
@melloware you can assign this to me and I can investigate.

**Comment by melloware** [comment]
Hmmm I can't get it to happen on the showcase using Mobile emulation in my browser?  I can swipe left and right even at both ends and its working properly?

**Comment by melloware** [comment]
Also @zeppelinux to disable touch on Tabview the docs: https://primefaces.github.io/primefaces/13_0_0/#/components/tabview?id=attributes

Say set `touchable="false"`

**Comment by FlipWarthog** [comment]
> Hmmm I can't get it to happen on the showcase using Mobile emulation in my browser? I can swipe left and right even at both ends and its working properly?

I think I found it. It looks like it's the `f:facet name="actions"` is adding extra `li` elements in the `navContainer`, so  `getLength()`  in the js is not returning just the number of tabs but the number of tabs _and_ actions elements. Should be a quick update to the JQuery selector for that so I'm testing it out now.

**Comment by FlipWarthog** [comment]
Yep, that was the case and PR is submitted. Here's a monkey patch to apply the same fix in your application @zeppelinux :

```js
PrimeFaces.widget.TabView = PrimeFaces.widget.TabView.extend({
    getLength: function() {
        return this.navContainer.children().filter(':not(.ui-tabs-actions)').length;
    }
});
```

**Comment by melloware** [comment]
Thanks I will check this out.

**Comment by melloware** [comment]
I will port this to 13.0.1.
