### ISSUE TITLE
Dynamic resource dependency loading

### ISSUE THREAD

**Issue by mrswadge** [primefaces/primefaces#1066]
Provide a mechanism to allow dynamic resource loading for primefaces extensions.

Full discussion here, including the forum user 'tandraschko' suggesting a solution for v6.0: http://forum.primefaces.org/viewtopic.php?f=14&t=44291

Original post:
I've been writing my first primefaces extension and it's been going well. I have a new component which is entirely functional when using the taglibs I have defined. This is great! However, I am having a lot of trouble when modifying the view through Java code as the resource dependencies are not dynamically being loaded. I have obviously done something wrong, but I'm unclear what.

I have the following structure. 

Library name **otbofaces**
Component name **dateentry**
- META-INF/resources/otbofaces/dateentry
  - dateentry.css
  - dateentry.js
  - jquery.autotab.js
  - jquery.caret.js
  - jquery.date-entry.js

My component is hooked up using annotations:

```
@FacesRenderer( componentFamily = DateEntry.COMPONENT_FAMILY, rendererType = DateEntryRenderer.RENDERER_TYPE )
public class DateEntryRenderer extends CoreRenderer {
   public static final String RENDERER_TYPE = "com.tracegroup.isys.faces.DateEntryRenderer";
```

```
@FacesComponent( value = DateEntry.COMPONENT_TYPE )
@ResourceDependencies( { 
   @ResourceDependency( library = "primefaces", name = "jquery/jquery.js" ), // JQuery !
   @ResourceDependency( library = "primefaces", name = "primefaces.js" ), // PrimeFaces !
   @ResourceDependency( library = "otbofaces",  name = "dateentry/jquery.autotab.js" ), // Auto Tab for automatic cursor transition between fields.
   @ResourceDependency( library = "otbofaces",  name = "dateentry/jquery.caret.js" ), // JQuery caret for cursor movement in fields.
   @ResourceDependency( library = "otbofaces",  name = "dateentry/jquery.date-entry.js" ), // Main body of the DateEntry definition.
   @ResourceDependency( library = "otbofaces",  name = "dateentry/dateentry.js" ), // Widget definition.
   @ResourceDependency( library = "otbofaces",  name = "dateentry/dateentry.css" ), // Main body of the DateEntry definition.
} )
public class DateEntry extends HtmlInputText implements Widget, ClientBehaviorHolder {
```

The dateentry.js is the widget definition which is invoking the javascript that is intended to build and render the widget client side. This code gets invoked absolutely fine when I use a tag notation as follows. This is working great!

Code: Select all
<otbofaces:date-entry id="datetime-enabled" date="29" month="1" year="1980" hour="9" minute="52" datepicker="true" format="datetime" binding="#{buttonView.datetime}" />

I'm struggling with the following scenario: If I add a button action that adds a DateEntry component to an arbitrary panel like so:

```
UIComponent component = actionEvent.getComponent();
DateEntry dateEntry = new DateEntry();
dateEntry.setFormat( "datetime" );
dateEntry.setDate( 15 );
dateEntry.setMonth( 8 );
dateEntry.setYear( 2011 );
dateEntry.setHour( 20 );
dateEntry.setMinute( 12 );
dateEntry.setDisabled( false );
dateEntry.setDatepicker( true );

datecontainer.getChildren().add( dateEntry );
```

The renderer is using the standard PrimeFaces org.primefaces.util.WidgetBuilder class within the overridden DateEntryRenderer.encodeEnd(FacesContext, UIComponent) method to create the javascript call to initiate the widget like so:

```
String clientId = component.getClientId();
String widgetVar = component.resolveWidgetVar();

WidgetBuilder wb = getWidgetBuilder( context );
wb.initWithDomReady( "DateEntry", widgetVar, clientId, "dateentry" );

encodeClientBehaviors( context, component );

wb.finish();
```

Without the "dateentry" parameter at the end of wb.initWithDomReady( "DateEntry", widgetVar, clientId, "dateentry" ); the client side was searching for /javax.faces.resource/undefined/undefined.css.xhtml?ln=primefaces&v=5.3 and /javax.faces.resource/undefined/undefined.js.xhtml?ln=primefaces&v=5.3 .. so I added the "dateentry" as the resource name, which edged me closer. It's still not enough...

It's executing the javascript with this javascript:

```
$(function(){PrimeFaces.cw("DateEntry","widget_j_idt8_j_id5",{id:"j_idt8:j_id5"},"dateentry");});
```

This is where the problems begin for me. As the requests for the scripts are being done on the client-side, I wonder how it could possibly know to load all the resource dependencies that are assigned to the component via the @ResourceDependency annotations as these are server-side and haven't as far as I can tell been transmitted to the client.

A small summary:
- The URL generated by the primefaces.js appears to think that these resources are in the primefaces library. i.e. from /javax.faces.resource/dateentry/dateentry.css.xhtml?ln=**primefaces**&v=**5.3** instead of /javax.faces.resource/dateentry/dateentry.css.xhtml?ln=**otbofaces**&v=**20160125162258** (I have a server-side OtboResourceHandler to add the version, I can include the sources for these later if necessary).
- As you can see, the component maps 5 client side resources to the component. I have only seen that it attempts to get dateentry.js and dateentry.css, so it is ignoring the other resource dependencies that are wired onto the Widget implementation using the @ResourceDependency annotations.

I suppose I could alter the javascript before the PrimeFaces.cw call is made to load the resource dependencies, something like that below, but I would have thought that is a little hacky. What is the correct way?

```
ResourceDependencies resourceDependencies = DateEntry.class.getAnnotation( ResourceDependencies.class );
for ( ResourceDependency dependency : resourceDependencies.value() ) {
   // insert javascript code that loads the javascript or stylesheet if it isn't present in the header.
}
```

**Comment by tandraschko** [comment]
There is one thing we must still evaluate!
In our latest version in the forum post, we are able to "render" the missing resources on the client.
The problem is now, that resouces may depend on each it, so it must NOT be loaded paralell.

Could you please develop a sample method like:

function loadResources(arrayWithResources) {

}

and load the resources after each other?
Not sure how i can do it with jquery, manually i would do something like:

```
$.getScript( "script1.js", function() {
           $.getScript( "script2.js", function() {
                       $.getScript( "script3.js", function() {

                       });
           });
});
```

**Comment by mrswadge** [comment]
How about something like this? I've not tested it, but I think it should work and it's pretty minimal.

```
function loadResources(resourcesArray) {
  var callback = function() {
    resourcesArray.shift();
  };
  while ( resourcesArray.length > 0 ) {
    $.getScript( resourcesArray[0], callback );
  } 
}
```

**Comment by tandraschko** [comment]
Looks good!
would be great if you could give it a try, i will try to implement it next week.

**Comment by tandraschko** [comment]
Commited! Please test test test, i only tested it with primefaces resources.

**Comment by mertsincan** [comment]
Hi @tandraschko ,

I tested this fix and found a bug on PF-Mobile. You can replicate it on Dynamic - Tabview example;
http://localhost:8080/showcase/mobile/tabView.xhtml

I think the problem is in line 289 and line 295 of PrimePartialResponseWriter.java.

**Comment by tandraschko** [comment]
I see but thats not related directly to this feature. The problem is that tabView doesn't post the ViewState.

**Comment by tandraschko** [comment]
the form was missing, fixed the example.

**Comment by stiemannkj1** [comment]
@tandraschko, @mrswadge,
I'm trying to test this feature by doing the following:

xhtml:

```
<h:form>
    <p:commandButton actionListener="#{bean.add}" update="@form" process="@form" value="add" />
</h:form>
```

**OR**

```
<h:form>
    <p:panel>
        <p:commandButton actionListener="#{bean.add}" update="@form" process="@form" value="add" />
    </p:panel>
</h:form>
```

java:

```
public void add(ActionEvent actionEvent) {
    final ColorPicker colorPicker = new ColorPicker();
    colorPicker.setMode("inline");
    actionEvent.getComponent().getParent().getChildren().add(colorPicker);
}
```

When I click the _Add_ button, the color picker does not appear in the browser. The following error appears in the client-side browser logs:

> Widget not available: ColorPicker

Am I doing something wrong? My example seems very similar to the one mentioned by @mrswadge. I am testing with Primefaces 6.0.RC3-SNAPSHOT on a webapp in tomcat.

**Comment by tandraschko** [comment]
works fine when you use:
    final ColorPicker colorPicker =
            (ColorPicker) FacesContext.getCurrentInstance().getApplication().createComponent(ColorPicker.COMPONENT_TYPE);

I will add it to the migration guide.

**Comment by stiemannkj1** [comment]
Thanks @tandraschko! This feature is working for me now! It also works in Portlets!

**Comment by tandraschko** [comment]
Great! thanks for testing! :)

**Comment by lkumarjain** [comment]
Hi Team,

I tried above Solution with Prime-faces 5.2  but this is not working for me for Google Map Component.. Any solution...

Code Example :
mapPanel.getChildren().clear();
GMap map = ENBeanLocator.createComponent(GMap.COMPONENT_TYPE);
map.setCenter("36.879466, 30.667648");
map.setZoom(15);
map.setType("ROADMAP");
mapPanel.getChildren().add(map);

Error is  : 
Jun 07, 2016 12:27:06 PM com.sun.faces.application.resource.ResourceHandlerImpl logMissingResource
WARNING: JSF1064: Unable to find or serve resource, undefined/undefined.css, from library, primefaces.
Jun 07, 2016 12:27:06 PM com.sun.faces.application.resource.ResourceHandlerImpl logMissingResource
WARNING: JSF1064: Unable to find or serve resource, undefined/undefined.js, from library, primefaces.
Jun 07, 2016 12:29:31 PM com.sun.faces.application.resource.ResourceHandlerImpl logMissingResource
WARNING: JSF1064: Unable to find or serve resource, undefined/undefined.css, from library, primefaces.

Thanks,
-Lokesh

**Comment by tandraschko** [comment]
can you see the "Milestone" in this ticket? it's on the right side ;)

**Comment by mrswadge** [comment]
Hi Thomas,

Finding an issue that might be related to this change.

```
SEVERE: Error Rendering View[/app/index.xhtml]
javax.faces.event.AbortProcessingException: java.lang.NullPointerException: Argument Error: Parameter resourceName is null
    at org.primefaces.context.PrimePartialResponseWriter.startMetadataIfNecessary(PrimePartialResponseWriter.java:303)
    at org.primefaces.context.PrimePartialResponseWriter.startUpdate(PrimePartialResponseWriter.java:142)
    at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:407)
    at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:290)
    at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:58)
    at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:974)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1674)
    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:388)
    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:121)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:509)
    at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
    at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
    at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)
    at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:27)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at com.tracegroup.isys.opentwins.ui.servlet.OpenTwinsSessionFilter.doFilter(OpenTwinsSessionFilter.java:265)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at com.tracegroup.isys.opentwins.ui.primefaces.DocumentModeFilter.doFilter(DocumentModeFilter.java:28)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at com.tracegroup.isys.opentwins.ui.primefaces.NoCacheFilter.doFilter(NoCacheFilter.java:36)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3748)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3714)
    at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
    at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
    at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2283)
    at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2182)
    at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1491)
    at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
    at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)
Caused by: java.lang.NullPointerException: Argument Error: Parameter resourceName is null
    at com.sun.faces.util.Util.notNull(Util.java:253)
    at com.sun.faces.application.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:109)
    at javax.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:84)
    at javax.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:84)
    at javax.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:84)
    at org.primefaces.util.ResourceUtils.filterScripts(ResourceUtils.java:114)
    at org.primefaces.context.PrimePartialResponseWriter.startMetadataIfNecessary(PrimePartialResponseWriter.java:293)
    at org.primefaces.context.PrimePartialResponseWriter.startUpdate(PrimePartialResponseWriter.java:142)
    at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:408)
    ... 34 more

```

This seems to happen when a resource gets into the list of ResourceInfos with null values. Effectively a RES_NOT_FOUND error. Could it be handled without needing to stack trace?

![image](https://cloud.githubusercontent.com/assets/6681203/16566411/18ca8368-420c-11e6-973a-b0bee06db360.png)

Cheers,
Stuart

**Comment by tandraschko** [comment]
Hi,

would be great if you could provide a new issue with sample app.

**Comment by mrswadge** [comment]
Time is a bit tight as we have a release next week, but I think I tracked it down to same script that's embedded into our main template xhtml.

```
<h:outputScript target="head">
var custom = function() { blah.etc(); }
</h:outputScript>
```

We do this as we use EL script to pass values from server side to local javascript, for example:

```
window.ot.context = "#{request.contextPath}";
window.ot.session = "#{session.id}";
```

It makes sense as the script doesn't have a library or name.

**Comment by mrswadge** [comment]
Raised #1580
