### ISSUE TITLE
CurrencyValidatorTest.java failing with java 21-ea

### ISSUE THREAD

**Issue by milansie** [primefaces/primefaces#10702]
### Describe the bug

This test will fail on all non-minor versions of java with non-numeric characters in the version.

```
java.lang.NumberFormatException: For input string: "21-ea"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:661)
	at java.base/java.lang.Integer.parseInt(Integer.java:777)
	at org.primefaces.util.CurrencyValidatorTest.getVersion(CurrencyValidatorTest.java:69)
	at org.primefaces.util.CurrencyValidatorTest.testIntegerValid(CurrencyValidatorTest.java:116)
```

### Expected behavior

Test will work :)

### PrimeFaces edition

None

### PrimeFaces version

13.0.0 (all)

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

21-ea

**Comment by melloware** [comment]
Thanks for the report!

**Comment by melloware** [comment]
Actually I am updating 13.X with this fix but since 14 is dropping JDK8 support I can remove this check entirely from master.
