### ISSUE TITLE
Dialog Framework Data composite component selectevent warning/error

### ISSUE THREAD

**Issue by kurtomerfaruk** [primefaces/primefaces#10777]
### Describe the bug

I am using Dialog Framework Data as a composite component. When I select a record from the dialog window that opens, it gives a warning in the primefaces-test project.

### Reproducer

**PrimeFaces 13.0.0
Jakarta 10 (jakarta.jakartaee-api)
Jakarta Faces (4.0.5)
JDK 11**

`<composite:attribute name="ajaxListener" method-signature="void ajaxListener(org.primefaces.event.SelectEvent)" required="true"/>`

If I use it this way in the primefaces-test project, it gives a warning but continues to work. But if I use it this way in my own project, it always returns null value.

However, in my own project  

`<composite:attribute name="ajaxListener" method-signature="void ajaxListener(org.primefaces.event.AbstractAjaxBehaviorEvent)" required="true"/>`

If I use it in this way, it gives a warning and continues to work.

[PrimeFaces-Test.zip](https://github.com/primefaces/primefaces/files/12807490/PrimeFaces-Test.zip)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

4.0.5

### Java version

11

**Comment by melloware** [comment]
Error:

````
Oct 04, 2023 3:40:35 PM com.sun.faces.facelets.el.ContextualCompositeMethodExpression invoke
WARNING: jakarta.el.MethodNotFoundException: Method not found: TestView(string=null, integer=null, decimal=null, localDateTime=null, list=[TestObject(id=c8f2b849-2ccc-4b19-88ec-c226034ecd5e, name=Thriller, artist=Michael Jackson, released=1982), TestObject(id=f2ac0163-73e0-4a3f-9f45-7b03bedb9555, name=Back in Black, artist=AC/DC, released=1980), TestObject(id=b38cc02f-a23c-47e4-ab23-a2adf9d8f694, name=The Bodyguard, artist=Whitney Houston, released=1992), TestObject(id=3498f4dd-2f74-4c4c-9d05-51601a075b97, name=The Dark Side of the Moon, artist=Pink Floyd, released=1973)], selected=null).selectedObject(org.primefaces.event.SelectEvent)
Oct 04, 2023 3:40:35 PM com.sun.faces.facelets.el.ContextualCompositeMethodExpression invoke
WARNING: faces.facelets.el.method.expression.invoke.error: jakarta.el.PropertyNotFoundException: /test.xhtml @30,64 ajaxListener="#{testView.selectedObject}": Property [selectedObject] not found on type [org.primefaces.test.TestView] #{testView.selectedObject}
```

**Comment by FlipWarthog** [comment]
If it's related to [this SO post](https://stackoverflow.com/questions/6453842/jsf-2-how-can-i-add-an-ajax-listener-method-to-composite-component-interface) it's been in Mojarra for a while?

**Comment by kurtomerfaruk** [comment]
> When I run with MyFaces `mvn clean jetty:run -Pmyfaces40` no warnings.

When I run with Mojarra mvn clean jetty:run -Pmojarra40 

gives warning in primefaces-test but gives error in my own project

**Comment by melloware** [comment]
@kurtomerfaruk are you sure you are using the same Mojarra version in both PF Test and you real app?

**Comment by tandraschko** [comment]
does it work with f:ajax?

**Comment by kurtomerfaruk** [comment]
> @kurtomerfaruk are you sure you are using the same Mojarra version in both PF Test and you real app?

Yes i updated them

**Comment by tandraschko** [comment]
the same exception also occurs with f:ajax, i dont see any reason why this should be a PF bug

**Comment by tandraschko** [comment]
Just as additional info:
i didnt check the case in detail but i got this eception on button click:

```
WARNUNG: /resources/ui/inputWithButton.xhtml @27,89 value="#{cc.attrs.inputValue}": /test.xhtml @30,64 inputValue="#{testView.selected.name}": Target Unreachable, [selected] returned null
jakarta.el.PropertyNotFoundException: /resources/ui/inputWithButton.xhtml @27,89 value="#{cc.attrs.inputValue}": /test.xhtml @30,64 inputValue="#{testView.selected.name}": Target Unreachable, [selected] returned null
        at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:64)
        at org.primefaces.util.ComponentUtils.getConverter(ComponentUtils.java:176)
        at org.primefaces.renderkit.InputRenderer.getConvertedValue(InputRenderer.java:47)
        at jakarta.faces.component.UIInput.getConvertedValue(UIInput.java:901)
        at jakarta.faces.component.UIInput.validate(UIInput.java:816)
        at jakarta.faces.component.UIInput.executeValidate(UIInput.java:1093)
        at jakarta.faces.component.UIInput.processValidators(UIInput.java:586)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIForm.processValidators(UIForm.java:222)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at org.primefaces.component.dialog.Dialog.processValidators(Dialog.java:152)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIComponentBase.processValidators(UIComponentBase.java:906)
        at jakarta.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1257)
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:49)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
        at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
        at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: jakarta.el.PropertyNotFoundException: /test.xhtml @30,64 inputValue="#{testView.selected.name}": Target Unreachable, [selected] returned null
        at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:64)
        at com.sun.faces.el.CompositeComponentAttributesELResolver.getType(CompositeComponentAttributesELResolver.java:138)
        at com.sun.faces.el.DemuxCompositeELResolver._getType(DemuxCompositeELResolver.java:169)
        at com.sun.faces.el.DemuxCompositeELResolver.getType(DemuxCompositeELResolver.java:194)
        at org.apache.el.parser.AstValue.getType(AstValue.java:59)
        at org.apache.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:173)
        at org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at com.sun.faces.facelets.el.ContextualCompositeValueExpression.getType(ContextualCompositeValueExpression.java:156)
        at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:62)
        ... 64 more
Caused by: jakarta.el.PropertyNotFoundException: Target Unreachable, [selected] returned null
        at org.apache.el.parser.AstValue.getTarget(AstValue.java:123)
        at org.apache.el.parser.AstValue.getType(AstValue.java:57)
        at org.apache.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:173)
        at org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:62)
        ... 72 more
```

for me it seems that TestView#selection is used outside the right scope
most people dont know that the DialogFramework will create its own ViewScope and the ViewScope of DF and the outer ones are not shared

**Comment by tandraschko** [comment]
also aligned the docs a bit: https://github.com/primefaces/primefaces/commit/fc1ed5672a822af0fbaa7f30fc117ce066fca0d2

**Comment by kurtomerfaruk** [comment]
I've been using it the same way for years and now I'm getting the error. The first PrimeFaces version I used was 3.4.2.
If the problem here is not related to PrimeFaces, I think it is a mojarra-side problem.
Thanks for your attention
