### ISSUE TITLE
DataTable: Error if filter facet element is bound to List

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#10830]
### Describe the bug

When using `f:facet name="filter"` and binding the `value` attribute of the element (in this case `p:selectOneMenu`), an error is thrown in `UITable`. It looks like it's expecting an Object[] rather than a (potential) List.

XHTML:
```xml
<p:column field="artist" filterMatchMode="in" filterValue="#{testView.artistFilter}">
    <f:facet name="filter">
        <p:selectCheckboxMenu value="#{testView.artistFilter}" multiple="true" styleClass="ui-custom-filter">
            <p:ajax process="@this" oncomplete="PF('testTable').filter()" />
            <f:selectItems value="#{testView.artists}" />
        </p:selectCheckboxMenu>
    </f:facet>
</p:column>
```

Java:
```java
private List<String> artistFilter;
private List<String> artists;

...

public void init() {
    string = "Welcome to PrimeFaces!!!";
    list = new ArrayList<>(Arrays.asList(
            new TestObject("Thriller", "Michael Jackson", 1982),
            new TestObject("Back in Black", "AC/DC", 1980),
            new TestObject("The Bodyguard", "Whitney Houston", 1992),
            new TestObject("The Dark Side of the Moon", "Pink Floyd", 1973)
    ));
    artists = list.stream().map(TestObject::getArtist).toList();
    artistFilter = Arrays.asList("AC/DC");
}
```

Full stacktrack from reproducer:
```
Oct 16, 2023 6:35:22 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [Ljava.lang.Object; (java.util.ArrayList and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
        at org.primefaces.component.api.UITable.lambda$updateFilterByValuesWithFilterRequest$3(UITable.java:214)
        at org.primefaces.component.api.ColumnAware.forEachColumn(ColumnAware.java:101)
        at org.primefaces.component.api.ColumnAware.forEachColumn(ColumnAware.java:54)
        at org.primefaces.component.api.ColumnAware.forEachColumn(ColumnAware.java:50)
        at org.primefaces.component.api.UITable.updateFilterByValuesWithFilterRequest(UITable.java:182)
        at org.primefaces.component.datatable.feature.FilterFeature.decode(FilterFeature.java:68)
        at org.primefaces.component.datatable.DataTable.processValidators(DataTable.java:308)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:622)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:671)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIForm.visitTree(UIForm.java:356)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:414)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:263)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:46)
        at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1308)
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Reproducer

On page load the error will occur in the console.

[table-filter-error.zip](https://github.com/primefaces/primefaces/files/12922506/table-filter-error.zip)

### Expected behavior

No error, List should be valid

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### Theme

n/a

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Chrome latest

**Comment by FlipWarthog** [comment]
Context:

This was found after we migrated from PF12 to PF13. I have other tables in this app that prefilter but they're binding the DataTable and messing with the FilterMeta. Those still work fine so I switched entirely to that pattern.

I think the error might relate to this change

https://github.com/primefaces/primefaces/pull/10068
