### ISSUE TITLE
release 13.0.2 my morpheus template not working

### ISSUE THREAD

**Issue by jrgamber** [primefaces/primefaces#10964]
### Describe the bug

when using 13 I get a stack trace.

FATAL:   JSF1073: java.lang.NoSuchMethodError caught during processing of RENDER_RESPONSE 6 : UIComponent-ClientId=, Message='boolean org.primefaces.util.LangUtils.isValueBlank(java.lang.String)'
FATAL:   'boolean org.primefaces.util.LangUtils.isValueBlank(java.lang.String)'
java.lang.NoSuchMethodError: 'boolean org.primefaces.util.LangUtils.isValueBlank(java.lang.String)'

### Expected behavior

should show page same as v12 did

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### Theme

Morpheus

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by jrgamber** [comment]
FATAL:   JSF1073: java.lang.NoSuchMethodError caught during processing of RENDER_RESPONSE 6 : UIComponent-ClientId=, Message='boolean org.primefaces.util.LangUtils.isValueBlank(java.lang.String)'
FATAL:   'boolean org.primefaces.util.LangUtils.isValueBlank(java.lang.String)'
java.lang.NoSuchMethodError: 'boolean org.primefaces.util.LangUtils.isValueBlank(java.lang.String)'
	at org.primefaces.morpheus.component.TabMenu.resolveWidgetVar(TabMenu.java:123)
	at org.primefaces.morpheus.component.TabMenuRenderer.encodeEnd(TabMenuRenderer.java:108)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tandraschko** [comment]
This issue tracker ist for PrimeFaces core only. AFAIK primetek didnt release a compatible version of the template for v13 yet.
Better try discussions on GitHub or discord. I think only small changes are required in morpheus code to align for v13

**Comment by melloware** [comment]
Yeah I updated Babylon it was easy.

**Comment by jrgamber** [comment]
just building my websites stenches my technical ability.  Would you update Morpheus?
Can you post these v13 templates on GitHub, or is that a license issue?

**Comment by melloware** [comment]
That is up to PrimeTek. This is just the open source community. If you have PRO support you can open a ticket through your PRO account.

**Comment by jepsar** [comment]
PrimeTek was going to upgrade the templates "in a few weeks" and "as soon as possible" months ago. See https://github.com/orgs/primefaces/discussions/50
