### ISSUE TITLE
Facelet parameter mapping not resolving when binding p:ajax listener to a method with an event argument

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#1098]
PrimeFaces 5.3.

Simple reproducer.

**ajaxview.xhtml**

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">
<f:view locale="en">
    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        </f:facet>
    </h:head>

    <h:body>
        <ui:include src="ajaxframe.xhtml">
            <ui:param name="paramBean" value="#{ajaxBean}" />
        </ui:include>
        <p:growl autoUpdate="true" />
    </h:body>
</f:view>
</html>
```

**ajaxframe.xhtml**

```
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">

    <!-- expects a ui:param "paramBean" -->

    <h:form>
        <h3>call via ui:param without args</h3>
        <p:tabView>
            <p:ajax event="tabChange" listener="#{paramBean.tabChangeNoArgs}" />
            <p:tab title="tab 0">
                tab 0
            </p:tab>
            <p:tab title="tab 1">
                tab 1
            </p:tab>
        </p:tabView>

        <h3>call via ui:param with event arg</h3>
        <p:tabView>
            <p:ajax event="tabChange" listener="#{paramBean.tabChangeWithEventArg}" />
            <p:tab title="tab 0">
                tab 0
            </p:tab>
            <p:tab title="tab 1">
                tab 1
            </p:tab>
        </p:tabView>

        <h3>call via cdi directly with event arg</h3>
        <p:tabView>
            <p:ajax event="tabChange" listener="#{ajaxBean.tabChangeWithEventArg}" />
            <p:tab title="tab 0">
                tab 0
            </p:tab>
            <p:tab title="tab 1">
                tab 1
            </p:tab>
        </p:tabView>
    </h:form>

</ui:composition>
```

**AjaxBean.java**

```
import java.io.Serializable;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import org.primefaces.event.TabChangeEvent;

@Named
@ConversationScoped
public class AjaxBean implements Serializable {

    private static final long serialVersionUID = 1L;

    public void tabChangeNoArgs() {
        signal("tabChangeNoArgs");
    }

    public void tabChangeWithEventArg(TabChangeEvent event) {
        signal("tabChangeWithEventArg " + event);
    }

    private void signal(String text) {
        System.out.println(text);
        FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO, text, ""));
    }

}
```

Deploy, open ajaxview.xhtml in the browser.
When changing tabs, observe the case "call via ui:param with event arg" result in

```
2016-02-02 17:08:01,407 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-54) javax.el.PropertyNotFoundException: Target Unreachable, identifier 'paramBean' resolved to null
    at com.sun.el.parser.AstValue.getTarget(AstValue.java:174)
    at com.sun.el.parser.AstValue.invoke(AstValue.java:275)
    at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
    at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
    at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
    at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
    at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
    at org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processCustomListener(AjaxBehaviorListenerImpl.java:88)
    at org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processArgListener(AjaxBehaviorListenerImpl.java:73)
    at org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processAjaxBehavior(AjaxBehaviorListenerImpl.java:57)
    at org.primefaces.event.TabChangeEvent.processListener(TabChangeEvent.java:42)
    at javax.faces.component.behavior.BehaviorBase.broadcast(BehaviorBase.java:106)
    at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:804)
    at org.primefaces.component.api.UITabPanel.broadcast(UITabPanel.java:1259)
    at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
    at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
    at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)
    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
    at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)
    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

The problem is in the `org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processCustomListener(FacesContext, ELContext, AjaxBehaviorEvent)` - it creates a new MethodExpression, which doesn't have the necessary facelet variable mapper.

The issue was previously reported at https://code.google.com/archive/p/primefaces/issues/4075.

**Comment by tandraschko** [comment]
We can't fix this easily as we don't know the EventClass at building time: AjaxBehaviorHandler
To fix this, we must create a mapping between Component - Eventname - EventClass.

**Comment by tandraschko** [comment]
If you would like to create such a mapping, please ping me.

**Comment by tandraschko** [comment]
i could imagine something like:

```
pubic interface PrimeClientBehaviorHolder {
    Map<String, Class<? extends BehaviorEvent>> getBehaviorEventMapping();
}
```

Components with custom events need to implement this e.g.:

```
Tree implements PrimeClientBehaviorHolder  {
    private static final Map<String, Class<? extends BehaviorEvent>> BEHAVIOR_EVENT_MAPPING = Collections.unmodifiableMap(new HashMap<String, Class<? extends BehaviorEvent>>() {{
        put("dragdrop", TreeDragDropEvent.class);
        put("unselect", NodeUnselectEvent.class);
    }});

    public Map<String, Class<? extends BehaviorEvent>> getBehaviorEventMapping() {
         return BEHAVIOR_EVENT_MAPPING ;
    }
}
```

The AjaxBehaviorHandler could lookup the event class via the event name and pass the a methodExpression for the event class to the AjaxBehaviorListenerImpl.

**Comment by tandraschko** [comment]
Done for TabView ;)

**Comment by Rapster** [comment]
I had a closer look on `PrimeClientBehaviorHolder` to understand the necessity of it. I tried the sample with 5.3 with different impl. they're all working. I only reproduced this problem if CDI used and no scope is set. Makes me wonder if `PrimeClientBehaviorHolder` is really necessary after all. The author of this ticket never replied...

**Comment by tandraschko** [comment]
it definitely was necessary for some cases (i also remind some case when passing listeners to a CC or something)

**Comment by VsevolodGolovanov** [comment]
I can confirm that this was fixed. After migrating to PF 6.1 we were able to remove our workaround for this issue.

**Comment by Rapster** [comment]
Strange, the original issue is a `PropertyNotFoundException`, the change that Thomas made is to try out the "original" listeners _(by cathing MethodNotFoundException)_ if not found: use a fallback listener. Your issue is a `PropertyNotFoundException`, I don't see how it fixes the problem. But again, it works fine in 5.3 without this change

**Comment by VsevolodGolovanov** [comment]
My issue was missing facelet context resulting in unresolveable ui:param, but only when calling a listener with event argument.
I think the unmentioned part of a fix for this was here: https://github.com/primefaces/primefaces/commit/cecf5b9c1117cec61d0eaad5897589f2ededbdf3
Note the FaceletContext change in processCustomListener.

PropertyNotFoundException shouldn't happen at all anymore, because the context is always there now. Only MethodNotFoundException would happen, because it would find the proper bean, but not the method.

**Comment by Rapster** [comment]
```console
juil. 24, 2019 1:39:11 PM com.sun.faces.config.ConfigureListener contextInitialized
INFOS: Initialisation de Mojarra 2.2.17 ( 20180411-2323 53e5a1509f6706550c6789ced710eb6ebf05fffd) pour le contexte «/primefaces-test»
juil. 24, 2019 1:39:11 PM com.sun.faces.spi.InjectionProviderFactory createInstance
INFOS: JSF1048 : Présence d’annotations PostConstruct/PreDestroy  Les méthodes de beans gérés marquées avec ces annotations auront des annotations dites traitées.
juil. 24, 2019 1:39:12 PM org.primefaces.webapp.PostConstructApplicationEventListener processEvent
INFOS: Running on PrimeFaces 5.3
[INFO] Started o.e.j.m.p.JettyWebAppContext@27bc1d44{/primefaces-test,[file:///D:/Development/Sources/primefaces/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/, jar:file:///D:/Development/Sources/primefaces/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/javax.faces-2.2.17.jar!/META-INF/resources, jar:file:///D:/Development/Sources/primefaces/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/primefaces-5.3.jar!/META-INF/resources],AVAILABLE}{D:\Development\Sources\primefaces\primefaces-test\target\primefaces-test-1.0-SNAPSHOT}
[INFO] Started ServerConnector@1cca3e8c{HTTP/1.1,[http/1.1]}{0.0.0.0:8181}
[INFO] Started @30009ms
[INFO] Started Jetty Server
tabChangeWithEventArg org.primefaces.event.TabChangeEvent[source=org.primefaces.component.tabview.TabView@3319402f]
tabChangeWithEventArg org.primefaces.event.TabChangeEvent[source=org.primefaces.component.tabview.TabView@24b16466]
tabChangeWithEventArg org.primefaces.event.TabChangeEvent[source=org.primefaces.component.tabview.TabView@71961053]

```

As a proof it is working with 5.3 using that sample. Would be nice to know what was wrong with CC?

**Comment by tandraschko** [comment]
i wont remove this until we have integration tests for this for all possible containers ;)

**Comment by VsevolodGolovanov** [comment]
@Rapster, tested the sample again on Wildfly 11 and PF 5.3 - indeed, no error. Tested on Wildfly 8.1 - and got the error.
I suspect some change in Mojarra affected this too.

**Comment by tandraschko** [comment]
Could also be releated to the EL impl/version. Also had this error from time to time and i used JUEL.

**Comment by Rapster** [comment]
I got it working with Wildfly (8.1.0, 9, etc.)

**Comment by Rapster** [comment]
@VsevolodGolovanov the commit cecf5b9c1117cec61d0eaad5897589f2ededbdf3 was pushed in 5.2 RC2 but get reverted for 5.2 Final. So cecf5b9c1117cec61d0eaad5897589f2ededbdf3 coulnd't fix your problem neither this fix. I don't mean to be annoying, but this change is quite impactful and more I try more I wonder if it was really necessary

But I must say, a lot of people came across that problem. IMO, a simpler solution could be found like cecf5b9c1117cec61d0eaad5897589f2ededbdf3 actually
