### ISSUE TITLE
InputSwitch: NPE on MyFaces 3.0

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11241]
java.lang.NullPointerException: Text must not be null.
	at org.apache.myfaces.shared.renderkit.html.HtmlResponseWriterImpl.writeText(HtmlResponseWriterImpl.java:951)
	at org.primefaces.component.inputswitch.InputSwitchRenderer.encodeOption(InputSwitchRenderer.java:99)
	at org.primefaces.component.inputswitch.InputSwitchRenderer.encodeMarkup(InputSwitchRenderer.java:83)
	at org.primefaces.component.inputswitch.InputSwitchRenderer.encodeEnd(InputSwitchRenderer.java:59)

**Comment by Rapster** [comment]
Not sure how you create your PR, but you're making references to different issues all over the place, see this for example https://github.com/primefaces/primefaces/issues/10838
