### ISSUE TITLE
DataTable: DefaultLazyDataModel throws IllegalArgumentException with external filter

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#11401]
### Describe the bug

`DefaultLazyDataModel#load()` can cause an IllegalArgumentException when the user is on a page > 1 and `DefaultLazyDataModel#filter` filters out _all_ elements

### Reproducer

Bean:
```java
@Named
@ViewScoped
public class DataTable044 implements Serializable {
    @Getter @Setter private String programmingLanguageFilter;
    @Getter private LazyDataModel<ProgrammingLanguage> lazyDataModel;

    @Inject private ProgrammingLanguageService service;

    @PostConstruct
    public void init() {
        lazyDataModel = DefaultLazyDataModel.<ProgrammingLanguage>builder()
                .valueSupplier(service::getLangs)
                .filter((ctx, value, filter, locale) -> {
                    if (programmingLanguageFilter == null) {
                        return true;
                    }

                    return ((ProgrammingLanguage) value).getName().contains(programmingLanguageFilter);
                }).build();
    }
}
```

XHTML:
```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html;charset=UTF-8" encoding="UTF-8">
    <h:head>

    </h:head>

    <h:body>

        <h:form id="form">
            <p:messages id="msgs" showDetail="true">
                <p:autoUpdate/>
            </p:messages>

            <p:inputText id="filterInput" value="#{dataTable044.programmingLanguageFilter}">
                <p:ajax process="@this" update="datatable"/>
            </p:inputText>

            <p:dataTable id="datatable" value="#{dataTable044.lazyDataModel}" paginator="true" rows="3" var="lang" >
                <p:column field="id"/>
                <p:column field="name"/>
                <p:column field="firstAppeared"/>
                <p:column field="type"/>
            </p:dataTable>
        </h:form>

    </h:body>
</f:view>

</html>
```

Test:
```java
public class DataTable044Test extends AbstractDataTableTest {
    @Test
    @DisplayName("first index is properly reset when table is filtered externally")
    public void test(Page page) throws InterruptedException {
        // Arrange
        page.dataTable.selectPage(2);

        // Act
        page.filterInput.setValue("asdf");

        // Assert
        assertTrue(page.isAt());
    }

    public static class Page extends AbstractPrimePage {
        @FindBy(id = "form:filterInput")
        InputText filterInput;
        @FindBy(id = "form:datatable")
        DataTable dataTable;

        @Override
        public String getLocation() {
            return "datatable/dataTable044.xhtml";
        }
    }
}
```

### Expected behavior

Works, table is empty

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-RC1

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by jungm** [comment]
@melloware is this really supposed to be on the 13.0.6 milestone? at least my fix is only 14.0.0 right now. not even sure if this was in 13.x

**Comment by melloware** [comment]
i will check it and backport it to 13.0.6 if it existed in 13.  Can you check the 13 branch?

**Comment by jungm** [comment]
Will do tomorrow, even if DefaultLazyDataModel is not in 13 I can imagine one is able to trigger the same bug by writing their own LazyDataModel that does filtering in a way the DataTable doesn't notice

I did just focus on 14.0.0-SNAPSHOT/RC1 for now because that's what we are running on :smile:

**Comment by melloware** [comment]
Yep looks like its in 13.0 as well: https://github.com/primefaces/primefaces/blob/8d0c666ca64d7d0271de81747002c6bc8a5e511a/primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java#L253

**Comment by Rapster** [comment]
Can you post the stacktrace to see where the exception comes from?

**Comment by jungm** [comment]
sure @Rapster 

```
java.lang.IllegalArgumentException: fromIndex(3) > toIndex(0)
        at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
        at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
        at org.primefaces.model.DefaultLazyDataModel.load(DefaultLazyDataModel.java:80)
        at org.primefaces.component.datatable.DataTable.loadLazyScrollData(DataTable.java:508)
        at org.primefaces.component.datatable.DataTable.loadLazyDataIfEnabled(DataTable.java:471)
        at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:131)
        at org.primefaces.component.datatable.DataTableRenderer.render(DataTableRenderer.java:108)
        at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:101)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:600)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1655)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:629)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:671)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIForm.visitTree(UIForm.java:356)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:414)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:46)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:46)
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1102)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1648)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
        at javax.faces.lifecycle.LifecycleWrapper.render(LifecycleWrapper.java:88)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.primefaces.webapp.filter.NoCacheFilter.doFilter(NoCacheFilter.java:45)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.primefaces.webapp.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:82)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
