### ISSUE TITLE
AutoUpdate: attach p:autoUpdate to a non-rendered component invokes visitTree of unrendered components during UIViewRoot#resetValues

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11408]
in case you attach p:autoUpdate to a non-rendered components e.g.
```
<h:outputPanel rendered="false">
    <h:outputPanel>
         <p:autoUpdate />
    </h:outputPanel>

    <p:dataTable value="...someEL which throws a exception when unrendered and therefore not in the right state">
          
    </p:dataTable>
</h:outputPanel>
```

it invokes the DataTable:

```
java.lang.NullPointerException: Cannot invoke "...." because the return value of "..." is null
	at org.neroe.MyController
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at jakarta.el.BeanELResolver.getValue(BeanELResolver.java:299)
	at jakarta.el.CompositeELResolver.getValue(CompositeELResolver.java:136)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
	at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:93)
	at jakarta.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:357)
	at jakarta.faces.component.UIData.getValue(UIData.java:2230)
	at jakarta.faces.component.UIData.createDataModel(UIData.java:2130)
	at jakarta.faces.component.UIData.getDataModel(UIData.java:2093)
	at org.primefaces.component.api.UIData.setRowModel(UIData.java:420)
	at org.primefaces.component.api.UIData.setRowIndexWithoutRowStatePreserved(UIData.java:413)
	at org.primefaces.component.api.UIData.setRowIndex(UIData.java:473)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:665)
	....
	at jakarta.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1196)
	at jakarta.faces.component.UIViewRoot.resetValues(UIViewRoot.java:1484)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:485)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:420)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:46)
```

**Comment by tandraschko** [comment]
the reason is actually our hack for stateless views
`p:autoUpdate` is actually handled via `PreRenderComponentEvent`
this means that if the component was rendered in the initial request, it will be added to the `renderIds` in the next request via `AutoUpdatePhaseListener`
those `renderIds` are remembered in the viewstate

in case of stateless view, can't remember the `renderIds` in the view state and we always listened to `PostAddToViewEvent`

we should at least only attach `PostAddToViewEvent` when the view is stateless

everything else should propably be fixed in the JSF impl and `#resetValues` called from `#processPartialRendering` should only visit rendered components

**Comment by fuinhaazulgit** [comment]
Hi. Discussion related : [LINK](https://github.com/orgs/primefaces/discussions/4109)
