### ISSUE TITLE
ShowCase : Ajax framework basic : KeyUp listener blows

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces#11483]
### Describe the bug

Go to https://www.primefaces.org/showcase/ui/ajax/basic.xhtml
- Focus on "Input" field
- Hit Tab to go to the next field "KeyUp"
The page blows and you'll get : 
```
Caused by: java.lang.NullPointerException
        at deployment.primefaces-showcase-14.0.0-SNAPSHOT.war//org.primefaces.showcase.view.ajax.BasicView.handleKeyEvent(BasicView.java:84)
```

### Expected behavior

You must be able to reach the field "KeyUp" with the Tab key.

Note : it works if you clic on the "KeyUp" field.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
Weird I tested the 13.0.7 and 14.0.0 showcase locally and its working so maybe its fixed?

**Comment by melloware** [comment]
Can someone else try this locally?

**Comment by melloware** [comment]
@ritonglue can you tell me more about your environment?  Are you running `mvn -Ddev` on the showcase?  What JDK version?

**Comment by ritonglue** [comment]
I use JDK 17 with wildly 25.

Make sure you go to the "Listener Key**u**p" with the tabulation key. The "Events Key**U**p" works fine.

**Comment by melloware** [comment]
Got it. I am using MyFaces with the Showcase and Wildfly is Mojarra which shows the issue:

```java
javax.el.ELException: /ui/ajax/basic.xhtml @71,105 listener="#{basicView.handleKeyEvent}": java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.text5" is null
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:71)
        at org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processAjaxBehavior(AjaxBehaviorListenerImpl.java:72)
        at javax.faces.event.AjaxBehaviorEvent.processListener(AjaxBehaviorEvent.java:100)
        at javax.faces.component.behavior.BehaviorBase.broadcast(BehaviorBase.java:82)
        at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:486)
```
