### ISSUE TITLE
DataTable: isLazy() evaluation error for rowExpansion nested table

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#11773]
### Describe the bug

When loading a nested table within the rowExpansion of an outer table, the code to dynamically determine if the inner table is lazy fails on a null value. This works on 13.0.8. Explicitly setting `lazy="false"` on the inner p:dataTable seems to alleviate the problem.

Stacktrace:
```
SEVERE: java.lang.IllegalArgumentException: No bean specified
        at org.apache.commons.beanutils.PropertyUtilsBean.getNestedProperty(PropertyUtilsBean.java:773)
        at org.apache.commons.beanutils.PropertyUtilsBean.getProperty(PropertyUtilsBean.java:885)
        at org.apache.commons.beanutils.PropertyUtils.getProperty(PropertyUtils.java:464)
        at org.apache.commons.beanutils.BeanComparator.compare(BeanComparator.java:163)
        at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
        at java.base/java.util.TreeMap.getEntry(TreeMap.java:344)
        at java.base/java.util.TreeMap.get(TreeMap.java:279)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at javax.el.BeanELResolver.invoke(BeanELResolver.java:155)
        at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:79)
        at org.apache.el.parser.AstValue.getValue(AstValue.java:158)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:181)
        at javax.faces.component.UIData.getValue(UIData.java:742)
        at org.primefaces.component.api.UIData.lambda$isLazy$0(UIData.java:87)
        at org.primefaces.util.ELUtils.getType(ELUtils.java:64)
        at org.primefaces.component.api.UIData.lambda$isLazy$1(UIData.java:85)
        at org.primefaces.util.ComponentUtils.eval(ComponentUtils.java:529)
        at org.primefaces.component.api.UIData.isLazy(UIData.java:81)
        at org.primefaces.component.datatable.DataTable.processEvent(DataTable.java:263)
        at com.sun.faces.lifecycle.RestoreViewPhase$1.visit(RestoreViewPhase.java:438)
        at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:127)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:671)
        at org.primefaces.component.api.UIData.visitColumnContent(UIData.java:887)
        at org.primefaces.component.api.UIData.visitRows(UIData.java:859)
        at org.primefaces.component.datatable.DataTable.visitRows(DataTable.java:763)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:687)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIForm.visitTree(UIForm.java:356)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at com.sun.faces.lifecycle.RestoreViewPhase.deliverPostRestoreStateEvent(RestoreViewPhase.java:433)
        at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:257)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:110)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Reproducer

[rowexpand-el-error.zip](https://github.com/primefaces/primefaces/files/15028825/rowexpand-el-error.zip)

Steps:
1) Start reproducer with `mvn clean jetty:run`
2) Navigate to `localhost:8080`
3) Expand any row

### Expected behavior

Same code works in 13.0.8. 

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-RC3

### Theme

N/A

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

JDK 11

### Browser(s)

All

**Comment by melloware** [comment]
Caused by this change: https://github.com/primefaces/primefaces/issues/10793
