### ISSUE TITLE
FileUpload component has dependency on Apache POI

### ISSUE THREAD

**Issue by antonireus** [primefaces/primefaces#11990]
### Describe the bug

The render of a FileUpload component fails with a `ClassNotFoundException` 

```
java.lang.ClassNotFoundException: org.apache.poi.util.StringUtil
     at org.primefaces.validate.FileValidator.getMetadata(FileValidator.java:165)
     at org.primefaces.renderkit.CoreRenderer.renderValidationMetadata(CoreRenderer.java:793)
     at org.primefaces.component.fileupload.FileUploadRenderer.renderValidation(FileUploadRenderer.java:417)
     at org.primefaces.component.fileupload.FileUploadRenderer.encodeInputField(FileUploadRenderer.java:315)
     at org.primefaces.component.fileupload.FileUploadRenderer.encodeChooseButton(FileUploadRenderer.java:283)
     at org.primefaces.component.fileupload.FileUploadRenderer.encodeAdvancedMarkup(FileUploadRenderer.java:150)
     at org.primefaces.component.fileupload.FileUploadRenderer.encodeMarkup(FileUploadRenderer.java:123)
     at org.primefaces.component.fileupload.FileUploadRenderer.encodeEnd(FileUploadRenderer.java:71)
```

The [dependencies page for PF 14.0.0](https://primefaces.github.io/primefaces/14_0_0/#/gettingstarted/dependencies) only mentions an optional dependency on "Apache Commons FileUpload", and seems that Apache POI shouldn't be required. But the `org.primefaces.validate.FileValidator#getMetadata` method uses the `org.apache.poi.util.StringUtil#isBlank` method.

### Reproducer

Create an empty WAR project with only the primefaces dependency and a page with a FileUpload component

### Expected behavior

Apache POI dependency shouldn't be required

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17.0.9

**Comment by melloware** [comment]
That is a bug.  Fixing for 14.0.1
