### ISSUE TITLE
<p:calendar> attribute valueChangeListener does not work in PF 5.3, when mode="popup"

### ISSUE THREAD

**Issue by ciroppina** [primefaces/primefaces#1219]
The use of the *_valueChangeListener *_ attr. of the `<p:calendar>` is not "exampled" in the:
- primefaces_user_guide_5_3 guide

It looks like is not working, when provided with an existing backing method in the @ManagedBean (or @Model). An exception occurs, whose message is: **Method not found**

Here some code, and the error:

```
<h:form>
<p:calendar
    id="startDate"
    mode="popup"
    navigator="true"
    value="#{startAppModel.aSQLDate}"
    valueChangeListener="#{startAppModel.handleCalendarChanged()}"
    yearRange="c-1:c+1"
    size="7"
    pattern="yyyy-MM-dd"
    readonlyInput="true"
    locale="it"
>
</p:calendar>
</h:form>

```

The Java @Model being:

```
@Model
@SessionScoped ///javax.enterprise.context
public class StartAppModel implements Serializable {

    @Inject
    ExchangeWSApp app;

    private Date aSQLDate;
    public Date getaSQLDate() {
        return aSQLDate;
    }
    public void setaSQLDate(Date aSQLDate) {
        this.aSQLDate = aSQLDate;
    }

    public void start() {
        try {
            //something ...
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Why p:calendar valueChangeListener doesnt call this-one ?
     * @param event
     */
    public void handleCalendarChanged(ValueChangeEvent event) {
        System.out.println("*** Calendar Changed: *** " 
            + event.getNewValue().toString() );
        this.setaSQLDate((Date) event.getSource() );
    }
}
```

I tried both with ValueChangeEvent and SelectEvent - obtaining, at runtime, always the same exception:

```
14:44:22,323 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: JBoss EAP 6.1.0.GA (AS 7.2.0.Final-redhat-8) started in 10094ms - Started 226 of 289 services (56 services are passive or on-demand)
14:44:31,136 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (http-/0.0.0.0:8080-2) JSF1073: javax.faces.event.AbortProcessingException caught during processing of PROCESS_VALIDATIONS 3 : UIComponent-ClientId=j_idt5:actionForm:startDate, Message=JBWEB006019: Method not found: it.skymedia.ews.model.StartAppModel@7c3dc724.handleCalendarChanged()
14:44:31,136 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (http-/0.0.0.0:8080-2) JBWEB006019: Method not found: it.skymedia.ews.model.StartAppModel@7c3dc724.handleCalendarChanged(): javax.faces.event.AbortProcessingException: JBWEB006019: Method not found: it.skymedia.ews.model.StartAppModel@7c3dc724.handleCalendarChanged()
    at javax.faces.event.MethodExpressionValueChangeListener.processValueChange(MethodExpressionValueChangeListener.java:153) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.event.ValueChangeEvent.processListener(ValueChangeEvent.java:134) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:775) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:751) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1166) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76) [jsf-impl-2.1.19-redhat-1.jar:2.1.19-redhat-1]
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.1.19-redhat-1.jar:2.1.19-redhat-1]
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118) [jsf-impl-2.1.19-redhat-1.jar:2.1.19-redhat-1]
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
```

Finally, some application specs:
- mvn/pom webapp appliaction servlet 3.1
- runtime: jboss-eap-6.1 (means: 7.2.0 Final)
- jbposs ejb api 3.2
- jsf api specs 2.2 [provided]
- el-api 2.2.1-b04
- el-impl 1.0
- primefaces 5.3
- o.s. Windows 8.1
- browser: FF 44

**Comment by tandraschko** [comment]
#{startAppModel.handleCalendarChanged()} means that your method doesn't have a parameter.

As you use ValueChangeEvent, you have to use #{startAppModel.handleCalendarChanged} 

Not related to PF, but to the EL specs.
