### ISSUE TITLE
Command*: throws exception when not placed inside a form, even when reference a form

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12194]
```
                                <p:commandLink id="link" action="#{sessionController.destroy()}" ajax="false" form="logout">
                                    <i class="pi pi-power-off"></i>
                                    <h6>Logout</h6>
                                </p:commandLink>

                                <h:form id="logout">
                                </h:form>
```

Exception:

```
2024-06-26 20:08:57,087 SEVERE [org.pri.app.exc.PrimeExceptionHandler] (executor-thread-48) Commandlink "link" must be inside a form component: jakarta.faces.FacesException: Commandlink "link" must be inside a form component
	at org.primefaces.component.commandlink.CommandLinkRenderer.encodeMarkup(CommandLinkRenderer.java:110)
	at org.primefaces.component.commandlink.CommandLinkRenderer.encodeEnd(CommandLinkRenderer.java:67)
```

**Comment by tandraschko** [comment]
nvm, it works fine when using ajax=true
and it cant work with ajax=false by design
