### ISSUE TITLE
DataTable: support read-only fields for filtering/sorting

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12354]
currently if you define a field, which does not have a setter, a exception will be thrown:

```
java.beans.IntrospectionException: Method not found: setId
	at java.desktop/java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:114)
	at java.desktop/java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:74)
	at org.primefaces.util.PropertyDescriptorResolver$DefaultResolver.lambda$getSimpleProperty$1(PropertyDescriptorResolver.java:99)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.primefaces.util.PropertyDescriptorResolver$DefaultResolver.getSimpleProperty(PropertyDescriptorResolver.java:97)
	at org.primefaces.util.PropertyDescriptorResolver$DefaultResolver.getValue(PropertyDescriptorResolver.java:77)
	at org.primefaces.util.SortTableComparator$FieldMapper.map(SortTableComparator.java:182)
	at org.primefaces.util.SortTableComparator.compareWithMapper(SortTableComparator.java:89)
	at org.primefaces.util.SortTableComparator.compare(SortTableComparator.java:77)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at org.primefaces.model.DefaultLazyDataModel.sort(DefaultLazyDataModel.java:86)
	at org.primefaces.model.DefaultLazyDataModel.load(DefaultLazyDataModel.java:69)
```

currently DataTable only need to read the field and something you dont have the chance to add a setter to a legacy backend code - 
we should support it

**Comment by tandraschko** [comment]
@melloware could you do me a favor and port to 14.x? sorry, dont have time currently, to much customer projects

**Comment by melloware** [comment]
Yep I got it!

**Comment by tandraschko** [comment]
even lost the commit on my fork, would be happy if you can also port to master ;D sorry!

**Comment by melloware** [comment]
yep i got it!
