### ISSUE TITLE
Spinner: Exception when entering only thousandSeparator

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#12365]
### Describe the bug

When entering only the thousandSeparator in a non-required spinner, a NumberFormatException is thrown on postback.

### Reproducer

[primefaces-test.zip](https://github.com/user-attachments/files/16454987/primefaces-test.zip)

1. Enter only your thousandSeparator (so probably . for you melloware :wink:)
2. Click the button
3. Exception in the log (would crash an application with proper AJAX error handler)
4. Yes, users are stupid

### Expected behavior

No error occurs and the value NULL is written to the associated field.

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.3

### JSF implementation

All

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
Let me add another integration test i have one for a similar issue.

**Comment by melloware** [comment]
@mkomko i am using your reproducer and I get no errors?

**Comment by mkomko** [comment]
@melloware Did you check the log output?

**Comment by melloware** [comment]
OHHHH I didn't follow your instructions exactly.  You mean literally just enter the thousand separator like `,` and now yes I get this..

```
Aug 01, 2024 8:17:07 AM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.NumberFormatException: empty String
java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:651)
        at org.primefaces.component.spinner.SpinnerRenderer.decode(SpinnerRenderer.java:69)
        at jakarta.faces.component.UIComponentBase.decode(UIComponentBase.java:499)
        at jakarta.faces.component.UIInput.decode(UIInput.java:646)
        at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:871)
        at jakarta.faces.component.UIInput.processDecodes(UIInput.java:550)
        at jakarta.faces.component.UIForm.processDecodes(UIForm.java:191)
        at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:866)
        at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:866)
        at jakarta.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:997)
        at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:51)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:131)
        at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
        at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1370)
        at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
        at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
        at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
        at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
```

**Comment by melloware** [comment]
PR submitted with Integration Test
