### ISSUE TITLE
PFS: update using @widgetVar crashes when migrating from 13.0.10 to 14.0.x

### ISSUE THREAD

**Issue by matsandreassen-triona** [primefaces/primefaces#12470]
### Describe the bug

The following is code I used in the reproducer project, but it works (unfortunately for me).

```xml
<p:tabView id="PeriodTabView" widgetVar="PeriodTabViewWdg">

                <p:tab title="Tab #1">

                    <p:dataTable>
                        <f:facet name="header">
                            <p:commandButton value="Ka-blam!" process="@this" update="@widgetVar(PeriodTabViewWdg)" />
                        </f:facet>
                    </p:dataTable>

                </p:tab>

</p:tabView>
```

My code is, of course, a lot more complex, but it was working fine, and it still does after downgrading, but after upgrading to 14.x I now encounter:

`jakarta.faces.FacesException: Expression does not match following pattern @widgetVar(var). Expression: "widgetVar(PeriodTabViewWdg)"
	at org.primefaces.expression.WidgetVarSearchKeywordResolver.resolve(WidgetVarSearchKeywordResolver.java:66)
	at com.sun.faces.component.search.CompositeSearchKeywordResolver.resolve(CompositeSearchKeywordResolver.java:52)
	at com.sun.faces.component.search.SearchExpressionHandlerImpl.invokeKeywordResolvers(SearchExpressionHandlerImpl.java:315)
	at com.sun.faces.component.search.SearchExpressionHandlerImpl.invokeOnComponent(SearchExpressionHandlerImpl.java:269)
	at jakarta.faces.component.search.SearchExpressionHandler.invokeOnComponent(SearchExpressionHandler.java:180)
	at com.sun.faces.component.search.SearchExpressionHandlerImpl.resolveClientIds(SearchExpressionHandlerImpl.java:109)
	at org.primefaces.expression.SearchExpressionUtils.resolveClientIdsAsString(SearchExpressionUtils.java:132)
	at org.primefaces.util.AjaxRequestBuilder.addExpressions(AjaxRequestBuilder.java:156)
	at org.primefaces.util.AjaxRequestBuilder.update(AjaxRequestBuilder.java:148)
	at org.primefaces.renderkit.CoreRenderer.preConfiguredAjaxRequestBuilder(CoreRenderer.java:468)
	at org.primefaces.renderkit.CoreRenderer.buildAjaxRequest(CoreRenderer.java:489)
	at org.primefaces.renderkit.CoreRenderer.buildAjaxRequest(CoreRenderer.java:485)
	at org.primefaces.component.commandbutton.CommandButtonRenderer.buildRequest(CommandButtonRenderer.java:154)
Caused by: java.lang.NullPointerException: Cannot invoke "jakarta.faces.component.UIComponent.getClientId(jakarta.faces.context.FacesContext)" because "target" is null
	at com.sun.faces.component.search.SearchExpressionHandlerImpl$ResolveClientIdsCallback.invokeContextCallback(SearchExpressionHandlerImpl.java:132)
	at jakarta.faces.component.search.SearchKeywordContext.invokeContextCallback(SearchKeywordContext.java:65)
	at org.primefaces.expression.WidgetVarSearchKeywordResolver.resolve(WidgetVarSearchKeywordResolver.java:58)
	`

I've debugged it, and the pattern does actually match, but 

```java
WidgetVarVisitCallback visitCallback = new WidgetVarVisitCallback(matcher.group(1));
context.getSearchExpressionContext().getFacesContext().getViewRoot().visitTree(
        VisitContext.createVisitContext(context.getSearchExpressionContext().getFacesContext(), null,
                ComponentUtils.VISIT_HINTS_SKIP_UNRENDERED),
        visitCallback);
```
                        
never finds the _target_ and proceeds to provoke an NPE.

### Reproducer

I would provide it, but I'm unable to reproduce in the reproducer.

### Expected behavior

The rendering should not crash on xhtml load.

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.x

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

21

**Comment by tandraschko** [comment]
thats by design
the search expression starts relative from commandButton but its not a child. You may do something like `@form:@widgetVar(PeriodTabViewWdg)` or `@root:@widgetVar(PeriodTabViewWdg)`

**Comment by matsandreassen-triona** [comment]
Oh. I thought widget variables had to be unique and therefore that @widgetVar isn't interpreted relatively. Thx for the supremely quick feedback.

**Comment by tandraschko** [comment]
we replaced the engine by the native jsf search expressions

**Comment by tandraschko** [comment]
but wait, it actually still uses the root
`context.getSearchExpressionContext().getFacesContext().getViewRoot().visitTree(`

**Comment by tandraschko** [comment]
then its a bug propably

**Comment by matsandreassen-triona** [comment]
That's good. Attempting to prepend @form: did not work (same error).

**Comment by melloware** [comment]
@matsandreassen-triona with your reproducer you couldn't reproduce did you try it with both `-Pmojarra40` and `-Pmyfaces40` to see if it was different between MyFaces and Mojarra?

**Comment by matsandreassen-triona** [comment]
I've tried both now. No change.

For what it's worth, you might want to change the last exception message thrown in WidgetVarSearchKeywordResolver to something more appropriate since it wrongly indicates that there was something wrong with the expression itself.

Back to my problem. I've tried stepping through `org.primefaces.expression.WidgetVarVisitCallback `as it is being called, watching the _target_ variable:

```java
public VisitResult visit(VisitContext context, UIComponent target) {
        if (target instanceof Widget && this.widgetVar.equalsIgnoreCase(((Widget)target).resolveWidgetVar(context.getFacesContext()))) {
            this.component = target;
            return VisitResult.COMPLETE;
        } else {
            return VisitResult.ACCEPT;
        }
    }
```

Only one iteration contains a TabView instance, but it's another TabView further up in the DOM.

**Comment by tandraschko** [comment]
could anyone create a IT for it?

**Comment by tandraschko** [comment]
i cant reproduce it, however i fixed the weird, unexpected exception

everything else needs a reproducer or integration test.

**Comment by tandraschko** [comment]
@melloware can you port it to 14.x branch?

**Comment by melloware** [comment]
Yes thanks for the fix!  @matsandreassen-triona let us know if you can reproduce the issue i know you were having trouble reproducing it locally.

**Comment by matsandreassen-triona** [comment]
Is it possible to test a snapshot version after you applied this fix?

**Comment by melloware** [comment]
@matsandreassen-triona sure check out the 14.X branch here and run `mvn clean install` https://github.com/primefaces/primefaces/tree/14.X that will be 14.0.5-SNAPSHOT for you to use.

**Comment by tandraschko** [comment]
thats not a fix at all, it should just give you the correct exception / error
