### ISSUE TITLE
Datepicker: NullPointerException if user blanks out left hand part of the input field

### ISSUE THREAD

**Issue by ismart-dev** [primefaces/primefaces#12639]
### Describe the bug

To reproduce:

```
    <p:datePicker
      id="dateRangePicker"
      showButtonPanel="true"
      showOtherMonths="true"
      monthNavigator="true"
      yearNavigator="true"
      selectOtherMonths="true"
      value="#{dateParameterBean.dateRange}"
      validatorMessage="Invalid date range"
      selectionMode="range"
      navigator="true"
      showOn="button"
      pattern="dd/MMM/yy"
      widgetVar="dateRangePickerVar">
      <p:ajax event="dateSelect" update="#{update}"/>
      <p:ajax event="change" update="#{update}"/>
    </p:datePicker>
```

- Click on the date picker's input field and select a date range - all good
- Edit the contents of the input field and delete the first part so it reads something like ' - 30/Sep/24'
- This will cause the following exception:

```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.util.List.get(int)" is null
	at org.primefaces.component.datepicker.DatePicker.validateValueInternal(DatePicker.java:185)
	at org.primefaces.component.datepicker.DatePicker.validateValue(DatePicker.java:124)
	at javax.faces.component.UIInput.validate(UIInput.java:633)
	at org.primefaces.component.datepicker.DatePicker.validate(DatePicker.java:101)
	at javax.faces.component.UIInput.processValidators(UIInput.java:282)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1458)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:788)
	at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1019)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
...
```

Specifically, within org.primefaces.component.datepicker.DatePicker, function validateValueInternal(FacesContext context, Object value), the following code block near the end:

```
      else {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, rangeValues.get(0).getClass().getTypeName() + " not supported", null);
                context.addMessage(getClientId(context), message);
            }

```    
It assumes rangeValues contains a non-null entry as the first element of the list.

I haven't formally tested whether this reproduces with the latest version of Primefaces, but have reviewed the code on master and it looks to be the same.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.7

### JSF implementation

MyFaces

### JSF version

2.2.12

### Java version

17

### Browser(s)

Firefox 130.0.1

**Comment by melloware** [comment]
@ismart-dev i suspect your correct any chnace you could put together a simple reproducer using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project. 

It will help you verify its a problem in 14.0.5 and help us fix it.

**Comment by melloware** [comment]
Reproducer:
[pf-12639.zip](https://github.com/user-attachments/files/17152772/pf-12639.zip)

**Comment by ismart-dev** [comment]
Many thanks for such a quick fix!
