### ISSUE TITLE
DataTable: the EL of filter resetValue() function cannot be resolved in the composite component

### ISSUE THREAD

**Issue by lih13800** [primefaces/primefaces#12695]
### Describe the bug

Hello, when I try to call the resetValue() function of the DataTable class, its EL of filter cannot be resolved in the composite component.

In the providing simple sample, the data table is build up with composite component of JSF. When I try to reset the filter value, it gets following error on console.
```
ERROR Utilities: - called: handleError('javax.el.PropertyNotFoundException: /resources/components/general_datatable_component/general_datatable.xhtml @302,12 filteredValue="#{cc.attrs.beanName.filteredValues}": Target Unreachable, identifier [cc] resolved to null', 'READ')
ERROR Utilities: - handling Exception
javax.el.PropertyNotFoundException: /resources/components/general_datatable_component/general_datatable.xhtml @302,12 filteredValue="#{cc.attrs.beanName.filteredValues}": Target Unreachable, identifier [cc] resolved to null
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:133) ~[jsf-impl-2.2.14.jar:2.2.14]
	at org.primefaces.component.datatable.DataTable.setFilteredValue(DataTable.java:967) ~[primefaces-13.0.0.jar:13.0.0]
	at org.primefaces.component.datatable.DataTable.resetValue(DataTable.java:551) ~[primefaces-13.0.0.jar:13.0.0]
ERROR Utilities: - called: handleError('javax.el.PropertyNotFoundException: /resources/components/general_datatable_component/general_datatable.xhtml @302,12 filteredValue="#{cc.attrs.beanName.filteredValues}": Target Unreachable, identifier [cc] resolved to null', 'READ')
ERROR Utilities: - handling Exception
javax.el.PropertyNotFoundException: /resources/components/general_datatable_component/general_datatable.xhtml @302,12 filteredValue="#{cc.attrs.beanName.filteredValues}": Target Unreachable, identifier [cc] resolved to null
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:133) ~[jsf-impl-2.2.14.jar:2.2.14]
	at org.primefaces.component.datatable.DataTable.setFilteredValue(DataTable.java:967) ~[primefaces-13.0.0.jar:13.0.0]
	at org.primefaces.component.datatable.DataTable.resetValue(DataTable.java:551) ~[primefaces-13.0.0.jar:13.0.0]

```

This error comes from the setFilteredValue() in DataTableBase.java file. In previous versions like PF6.2 https://github.com/primefaces/primefaces/blob/acd27bd5b14394eec8fb70f4b236f5b9fea32826/primefaces/src/main/java/org/primefaces/component/datatable/DataTableBase.java#L288-L290, it does not have this error . The problem occurs after the change in this commit https://github.com/primefaces/primefaces/commit/24c939e62d51a5ea0a341675b95f997cca1cc7e0#diff-4701970a7aabff8b155f0f3a7e3c2a54291a39b17a4176684c82ed83cb8fe53eR953-R958

I replicate the issue on PF14 test. Please have a review on it.
[primefaces-test-14.0.0.zip](https://github.com/user-attachments/files/17296960/primefaces-test-14.0.0.zip)

### Reproducer

1. input anything in the filter of data table.
2. click the 'reset' button under the table
3. go to the console, there is error message there

### Expected behavior

No error message on console and values should be reset on filter.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 130.0.1

**Comment by melloware** [comment]
This was the bug it fixed: https://github.com/primefaces/primefaces/issues/7999

**Comment by melloware** [comment]
Could be related: https://github.com/primefaces/primefaces/issues/9990

**Comment by tandraschko** [comment]
You cant use findComponent, you need visitTree or invokeOnComponent. Thats by design.

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/issues/12664#event-14561231790

This should also work

**Comment by jxmai** [comment]
It looks like changing from 

```java
public void setFilteredValue(java.util.List<?> filteredValue) {
    getStateHelper().put(PropertyKeys.filteredValue, filteredValue);
}
```

to

```java
public void setFilteredValue(java.util.List<?> filteredValue) {
    ValueExpression ve = getValueExpression(PropertyKeys.filteredValue.name());
    if (ve != null) {
        ve.setValue(getFacesContext().getELContext(), filteredValue);
    }
}
```

in #7999 via https://github.com/primefaces/primefaces/commit/24c939e62d51a5ea0a341675b95f997cca1cc7e0#diff-4701970a7aabff8b155f0f3a7e3c2a54291a39b17a4176684c82ed83cb8fe53eR953-R958
may introduce different behaviour for cc resolution.

the original method  stores the filteredValue in the component's state using the StateHelper. It directly interacts with the component's state map. The new method uses ValueExpression but composite components often do not have direct ValueExpression bindings for their internal properties which is in result of null.

In the case of the user: If the composite component depends on getStateHelper().put to store and retrieve values, switching to ValueExpression may disrupt its behavior.

Should this be classified as breaking changes in PF 11?

**Comment by lih13800** [comment]
findComponent works for the sample code. It can locate the data table even it build by context like CC

![image](https://github.com/user-attachments/assets/28f11e04-04e0-40d6-9572-e843686c7f07)

The issue should be caused by change of setFilteredValue() mentioned. This change might have different behaviour for cc resolution.

**Comment by tandraschko** [comment]
findComponent resolves the DT but there is no parent CC context like i said, this wont work.

**Comment by tandraschko** [comment]
@jxmai yeah, feel free to add it to the migration guide
this was by design in #7999

**Comment by jxmai** [comment]
@lih13800 Please try:

[primefaces-test-14.0.0-fix.zip](https://github.com/user-attachments/files/31107180/primefaces-test-14.0.0-fix.zip)

Yes, It is by design that filteredValue is now a genuine EL binding in #7999, what it means is that it binds to directly resolvable bean in normal bean scope, there's no cc context entirely. It is Faces spec, not related to Primefaces, so any EL outside of the traversal fails.

Admittedly that's a breaking change but previously it was more like worked by accident, it is understandable that we did not provide a fallback but hard fail in this case.

To address this, following the recommendation, https://github.com/primefaces/primefaces/issues/12695#issuecomment-2400554818, one of the options is to use visitTree.

In the sample, TestView.java, add the following import:

```java
import java.util.EnumSet;
import javax.faces.component.visit.VisitContext;
import javax.faces.component.visit.VisitHint;
import javax.faces.component.visit.VisitResult;
```

Replace the resetDataTable method to the following:

```java
public void resetDataTable() {
        FacesContext context = FacesContext.getCurrentInstance();

        context.getViewRoot().visitTree(
                VisitContext.createVisitContext(context, null, EnumSet.of(VisitHint.SKIP_UNRENDERED)),
                (visitContext, target) -> {
                    if (target instanceof DataTable && TABLE_PATH.equals(target.getClientId(visitContext.getFacesContext()))) {
                        DataTable dataTable = (DataTable) target;
                        dataTable.resetValue();
                        dataTable.setFilterByAsMap(null);
                        return VisitResult.COMPLETE;
                    }
                    return VisitResult.ACCEPT;
                });
    }
```

One subtle details related to the sample is to add `partialSubmit="true"` attribute to the reset button makes PF serialize only the components in process (the button itself) instead of the whole form. The reason is that the filter input values are no longer in the request parameter map, the renderer's fallback has nothing to re-display, and the inputs render empty. And of course, alternatively, we can use client side clearFilter to reset the input from the UI.

**Comment by lih13800** [comment]
Thank you @jxmai. This approach works with the button successfully. However, if we put the 'resetDataTable()' on the under @PostConstruct  function. You will get following exception appearing on the console repeatedly. I also provide the sample for testing.

[primefaces-test-14.0.0.zip](https://github.com/user-attachments/files/31226644/primefaces-test-14.0.0.zip)

Please try to put the function in this area and run the project. The error would be shown.

<img width="584" height="442" alt="Image" src="https://github.com/user-attachments/assets/08a42d37-f4dc-4912-be0e-f9c20917e825" />

```
Caused by: com.sun.faces.spi.InjectionProviderException
        at com.sun.faces.vendor.WebContainerInjectionProvider.invokeAnnotatedMethod(WebContainerInjectionProvider.java:85)
        at com.sun.faces.vendor.WebContainerInjectionProvider.invokePostConstruct(WebContainerInjectionProvider.java:70)
        at com.sun.faces.mgbean.BeanBuilder.invokePostConstruct(BeanBuilder.java:197)
        at com.sun.faces.mgbean.BeanBuilder.build(BeanBuilder.java:79)
        at com.sun.faces.mgbean.BeanManager.createAndPush(BeanManager.java:387)
        at com.sun.faces.mgbean.BeanManager.create(BeanManager.java:247)
        at com.sun.faces.el.ManagedBeanELResolver.resolveBean(ManagedBeanELResolver.java:200)
        at com.sun.faces.el.ManagedBeanELResolver.getValue(ManagedBeanELResolver.java:55)
        at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:156)
        at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:184)
        at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:93)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
        at javax.faces.component.UIComponentBase$AttributesMap.get(UIComponentBase.java:2018)
        at com.sun.faces.el.CompositeComponentAttributesELResolver$ExpressionEvalMap.get(CompositeComponentAttributesELResolver.java:381)
        at javax.el.MapELResolver.getValue(MapELResolver.java:61)
        at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:156)
        at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:184)
        at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at com.sun.faces.facelets.el.ContextualCompositeValueExpression.getValue(ContextualCompositeValueExpression.java:117)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:181)
        at javax.faces.component.UIData.getValue(UIData.java:742)
        at javax.faces.component.UIData.getDataModel(UIData.java:1850)
        at org.primefaces.component.api.UIData.setRowModel(UIData.java:420)
        at org.primefaces.component.api.UIData.setRowIndexWithoutRowStatePreserved(UIData.java:413)
        at org.primefaces.component.api.UIData.setRowIndex(UIData.java:473)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:665)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:150)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIForm.visitTree(UIForm.java:356)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469)
        at org.primefaces.test.TestView.resetDataTable(TestView.java:61)
        at org.primefaces.test.TestView.init(TestView.java:52)
```

**Comment by jxmai** [comment]
@lih13800 Calling resetDataTable() in `@PostConstruct` is an anti-pattern, A `@ViewScoped` bean is created fresh on each new GET. filteredValues is null, and the DataTable's filter state (filterByAsMap) is empty by default. So on a normal first load, the filter is already empty, there's nothing to clear. You don't need resetDataTable() for that.

resetDataTable() does visitTree on the view root, while in the PostContruct phase, the view is still being built, violating the lifecycle.

Please remove resetDataTable from postContruct in the provided sample.
