### ISSUE TITLE
selectBooleanCheckbox/selectBooleanButton: add support for converters

### ISSUE THREAD

**Issue by crick77** [primefaces/primefaces#12851]
### Describe the bug

In my application I need to use switch that will set a 0 or 1 (I cannot change database field to boolean) on an integer field. For that purpose I've written a Faces Converter that converts boolean to int (0 or 1) and works flawlessly unitil I use toggleSwitch. When I use one of the two mentioned component the converter is not called anymore.

### PrimeFaces edition

None

### PrimeFaces version

14.0.6

### Theme

Verona

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17.0.2 LTS

**Comment by tandraschko** [comment]
the code in selectBooleanButton looks the same in toggleSwitch.
a reproducer will help here.

**Comment by crick77** [comment]
Here it is... 

There are simply 3 components (toggle, booleanbutton and booleancheckbox)
If you remove button and checkbox it works (so with only toggleswitch) instead if you add one (or both) of them a 500 error occur (canno convert 0 (integer) to boolean).

thank you!

[TestProjects.zip](https://github.com/user-attachments/files/17674887/TestProjects.zip)

**Comment by crick77** [comment]
Here it is...

There are simply 3 components (toggle, booleanbutton and booleancheckbox)
If you remove button and checkbox it works (so with only toggleswitch) instead if you add one (or both) of them a 500 error occur (canno convert 0 (integer) to boolean).

thank you!

[Uploading primefaces-test.zip…]()

**Comment by melloware** [comment]
Thanks for the reproducer i will take a look.

**Comment by melloware** [comment]
Confirmed and there is not much in the stack trace exactly where its happening.

**Comment by melloware** [comment]
Both button and checkbox extend `HtmlSelectBooleanCheckbox` while SelectBooleanButton does not. That is the only thing I see in common with the two not working components.

**Comment by melloware** [comment]
@crick77 this might be a Mojarra bug?  I confirmed it fails with Mojarra and passes with MyFaces.

`mvn clean jetty:run -Pmojarra40` - FAILS

`mvn clean jetty:run -Pmyfaces40` WORKS!

**Comment by melloware** [comment]
OK so the page loads now with MyFaces but when you press the `selectBooleanButton` you get this stack trace.

```
Nov 09, 2024 8:54:36 AM org.apache.myfaces.context.ExceptionHandlerUtils logException
SEVERE: jakarta.faces.component.UpdateModelException occured while processing UPDATE_MODEL_VALUES [Location=/test.xhtml at line 22 and column 100, value="#{testView.buttonValue}", clientId="frmTest:j_id_b"]
jakarta.faces.component.UpdateModelException: org.apache.myfaces.view.facelets.el.ContextAwareELException: jakarta.el.ELException: Cannot convert [true] of type [class java.lang.Boolean] to [class java.lang.Integer]
        at jakarta.faces.component.UIInput.updateModel(UIInput.java:421)
        at jakarta.faces.component.UIInput.processUpdates(UIInput.java:351)
        at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:721)
        at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:226)
        at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:880)
        at jakarta.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1120)
        at jakarta.faces.component.UIForm.visitTree(UIForm.java:343)
        at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:908)
        at jakarta.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1120)
        at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:908)
        at jakarta.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1120)
        at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialExecute(PartialViewContextImpl.java:407)
        at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:388)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:61)
        at jakarta.faces.component.UIViewRoot$UpdateModelPhaseProcessor.process(UIViewRoot.java:1884)
        at jakarta.faces.component.UIViewRoot._process(UIViewRoot.java:1714)
        at jakarta.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:979)
        at org.apache.myfaces.lifecycle.UpdateModelValuesExecutor.execute(UpdateModelValuesExecutor.java:39)
        at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:172)
        at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:125)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:223)
        at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1370)
        at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
        at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:819)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
        at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
        at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
        at org.eclipse.jetty.server.Server.handle(Server.java:182)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.myfaces.view.facelets.el.ContextAwareELException: jakarta.el.ELException: Cannot convert [true] of type [class java.lang.Boolean] to [class java.lang.Integer]
        at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.setValue(ContextAwareTagValueExpression.java:166)
        at jakarta.faces.component.UIInput.updateModel(UIInput.java:403)
        ... 48 more
Caused by: jakarta.el.ELException: Cannot convert [true] of type [class java.lang.Boolean] to [class java.lang.Integer]
        at org.apache.el.lang.ELSupport.coerceToNumber(ELSupport.java:387)
        at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:526)
        at org.apache.el.parser.AstValue.setValue(AstValue.java:192)
        at org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:199)
        at org.jboss.weld.module.web.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
        at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.setValue(ContextAwareTagValueExpression.java:153)
```

**Comment by crick77** [comment]
Same exception as mine...at least myfaces gives you more information (page, component and line number)...with mojarra you have to do target shooting. I don't know components inheritance tree but just make this two derive from the same class as ToggleSwitch (which works)?

**Comment by melloware** [comment]
@crick77 its not that simple....we need to get to the bottom of why unless its something core with `HtmlCheckBox` at the Faces level.

**Comment by melloware** [comment]
@tandraschko correct this gives the exact same error.

```xml
<h:selectBooleanCheckbox value="#{testView.checkboxValue}" converter="booleanIntConverter" />
```

![image](https://github.com/user-attachments/assets/e478f720-3f76-462b-aab7-931bec48a7c5)

**Comment by crick77** [comment]
> @crick77 its not that simple....we need to get to the bottom of why unless its something core with `HtmlCheckBox` at the Faces level.

I know but perhaps is a wanted behaviour per design of htmlcheckbox....I mean you are dealing with boolean and the converter is simply ignored.

**Comment by melloware** [comment]
@crick77 here is a post from BalusC explaining exactly why this won't work: https://stackoverflow.com/a/6356969/502366

**Comment by crick77** [comment]
Yep...As I supposed and wrote in the post before it is per-design. Thank you.
