### ISSUE TITLE
CSP: "Missing CSP nonce" on error page

### ISSUE THREAD

**Issue by jbb01** [primefaces/primefaces#12901]
### Describe the bug

When a POST request throws an exception and is redirected to the configured custom error page, Primefaces fails to get the current CSP and throws a `CspException`, preventing the custom error page from being displayed. Instead, Tomcat renders its default error page for the original exception and logs the following

```
18-Nov-2024 14:40:45.195 SCHWERWIEGEND [http-nio-8080-exec-5] org.apache.catalina.core.StandardHostValve.custom Exception Processing [ErrorPage[errorCode=0, location=/error.xhtml]]
	jakarta.servlet.ServletException: Missing CSP nonce
		at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:709)
		at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:632)
		at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:410)
		at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:330)
		at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:267)
		at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:362)
		at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:222)
		at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:308)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:149)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
	Caused by: org.primefaces.csp.CspException: Missing CSP nonce
		at org.primefaces.csp.CspState.validate(CspState.java:92)
		at org.primefaces.csp.CspState.getNonce(CspState.java:71)
		at org.primefaces.csp.CspPhaseListener.initCsp(CspPhaseListener.java:94)
		at org.primefaces.csp.CspPhaseListener.beforePhase(CspPhaseListener.java:66)
		at com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:179)
		at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:70)
		at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
		at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
		... 24 more
```

### Reproducer

[demo.zip](https://github.com/user-attachments/files/17801071/demo.zip)

/webapp/index.xhtml
```xml
<!DOCTYPE html>
<html xmlns:h="jakarta.faces.html" lang="en">
<h:head>
    <title>Index</title>
</h:head>
<h:body>
    <h:form>
        <h:commandButton action="#{indexBean.action()}" value="Button"/>
    </h:form>
</h:body>
</html>
```

/webapp/error.xhtml
```xml
<!DOCTYPE html>
<html xmlns:h="jakarta.faces.html" lang="en">
<h:head>
    <title>Error</title>
</h:head>
<h:body>
    An error occurred.
</h:body>
</html>
```

/java/org/example/demo1/IndexBean.java
```java
package org.example.demo1;

import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Named;

@Named
@RequestScoped
public class IndexBean {

    public void action() {
        throw new RuntimeException("Something has gone wrong.");
    }
}
```

/webapp/WEB-INF/web.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="6.0" xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_6_0.xsd">

    <context-param>
        <param-name>primefaces.CSP</param-name>
        <param-value>true</param-value>
    </context-param>

    <servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>jakarta.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>

    <error-page>
        <location>/error.xhtml</location>
    </error-page>
</web-app>
```

### Expected behavior

Primefaces should be aware of error requests and not handle them the same as all other postback requests. A new CspState should be created and the custom error page should be rendered.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.7

### JSF implementation

Mojarra

### JSF version

4.0.4

### Java version

21.0.2

**Comment by tandraschko** [comment]
do you use PF ExceptionHandler?

i think default servlet exception handling does a forward; ours hould redirect

**Comment by jbb01** [comment]
> do you use PF ExceptionHandler?
> 
> i think default servlet exception handling does a forward; ours should redirect

I did not configure an exception handler manually, so I'm only using it if Primefaces configures it automatically. I agree that using a redirect instead of a forward would probably fix the issue, but I would prefer to use forwards.

> please fix your example to use primefaces-test repository, so we can just run with jetty also i need some steps to replicate

I'm not familiar with jetty, but I'll see what I can do. As for steps to replicate: Just go to the index page and click the button.

**Comment by jbb01** [comment]
I am also irritated by the warning message, but I still think that PF is in the wrong here. When I run jetty with `--debug` I get the following stacktrace from `org.eclipse.jetty.ee10.servlet.ErrorHandler`

```
[DEBUG] Unable to call error dispatcher
jakarta.servlet.ServletException: Missing CSP nonce
    at jakarta.faces.webapp.FacesServlet.executeLifecyle (FacesServlet.java:709)
    at jakarta.faces.webapp.FacesServlet.service (FacesServlet.java:449)
    at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service (ServletHolder.java:1370)
    at org.eclipse.jetty.ee10.servlet.ServletHolder.handle (ServletHolder.java:736)
    at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter (ServletHandler.java:1614)
    at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle (ServletHandler.java:1547)
    at org.eclipse.jetty.ee10.servlet.Dispatcher.error (Dispatcher.java:115)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.handle (ErrorHandler.java:114)
    at org.eclipse.jetty.ee10.servlet.ServletChannel.handle (ServletChannel.java:496)
    at org.eclipse.jetty.ee10.servlet.ServletHandler.handle (ServletHandler.java:464)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:575)
    at org.eclipse.jetty.ee10.servlet.SessionHandler.handle (SessionHandler.java:717)
    at org.eclipse.jetty.server.handler.ContextHandler.handle (ContextHandler.java:1060)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:151)
    at org.eclipse.jetty.server.Server.handle (Server.java:182)
    at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run (HttpChannelState.java:662)
    at org.eclipse.jetty.server.internal.HttpConnection.onFillable (HttpConnection.java:418)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:322)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:99)
    at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run (SelectableChannelEndPoint.java:53)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:979)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob (QueuedThreadPool.java:1209)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (QueuedThreadPool.java:1164)
    at java.lang.Thread.run (Thread.java:1583)
Caused by: org.primefaces.csp.CspException: Missing CSP nonce
    at org.primefaces.csp.CspState.validate (CspState.java:92)
    at org.primefaces.csp.CspState.getNonce (CspState.java:71)
    at org.primefaces.csp.CspPhaseListener.initCsp (CspPhaseListener.java:94)
    at org.primefaces.csp.CspPhaseListener.beforePhase (CspPhaseListener.java:66)
    at com.sun.faces.lifecycle.Phase.handleBeforePhase (Phase.java:179)
    at com.sun.faces.lifecycle.Phase.doPhase (Phase.java:70)
    at com.sun.faces.lifecycle.LifecycleImpl.render (LifecycleImpl.java:150)
    at jakarta.faces.webapp.FacesServlet.executeLifecyle (FacesServlet.java:692)
    at jakarta.faces.webapp.FacesServlet.service (FacesServlet.java:449)
    at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service (ServletHolder.java:1370)
    at org.eclipse.jetty.ee10.servlet.ServletHolder.handle (ServletHolder.java:736)
    at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter (ServletHandler.java:1614)
    at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle (ServletHandler.java:1547)
    at org.eclipse.jetty.ee10.servlet.Dispatcher.error (Dispatcher.java:115)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.handle (ErrorHandler.java:114)
    at org.eclipse.jetty.ee10.servlet.ServletChannel.handle (ServletChannel.java:496)
    at org.eclipse.jetty.ee10.servlet.ServletHandler.handle (ServletHandler.java:464)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:575)
    at org.eclipse.jetty.ee10.servlet.SessionHandler.handle (SessionHandler.java:717)
    at org.eclipse.jetty.server.handler.ContextHandler.handle (ContextHandler.java:1060)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:151)
    at org.eclipse.jetty.server.Server.handle (Server.java:182)
    at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run (HttpChannelState.java:662)
    at org.eclipse.jetty.server.internal.HttpConnection.onFillable (HttpConnection.java:418)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:322)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:99)
    at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run (SelectableChannelEndPoint.java:53)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:979)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob (QueuedThreadPool.java:1209)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (QueuedThreadPool.java:1164)
    at java.lang.Thread.run (Thread.java:1583)
```

Looking at the [source code](https://github.com/jetty/jetty.project/blob/0b851fce3fb89180b965f894ec215d21cd98f095/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ErrorHandler.java#L125) of jetty, this message is logged when rendering the custom error page fails.

The debug log also reveals the cause for the "Error page too large" message, which can be traced back to the rendering of jetty's default error page.

```
[WARNING] Error page too large: 500 jakarta.servlet.ServletException: Something went wrong ServletApiRequest@1ae350aa{ServletContextRequest@750b84a4{POST@74345c69 http://localhost:8080/test.xhtml HTTP/1.1}}
java.nio.BufferOverflowException
    at java.nio.ByteBuffer.put (ByteBuffer.java:1210)
    at org.eclipse.jetty.util.BufferUtil.append (BufferUtil.java:484)
    at org.eclipse.jetty.io.ByteBufferOutputStream.write (ByteBufferOutputStream.java:50)
    at sun.nio.cs.StreamEncoder.writeBytes (StreamEncoder.java:309)
    at sun.nio.cs.StreamEncoder.implWrite (StreamEncoder.java:381)
    at sun.nio.cs.StreamEncoder.implWrite (StreamEncoder.java:357)
    at sun.nio.cs.StreamEncoder.lockedWrite (StreamEncoder.java:158)
    at sun.nio.cs.StreamEncoder.write (StreamEncoder.java:139)
    at sun.nio.cs.StreamEncoder.write (StreamEncoder.java:167)
    at java.io.OutputStreamWriter.write (OutputStreamWriter.java:237)
    at java.io.PrintWriter.implWrite (PrintWriter.java:621)
    at java.io.PrintWriter.write (PrintWriter.java:613)
    at java.io.PrintWriter.write (PrintWriter.java:635)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.writeErrorPageStacks (ErrorHandler.java:511)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.writeErrorPageBody (ErrorHandler.java:400)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.writeErrorPage (ErrorHandler.java:369)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.handleErrorPage (ErrorHandler.java:358)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.generateAcceptableResponse (ErrorHandler.java:317)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.generateAcceptableResponse (ErrorHandler.java:170)
    at org.eclipse.jetty.ee10.servlet.ErrorHandler.handle (ErrorHandler.java:138)
    at org.eclipse.jetty.ee10.servlet.ServletChannel.handle (ServletChannel.java:496)
    at org.eclipse.jetty.ee10.servlet.ServletHandler.handle (ServletHandler.java:464)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:575)
    at org.eclipse.jetty.ee10.servlet.SessionHandler.handle (SessionHandler.java:717)
    at org.eclipse.jetty.server.handler.ContextHandler.handle (ContextHandler.java:1060)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:151)
    at org.eclipse.jetty.server.Server.handle (Server.java:182)
    at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run (HttpChannelState.java:662)
    at org.eclipse.jetty.server.internal.HttpConnection.onFillable (HttpConnection.java:418)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:322)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:99)
    at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run (SelectableChannelEndPoint.java:53)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:979)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob (QueuedThreadPool.java:1209)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (QueuedThreadPool.java:1164)
    at java.lang.Thread.run (Thread.java:1583
```

**Comment by melloware** [comment]
Good analysis @jbb01 i will wait to see what @tandraschko says.

**Comment by tandraschko** [comment]
i can actually 2 things as root for this exception:
1) test.html does not contain a PF component -> no core.js -> we just dont add the CSP hidden input to the form
2) as there is wether a nonce in the request, nor in the viewstate, we throw the exception

for 1) we can log a JS error on the client side
we could workaround 2) and create a new nonce but not sure yet

**Comment by tandraschko** [comment]
actually another error

3) initScripts in non-ajax mode, added by BodyRenderer, requires $, which is also not there
