### ISSUE TITLE
Occasional ConcurrentModificationException in dataTable

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1299]
Hi, i noticed this exception. However i can't say how it is reproduced for now. May happen when using the sort feature.

`java.util.ConcurrentModificationException
    at java.util.ArrayList.sort(ArrayList.java:1456)
    at java.util.Collections.sort(Collections.java:175)
    at org.primefaces.component.datatable.feature.SortFeature.singleSort(SortFeature.java:148)
    at org.primefaces.component.datatable.feature.SortFeature.encode(SortFeature.java:106)
    at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:80)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
    at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582)
    at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
    at org.primefaces.component.api.UIData.visitTree(UIData.java:827)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)`

Environment: PrimeFaces 5.3.10 + 2.2.13 @ WildFly10 Final

**Comment by tandraschko** [comment]
That would mean that multiple threads are accessing your ArrayList - we can't avoid that on PF level.

**Comment by tandraschko** [comment]
If you have a sample to replicate without multiple threads, please come back.
