### ISSUE TITLE
Tree: Duplicate component ID when using jakarta.faces.PARTIAL_STATE_SAVING=false

### ISSUE THREAD

**Issue by jOlliv** [primefaces/primefaces#13009]
### Describe the bug

The tree component seems to add the UITreeNode components twice when `jakarta.faces.PARTIAL_STATE_SAVING=false` is configured in web.xml. So state saving is not working because it found a duplicate component ID:

```
Dec 05, 2024 3:57:55 PM com.sun.faces.util.Util checkIdUniqueness
SEVERE: JSF1007: Duplicate component ID j_idt8:j_idt10:j_idt11 found in view.
Dec 05, 2024 3:57:55 PM com.sun.faces.util.Util checkIdUniqueness
SEVERE: +id: j_id1
 type: jakarta.faces.component.UIViewRoot@4971bc3c
  +id: jakarta_faces_location_HEAD
   type: com.sun.faces.component.ComponentResourceContainer@967a04a
    +id: j_id2
     type: jakarta.faces.component.UIOutput@12468c9f
    +id: j_id3
     type: jakarta.faces.component.UIOutput@389e81a2
    +id: j_id4
     type: jakarta.faces.component.UIOutput@48b7cc8b
    +id: j_id5
     type: jakarta.faces.component.UIOutput@7c665027
    +id: j_id6
     type: jakarta.faces.component.UIOutput@5a621940
    +id: j_idt5
     type: jakarta.faces.component.UIOutput@163d003f
  +id: j_idt1
   type: <html xmlns="http://www.w3.org/1999/xhtml">

    
  +id: j_idt2
   type: jakarta.faces.component.UIOutput@601845e7
    +id: j_idt3
     type: 
        <title>PrimeFaces Test</title>
        
    +id: j_idt4
     type: jakarta.faces.component.UIOutput@2e31d6ab
  +id: j_idt6
   type: jakarta.faces.component.html.HtmlBody@64536234
    +id: j_idt7
     type: 

        <h1>Tree Basic example from PrimeFaces Showcase</h1>
        
    +id: j_idt8
     type: jakarta.faces.component.html.HtmlForm@1a91ba79
      +id: j_idt9
       type: 
            <div class="card">
                <h5 style="margin-top:0">Client</h5>
                
      +id: j_idt10
       type: org.primefaces.component.tree.Tree@3884f3b1
        +id: j_idt11  <===============
         type: org.primefaces.component.tree.UITreeNode@18a0fe84
          +id: j_idt12
           type: jakarta.faces.component.html.HtmlOutputText@679d6d66
        +id: j_idt11  <===============
         type: org.primefaces.component.tree.UITreeNode@7048419e
          +id: j_idt12
           type: jakarta.faces.component.html.HtmlOutputText@6f4e2d5d
      +id: j_idt13
       type: 
            </div>

            <div class="card">
                <h5>Ajax and No Border</h5>
                
      +id: j_idt14
       type: org.primefaces.component.tree.Tree@7085aaee
        +id: j_idt15
         type: org.primefaces.component.tree.UITreeNode@7c7f1fc5
          +id: j_idt16
           type: jakarta.faces.component.html.HtmlOutputText@4e09f565
        +id: j_idt15
         type: org.primefaces.component.tree.UITreeNode@50330d3c
          +id: j_idt16
           type: jakarta.faces.component.html.HtmlOutputText@d3c1f0e
      +id: j_idt17
       type: 
            </div>
        
  +id: j_idt18
   type: 
</html>

Dec 05, 2024 3:57:55 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.IllegalStateException: Component ID j_idt8:j_idt10:j_idt11 has already been found in the view.  
java.lang.IllegalStateException: Component ID j_idt8:j_idt10:j_idt11 has already been found in the view.  
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1200)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1189)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1189)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1189)
        at com.sun.faces.application.view.FaceletFullStateManagementStrategy.saveView(FaceletFullStateManagementStrategy.java:655)
        at jakarta.faces.application.StateManager.getViewState(StateManager.java:243)
        at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:523)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:315)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:61)
        at jakarta.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1092)
        at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1435)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:422)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:160)
        at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
        at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:150)
        at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
        at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1370)
        at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
        at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:819)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
        at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
        at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
        at org.eclipse.jetty.server.Server.handle(Server.java:182)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Reproducer

The attached reproducer is the "Tree Basic" example from PrimeFaces showcase with 'jakarta.faces.PARTIAL_STATE_SAVING=false' configuration in web.xml.

[primefaces-tree-partial-state-saving-reproducer.zip](https://github.com/user-attachments/files/18024883/primefaces-tree-partial-state-saving-reproducer.zip)

1. Go to 'http://localhost:8080/'
2. Expand node "Documents" under section "Ajax and No Border"
3. See error in console: `SEVERE: JSF1007: Duplicate component ID j_idt8:j_idt10:j_idt11 found in view.`

### PrimeFaces edition

Community

### PrimeFaces version

14.0.8

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

Java 17

**Comment by tandraschko** [comment]
does it work with myfaces?

**Comment by jOlliv** [comment]
> does it work with myfaces?

Yes, with `mvn clean jetty:run -Pmyfaces40` I don't get the error.

**Comment by melloware** [comment]
@jOlliv marked as "third-party" and feel free to report this to Mojarra team but closing it here.
