### ISSUE TITLE
Column: component not pushed to EL

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#13016]
```
<p:column field="orderNumber" headerText="#{myController.getColumnHeader(component)}"
        filterMatchMode="contains" />
```
resolves to DataTable

```
	at jakarta.el.ELUtil.invokeMethod(ELUtil.java:215)
	at jakarta.el.BeanELResolver.invoke(BeanELResolver.java:487)
	at jakarta.el.CompositeELResolver.invoke(CompositeELResolver.java:198)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:159)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:100)
	at jakarta.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:354)
	at org.primefaces.component.column.ColumnBase.getHeaderText(ColumnBase.java:214)
	at org.primefaces.component.column.Column.getHeaderText(Column.java:84)
	at org.primefaces.renderkit.DataRenderer.getHeaderLabel(DataRenderer.java:201)
	at org.primefaces.component.datatable.DataTableRenderer.encodeColumnHeader(DataTableRenderer.java:668)
```

**Comment by tandraschko** [comment]
does anyone know the relationship between ariaHeaderText, headerText and hiding the columnTitle?

```
        String headerText = column.getHeaderText();
        String ariaHeaderText = column.getAriaHeaderText();
        String titleStyleClass = getStyleClassBuilder(context)
                .add(DataTable.COLUMN_TITLE_CLASS)
                .add(LangUtils.isNotBlank(ariaHeaderText), "ui-helper-hidden-accessible")
                .build();
        headerText = LangUtils.isNotBlank(headerText) ? headerText : ariaHeaderText;
```

why should we hide the column header/title when ARIA is set?

**Comment by tandraschko** [comment]
#4725

**Comment by melloware** [comment]
Yep that is it. For columns that have an icon or empty header.

**Comment by tandraschko** [comment]
but how is this related to ariaHeaderText?

i would say: if there is no headerText or headerFacet, then we could add the hidden style?

**Comment by tandraschko** [comment]
something like

```
.add(headerFacet == null && isValueBlank(headerText), "ui-helper-hidden-accessible")
```

**Comment by tandraschko** [comment]
the current approach is that if you set a ariaHeaderText, headerText or headerFacet is rendered but invisible. It this by design?

**Comment by melloware** [comment]
I thought it only adds `ui-hidden-accessible` if AriaHeaderText is set 


```java
.add(LangUtils.isNotBlank(ariaHeaderText), "ui-helper-hidden-accessible")
```

It should not be hidden UNLESS you specifically use `ariaHeaderText="Foo"` when you have an empty header or using an Icon in your header for example. `ariaHeaderText` should not be used if `headerText` is used.

**Comment by melloware** [comment]
Maybe i need to update the docs for AriaHeaderText?

**Comment by tandraschko** [comment]
yeah, that would be great
