### ISSUE TITLE
ColumnToggler not compatible with TreeTable

### ISSUE THREAD

**Issue by skybber** [primefaces/primefaces#13029]
`ColumnToggler` assumes a `DataTable` as its data source and fails if it is actually a `TreeTable`. The code always casts to `DataTable`, causing errors when toggling columns in `TreeTable`:

```
java.lang.ClassCastException: class org.primefaces.component.treetable.TreeTable cannot be cast to class org.primefaces.component.datatable.DataTable (org.primefaces.component.treetable.TreeTable and org.primefaces.component.datatable.DataTable are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @408ae651)
	at org.primefaces.component.columntoggler.ColumnToggler.queueEvent(ColumnToggler.java:93)
	at org.primefaces.behavior.ajax.AjaxBehaviorRenderer.decode(AjaxBehaviorRenderer.java:55)
```	

**Current Code ColumnToggler.queueEvent():**
```java
UIColumn column = ((DataTable) getDataSourceComponent()).getColumns().get(index);
```

### Expected behavior

`ColumnToggler` should check the component type (e.g., `TreeTable`) and retrieve columns accordingly.

**Proposed Fix:**
```java
UIComponent dataSource = getDataSourceComponent();
List<UIColumn> columns = dataSource instanceof DataTable
    ? ((DataTable) dataSource).getColumns()
    : ((TreeTable) dataSource).getColumns();
```

### PrimeFaces edition

Community

### PrimeFaces version

14.0.8

### JSF implementation

MyFaces

### JSF version

4.0.2

### Java version

21.0.5

### Browser(s)

Firefox

**Comment by melloware** [comment]
@skybber did you test whether the proposed fix works?   Its possible there are even more limitations to ColumnToggler not working with TreeTable...

**Comment by tandraschko** [comment]
yeah, almost sure that its not the only place to adjust

**Comment by melloware** [comment]
I am going to check it.  It seems like it has TreeTable in some places and not others.  

```
UIColumn column = ((UITable) getDataSourceComponent()).getColumns().get(index);
```

but it should be UITable and not DataTable specifically.

**Comment by melloware** [comment]
OK shockingly it all works.  I just tested it.

```xml
<p:treeTable id="documents" value="#{ttBasicView.root}" var="document">
                    <f:facet name="header">
                        <div class="flex justify-content-between align-items-center">
                            Document Viewer

                            <div>
                                <p:commandButton id="toggler" type="button" value="Columns" icon="pi pi-align-justify"/>
                                <p:columnToggler datasource="documents" trigger="toggler">
                                </p:columnToggler>
                            </div>
                        </div>
                    </f:facet>
                    <p:column headerText="Name">
                        <h:outputText value="#{document.name}"/>
                    </p:column>
                    <p:column headerText="Size">
                        <h:outputText value="#{document.size}"/>
                    </p:column>
                    <p:column headerText="Type">
                        <h:outputText value="#{document.type}"/>
                    </p:column>
                    <p:column style="width:3rem" ariaHeaderText="Actions">
                        <p:commandButton update=":form:documentPanel" oncomplete="PF('documentDialog').show()"
                                       title="View Detail" icon="pi pi-search">
                            <f:setPropertyActionListener value="#{document}" target="#{ttBasicView.selectedDocument}"/>
                        </p:commandButton>
                    </p:column>
                </p:treeTable>
```

**Comment by skybber** [comment]
Thanks! It used to work in 13.0.x, but a breaking change was introduced in 14.0.

**Comment by melloware** [comment]
yep it works again!
