### ISSUE TITLE
PrimeExceptionHandler: Infinite loop on MyFaces with invalid ContentType

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#13104]
### Describe the bug

IF you hit a MyFaces app using PrimeFaces and the Content-Type is invalid it gets in an infinite redirect loop if you have an `error-page` mapped.

```
Dec 21, 2024 10:09:19 AM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
SEVERE: ContentTypeList does not contain a supported content type: text/plain
java.lang.IllegalArgumentException: ContentTypeList does not contain a supported content type: text/plain
        at org.apache.myfaces.renderkit.html.HtmlRenderKitImpl.createResponseWriter(HtmlRenderKitImpl.java:311)
        at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.createResponseWriter(FaceletViewDeclarationLanguage.java:2116)
        at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1751)
        at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:316)
        at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:74)
        at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:74)
        at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:122)
        at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:241)
        at jakarta.faces.lifecycle.LifecycleWrapper.render(LifecycleWrapper.java:43)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:225)
```

### Reproducer

1. Simply run the Showcase using MyFaces 4.0
2. Execute `curl` or `PowerShell` to hit the site with an invalid Content-Type.

```powershell
$response = Invoke-WebRequest -Uri "http://localhost:8080/showcase/ui/ajax/process.xhtml" -Method GET -Headers @{ Accept = "text/plain" } -AllowInsecureRedirect
```

3. Because it gets the error it tries to redirect to `/showcase/error.xhtml` using `externalContext.redirect(url);`.  This however just generates the same error in MyFaces in an infinite loop.

### Expected behavior

No infinite loop.  Mojarra does not happen this way.

Hack that fixes it in `PrimeExceptionHandler`

```java
if (rootCause instanceof IllegalArgumentException &&
                        rootCause.getMessage().contains("ContentTypeList does not contain a supported content type")) {
       // MyFaces workaround to prevent infinite redirect loop
}
else {
      externalContext.redirect(url);
}
```

### PrimeFaces edition

Community

### PrimeFaces version

14.0.9

### Theme

ANY

### JSF implementation

MyFaces

### JSF version

4.0.2

### Java version

11

### Browser(s)

ALL

**Comment by melloware** [comment]
I have tried setting `Accept` header and `Content-Type` header to no avail it keeps the original header.

```java
externalContext.setResponseHeader("Accept", "text/html,application/xhtml+xml,application/xml");
externalContext.redirect(url);
```

**Comment by tandraschko** [comment]
but why doesnt it happen on mojarra? i think thats the key

**Comment by melloware** [comment]
I don't know whether its a spec issue or not but MyFaces does this and Mojarra does not.

https://github.com/apache/myfaces/blob/5ebb131072490a6175aa38b10cb36afd59462156/impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlRenderKitImpl.java#L303-L313

**Comment by melloware** [comment]
Mojarra just defaults.

```java
// Step 3: Check the Accept Header content type
        // Evaluate the accept header in accordance with HTTP specification -
        // Section 14.1
        // Preconditions for this (1 or 2):
        // 1. content type was not specified to begin with
        // 2. an unsupported content type was retrieved from the response
        if (null == desiredContentTypeList || contentTypeNullFromResponse) {
            String[] typeArray = context.getExternalContext().getRequestHeaderValuesMap().get("Accept");
            if (typeArray.length > 0) {
                StringBuffer buff = new StringBuffer();
                buff.append(typeArray[0]);
                for (int i = 1, len = typeArray.length; i < len; i++) {
                    buff.append(',');
                    buff.append(typeArray[i]);
                }
                desiredContentTypeList = buff.toString();
            }

            if (null != desiredContentTypeList) {
                desiredContentTypeList = RenderKitUtils.determineContentType(desiredContentTypeList, SUPPORTED_CONTENT_TYPES,
                        preferXhtml() ? RIConstants.XHTML_CONTENT_TYPE : null);
                if (null != desiredContentTypeList) {
                    contentType = findMatch(desiredContentTypeList, SUPPORTED_CONTENT_TYPES_ARRAY);
                }
            }
        }

        // Step 4: Default to text/html
        if (contentType == null) {
            if (null == desiredContentTypeList) {
                contentType = getDefaultContentType();
            } else {
                String[] desiredContentTypes = contentTypeSplit(desiredContentTypeList);
                for (String desiredContentType : desiredContentTypes) {
                    if (RIConstants.ALL_MEDIA.equals(desiredContentType.trim())) {
                        contentType = getDefaultContentType();
                    }
                }
            }
        }
```

**Comment by tandraschko** [comment]
maybe we should do the same in MF
can you check git history or comments in code/jira of MF?

**Comment by melloware** [comment]
yep let me do that.

**Comment by melloware** [comment]
Commit was 11 years ago by Leoardo Uribe.

![image](https://github.com/user-attachments/assets/4a7376fb-e34a-45fa-8824-1673a9644808)


Git commit has no JIRA ticket and when I search through JIRA tickets for "ContentType" or "Accept" header nothing is related.   I feel like we should make it match Mojarra and just default the content type?

**Comment by tandraschko** [comment]
Yeah
+1

**Comment by melloware** [comment]
OK i am going to open MyFaces ticket and fix it.

**Comment by melloware** [comment]
Closing this ticket a MyFaces PR opened: https://github.com/apache/myfaces/pull/823
