### ISSUE TITLE
p:inputNumber

### ISSUE THREAD

**Issue by herwintr** [primefaces/primefaces#1322]
A component of PrimeFaces not found in the libraries of ui, tried to use it, then look for information about this component and me nothing appears.

the error : 
@309,55 <p:inputNumber> Tag Library supports namespace: http://primefaces.org/ui, but no tag was defined for name: inputNumber
    at com.sun.faces.facelets.compiler.CompilationManager.pushTag(CompilationManager.java:289)
    at com.sun.faces.facelets.compiler.SAXCompiler$CompilationHandler.startElement(SAXCompiler.java:228)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)

**Comment by tandraschko** [comment]
Use the forum, it's works fine in the showacse and is only available for elite and 6.0
