### ISSUE TITLE
Primefaces 6.0 - Primefaces Extension Analog Clock stops working

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#1504]
Code works fine under primefaces 5.3.x: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
  xmlns:p="http://primefaces.org/ui"
  xmlns:fn="http://java.sun.com/jsp/jstl/functions"
  xmlns:pe="http://primefaces.org/ui/extensions"
  >
<h:head>
</h:head>
<h:body style="padding:10px 10px 10px 10px; border-style:solid;">

    <h:form id="mainForm" enctype="multipart/form-data">
        <p:growl id="messages" showDetail="true" />

            <p:panelGrid columns="2" style="width:100%;" columnClasses="clockCloumn,clockCloumn">  
                <h:outputText value="Client"/>  
                <h:outputText value="Server"/>  
                <pe:analogClock/>  
                <pe:analogClock mode="server" startTime="#{basicAnalogClockController.now}"/>  
            </p:panelGrid>  

            <style>  
                .clockCloumn{  
                    width: 50%;  
                }  
            </style> 
    </h:form>


</h:body>



</html>
```

**_But in primefaces 6.0**_:

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/15872381/ca9990e2-2cbe-11e6-9f2c-137b422f2304.png)

Stack trace:

```
SEVERE: Servlet.service() for servlet [Faces Servlet] in context with path [/JsfPrimefacesPrj] threw exception [org.primefaces.context.ApplicationContext.getConfig()Lorg/primefaces
/config/ConfigContainer;] with root cause
java.lang.NoSuchMethodError: org.primefaces.context.ApplicationContext.getConfig()Lorg/primefaces/config/ConfigContainer;
    at org.primefaces.extensions.component.analogclock.AnalogClock.getDefaultColorTheme(AnalogClock.java:88)
    at org.primefaces.extensions.component.analogclock.AnalogClock.getColorTheme(AnalogClock.java:83)
    at org.primefaces.extensions.component.analogclock.AnalogClockRenderer.encodeScript(AnalogClockRenderer.java:55)
    at org.primefaces.extensions.component.analogclock.AnalogClockRenderer.encodeEnd(AnalogClockRenderer.java:34)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
    at org.primefaces.component.panelgrid.PanelGridRenderer.encodeDynamicBody(PanelGridRenderer.java:131)
    at org.primefaces.component.panelgrid.PanelGridRenderer.encodeTableBody(PanelGridRenderer.java:102)
    at org.primefaces.component.panelgrid.PanelGridRenderer.encodeTableLayout(PanelGridRenderer.java:65)
    at org.primefaces.component.panelgrid.PanelGridRenderer.encodeEnd(PanelGridRenderer.java:37)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
    at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
    at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:458)
    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by tandraschko** [comment]
Extensions is currently not compatible with 6.0, a new release of extensions will follow.
