### ISSUE TITLE
Stack trace when adding an inline script to an xhtml page.

### ISSUE THREAD

**Issue by mrswadge** [primefaces/primefaces#1580]
Primefaces team,

Finding an issue that might be related to issue #1066.

```
SEVERE: Error Rendering View[/app/index.xhtml]
javax.faces.event.AbortProcessingException: java.lang.NullPointerException: Argument Error: Parameter resourceName is null
    at org.primefaces.context.PrimePartialResponseWriter.startMetadataIfNecessary(PrimePartialResponseWriter.java:303)
    at org.primefaces.context.PrimePartialResponseWriter.startUpdate(PrimePartialResponseWriter.java:142)
    at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:407)
    at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:290)
    at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:58)
    at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:974)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1674)
    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:388)
    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:121)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:509)
    at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
    at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
    at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)
    at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:27)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at com.tracegroup.isys.opentwins.ui.servlet.OpenTwinsSessionFilter.doFilter(OpenTwinsSessionFilter.java:265)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at com.tracegroup.isys.opentwins.ui.primefaces.DocumentModeFilter.doFilter(DocumentModeFilter.java:28)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at com.tracegroup.isys.opentwins.ui.primefaces.NoCacheFilter.doFilter(NoCacheFilter.java:36)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3748)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3714)
    at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
    at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
    at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2283)
    at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2182)
    at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1491)
    at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
    at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)
Caused by: java.lang.NullPointerException: Argument Error: Parameter resourceName is null
    at com.sun.faces.util.Util.notNull(Util.java:253)
    at com.sun.faces.application.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:109)
    at javax.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:84)
    at javax.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:84)
    at javax.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:84)
    at org.primefaces.util.ResourceUtils.filterScripts(ResourceUtils.java:114)
    at org.primefaces.context.PrimePartialResponseWriter.startMetadataIfNecessary(PrimePartialResponseWriter.java:293)
    at org.primefaces.context.PrimePartialResponseWriter.startUpdate(PrimePartialResponseWriter.java:142)
    at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:408)
    ... 34 more
```

This seems to happen when a resource gets into the list of ResourceInfos with null values. Effectively a RES_NOT_FOUND error. Could it be handled more cleanly without needing to stack trace?

![image](https://cloud.githubusercontent.com/assets/6681203/16566411/18ca8368-420c-11e6-973a-b0bee06db360.png)

I think I tracked it down to same script that's embedded into our main template xhtml. We do this as we use EL script to pass values from server side to local javascript: e.g.

```
<h:outputScript target="head">
window.ot.context = "#{request.contextPath}";
window.ot.session = "#{session.id}";
</h:outputScript>
```

It makes sense as the script doesn't have a library or name, so I think this is the cause of the stack trace.

Cheers,
Stuart

**Comment by mrswadge** [comment]
org.primefaces.util.ResourceUtils.getComponentResources(FacesContext) gets all component resources targeting "head". Our in-line script also targets head for script ordering reasons.

When the call is made to org.primefaces.util.ResourceUtils.filterScripts(FacesContext, ArrayList<ResourceInfo>) it doesn't weed out the in-line script, therefore causing it to call javax.faces.application.ResourceHandler.createResource(String) with a null value as the resourceInfo doesn't have a name (or library).

**Comment by mrswadge** [comment]
I would think the following would do the trick in ResourceUtils.

```
    /**
     * Is the script inline or does it require the source to be downloaded as a component resource.
     */
    public static boolean isInline(ResourceInfo resourceInfo) {
        if ( resourceInfo != null ) {
            return ComponentUtils.isValueBlank(resourceInfo.getLibrary()) && ComponentUtils.isValueBlank(resourceInfo.getName());
        }
        return false;
    }

    public static ArrayList<String> filterScripts(FacesContext context, ArrayList<ResourceInfo> resourceInfos) {
        if (resourceInfos == null || resourceInfos.isEmpty()) {
            return null;
        }

        ResourceHandler resourceHandler = context.getApplication().getResourceHandler();

        ArrayList<String> scripts = new ArrayList<String>();
        for (ResourceInfo resourceInfo : resourceInfos) {
            if (isScript(resourceInfo.getResource()) && !isInline(resourceInfo)) {
                Resource resource;
                if (ComponentUtils.isValueBlank(resourceInfo.getLibrary())) {
                    resource = resourceHandler.createResource(resourceInfo.getName());
                }
                else {
                    resource = resourceHandler.createResource(resourceInfo.getName(), resourceInfo.getLibrary());
                }
                scripts.add(resource.getRequestPath());
            }
        }
        return scripts;
    }
```

**Comment by tandraschko** [comment]
Applied your change, thanks!
Please test a build from source :)

**Comment by mrswadge** [comment]
Great, I saw you also applied it to inline style :+1:
