### ISSUE TITLE
Binding the steps component with the ID attribute set, in ui:define, causes duplicate IDs

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#1691]
I'm on PF 6.0.

**Comment by tandraschko** [comment]
please provide a full working example or it will be closed as invalid.

**Comment by jepsar** [comment]
It must be a combination of different components.. Let me figure out what is causing this.

**Comment by jepsar** [comment]
Basically it comes down to the following conditions:
- Steps must be bound
- Steps must have an id attribute set
- Steps must be in a Facelet (in ui:define)

If you eliminate one of those conditions, steps will be rendered, else a duplicate ID is generated:

```
java.lang.IllegalStateException: Component ID main:j_idt16 has already been found in the view.  
    at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1026)
    at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
    at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
    at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1010)
    at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.saveView(FaceletPartialStateManagementStrategy.java:460)
    at com.sun.faces.application.StateManagerImpl.saveView(StateManagerImpl.java:89)
    at com.sun.faces.application.view.WriteBehindStateWriter.getState(WriteBehindStateWriter.java:327)
    at com.sun.faces.application.view.WriteBehindStateWriter.flushToWriter(WriteBehindStateWriter.java:221)
    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:475)
    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
    at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
    at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:180)
    at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
    at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
    at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
    at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
    at java.lang.Thread.run(Thread.java:745)

      +id: steps
       type: org.primefaces.component.steps.Steps@765015d1
        +id: j_idt10
         type: org.primefaces.component.menuitem.UIMenuItem@5d318e7e
        +id: j_idt11
         type: org.primefaces.component.menuitem.UIMenuItem@29f8da52
        +id: j_idt12
         type: org.primefaces.component.menuitem.UIMenuItem@5b90977
        +id: j_idt13
         type: org.primefaces.component.menuitem.UIMenuItem@5a9bfc47
        +id: j_idt16  <===============
         type: org.primefaces.component.menuitem.UIMenuItem@2e145a73
        +id: j_idt17
         type: org.primefaces.component.menuitem.UIMenuItem@7ddebacb
        +id: j_idt18
         type: org.primefaces.component.menuitem.UIMenuItem@1f103a58
        +id: j_idt19
         type: org.primefaces.component.menuitem.UIMenuItem@4271310e
        +id: j_idt16  <===============
         type: org.primefaces.component.menuitem.UIMenuItem@23a4fe2b
        +id: j_idt17
         type: org.primefaces.component.menuitem.UIMenuItem@529898dc
        +id: j_idt18
         type: org.primefaces.component.menuitem.UIMenuItem@46ce88e2
        +id: j_idt19
         type: org.primefaces.component.menuitem.UIMenuItem@2ac70b4b
        +id: j_idt16  <===============
         type: org.primefaces.component.menuitem.UIMenuItem@116be75a
        +id: j_idt17
         type: org.primefaces.component.menuitem.UIMenuItem@1b9a7882
        +id: j_idt18
         type: org.primefaces.component.menuitem.UIMenuItem@67558978
        +id: j_idt19
         type: org.primefaces.component.menuitem.UIMenuItem@587247a9
        +id: j_idt16  <===============
         type: org.primefaces.component.menuitem.UIMenuItem@343e0f03
        +id: j_idt17
         type: org.primefaces.component.menuitem.UIMenuItem@6dd8d709
        +id: j_idt18
         type: org.primefaces.component.menuitem.UIMenuItem@139c9f4d
        +id: j_idt19
         type: org.primefaces.component.menuitem.UIMenuItem@6279e463
        +id: j_idt16  <===============
         type: org.primefaces.component.menuitem.UIMenuItem@7b7dede1
        +id: j_idt17
         type: org.primefaces.component.menuitem.UIMenuItem@73952a5a
        +id: j_idt18
         type: org.primefaces.component.menuitem.UIMenuItem@75b2d873
        +id: j_idt19
         type: org.primefaces.component.menuitem.UIMenuItem@682bf5fa
```

I'm using Payara 4.1.1.162 (Mojarra 2.2.13).

XHTML:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/tpl/template.xhtml"
                                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

  <ui:define name="title">
    <h:outputText value="#{msg.title_settings}"/>
  </ui:define>

  <ui:define name="body">
        <p:steps id="steps" binding="#{settings.steps}">
            <p:menuitem value="Personal" />
            <p:menuitem value="Seat Selection" />
            <p:menuitem value="Payment" />
            <p:menuitem value="Confirmation" />
        </p:steps>
  </ui:define>

</ui:composition>
```

Template:

```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      lang="#{settings.language}"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:o="http://omnifaces.org/ui">
  <f:view locale="#{settings.locale}">
    <h:head>
      <title><ui:insert name="title" /></title>
      <h:outputStylesheet name="css/screen.css"/>
    </h:head>
    <h:body>

      <div class="page">
        <div class="content">
          <o:form id="main">
            <ui:insert name="body" />
          </o:form>
        </div>
      </div>

    </h:body>
  </f:view>
</html>
```

Just to be sure, I've replaced `o:form` with `h:form` but the result was the same.

**Comment by tandraschko** [comment]
I just wonder if binding works with other components in this case?
Binding often has problems or it could be a mojarra bug, too.

**Comment by jepsar** [comment]
Probably invalid. I'll close it.

See also:
http://stackoverflow.com/questions/2101755/binding-attribute-causes-duplicate-component-id-found-in-the-view
