### ISSUE TITLE
breadcrumb throws a NumberFormatException when its items have a command but not an id.

### ISSUE THREAD

**Issue by jrcampins** [primefaces/primefaces#1729]
I'm using PrimeFaces 6.0 now. I found the problem when I started setting the menu item’s **command** instead of its **URL** or **outcome** (curiously it never happened when all the items had either URL or outcome).

I followed the code execution using the debugger and I realized that it is trying to get the item position within the breadcrumb converting its **id** to integer (at org.primefaces.component.menu.BaseMenuRenderer.findMenuitem(BaseMenuRenderer.java:89)).

So, to work around the problem I simply had to add the following line to the method I use to that add menu items to the breadcrumb's menu model elements list:

`item.setId(elements.size() + "");`

This is the exception stack:

```
Severe:   java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:592)
    at java.lang.Integer.parseInt(Integer.java:615)
    at org.primefaces.component.menu.BaseMenuRenderer.findMenuitem(BaseMenuRenderer.java:89)
    at org.primefaces.component.menu.BaseMenuRenderer.decode(BaseMenuRenderer.java:67)
    at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:832)
    at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1227)
    at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:573)
    at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at javax.faces.component.UIForm.visitTree(UIForm.java:371)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
    at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:266)
    at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
    at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:927)
    at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
    at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:413)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
    at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
    at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by jrcampins** [comment]
The breadcrumb component is part of a layout:

```
                <p:layoutUnit id="centerUnit" position="center">
                    <h:form id="centerNorthForm">
                        <p:breadCrumb
                            id="breadCrumbs"
                            model="#{requestBean.paginaActual.modeloMigasPan}"/>
                    </h:form>
                    <ui:insert name="center"/>
                </p:layoutUnit>
```

These are the controller declaration and the model property getter (requestBean.paginaActual.modeloMigasPan): 

```
    @Inject
    protected BreadCrumbController breadCrumbController;

    @Override
    public MenuModel getModeloMigasPan() {
        return breadCrumbController.getBreadCrumbModel();
    }
```

This is how items are added to the breadcrumb (if you comment **item.setId(elements.size() + "");** you should get the exception):

```
    private void updateBreadCrumbModel() {
        String page = BaseBundle.getPage(SIMPLE);
        if (page != null) {
            String command = "#" + "{requestBean.paginaActual.getPostBackFacesOutcome('" + page + "')" + "}";
            MenuModel breadCrumbModel = getModeloMigasPan();
            List<MenuElement> elements = breadCrumbModel.getElements();
            boolean first;
            boolean found = false;
            DefaultMenuItem item;
            String urx, pagina;
            final String zero = "0";
            if (elements != null && !elements.isEmpty()) {
                /* copy list to array to be able to remove elements without disrupting the following for */
                MenuElement[] array = elements.toArray(new MenuElement[0]);
                for (MenuElement element : array) {
                    if (found) {
                        if (element instanceof DefaultMenuItem) {
                            item = (DefaultMenuItem) element;
                            urx = StringUtils.substringBetween(item.getCommand(), "'");
                            pagina = FacesUtils.getPageName(urx);
                            sessionBean.removeState(pagina);
                        }
                        elements.remove(element);
                    } else if (element instanceof DefaultMenuItem) {
                        item = (DefaultMenuItem) element;
                        first = zero.equals(item.getId());
                        found = command.equals(item.getCommand());
                        item.setDisabled(found && !first);
                    }
                }
                if (!found && updateBreadCrumbs()) {
                    String value = getEtiquetaMigasPan();
                    String title = getNombre();
                    item = new DefaultMenuItem();
                    item.setId(elements.size() + "");
                    item.setValue(value);
                    item.setTitle(title);
                    item.setCommand(command);
                    item.setAjax(true);
                    item.setDisabled(true);
                    item.setPartialSubmit(true);
                    item.setProcess("@this");
                    item.setUpdate("@none");
                    breadCrumbModel.addElement(item);
                }
            }
        }
    }
```

And this is the controller code:

```
package jee2ap101.web.app.controller;

import java.util.List;
import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import jee2ap101.lib.base.BaseBundle;
import jee2ap101.lib.base.bundle.BundleWebui;
import jee2ap101.web.app.AbstractSessionBean;
import jee2ap101.web.pages.Menu;
import org.primefaces.model.menu.DefaultMenuItem;
import org.primefaces.model.menu.DefaultMenuModel;
import org.primefaces.model.menu.MenuElement;
import org.primefaces.model.menu.MenuModel;

/**
 * @author Jorge Campins
 */
@Named
@SessionScoped
public class BreadCrumbController extends AbstractSessionBean {

    @Override
    @PostConstruct
    public void postConstruct() {
        super.postConstruct();
        initBreadCrumbModel();
    }

    @Override
    @PreDestroy
    public void preDestroy() {
        super.preDestroy();
    }

    private void initBreadCrumbModel() {
        breadCrumbModel = new DefaultMenuModel();
        addPaginaMenu();
    }

    public void resetBreadCrumbModel() {
        boolean found = false;
        List<MenuElement> elements = breadCrumbModel.getElements();
        if (elements != null && !elements.isEmpty()) {
            /* copy list to array to be able to remove elements without disrupting the following for */
            MenuElement[] array = elements.toArray(new MenuElement[0]);
            for (MenuElement element : array) {
                if (found) {
                    elements.remove(element);
                } else if (element instanceof DefaultMenuItem) {
                    found = true;
                }
            }
        }
    }

    private void addPaginaMenu() {
        String value = BundleWebui.getString("botonAbrirMenuInicio.text");
        String title = BundleWebui.getString("botonAbrirMenuInicio.toolTip");
//      String page = URX.INICIO;
        String page = BaseBundle.getPage(Menu.class.getSimpleName());
        String command = "#" + "{requestBean.paginaActual.getPostBackFacesOutcome('" + page + "')" + "}";
        DefaultMenuItem item = new DefaultMenuItem();
        item.setId("0");
        item.setValue(value);
        item.setTitle(title);
        item.setCommand(command);
        item.setAjax(true);
        breadCrumbModel.addElement(item);
    }

    private MenuModel breadCrumbModel;

    public MenuModel getBreadCrumbModel() {
        return breadCrumbModel;
    }

}
```

**Comment by jrcampins** [comment]
I forgot to mention an important point. **You'll get the exception clicking a link corresponding to an item without id** (not when the item is added to the breadcrumb)

**Comment by jrcampins** [comment]
Another point that might be worth mentioning: if you omit **item.setId("0");** when adding the first item to the breadcrumb nothing wrong happens. Following the code with the debugger you will see that such item's id is initialized anyway (to "0"). Such internal initialization doesn't take place for the rest of items.

**Comment by Majasi** [comment]
I have the issue with the `p:menu` component when trying to create the menu nodes programmatically.

**Comment by tandraschko** [comment]
The sample is not runnable simple mvce, will close it as invalid for now.
If the problem still persists with the current trunk version, please create new issue with a fully runnable and small sample bean+xhtml.
