### ISSUE TITLE
IE11: Could not complete the operation due to error 800a025e

### ISSUE THREAD

**Issue by beevelop** [primefaces/primefaces#1799]
> This issue has been logged with the help of Sentry and can be reproduced reliably in our environment.
## 1) Environment
- PrimeFaces version: 5.3
- Affected browsers: IE11 (11.0.9600.*)
## 2) Expected behavior

Executing `PrimeFaces.clearSelection()` should not trigger an exception.
## 3) Actual behavior

Running `PrimeFaces.clearSelection()` triggers the following exception for rowClicks on a datatable in IE11:

```
Error: Could not complete the operation due to error 800a025e.
  at b.clearSelection(/javax.faces.resource/primefaces.js:1:4094)
  at onRowClick(/javax.faces.resource/primefaces.js:18:20202)
  at Anonymous function(/javax.faces.resource/primefaces.js:18:5632)
  at bH.event.dispatch(/javax.faces.resource/jquery/jquery.js:25:40977)
  at cd.handle(/javax.faces.resource/jquery/jquery.js:25:37104)
  at d(/javax.faces.resource/js/raven.min.js:2:3984)
```
## 4) Steps to reproduce

Click on a row in a datatable or manually execute `PrimeFaces.clearSelection()` with the browser's developer console.

**Comment by tandraschko** [comment]
Merged, thanks!
