### ISSUE TITLE
Exception when building from source

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#1867]
### Steps to reproduce:

1. Clone the `maven-jsf-plugin`:

        git clone https://github.com/primefaces/maven-jsf-plugin

2. Build the `maven-jsf-plugin`:

        mvn clean install

3. Clone `primefaces`:

        git clone https://github.com/primefaces/primefaces

4. Build `primefaces` (**version `6.1-SNAPSHOT`**):

        mvn clean install

### Results

If the bug still exists, the following exception will appear multiple  times in the maven output:

```
Oct 31, 2016 3:06:12 PM org.primefaces.config.PrimeConfiguration initBuildProperties
SEVERE: Could not load pom.properties
java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at org.primefaces.config.PrimeConfiguration.initBuildProperties(PrimeConfiguration.java:186)
        at org.primefaces.config.PrimeConfiguration.<init>(PrimeConfiguration.java:81)
        at org.primefaces.context.DefaultApplicationContext.<init>(DefaultApplicationContext.java:41)
        at org.primefaces.context.DefaultRequestContext.getApplicationContext(DefaultRequestContext.java:249)
        at org.primefaces.el.ValueExpressionAnalyzer.getExpression(ValueExpressionAnalyzer.java:53)
        at org.primefaces.el.ValueExpressionAnalyzerTest.firstLevelValueReference(ValueExpressionAnalyzerTest.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

If the bug is fixed, the exception will not appear.

### Notes

Note that the build still completes successfully.

**Comment by tandraschko** [comment]
Could you please try to analyse the problem?
I also have it on my local machine but i don't know why. For me it occured after upgrading java on my linux mint 1-2 years before.
AFAIR it was a java bug when reading something from a jar's META-INF.
The file exists in the target, no idea.

**Comment by stiemannkj1** [comment]
@tandraschko, the issue is happening because [you are trying to access the **`pom.properties`** file during testing](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/config/PrimeConfiguration.java#L185). However, [that file is only available during and after the package phase](http://stackoverflow.com/questions/3886753/access-maven-project-version-in-spring-config-files#3886921) (see [MJAR-76](http://jira.codehaus.org/browse/MJAR-76) for more details). To fix this, you can [create another properties file within your project that contains `version=${project.version}` and filter that file](http://www.avajava.com/tutorials/lessons/how-do-i-filter-resources-based-on-values-from-a-properties-file.html). Then access that file from `PrimeConfiguration` since it is available during the test phase and at runtime. There are other solutions like getting the value from the **`MANIFEST.MF`** via `this.getClass().getPackage().getImplementationVersion()`, but PrimeFaces does not include those values in the **`MANIFEST.MF`** currently (except during a `-P release`).

**Comment by tandraschko** [comment]
I moved the manifest creation to the normal build but this.getClass().getPackage().getImplementationVersion() is null.
Do you have experience with this stuff?
Solutions are to get the manifest manually but it's not very cool...

**Comment by stiemannkj1** [comment]
I think the problem is that the `MANIFEST.MF` does not get created until the package phase either. Maybe it'd be worth including a default `buildVersion` like `TESTING` when  `this.getClass().getPackage().getImplementationVersion() == null`. If you really want to get an accurate version while in the test phase, I think you will need to add a file like **`src/main/resources/example.properties`** file with content like this:

```
version=${project.version}
```

Then in the **`pom.xml`**, change the `<resources>` section to this:

```
<resources>
    <resource>
        <directory>src/main/resources</directory>
        <includes>
            <include>src/main/resources/example.properties</include>
        </includes>
        <filtering>true</filtering>
    </resource>
    <resource>
        <directory>src/main/resources</directory>
    </resource>
</resources>
```

Then when you access the **`example.properties`** file, the property will have been filtered to something like `6.1-SNAPSHOT`.

**Comment by tandraschko** [comment]
Thanks but fixed it a little bit different :)
