### ISSUE TITLE
PrimeFaces Data Exporter causes stack trace with OmniFaces Gzip 

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1993]
Details; https://github.com/omnifaces/omnifaces/issues/336

**Comment by mydeadlyvenoms** [comment]
Hi @mertsincan, I guess the exception gets still thrown when using "XML". All other formats are working fine.

```
[2017-03-21T15:54:34.549+0100] [Payara 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=137 _ThreadName=http-thread-pool::http-listener-2(3)] [timeMillis: 1490108074549] [levelValue: 900] [[
  java.io.IOException: Stream is already closed.
javax.faces.FacesException: java.io.IOException: Stream is already closed.
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:145)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:814)
	at javax.faces.component.UICommand.broadcast(UICommand.java:300)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1696)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:124)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:181)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at ch.cxa.asap.ucp.httpfilter.SecurityHeaderHttpFilter.doFilter(SecurityHeaderHttpFilter.java:49)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessToExtension(FacesViewsForwardingFilter.java:184)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:141)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:127)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:88)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stream is already closed.
	at org.omnifaces.io.ResettableBufferedOutputStream.checkClosed(ResettableBufferedOutputStream.java:177)
	at org.omnifaces.io.ResettableBufferedOutputStream.flush(ResettableBufferedOutputStream.java:145)
	at org.omnifaces.io.DefaultServletOutputStream.flush(DefaultServletOutputStream.java:56)
	at org.omnifaces.servlet.HttpServletResponseOutputWrapper.flushBuffer(HttpServletResponseOutputWrapper.java:127)
	at org.omnifaces.servlet.GzipHttpServletResponse.flushBuffer(GzipHttpServletResponse.java:120)
	at com.sun.faces.context.ExternalContextImpl.responseFlushBuffer(ExternalContextImpl.java:990)
	at javax.faces.context.ExternalContextWrapper.responseFlushBuffer(ExternalContextWrapper.java:940)
	at org.primefaces.component.export.XMLExporter.export(XMLExporter.java:62)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:134)
	... 65 more
```

**Comment by mertsincan** [comment]
Hi, 
Can you please attach a sample maven project for us to replicate? You can use this project for it; https://github.com/primefaces/primefaces-test

**Comment by mydeadlyvenoms** [comment]
Yes sure, I'll try to provide you the project by the end of the week.

**Comment by mydeadlyvenoms** [comment]
Hi @mertsincan 

Sorry for the delay, here you go: https://github.com/mydeadlyvenoms/PrimeFacesIssues
Just click the export buttons under the datatable, the XML button will throw the mentioned exception. Your template project didn't work with OmniFaces therefore I created one from scratch, I tested it using the latest Payara server.

**Comment by mydeadlyvenoms** [comment]
Hi @mertsincan were you able to reproduce the issue? If not, let me know.

**Comment by melloware** [comment]
@mydeadlyvenoms I am the original reporter of the OmniFaces defect and I am not having this issue with XML exports on PF 6.0.17 + OmniFaces 2.1+.    What versions are you using?

**Comment by mydeadlyvenoms** [comment]
Hi @melloware humm interesting... Here you can find my POM: https://github.com/mydeadlyvenoms/PrimeFacesIssues/blob/master/PrimeFacesIssues/pom.xml

**Comment by melloware** [comment]
OK so I see what you have so I ran the following test:

- Jboss Wildfly 10
- JDK 8
- OmniFaces 2.6.2
- PrimeFaces 6.1-SNAPSHOT

When I run the XML does download for me but I can confirm I do see this stack trace in the logs.

**Comment by mydeadlyvenoms** [comment]
Hi there, thank you very much for the verification. But I don't want to open a new issue, since this one clearly belongs to your original issue.

**Comment by melloware** [comment]
Both CSVExporter and XML Exporter both do this...

```java
        writer.flush();
        writer.close();
        
        externalContext.responseFlushBuffer();
```
So it is weird CSVExporter works but XMLExporter throws the stack trace.

**Comment by melloware** [comment]
Submitted PR.

**Comment by mydeadlyvenoms** [comment]
Awesome, Thank you @melloware - that was fast ;-)
