### ISSUE TITLE
Support "_" and "-" in @id(id) PrimeFaces SEF keyword

### ISSUE THREAD

**Issue by ReedElliott** [primefaces/primefaces#2007]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.0.13
- Does it work on the newest PrimeFaces version? No
- Application server + version: GlassFish 4.1.1
- Affected browsers: Chome

## 2) Expected behavior

@id(help-dialog) should find the p:dialog id="help-dialog" component.

## 3) Actual behavior

Throws error:

2017-01-10T10:40:27.810-0600|Severe: Error Rendering View[/procedure/ProcedureCreater.xhtml]
javax.faces.FacesException: Expression does not match following pattern @id(id). Expression: "@id(help-dialog)"
   at org.primefaces.expression.impl.IdExpressionResolver.extractId(IdExpressionResolver.java:58)
   at org.primefaces.expression.impl.IdExpressionResolver.resolveComponents(IdExpressionResolver.java:39)
   at org.primefaces.expression.SearchExpressionFacade.resolveClientIdsByExpressionChain(SearchExpressionFacade.java:632)
   at org.primefaces.expression.SearchExpressionFacade.resolveClientIds(SearchExpressionFacade.java:205)
   at org.primefaces.util.AjaxRequestBuilder.addExpressions(AjaxRequestBuilder.java:92)
   at org.primefaces.util.AjaxRequestBuilder.update(AjaxRequestBuilder.java:85)
   at org.primefaces.renderkit.CoreRenderer.buildAjaxRequest(CoreRenderer.java:389)

## 4) Steps to reproduce

See http://forum.primefaces.org/viewtopic.php?f=3&t=48935

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by Rapster** [comment]
`\w` does not take account non digit character such as `-`
