### ISSUE TITLE
p:focus with ValueExpression Attribute "for"

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#2146]
Reference http://forum.primefaces.org/viewtopic.php?f=3&t=49812

project : https://github.com/ravihariharan/primefaces-test --> refer main/webapp/focus.xhtml

# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? Version? 6.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tested on 7.0.75 with EL 2.2 , 8.5.11 with EL 3 ,  glassfish-4.1.1-web
- Affected browsers: All

## 2) Expected behavior
The objective is when the value is null it should follow the encodeImplicitFocus behavior of FocusRenderer.

The "for" has the default value as null and documentation. 
The issue come up when used with ValueExpression which evaluate the null as an empty String.
...

## 3) Actual behavior

java.lang.NullPointerException
	at org.primefaces.component.focus.FocusRenderer.encodeExplicitFocus(FocusRenderer.java:70)
	at org.primefaces.component.focus.FocusRenderer.encodeEnd(FocusRenderer.java:57)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:89)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
	at org.primefaces.component.panel.PanelRenderer.encodeContent(PanelRenderer.java:206)
	at org.primefaces.component.panel.PanelRenderer.encodeMarkup(PanelRenderer.java:123)
	at org.primefaces.component.panel.PanelRenderer.encodeEnd(PanelRenderer.java:58)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
..

## 4) Steps to reproduce
Run the project : https://github.com/ravihariharan/primefaces-test --> refer main/webapp/focus.xhtml
.. 

## 5) Sample XHTML
<h:form>
		<p:panel id="panel" header="Register">

			<p:focus context="panel" for="#{focusView.forFocus}" />

			<p:messages />

			<h:panelGrid columns="3">
				<p:outputLabel for="username" value="Username" />
				<p:inputText id="username" value="#{focusView.username}"
					required="true" label="User Name">
					<f:validateLength minimum="2" />
				</p:inputText>
				<p:message for="username" />

				<p:outputLabel for="password" value="Password" />
				<p:inputText id="password" value="#{focusView.password}"
					required="true" label="Password" />
				<p:message for="password" />
			</h:panelGrid>

			<p:commandButton id="submitButton" value="Save" update="@parent"
				actionListener="#{focusView.save}" />
		</p:panel>
	</h:form>
..

## 6) Sample bean
@ManagedBean
@ViewScoped
public class FocusView implements Serializable {

	private String forFocus;

	private String username;
	private String password;

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void save() {

		if (!"admin".equals(username)) {
			forFocus = "username";

			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Invalid User Name", "Invalid User Name"));
		} else if (!"admin".equals(password)) {
			forFocus = "password";

			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Invalid Password", "Invalid Password"));
		} else {

			username = null;
			password = null;
			forFocus = null;
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_INFO, "Success", "Success"));

		}
	}

	public String getForFocus() {
		System.out.println("getForFocus " + forFocus);
		return forFocus;
	}

	public void setForFocus(String forFocus) {
		System.out.println("setForFocus " + forFocus);
		this.forFocus = forFocus;
	}

}
..

**Comment by ravihariharan** [comment]
The issue has been fixed at ravihariharan/primefaces and tested on tomcat 8.5.11 and Mojarra 2.2.14.
