### ISSUE TITLE
Schedule problem with el expression on then "view" propertie

### ISSUE THREAD

**Issue by kemperalves** [primefaces/primefaces#2253]
When using schedule with dynamic view property its causes a throw, tested in the last version, is too simple to reproduce, simple set the "view" property of schedule to use a el expression, like this:

I uploaded a project that simulate this issue to:

https://github.com/kemperalves/WebApplication1

`
view="#{(true)?'agendaDay':'agendaWeek'}"
`

or simple

`
view="#{'agendaDay'}"
`

Complete example:

`
    <p:button onclick="PF('schedule').update();return false" value="THIS BUTTON CAUSES ERROR"/>

    <p:schedule
        value="#{scheduleView.eventModel}" 
        aspectRatio="3"
        draggable="true"
        resizable="true"
        showHeader="true"
        id="schedule"
        widgetVar="schedule"
        scrollTime="07:00:00"
        timeFormat="HH:mm"
        timeZone="GMT-3"
        clientTimeZone="local"
        allDaySlot="false"
        slotDuration="00:15:00"
        view="#{(true)?'agendaDay':'agendaWeek'}"
        tooltip="true"
        locale="br">

        <p:ajax event="dateSelect" listener="#{scheduleView.onDateSelect}" update="eventDetails" oncomplete="PF('eventDialog').show();" />
        <p:ajax event="eventSelect" listener="#{scheduleView.onEventSelect}" update="eventDetails" oncomplete="PF('eventDialog').show();" />
        <p:ajax event="eventMove" listener="#{scheduleView.onEventMove}" update="messages" />
        <p:ajax event="eventResize" listener="#{scheduleView.onEventResize}" update="messages" />

    </p:schedule>
`

this throw this error

`
07-Apr-2017 16:57:51.782 INFO [http-nio-8084-exec-140] com.sun.faces.context.PartialViewContextImpl.processPartial javax.el.PropertyNotWritableException: /index.xhtml @46,30 view="#{(true)?'agendaDay':'agendaWeek'}": Illegal Syntax for Set Operation
 javax.el.PropertyNotWritableException: /index.xhtml @46,30 view="#{(true)?'agendaDay':'agendaWeek'}": Illegal Syntax for Set Operation
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:136)
	at org.primefaces.component.schedule.Schedule.processUpdates(Schedule.java:524)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:577)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:266)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:1252)
	at com.sun.faces.lifecycle.UpdateModelValuesPhase.execute(UpdateModelValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.el.PropertyNotWritableException: Illegal Syntax for Set Operation
	at org.apache.el.parser.SimpleNode.setValue(SimpleNode.java:137)
	at org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:257)
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:131)
	... 41 more

07-Apr-2017 16:57:51.783 WARNING [http-nio-8084-exec-140] com.sun.faces.lifecycle.UpdateModelValuesPhase.execute javax.el.PropertyNotWritableException: /index.xhtml @46,30 view="#{(true)?'agendaDay':'agendaWeek'}": Illegal Syntax for Set Operation

`

**Comment by kukel** [comment]
But #{'view'} is not writable, so the error is correct...  Use a normal 'field' with getter and setter that contains the logic...

**Comment by tandraschko** [comment]
As @kukel said, a property getter/setter is epxected by the view property
