### ISSUE TITLE
contextMenu error on toggler icon of tree

### ISSUE THREAD

**Issue by qstpss** [primefaces/primefaces#2317]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? There is no newer version yet.
- Does it work on the newest sources in GitHub? (Error may reproduced whatever)
- Application server + version: Tomcat 8. (In showcase too)
- Affected browsers: All

## 2) Expected behavior

ContextMenu should invoke for selected node

## 3) Actual behavior

Node remains unselected and ContextMenu invokes for indefinite node and delete operation shows error

## 4) Steps to reproduce

right click on ui-tree-toggler of node to invoke contextMenu and choose DELETE

## 5) Sample XHTML

from showcase (https://www.primefaces.org/showcase/ui/data/tree/contextMenu.xhtml)

## 6) Sample bean

from showcase (https://www.primefaces.org/showcase/ui/data/tree/contextMenu.xhtml)

**Comment by melloware** [comment]
Stack Trace: 

```
java.lang.NullPointerException
at org.primefaces.showcase.view.data.tree.ContextMenuView.deleteNode(ContextMenuView.java:68)
at sun.reflect.GeneratedMethodAccessor11173.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
at javax.faces.event.MethodExpressionActionListener.processAction(MethodExpressionActionListener.java:149)
at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)
at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:813)
at javax.faces.component.UICommand.broadcast(UICommand.java:300)
at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
at org.primefaces.showcase.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:564)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by kukel** [comment]
Where does this error occur since the online showcase seems to be working for me

**Comment by qstpss** [comment]
Probably you don't follow steps to reproduce.

**Comment by melloware** [comment]
@kukel you have to right click on one of the "arrow" icons in the tree.  I had to do it a few times before I got the stack trace.

**Comment by jxmai** [comment]
Replicated in the showcase. Here is the line that reports the null pointer in showcase's codebase https://github.com/primefaces/showcase/blob/24cfcd9946d24010ca14539e105722b6fce4b34b/src/main/java/org/primefaces/showcase/view/data/tree/ContextMenuView.java#L68.

```java
selectedNode.getChildren().clear();
```

The issue should be because  `selected node` is not set properly by right clicking the icon. Either we should prevent the context menu from popping up if user right clicks on the icon directly or we should set the node correctly rather than `null` behind the scene.

**Comment by melloware** [comment]
I vote for selecting the node on right click.

**Comment by jxmai** [comment]
OK, I see the problem, but I am not entirely sure why the code specifically skips the toggler on purpose

In `tree.js`

https://github.com/primefaces/primefaces/blob/7d46489a6ea47b00539f4a1a22cb71c5cf17c39f/src/main/resources/META-INF/resources/primefaces/tree/tree.js#L317

The `if` statement above will be skipped if we right click on the icon, which will skip the entire bloc of code below

https://github.com/primefaces/primefaces/blob/7d46489a6ea47b00539f4a1a22cb71c5cf17c39f/src/main/resources/META-INF/resources/primefaces/tree/tree.js#L317-L335

Since no node has been selected, the selection variable will be an empty string

https://github.com/primefaces/primefaces/blob/7d46489a6ea47b00539f4a1a22cb71c5cf17c39f/src/main/java/org/primefaces/component/tree/TreeRenderer.java#L71

@melloware  thought on this ? I guess we just need to fix the js if statement.

**Comment by melloware** [comment]
OK so if I am reading that right it says as long as the target is NOT the tree toggler icon?   My guess is that clicking the icon shows and hides the tree node so they didn't want any other click events happening on it?

I am wondering if that will have side effects changing it.   Worth a shot though?  It might even take another if that if its the toggler and its a right click do a "select".

**Comment by jxmai** [comment]
> OK so if I am reading that right it says as long as the target is NOT the tree toggler icon? 

Exactly correct. It was introduced several years ago in https://github.com/primefaces/primefaces/commit/8c9fd3928163b5b28462f0f527270176b1396670#diff-3cc01523b05bd1fb5ffa60e642384c14R213

> I am wondering if that will have side effects changing it. 

Not sure yet since the commit only says 'fixes and refactor' without any sample, so we need some testing to tell.

> Worth a shot though? 

I would say it depends. On one hand,  this issue can be easily prevented with a simple null check in the application and we are dealing with potential regression if we try to fix.  On the other hand, showing up a context menu that cannot delete a node is not user friendly (but only if they right click on an icon instead of a node :sweat: ).

**Comment by tandraschko** [comment]
+1 to fix our code and ignore right clicks on the toggler

**Comment by jxmai** [comment]
OK, I will take a shot later

**Comment by jxmai** [comment]
PR: #2773. The node can be set correctly by right clicking either node or icon when the patch is applied.

I was thinking to also remove the toggler check on left click, but that's not relevant to this issue so I did not touch it.

https://github.com/primefaces/primefaces/blob/dfdd412e01cc6b8c6db11c5deba49c64214f047d/src/main/resources/META-INF/resources/primefaces/tree/tree.js#L275-L276

**Comment by mertsincan** [comment]
Please see; https://github.com/primefaces/primefaces/issues/2978
