### ISSUE TITLE
Dashboard serialize (Tomcat Clustered)

### ISSUE THREAD

**Issue by holiiveira** [primefaces/primefaces#2413]
PrimeFaces version: 6.1

When using the Dashboard component, in an environment with Tomcat 7 (Clustered), the following exception occurs:

`Jun 05, 2017 5:38:14 PM org.apache.catalina.ha.session.DeltaManager requestCompleted
Grave: Unable to serialize delta request for sessionid [8340FA2C62CD4C0A4B44910A44AF0691.node-tomcata]
java.io.NotSerializableException: org.primefaces.component.dashboard.Dashboard
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at java.util.HashMap.writeObject(HashMap.java:1133)
        at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at java.util.HashMap.writeObject(HashMap.java:1133)
        at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at org.apache.catalina.ha.session.DeltaRequest$AttributeInfo.writeExternal(DeltaRequest.java:392)
        at org.apache.catalina.ha.session.DeltaRequest.writeExternal(DeltaRequest.java:285)
        at org.apache.catalina.ha.session.DeltaRequest.serialize(DeltaRequest.java:299)
        at org.apache.catalina.ha.session.DeltaManager.serializeDeltaRequest(DeltaManager.java:621)
        at org.apache.catalina.ha.session.DeltaManager.requestCompleted(DeltaManager.java:1053)
        at org.apache.catalina.ha.session.DeltaManager.requestCompleted(DeltaManager.java:1018)
        at org.apache.catalina.ha.tcp.ReplicationValve.send(ReplicationValve.java:537)
        at org.apache.catalina.ha.tcp.ReplicationValve.sendMessage(ReplicationValve.java:524)
        at org.apache.catalina.ha.tcp.ReplicationValve.sendSessionReplicationMessage(ReplicationValve.java:506)
        at org.apache.catalina.ha.tcp.ReplicationValve.sendReplicationMessage(ReplicationValve.java:419)
        at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:343)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)`

In Tomcat environment without Cluster, the error does not occur.

**Comment by tandraschko** [comment]
As you ignored our issue template and didn't provide a example, i will close it as invalid.

JFYI:
such exceptions occur very likely if you use a binding to a session or viewscoped bean. This will never work as components are not serializable.
