### ISSUE TITLE
dataTable: tableStyle="display:inline" increases cellEditor

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#2541]
Following dataTable increases the input field, if you click on cell. Without *"display:inline"* it works correctly.
~~~ xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui" >
    <h:head/>
    <h:body>
        <h:form id="form">
            <p:dataTable var="row" value="#{[0,1]}" editable="true" editMode="cell" 
                 tableStyle="display:inline">
                <p:columns var="col" value="#{[0,1]}">
                    <p:cellEditor>
                        <f:facet name="output"><h:outputText value="#{row},#{col}" /></f:facet>
                        <f:facet name="input"><h:inputText value="#{row},#{col}" /></f:facet>
                    </p:cellEditor>
                </p:columns>
            </p:dataTable>
        </h:form>
    </h:body>
</html>
~~~
## 1) Environment
PF 6.1, Chrome, Payara (On Firefox/IE it works ok)
## 2) Expected behavior
After clicking on a cell, the editor input field should be as wide as the cell was before.
## 3) Actual behavior
Input editor seems to have a fixed width, that is a lot wider.
## 6) Sample bean
No bean needed.

**Comment by jxmai** [comment]
@mdzaebel  I tried your sample running against 6.2 Snapshot, but the sample could not be run at all. Please verify the sample to see if anything goes wrong.

```
HTTP ERROR 500
Problem accessing /primefaces-test/. Reason:

    /test.xhtml @8,46 value="#{[0,1]}" Error Parsing: #{[0,1]}
Caused by:
javax.faces.view.facelets.TagAttributeException: /test.xhtml @8,46 value="#{[0,1]}" Error Parsing: #{[0,1]}
	at com.sun.faces.facelets.tag.TagAttributeImpl.getValueExpression(TagAttributeImpl.java:428)
	at com.sun.faces.facelets.tag.TagAttributeImpl.getValueExpression(TagAttributeImpl.java:378)
	at com.sun.faces.facelets.tag.jsf.ComponentRule$ValueExpressionMetadata.applyMetadata(ComponentRule.java:107)
	at com.sun.faces.facelets.tag.MetadataImpl.applyMetadata(MetadataImpl.java:81)
	at javax.faces.view.facelets.MetaTagHandler.setAttributes(MetaTagHandler.java:129)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.setAttributes(DelegatingMetaTagHandler.java:102)
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.doNewComponentActions(ComponentTagHandlerDelegateImpl.java:473)
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:179)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:203)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:203)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93)
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87)
	at com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:161)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:990)
```

**Comment by mdzaebel** [comment]
Well, this is JEE 7 (EL 3.0) where #{[0,1]} is valid. It seems you have a JEE 6 environment while JEE 8 is already out. Of course, in JEE6 you can work around with #{bean.list} that must be initialized with {0,1}.

**Comment by mdzaebel** [comment]
JEE7 with EL 3.0 allows this syntax. You might have a JEE6 environment, where you can work around with #{bean.list} rather than #{[0,1]}

**Comment by jxmai** [comment]
@mdzaebel You says:

> PF 6.1, Chrome, Payara (On Firefox/IE it works ok)

Even using Firefox v57, I could see the width increases when I click on a cell. (This is not an issue really, and I will explain below)

![snapshot1](https://user-images.githubusercontent.com/10467831/34189262-4913e166-e500-11e7-9b97-81ea736a1274.png)


---

> Input editor seems to have a fixed width, that is a lot wider.

that's not related to  Primefaces at all since what you saw was the default html behavior.


you can simply put `<input></input>` to any html pages

![snapshot1](https://user-images.githubusercontent.com/10467831/34189335-8c66bbfa-e500-11e7-9f96-143c9c2e31ce.png)


or using `jsfiddle`

![snapshot1](https://user-images.githubusercontent.com/10467831/34189382-cd471f16-e500-11e7-84cf-fdf836e63ea9.png)

---

The default input size depends on browser, so I don't think this is an issue at all. You can always define your own css rule to control the width of the input, so there is nothing primefaces can do / should do.

**Comment by jxmai** [comment]
@mdzaebel Thanks for reporting :+1: , but this is really not an issue for Primefaces.

@tandraschko This issue can be closed.
