### ISSUE TITLE
Filtering on dynamic columns broken

### ISSUE THREAD

**Issue by ltrabanelli** [primefaces/primefaces#2550]
## 1) Environment
- PrimeFaces version: 6.1.3 (I'm sure that in 6.0.15 all works fine...I've downgraded to this version)
- Tomcat 7 - Java 7

- Affected browsers: all browsers

## 2) Expected behavior
I've a datatatable with dynamic columns and filtering on each column with a custom filterFunction.
I filter with enter key.

Here the code:

```
<p:columns value="#{portale.colonneVisualizzate}" var="campo" width="#{campo.sizeColumn}"  
                                               filterValue="#{!empty campo ? campo.filtro : portale.scratchField}"
                                               sortBy="#{doc.mappaCampi[campo.codiceCampo]}" 
                                               headerText="#{portale.getDescrizioneCampo(campo)}"
                                               filterBy="#{doc.mappaCampi[campo.codiceCampo]}" 
                                               filterFunction="#{portale.ut.filtraColonneTabella}">

                                        <h:outputText value="#{doc.mappaCampi[campo.codiceCampo]}" rendered="#{campo.campoDate}">
                                            <f:convertDateTime  pattern="#{sessionBean.calendarPattern}" timeZone="#{sessionBean.timeZone}" /> 
                                        </h:outputText>
                                        <h:outputText value="#{doc.mappaCampi[campo.codiceCampo]}" rendered="#{!campo.campoDate}"/>
                                    </p:columns>

```

## 3) Actual behavior
With PF 6.1.3 when i filter i get the following stack trace
```
2017-07-18 15:50:40 INFO  context:266 - javax.el.PropertyNotWritableException: /IMAGE/IMG_ARCH_PORTALE.xhtml @121,100 filterValue="#{!empty campo ? campo.filtro : portale.scratchField}": Illegal Syntax for Set Operation
javax.el.PropertyNotWritableException: /IMAGE/IMG_ARCH_PORTALE.xhtml @121,100 filterValue="#{!empty campo ? campo.filtro : portale.scratchField}": Illegal Syntax for Set Operation
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:136)
	at org.primefaces.component.datatable.DataTable.processUpdates(DataTable.java:890)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:554)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:827)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:399)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:263)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:1252)
	at com.sun.faces.lifecycle.UpdateModelValuesPhase.execute(UpdateModelValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.labinf.comuni.filters.CaricaVariabili.doFilter(CaricaVariabili.java:163)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.el.PropertyNotWritableException: Illegal Syntax for Set Operation
	at org.apache.el.parser.SimpleNode.setValue(SimpleNode.java:141)
	at org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:252)
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:131)
	... 43 more
2017-07-18 15:50:40 WARN  lifecycle:90 - javax.el.PropertyNotWritableException: /IMAGE/IMG_ARCH_PORTALE.xhtml @121,100 filterValue="#{!empty campo ? campo.filtro : portale.scratchField}": Illegal Syntax for Set Operation
2017-07-18 15:50:40 ERROR application:1204 - Error Rendering View[/IMAGE/IMG_ARCH_PORTALE.xhtml]
java.lang.NullPointerException
	at javax.faces.component.StateHolderSaver.<init>(StateHolderSaver.java:96)
	at javax.faces.component.UIComponentBase.saveAttachedState(UIComponentBase.java:1738)
	at javax.faces.component.ComponentStateHelper.saveMap(ComponentStateHelper.java:378)
	at javax.faces.component.ComponentStateHelper.saveState(ComponentStateHelper.java:256)
	at javax.faces.component.UIComponentBase.saveState(UIComponentBase.java:1545)
	at javax.faces.component.UIData.saveState(UIData.java:1780)
	at org.primefaces.component.api.UIData.saveState(UIData.java:1340)
	at org.primefaces.component.datatable.DataTable.saveState(DataTable.java:1919)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy$3.visit(FaceletPartialStateManagementStrategy.java:482)
	at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:151)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:827)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1740)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.saveView(FaceletPartialStateManagementStrategy.java:472)
	at com.sun.faces.application.StateManagerImpl.saveView(StateManagerImpl.java:89)
	at javax.faces.application.StateManager.getViewState(StateManager.java:593)
	at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:454)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1004)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1896)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:425)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:131)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.labinf.comuni.filters.CaricaVariabili.doFilter(CaricaVariabili.java:163)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
..
I've tried to remove the tag that cause the PropertyNotWritableException but nothing changes.
Seems that with this version the system process some columns with null value...

**Comment by Rapster** [comment]
I wouldn't advise to use conditional expression in EL (expecting a getter or a setter), use `ui:param` to determine what should be called.

https://stackoverflow.com/questions/30656310/javax-el-propertynotwritableexception-when-using-el-conditional-operator-in-valu

**Comment by Rapster** [comment]
@tandraschko not a defect IMO

**Comment by tandraschko** [comment]
And i even can't replicate as a runnable example is missing -> invalid.
