### ISSUE TITLE
DataTable: Filtering on dynamic columns broken with Example

### ISSUE THREAD

**Issue by mobegoulm** [primefaces/primefaces#2606]
This is similar to Issue #2550

the following works with primefaces 6.0.21 but NOT with 6.1.3

```
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui" 
      xmlns:mc="http://java.sun.com/jsf/composite/compositecomponents"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <f:view>
        <h:head>
            <title>Demo</title>
        </h:head>

        <h:body>
            <h:form>
                <p:commandButton value="init" actionListener="#{dummyBean.init(null)}" update="@all"></p:commandButton>
                <br />
                <br />
            </h:form>

            <p:tabView scrollable="true" value="#{dummyBean.garages}" var="garage" dynamic="true" cache="false" id="garageTabView" activeIndex="#{dummyBean.activetabIndex}"  widgetVar="widgetGarageTabView">
                <p:ajax event="tabChange" listener="#{dummyBean.onTabChange(garage)}"/>

                <p:tab id="garageTab">
                    <f:facet name="title">
                        <h:outputText value="#{garage.name}" />
                    </f:facet>

                    <h:form id="formco#{garage.id}">
                        <p:dataTable var="car" id="cot" widgetVar="widgetCot#{car.id}"
                                     value="#{dummyBean.carDataModel}" 
                                     selectionMode="single" selection="#{dummyBean.selectedCar}"
                                     paginator="false"
                                     scrollable="true"  rowIndexVar="index"  scrollHeight="500" 
                                     scrollRows="50" liveScroll="true"
                                     sortBy="#{car.id}"
                                     rowKey="#{car.id}"
                                     filterDelay="1100">

                            <p:ajax event="rowSelect" listener="#{dummyBean.deepLoadCar}"/> 
                            <f:facet name="header">
                                <p:outputPanel layout="inline" styleClass="tabSpacer">
                                    <h:outputText value="Global Filter:" />
                                    <p:inputText id="globalFilter" onkeyup="PF('widgetCot#{car.id}').filter()" style="width:150px;margin-left:10px;"/>
                                </p:outputPanel>
                            </f:facet>
                            <p:column id="myid" style="white-space: nowrap;" headerText="CarId" sortBy="#{car.id}">
                                <h:outputText value="#{car.id}"/>
                            </p:column>
                            <p:columns id="dyn" value="#{garage.childList}" var="dummyChild" columnIndexVar="colIndex"  filterValue="#{dummyBean.carsFilteMap[dummyChild.name]}" filterMatchMode="contains" filterBy="#{car.fields[dummyChild.name]}" sortBy="#{car.fields[dummyChild.name]}">
                                <f:facet name="header">
                                    <h:outputText value="#{dummyChild.name}" />
                                </f:facet>
                                <h:outputText value="#{car.fields[dummyChild.name]}" />
                            </p:columns>

                        </p:dataTable>
                    </h:form>
                </p:tab>
            </p:tabView>
        </h:body>        
    </f:view>
</html>
```

```
package de.fumo.gui;

import de.fumo.model.Car;
import de.fumo.model.Garage;
import de.fumo.model.datamodel.CarDataModel;
import de.fumo.service.CarService;
import java.util.HashMap;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@SessionScoped
public class DummyBean implements java.io.Serializable {
    
    @Inject
    private  CarService carService;
    private List<Garage> garages;

    private CarDataModel carDataModel = new CarDataModel();    
    private List<Car> cars;
    private List<Car> filteredCars;
    private Car selectedCar;
    private HashMap<String,Object> carsFilteMap = new HashMap();
    
    private int activetabIndex;
    
    public void init(Garage garage) {
        carsFilteMap.clear();
        if(this.getGarages() == null)
            setGarages(carService.createGarages());
        if(garage != null) {
            this.setCarDataModel(new CarDataModel(carService.createCars(10,garage)));
        } else {
            this.setCarDataModel(new CarDataModel(carService.createCars(10,this.getGarages().get(0))));
        }
    }
    
    public void onTabChange(Garage garage) {
        System.out.println("onTabChange " + garage);
        carsFilteMap.clear();
        this.setCarDataModel(new CarDataModel(carService.createCars(10,garage)));
    }
    
    public void deepLoadCar() {
        System.out.println("deepLoadCar " + this.getSelectedCar().getId());
    }
    

    /**
     * @return the activetabIndex
     */
    public int getActivetabIndex() {
        return activetabIndex;
    }

    /**
     * @param activetabIndex the activetabIndex to set
     */
    public void setActivetabIndex(int activetabIndex) {
        this.activetabIndex = activetabIndex;
    }

    /**
     * @return the selectedCar
     */
    public Car getSelectedCar() {
        return selectedCar;
    }

    /**
     * @param selectedCar the selectedCar to set
     */
    public void setSelectedCar(Car selectedCar) {
        this.selectedCar = selectedCar;
    }

    /**
     * @return the cars
     */
    public List<Car> getCars() {
        return cars;
    }

    /**
     * @param cars the cars to set
     */
    public void setCars(List<Car> cars) {
        this.cars = cars;
    }

    /**
     * @return the filteredCars
     */
    public List<Car> getFilteredCars() {
        return filteredCars;
    }

    /**
     * @param filteredCars the filteredCars to set
     */
    public void setFilteredCars(List<Car> filteredCars) {
        this.filteredCars = filteredCars;
    }

    /**
     * @return the garages
     */
    public List<Garage> getGarages() {
        return garages;
    }

    /**
     * @param garages the garages to set
     */
    public void setGarages(List<Garage> garages) {
        this.garages = garages;
    }

    /**
     * @return the carDataModel
     */
    public CarDataModel getCarDataModel() {
        return carDataModel;
    }

    /**
     * @param carDataModel the carDataModel to set
     */
    public void setCarDataModel(CarDataModel carDataModel) {
        this.carDataModel = carDataModel;
    }

    /**
     * @return the carsFilteMap
     */
    public HashMap<String,Object> getCarsFilteMap() {
        return carsFilteMap;
    }

    /**
     * @param carsFilteMap the carsFilteMap to set
     */
    public void setCarsFilteMap(HashMap<String,Object> carsFilteMap) {
        this.carsFilteMap = carsFilteMap;
    }
    
}

```

```

package de.fumo.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;

public class Car implements Serializable {
    
    public Integer id;
    public String brand;
    public int year;
    public String color;
    public int price;
    public boolean sold;
    private HashMap fields = new HashMap();


    public Car() {}
    
    public Car(int id, String brand, int year, String color) {
        this.id = id;
        this.brand = brand;
        this.year = year;
        this.color = color;
    }
    
    public Car(int id, String brand, int year, String color, int price, boolean sold) {
        this.id = id;
        this.brand = brand;
        this.year = year;
        this.color = color;
        this.price = price;
        this.sold = sold;
}


    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBrand() {
        return brand;
    }
    public void setBrand(String brand) {
        this.brand = brand;
    }

    public int getYear() {
        return year;
    }
    public void setYear(int year) {
        this.year = year;
    }

    public String getColor() {
        return color;
    }
    public void setColor(String color) {
        this.color = color;
    }

    public int getPrice() {
        return price;
    }
    public void setPrice(int price) {
        this.price = price;
    }

    public boolean isSold() {
        return sold;
    }
    public void setSold(boolean sold) {
        this.sold = sold;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Car other = (Car) obj;
        if ((this.id == null) ? (other.id != null) : !this.id.equals(other.id)) {
            return false;
        }
        return true;
}

    /**
     * @return the fields
     */
    public HashMap getFields() {
        return fields;
    }

    /**
     * @param fields the fields to set
     */
    public void setFields(HashMap fields) {
        this.fields = fields;
    }

}

```

```

package de.fumo.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Garage implements Serializable {
    
    public Integer id;
    public String name;
    private List<DummyChild> childList = new ArrayList();


    public Garage() {}
    
    public Garage(int id, String name) {
        this.id = id;
        this.name = name;
    }
    
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Garage other = (Garage) obj;
        if ((this.id == null) ? (other.id != null) : !this.id.equals(other.id)) {
            return false;
        }
        return true;
}

    /**
     * @return the childList
     */
    public List<DummyChild> getChildList() {
        return childList;
    }

    /**
     * @param childList the childList to set
     */
    public void setChildList(List<DummyChild> childList) {
        this.childList = childList;
    }
}

```

```
package de.fumo.service;

import de.fumo.model.Car;
import de.fumo.model.DummyChild;
import de.fumo.model.Garage;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import java.util.UUID;

@Named
@ApplicationScoped
public class CarService {

    private final static String[] colors;
     
    private final static String[] brands;
    private final static String[] garages;
     
    static {
        garages = new String[5];
        garages[0] = "Garage 1";
        garages[1] = "Garage 2";
        garages[2] = "Garage 3";
        garages[3] = "Garage 4";
        garages[4] = "Garage 5";


        colors = new String[10];
        colors[0] = "Black";
        colors[1] = "White";
        colors[2] = "Green";
        colors[3] = "Red";
        colors[4] = "Blue";
        colors[5] = "Orange";
        colors[6] = "Silver";
        colors[7] = "Yellow";
        colors[8] = "Brown";
        colors[9] = "Maroon";
         
        brands = new String[10];
        brands[0] = "BMW";
        brands[1] = "Mercedes";
        brands[2] = "Volvo";
        brands[3] = "Audi";
        brands[4] = "Renault";
        brands[5] = "Fiat";
        brands[6] = "Volkswagen";
        brands[7] = "Honda";
        brands[8] = "Jaguar";
        brands[9] = "Ford";
    }
     
    public List<Garage> createGarages() {
        List<Garage> list = new ArrayList();
        for(int i = 0 ; i < 5 ; i++) {
            Garage garage = new Garage(getRandomId(), garages[i]);
            
            for(int j = 0 ; j < getRandomNumberInRange(1,6) ; j++) {
                DummyChild dummyChild = new DummyChild();
                dummyChild.setId(getRandomId());
                dummyChild.setName(getRandomColor());
                garage.getChildList().add(dummyChild);
            }
            list.add(garage);
        }
        return list;
    }
    
    private static int getRandomNumberInRange(int min, int max) {
            if (min >= max) {
                throw new IllegalArgumentException("max must be greater than min");
            }
            Random r = new Random();
            return r.nextInt((max - min) + 1) + min;
    }
    
    public List<Car> createCars(int size, Garage garage) {
        List<Car> list = new ArrayList();
        for(int i = 0 ; i < size ; i++) {
            Car car = new Car(getRandomId(), getRandomBrand(), getRandomYear(), getRandomColor(), getRandomPrice(), getRandomSoldState());
            HashMap fields = new HashMap();
            car.setFields(fields);
            for(DummyChild dummyChild: garage.getChildList()) {
                fields.put(dummyChild.getName(), getRandomBrand());
            }
            list.add(car);
        }
         
        return list;
    }
     
    private int getRandomId() {
        return Math.abs(new Random().nextInt());
    }
     
    private int getRandomYear() {
        return (int) (Math.random() * 50 + 1960);
    }
     
    private String getRandomColor() {
        return colors[(int) (Math.random() * 10)];
    }
     
    private String getRandomBrand() {
        return brands[(int) (Math.random() * 10)];
    }
    
     
    public int getRandomPrice() {
        return (int) (Math.random() * 100000);
    }
     
    public boolean getRandomSoldState() {
        return (Math.random() > 0.5) ? true: false;
    }
 
    public List<String> getColors() {
        return Arrays.asList(colors);
    }
     
    public List<String> getBrands() {
        return Arrays.asList(brands);
    }

    
}

```

```
package de.fumo.model.datamodel;

import de.fumo.model.Car;
import java.util.List;

public class CarDataModel extends BaseDataModel<Car>  {
  
  
    public CarDataModel() {  
    }  
  
    public CarDataModel(Object data) {  
        super(data);
    }  
    @Override
    public Car getRowData(String rowKey) {  
        int id;
        try {
            id = Integer.parseInt(rowKey);
        } catch (Exception e) {
            return null;
        }
        List<Car> dataList = (List<Car>) getWrappedData();  
          
        for(Car car : dataList) {  
            if(car.getId() == id)  {
                return car;  
            }
                
        }  
        return null;  
    }  
    @Override
    public String getRowKey(Car car) {  
        return Integer.toString(car.getId());  
    }  
    
    
    
    
    
    
    

    
}  


```

```
package de.fumo.model;

import java.util.Date;

public class DummyChild {
    private Integer id;
    private String name;
    private Date lastAccess;

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the lastAccess
     */
    public Date getLastAccess() {
        return lastAccess;
    }

    /**
     * @param lastAccess the lastAccess to set
     */
    public void setLastAccess(Date lastAccess) {
        this.lastAccess = lastAccess;
    }
    
}

```

```
package de.fumo.model.datamodel;
import java.io.Serializable;
import javax.faces.model.ListDataModel;
import org.primefaces.model.SelectableDataModel;

/**
 *
 * @author juergen
 */
public class BaseDataModel<T> extends ListDataModel implements SelectableDataModel<T>, Serializable {
            
    public BaseDataModel() {}
    
    public BaseDataModel(Object data) {
        setWrappedData(data);
    }
    
    public String getRowKey(T object) {
        throw new UnsupportedOperationException("Must be implemented");
    }
    
    public T getRowData(String rowKey) {
        throw new UnsupportedOperationException("Must be implemented");
    }

}
```

```
java.lang.NullPointerException
	at javax.faces.component.StateHolderSaver.<init>(StateHolderSaver.java:96)
	at javax.faces.component.UIComponentBase.saveAttachedState(UIComponentBase.java:1746)
	at javax.faces.component.ComponentStateHelper.saveMap(ComponentStateHelper.java:372)
	at javax.faces.component.ComponentStateHelper.saveState(ComponentStateHelper.java:256)
	at javax.faces.component.UIComponentBase.saveState(UIComponentBase.java:1553)
	at javax.faces.component.UIData.saveState(UIData.java:1780)
	at org.primefaces.component.api.UIData.saveState(UIData.java:1340)
	at org.primefaces.component.datatable.DataTable.saveState(DataTable.java:1919)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy$3.visit(FaceletPartialStateManagementStrategy.java:481)
	at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:151)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:827)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:927)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.saveView(FaceletPartialStateManagementStrategy.java:471)
	at com.sun.faces.application.StateManagerImpl.saveView(StateManagerImpl.java:89)
	at javax.faces.application.StateManager.getViewState(StateManager.java:593)
	at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:483)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:325)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1004)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:432)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
	at com.ocpsoft.pretty.faces.application.PrettyViewHandler.renderView(PrettyViewHandler.java:163)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:201)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at de.fumo.filter.LoginFilter.doFilter(LoginFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.ocpsoft.pretty.PrettyFilter.doFilter(PrettyFilter.java:145)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:122)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Rapster** [comment]
With this amount of code information, I'd suggest you to use the provided tempate (primefaces-test) so PF team can reproduce the problem. FYI, follow the issue template ;-)

**Comment by Rapster** [comment]
I simply try this and it works

``` xml
 <p:dataTable var="car" value="#{dtFilterView.cars}" widgetVar="carsTable"
                         emptyMessage="No cars found with given criteria" filteredValue="#{dtFilterView.filteredCars}">

                <f:facet name="header">
                    <p:outputPanel>
                        <h:outputText value="Search all fields:" />
                        <p:inputText id="globalFilter" onkeyup="PF('carsTable').filter()" style="width:150px" placeholder="Enter keyword"/>
                    </p:outputPanel>
                </f:facet>

                <p:columns value="#{dtColumnsView.columns}" var="column" columnIndexVar="colIndex" sortBy="#{column.property}" filterBy="#{car[column.property]}">
                    <f:facet name="header">
                        <h:outputText value="#{column.header}" />
                    </f:facet>
                    <h:outputText value="#{car[column.property]}" />
                </p:columns>
            </p:dataTable>
```

**Comment by mobegoulm** [comment]
Works now with mojarra 2.2.15!
