### ISSUE TITLE
BaseMenuRenderer.encodeEnd(..) always throws IllegalArgumentException

### ISSUE THREAD

**Issue by croo** [primefaces/primefaces#2813]
## 1) Environment
- PrimeFaces version: 6.2 (2 months old build from source)
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? I didn't test it but checked the primefaces sources on github and the problem seems to be still there
- Application server + version: JBOSS 7 eap
- Affected browsers: all

## 2) Expected behavior
Should not throw IllegalArgumentException if I create a DefaultMenuModel with UIMenuItems and use it as a model for a <p:menuButton>

## 3) Actual behavior
The fuction `BaseMenuRenderer.encodeEnd(..)` _*always*_ throws IllegalArgumentException regardless of function parameters.
This happens because `MenuModel.generateUniqueIds()` uses `(String)null` as input parameter for seed when generating a uniqueId which causes the uniqueId to be a simple number. This number gets validated in `UIComponentBase.validateId()` wich in turn throws an IllegalArgumentException because the id must start with a letter or the character '_'.

## 4) Steps to reproduce
I didn't test it with the base classes but creating a DefaultMenuModel with UIMenuItems in it and show it through 
```
 <p:menuButton id="taskListRowMenubar"
                          model="#{bean.menuModel}"...> 

```
should trigger the same problem.

## 5) Sample XHTML
--
## 6) Sample bean
--

## 7) Stacktrace:

java.lang.IllegalArgumentException: 0
at javax.faces.component.UIComponentBase.validateId(UIComponentBase.java:587)
at javax.faces.component.UIComponentBase.setId(UIComponentBase.java:413)
at org.primefaces.model.menu.BaseMenuModel.generateUniqueIds(BaseMenuModel.java:56)
at org.primefaces.model.menu.BaseMenuModel.generateUniqueIds(BaseMenuModel.java:44)
at org.primefaces.model.menu.DefaultMenuModel.generateUniqueIds(DefaultMenuModel.java:28)
at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:111)
at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
at javax.faces.render.RendererWrapper.encodeChildren(RendererWrapper.java:95)
at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890)
at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:458)
at javax.faces.view.ViewDeclarationLanguageWrapper.renderView(ViewDeclarationLanguageWrapper.java:146)
at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
at com.liferay.faces.bridge.application.internal.ViewHandlerCompatImpl.renderView(ViewHandlerCompatImpl.java:95)
at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
...

**Comment by melloware** [comment]
@croo do you have a proposed fix?

**Comment by croo** [comment]
Nope. I tried to work along the lines of this thread and override the Renderer:
https://code.google.com/archive/p/primefaces/issues/6187
but did not succeed.

What I confirmed is when I use DefaultMenuItem instead of UIMenuItem the problem goes away. Can you confirm that this approach should work? (as far as I can tell from the primefaces source it *should* work..)

Similar the "programmatically" part of this example :https://www.primefaces.org/showcase/ui/menu/menu.xhtml but with UIMenuItems instead of DefaultMenuItems in the backing bean.

**Comment by tandraschko** [comment]
I never used models but i think it's not valid to use UIMenuItem, as UIMenuItem is a real UI component, not a model pojo.
See here some usages of UIMenuItem:
        UIMenuItem menuItem =
                (UIMenuItem) fc.getApplication().createComponent(UIMenuItem.COMPONENT_TYPE);

**Comment by tandraschko** [comment]
This will likely be closed as invalid.

**Comment by Rapster** [comment]
I do agree with @tandraschko I think you're misusing the class you should use. I think I ended up having the same issue by using `UISeparator `instead of `DefaultSeparator`. Make sure to use classes contained in `org.primefaces.model`. Next time, post the code you wrote to generate the model
