### ISSUE TITLE
FileUpload: advanced upload fails - Missing content for multipart request

### ISSUE THREAD

**Issue by happyherp** [primefaces/primefaces#2909]
## 1) Environment
- PrimeFaces version: The one that is deployed on primefaces.org on 8.11.2017 15:50

- Browser: Firefox 56.0.2 (64-Bit) and Google Chrome  Version 61.0.3163.100 (Offizieller Build) (64-Bit)
- OS: Windows 110 

## 2) Expected behavior

I don't know. 

## 3) Actual behavior

Stacktrace appears 

`java.lang.RuntimeException: java.io.IOException: Missing content for multipart request
at org.eclipse.jetty.server.Request.extractMultipartParameters(Request.java:525)
at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:442)
at org.eclipse.jetty.server.Request.getParameters(Request.java:366)
at org.eclipse.jetty.server.Request.getParameterNames(Request.java:1018)
at javax.servlet.ServletRequestWrapper.getParameterNames(ServletRequestWrapper.java:212)
at org.primefaces.webapp.MultipartRequest.getParameterNames(MultipartRequest.java:143)
at com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:80)
at com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:57)
at java.util.Collections$UnmodifiableMap.get(Collections.java:1454)
at org.primefaces.component.lifecycle.LifecyclePhaseListener.isGetLifecycleInfoRequest(LifecyclePhaseListener.java:101)
at org.primefaces.component.lifecycle.LifecyclePhaseListener.beforePhase(LifecyclePhaseListener.java:32)
at com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:225)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:98)
at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:133)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:670)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:97)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
at org.primefaces.showcase.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:564)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Missing content for multipart request
at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:554)
at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:441)
at org.eclipse.jetty.server.Request.getParts(Request.java:2319)
at org.eclipse.jetty.server.Request.extractMultipartParameters(Request.java:520)
... 49 more`
..

## 4) Steps to reproduce

Goto: 
https://www.primefaces.org/showcase/ui/file/upload/multiple.xhtml

Choose a file: [
![hp](https://user-images.githubusercontent.com/2945814/32555868-2b65eec0-c49e-11e7-82eb-9675b2e60631.PNG)
](url)

Click Upload. 
..

**Comment by happyherp** [comment]
![grafik](https://user-images.githubusercontent.com/2945814/32556081-b5ca4912-c49e-11e7-8b70-5dd83a0364e2.png)

Screenshot as proof.

**Comment by tandraschko** [comment]
Can you reproduce it in your app or is it just in the showcase? Maybe we just dont set the encType in the showcase.

**Comment by happyherp** [comment]
In the app I am still using richfaces for fileuploads where I ran into this similiar issue: 
https://issues.jboss.org/browse/RF-11988
I was thinking of migrating the component(mine) that does fileuploads to primefaces to fix that problem. As you can see, I did not come very far.

**Comment by tandraschko** [comment]
Seems like nothing will be uploaded, maybe because of our jquery update

**Comment by melloware** [comment]
Hmm I am using PF 6.1.8 with the JQ update and File Upload is working in my production projects.

With Jboss EAP 6.4.  could this be a Jetty issue?

**Comment by tandraschko** [comment]
Can you try 6.2-SNAPSHOT in your application? Not sure if it's a jetty problem.

**Comment by tandraschko** [comment]
The problem is commons-fileupload in combination with jetty currently: https://github.com/eclipse/jetty.project/issues/182

will switch to native upload for the showcase - this also fixes the problem
