### ISSUE TITLE
<p:dataExporter type="xls" throws Exception

### ISSUE THREAD

**Issue by vitsin** [primefaces/primefaces#2915]
GUI issue: element <p:dataExporter type="xls" returns:
SEVERE: Servlet.service() for servlet [Spring MVC Dispatcher Servlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.CellStyle.setAlignment(S)V] with root cause
java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.CellStyle.setAlignment(S)V
	at org.primefaces.component.export.ExcelExporter.applyOptions(ExcelExporter.java:290)
	at org.primefaces.component.export.ExcelExporter.export(ExcelExporter.java:75)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:134)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:814)
	at javax.faces.component.UICommand.broadcast(UICommand.java:300)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at org.springframework.faces.webflow.FlowLifecycle.invokePhase(FlowLifecycle.java:97)
	at org.springframework.faces.webflow.FlowLifecycle.execute(FlowLifecycle.java:69)
	at org.springframework.faces.webflow.JsfView.processUserEvent(JsfView.java:111)
	at org.springframework.webflow.engine.ViewState.handleEvent(ViewState.java:225)
	at org.springframework.webflow.engine.ViewState.resume(ViewState.java:195)
	at org.springframework.webflow.engine.Flow.resume(Flow.java:537)

Maven jars:
		<dependency>
			<groupId>org.apache.poi</groupId>
		    <artifactId>poi</artifactId>
		    <version>3.17</version>
		</dependency>

		<dependency>
			<groupId>org.primefaces</groupId>
		    <artifactId>primefaces</artifactId>
		    <version>6.1</version>
		</dependency>

Note: <p:dataExporter type="csv" or "pdf" - working completely fine. 

## 5) Sample XHTML
<h:form id="exportForm">
<sv:csrfHidden />
	<div class="MyButtonContainer">
        <p:commandButton ajax="false" value="Export to XLS">  
            <p:dataExporter type="xls" target=":viewForm:viewTable" fileName="translatedText" encoding="UTF-8"/>  
        </p:commandButton>
        <p/>
      	</div>  
</h:form>

**Comment by tandraschko** [comment]
POI 3.17 is not supported in 6.1: https://github.com/primefaces/primefaces/issues/2885

**Comment by myset** [comment]
It works with POI 3.16
