### ISSUE TITLE
Exception when using sortBy in PF 6.1.8 when datatable is not in a form

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#2920]
Hi, PF6.1.8 @ WildFly11 - Using the Showcase classes

```xml
<html xmlns="http://www.w3.org/1999/xhtml"  
    xmlns:h="http://java.sun.com/jsf/html"  
    xmlns:f="http://java.sun.com/jsf/core"  
    xmlns:p="http://primefaces.org/ui">  
    <h:head>  
    </h:head>  
    <h:body>  
      <p:dataTable var="car" value="#{dtBasicView.cars}" sortMode="multiple">
	    <p:column headerText="Year" sortBy="#{car.year}">
	        <h:outputText value="#{car.year}" />
	    </p:column>
	</p:dataTable>
    </h:body>  
</html>   
```
causes

```java
[31m13:07:55,635 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-18) Error Rendering View[/table.xhtml]: java.lang.NullPointerException
	at org.primefaces.component.datatable.feature.SortFeature.multiSort(SortFeature.java:216)
	at org.primefaces.component.datatable.feature.SortFeature.encode(SortFeature.java:109)
	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:87)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:949)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1912)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:638)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:827)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:423)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:342)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1124)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:465)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
	at javax.faces.application.ViewHandlerWra
```

Adding a form makes it work.

```xml
<html xmlns="http://www.w3.org/1999/xhtml"  
    xmlns:h="http://java.sun.com/jsf/html"  
    xmlns:f="http://java.sun.com/jsf/core"  
    xmlns:p="http://primefaces.org/ui">  
    <h:head>  
    </h:head>  
    <h:body>
      <h:form>
       <p:dataTable var="car" value="#{dtBasicView.cars}" sortMode="multiple">
	    <p:column headerText="Year" sortBy="#{car.year}">
	        <h:outputText value="#{car.year}" />
	    </p:column>
		</p:dataTable>
      </h:form>  
    </h:body>  
</html>  
```

**Comment by tandraschko** [comment]
As sorting in done on the server AFAIR, the dataTable must be inside a form. @melloware correct me please if it's not correct.

**Comment by melloware** [comment]
Yes a datatable must reside inside an h:form and sorting and filtering do form submit's to send the data.
