### ISSUE TITLE
FileUpload doesn't work on JSF 2.3

### ISSUE THREAD

**Issue by dmatej** [primefaces/primefaces#2988]
FileUpload should work but it does not and I still don't know why but I tried many configuration variants and found out this stack trace when I set this in web.xml and use the `@FacesConfig(version = Version.JSF_2_3)` annotation. (But commons variant does still nothing.)
```
  <context-param>
    <param-name>javax.faces.ENABLE_CDI_RESOLVER_CHAIN</param-name>
    <param-value>true</param-value>
  </context-param>
  <context-param>
    <param-name>primefaces.UPLOADER</param-name>
    <param-value>native</param-value>
  </context-param>
```
```
[2017-11-23T00:31:54.932+0100] [] [INFO] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=28 _ThreadName=http-thread-pool::http-listener(10)] [timeMillis: 1511393514932] [levelValue: 800] [[
  javax.faces.FacesException: native uploader requires at least a JSF 2.2 runtime
javax.faces.FacesException: native uploader requires at least a JSF 2.2 runtime
        at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:59)
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:533)
        at javax.faces.component.UIInput.decode(UIInput.java:822)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:910)
        at javax.faces.component.UIInput.processDecodes(UIInput.java:716)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:629)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1479)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1491)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1491)
        at javax.faces.component.UIForm.visitTree(UIForm.java:379)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1491)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1491)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:423)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:284)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
        at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1031)
        at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:79)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
...
```

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest sources in GitHub? No, tested against commit ca1d82f18c9fd78ed1435fde3f967b0c77ee3df6
- Application server + version: Payara 5...-SNAPSHOT, micro
- Affected browsers: all

## 2) Expected behavior
No stacktrace and working FileUpload component in both variants (native/commons).

## 3) Actual behavior
Request is sent but causes only a stacktrace for native variant and nothing for commons variant.

## 4) Steps to reproduce
web.xml (note: result is same with or without the filter-mapping):
```
<!--   <filter> -->
<!--     <filter-name>PrimeFaces FileUpload Filter</filter-name> -->
<!--     <filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class> -->
<!--   </filter> -->
<!--   <filter-mapping> -->
<!--     <filter-name>PrimeFaces FileUpload Filter</filter-name> -->
<!--     <servlet-name>Faces Servlet</servlet-name> -->
<!--     <dispatcher>FORWARD</dispatcher> -->
<!--     <dispatcher>REQUEST</dispatcher> -->
<!--   </filter-mapping> -->
  <context-param>
    <param-name>primefaces.UPLOADER</param-name>
    <param-value>native</param-value>
  </context-param>
```

```
@FacesConfig(version = Version.JSF_2_3)
@Named
public class JsfConfiguration {
}
```

## 5) Sample XHTML
```
      <h:form enctype="multipart/form-data">
        <h:panelGrid columns="2">
          <h:outputText value="Input file: " />
          <p:fileUpload fileUploadListener="#{xImport.uploadFile}" mode="advanced" dragDropSupport="true"
           update="messages" sizeLimit="10000000" sequential="true" />
        </h:panelGrid>
      </h:form>
```
..

## 6) Sample bean
```
@Named
@ViewScoped // @RequestScoped - no difference
public class XImport implements Serializable {

  private static final long serialVersionUID = -6731613465171745866L;

  private static final Logger LOG = LogManager.getLogger(XImport.class);

  @Inject
  private FacesContext facesContext;

  public void uploadFile(final FileUploadEvent event) {
    final UploadedFile file = event.getFile();
    LOG.debug("File size: {}", file.getSize());
    final FacesMessage message = new FacesMessage("Succesful", file.getFileName() + " is uploaded.");
    this.facesContext.addMessage(null, message);
  }
```

Final question: sources still must support Java 6.0?

**Comment by tandraschko** [comment]
Please debug PrimeConfig.class - we wont scan this annotation but we automatically check the running jsf implemtation.

**Comment by dmatej** [comment]
I see one problem ... I hope I could provide a pull request soon; the issue name is somehow misleading because covers two or three interacting things.
I suppose that for Primefaces is not important the FacesConfig compatibility so it can ignore it. But it is still needed to know the implementation version; finally the problem is simple - the current mojarra moved to 2.4-SNAPSHOT but the check is made only to 2.1/2.2/2.3 (but 2.3 is not detected in filter) and fallback is missed.

**Comment by tandraschko** [comment]
2.4 is of course not supported now. A PR is welcome.

**Comment by tandraschko** [comment]
committed something and should work now.
Some notes:
1) you don't even need to the filter on JSF 2.2 environments, so therefore you can just remove it from your web.xml
2) the handling of the PrimeConfiguration will be redeveloped in 6.3, after RequestContext will be removed. So it will be cleaner soon.

Would be great if you can test + review.
