### ISSUE TITLE
private final EventBus eventBus = EventBusFactory.getDefault(); throws NPE

### ISSUE THREAD

**Issue by jveverka** [primefaces/primefaces#300]
After upgrading my project to PrimeFaces 5.2 (or 5.2.3) and atmosphere runtime 2.3.0 (or 2.3.1), 

``` java
org.primefaces.push.EventBusFactory.getDefault().eventBus(); 
```

throws NPE. Unfortunately, suggested solution [here](https://groups.google.com/forum/#!topic/atmosphere-framework/ZOMmqMcBw94) is not working. Push was working fine when I used PrimeFaces 5.1.x jars.
### web.xml configuration:

``` xml
  <servlet>
    <servlet-name>Push Servlet</servlet-name>
    <servlet-class>org.primefaces.push.PushServlet</servlet-class>
    <init-param>
       <param-name>org.atmosphere.cpr.broadcasterCacheClass</param-name>
       <param-value>org.atmosphere.cache.UUIDBroadcasterCache</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
    <async-supported>true</async-supported>
  </servlet>

  <servlet-mapping>
    <servlet-name>Push Servlet</servlet-name>
    <url-pattern>/primepush/*</url-pattern>
  </servlet-mapping>
```
### jar files used in project

all-themes-1.0.10.jar
atmosphere-runtime-2.3.1.jar
barcode4j-2.1.jar
commons-fileupload-1.3.jar
commons-io-2.4.jar
core-3.0.0.jar
javase-3.0.0.jar
omnifaces-2.0.jar
poi-3.11.jar
primefaces-5.2.3.jar
qrgen-1.4.jar
slf4j-api-1.6.1.jar

**Comment by cagataycivici** [comment]
@jfarcand Do you know what could cause this?

**Comment by jfarcand** [comment]
@jveverka I need more information about your use case. Are you invoking `org.primefaces.push.EventBusFactory.getDefault().eventBus();` directly? It seems the PushServlet in your use case is not installed properly => `https://goo.gl/AX9TX6`

**Comment by jveverka** [comment]
Hi 
this https://github.com/jveverka/pfpush is simple example which is showing the problem. I hope my servlet config is ok, this is the config I am using for quite some time (since PF 5.0)
after upgrading to PF 5.2.x as described above, I get NPE.
runtime is wildfly 8.2.0 

Thanks in advance

**Comment by jfarcand** [comment]
@jveverka Everything looks OK. Are you sure you only have one version of primefaces installed? It seems the `PushServlet` is not properly installed. Can you package your code inside a .war and send me a link to it?

**Comment by jveverka** [comment]
Hi Jeanfrancois 

sure, both war files are here https://github.com/jveverka/pfpush/tree/master/bin
there are no special dependencies, you can deploy them into WF 8.2.0 directly.
PFPushDemo.5.1.war - works fine
PFPushDemo.5.2.war - does not deploy because of NPE
no other apps are deployed in AS. hopefully I am not doing anything stupid :)
thanks !

**Comment by jveverka** [comment]
or maybe it would be better to get reference to EventBus using CDI, but that was not working for me either (using atmosphere-cdi). if you have some hints how to use CDI to inject EventBus, please let me know.

**Comment by jfarcand** [comment]
@jveverka 5.2 doesn't start properly. Is it the exception below that is caused by this issue? The PushServlet hasn't been initialized when this is called. This is an API change from 5.1 so you will need to make sure the `PushServlet` is initialized before you can get the 'EventBus`

``` java
Caused by: java.lang.NullPointerException
    at org.itx.pfpushdemo.BackendService.<init>(BackendService.java:18)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_40]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_40]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_40]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [rt.jar:1.8.0_40]
    at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:113)
    at org.jboss.weld.injection.ConstructorInjectionPoint$1.proceed(ConstructorInjectionPoint.java:95)
    at org.jboss.as.weld.injection.WeldManagedReferenceFactory.create(WeldManagedReferenceFactory.java:51)
    at org.jboss.as.ee.component.ComponentInstantiatorInterceptor.processInvocation(ComponentInstantiatorInterceptor.java:68) [wildfly-ee-8.2.0.Final.jar:8.2.0.Final]
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
    at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doLifecycleInterception(Jsr299BindingsInterceptor.java:114)
    at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:105)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
    at org.jboss.as.weld.injection.WeldConstructionStartInterceptor$1.aroundConstruct(WeldConstructionStartInterceptor.java:53)
    at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallback(ConstructorInjectionPoint.java:103)
    at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallbacks(ConstructorInjectionPoint.java:89)
    at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:74)
    at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)
    at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:194)
    at org.jboss.weld.injection.producer.ejb.SessionBeanInjectionTarget.produce(SessionBeanInjectionTarget.java:126)
    at org.jboss.as.weld.injection.WeldInjectionContext.produce(WeldInjectionContext.java:46)
    at org.jboss.as.weld.injection.WeldConstructionStartInterceptor.processInvocation(WeldConstructionStartInterceptor.java:37)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
    at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
    at org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:26) [wildfly-ee-8.2.0.Final.jar:8.2.0.Final]
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
    at org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
    at org.jboss.as.weld.ejb.Jsr299BindingsCreateInterceptor.processInvocation(Jsr299BindingsCreateInterceptor.java:94)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
    at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50) [wildfly-ee-8.2.0.Final.jar:8.2.0.Final]
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:273)
```

**Comment by jfarcand** [comment]
With 5.2 you can't inject the `EventBus`, but I've filled https://github.com/primefaces/primefaces/issues/316 so it can be implemented.

**Comment by cagataycivici** [comment]
Thank you @jfarcand

**Comment by jveverka** [comment]
Hi Jeanfrancois
Yest, that's the exception. OK, so the root cause of the problem is that there is race condition on deployment time and when EventBusFactory.getDefault(); is called from @Singleton @Startup annotated class (private field init part or @PostConstruct method), PushServlet is not initialized yet and NPE is thrown. I had to remove @Startup annotation and place EventBusFactory.getDefault(); into @PostConstruct method to make the demo work (still not good solution). Thanks for your support, I will have to find more reliable way of getting the reference to EventBus and also I am looking forward for #316 implementation :) Thanks !

**Comment by kmistry361** [comment]
just put this code below to a default constructor

`public ChatView() {eventBus = EventBusFactory.getDefault().eventBus(); }` 

It will work for any version
