### ISSUE TITLE
Treetable: null pointer exception in encodeMarkup if value is undefined

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#3081]
## 1) Environment
- PrimeFaces version: PF latest
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Not relevant
- Affected browsers: Not relevant

## 2) Expected behavior

Treetable renderer should not throw null pointer exception

## 3) Actual behavior

Treetable renderer will throw null pointer exception if value isn't set

## 4) Steps to reproduce

load the xhtml code to any primefaces project

## 5) Sample XHTML

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<f:view contentType="text/html">
	<h:head>
	</h:head>
	<h:body>

		<h:form id="mainForm">
			<p:treeTable></p:treeTable>
		</h:form>

	</h:body>
</f:view>

</html>
```

then you will see the following stacktrace:

```
HTTP ERROR 500
Problem accessing /primefaces-test/. Reason:

    Server Error
Caused by:
java.lang.NullPointerException
	at org.primefaces.component.treetable.TreeTableRenderer.encodeMarkup(TreeTableRenderer.java:270)
	at org.primefaces.component.treetable.TreeTableRenderer.encodeEnd(TreeTableRenderer.java:207)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:276)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:566)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
```

## 6) Analysis

This issue is most likely caused by no null check for the following line of code

https://github.com/primefaces/primefaces/blob/5a3fd43ae2fb0e6ed868d48f31694112bac5985c/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java#L263

The similar xhtml code for datatable does not throw null pointer, so we should expect treetable to work as datatable

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<f:view contentType="text/html">
	<h:head>
	</h:head>
	<h:body>

		<h:form id="mainForm">
			<p:dataTable></p:dataTable>
		</h:form>

	</h:body>
</f:view>

</html>
```

**Comment by tandraschko** [comment]
PR is welcome ;) If you don't provide a PR, i would likely close it as invalid.

**Comment by jxmai** [comment]
tree table is different from datatable from what I can tell. I would say the value is required and to throw new facesexception if no value.

**Comment by jxmai** [comment]
PR: #3086 


can be verfied by 

1. the sample above (null pointer becomes a cleaner FacesException)

2. http://localhost:8080/showcase/ui/data/treetable/basic.xhtml ... (No regression)
