### ISSUE TITLE
NullPointerException on sorting of nested DataTables

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#3372]
Given a table (outer table) with another nested table (inner table). Inner table resides inside a column of outer table. The visibility of the column containing inner table can be toggled by a checkbox. If you now make one inner table visible, sort it, hide it again, then a NullPointerException is thrown whenever another table is made visible.

Inner table has `sortMode="multiple"`.

To clarify the issue I’ve attached a minimal project to reproduce it.

Environment: Primefaces 6.1, Mojarra 2.2.14.

Exception:
```
SCHWERWIEGEND: java.lang.NullPointerException
    at org.primefaces.component.datatable.feature.SortFeature.multiSort(SortFeature.java:216)
    at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:131)
    at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:90)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
    at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:89)
    at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
    at org.primefaces.component.column.ColumnRenderer.encodeEnd(ColumnRenderer.java:54)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
    at org.primefaces.component.datatable.DataTableRenderer.encodeCell(DataTableRenderer.java:1229)
    at org.primefaces.component.datatable.DataTableRenderer.encodeRow(DataTableRenderer.java:1177)
    at org.primefaces.component.datatable.DataTableRenderer.encodeRows(DataTableRenderer.java:1081)
    at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:1017)
    at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:970)
    at org.primefaces.component.datatable.DataTableRenderer.encodeRegularTable(DataTableRenderer.java:363)
    at org.primefaces.component.datatable.DataTableRenderer.encodeMarkup(DataTableRenderer.java:325)
    at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:92)
    ...
```

Debugging shows the following:
The line (1638)

```
List<MultiSortState> multiSortStateList = (List<MultiSortState>) this.getStateHelper().get("multiSortState");
```

and the following code in `org.primefaces.component.datatable.DataTable` produces a SortMeta object with column = null, which results in the NPE later. 

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? No Version? 6.1
- Does it work on the newest sources in GitHub? Don’t know, I got “fatal: unable to access 'https://github.com/primefaces/primefaces.git/': Failed to connect to github.com port 443: Connection refused” on cloning the repository. Maybe a firewall issue at our side.

- Application server + version: Apache Tomcat/7.0.47

- Affected browsers: At least Chrome

## 2) Expected behavior
No NullPointerException, the nested table shall be sortable independently from the other tables.

## 3) Actual behavior
See description above.

## 4) Steps to reproduce
Start the example project and follow the steps described on the page. See also the readme.txt in the example project.

## 5) Example project

[PrimefacesNestedTables.zip](https://github.com/primefaces/primefaces/files/1763862/PrimefacesNestedTables.zip)

**Comment by cnsgithub** [comment]
In `DataTable`, line 1702 (PF 6.2-SNAPSHOT) no column is returned by `findColumn(multiSortState.getSortKey()) `because `getSortKey() ` contains a client ID of an inner table column which is not rendered anymore and therefore cannot be found in the component tree.

So, I would say this issue is invalid.

In your `TestPage.xhtml `if you change `rendered="#{outerRow.expanded}" `to `style="#{!outerRow.expanded ? 'display:none;' : ''}" `it will work as expected.

**Comment by cnsgithub** [comment]
Ok, I have to correct something: the issue disappeared only if you exactly follow the steps provided by @reiudo. If you randomly click at various check boxes and columns it appears again.

The reason is probably in the line mentioned afore:
![image](https://user-images.githubusercontent.com/13161711/36784700-aa73c48c-1c80-11e8-90a7-a757de07344c.png)

Columns of the inner table are searched for in the outer table and of course cannot be found. I would suggest to simply checking for null return values and then skip to the next. Does anyone see a problem with this suggestion?

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3377

**Comment by ghost** [comment]
Will every nested table now keep its own state like sorting, filtering or column order, even if it would be hidden and made visible again?

**Comment by cnsgithub** [comment]
No, I think only the last one will remember its state. The PR was just about fixing the NPE, not adding functionality that hadn't been there before.

**Comment by tandraschko** [comment]
yep, thanks.
