### ISSUE TITLE
NullPointer on <p:menubar> 5.2.3...

### ISSUE THREAD

**Issue by koekiebox** [primefaces/primefaces#346]
Elite User: Upgraded to 5.2.3.

I receive a Nullpointer on my menubar (On and off)

XHTML:

` <p:menubar model="#{topMenuBean.topMenuModel}">
            <f:facet name="options">
                
                <p:autoComplete id="itemTip" value="#{quickSearchBean.selectedSearchResult}"
                                style="margin-right:30px"
                                completeMethod="#{quickSearchBean.actionCompletePossibleSearchResults}"
                                var="searchItem"
                                itemLabel="#{searchItem.title}"
                                itemValue="#{searchItem}"
                                converter="#{quickSearchConverter}"
                                forceSelection="true"
                                placeholder="Type to Search..."
                                queryDelay="800">
                    <p:ajax event="itemSelect" listener="#{quickSearchBean.actionOnItemSelect}" update=":inventoryDataTable">/p:ajax
                    <f:facet name="itemtip">
                        <p:dataTable var="itemProp" value="#{searchItem.values}">
                            <p:column headerText="#{searchItem.title}">
                                <h:outputText value="#{itemProp}"/>
                            /p:column
                        /p:dataTable
                    /f:facet
                /p:autoComplete

```
            <!--Logout-->
            <p:commandButton id="logoutButton"
                             type="button"
                             onclick="logOutAndStopSetInterval();"
                             value="Log out"
                             icon="fa fa-sign-out"
                             styleClass="RedButton"
                             ajax="true"
                             title="Log out #{user.username}.">
            </p:commandButton>

            <p:tooltip for="logoutButton" showEffect="clip" hideEffect="explode" />
        </f:facet>
    </p:menubar>`
```

JAVA:
`
/**
     *
     */
    public void actionPopulateTopMenuModel() {
        this.topMenuModel = new DefaultMenuModel();

```
    //File
    DefaultSubMenu fileSubMenu = new DefaultSubMenu("File", "fa fa-file");

    //File - Search...
    DefaultMenuItem fileSearchItem = new DefaultMenuItem("Search", "fa fa-search");
    //File - Change Password...
    DefaultMenuItem fileChangePasswordItem = new DefaultMenuItem("Change Password", "fa fa-key");
    fileChangePasswordItem.setAjax(true);
    fileChangePasswordItem.setOncomplete("PF('changePassword').show();");

    //Help
    DefaultSubMenu helpSubMenu = new DefaultSubMenu("Help", "fa fa-question-circle");

    //Refresh
    DefaultMenuItem refreshSubMenu = new DefaultMenuItem("Refresh", "fa fa-refresh");
    refreshSubMenu.setOutcome(Outcome.MAIN_PAGE);

    //Messenger...
    try {
        this.chatBean.actionLoadOnlineUsers();
    }
    //
    catch (WebSessionExpiredException expiredException) {
        //Do nothing for now...
        return;
    }

    //Help - Documentation...
    DefaultMenuItem helpDocumentationItem = new DefaultMenuItem("Documentation", "fa fa-file-code-o");
    helpDocumentationItem.setHref("/../fluid-docs");
    helpDocumentationItem.setTarget("_blank");

    //DefaultMenuItem helpVideoItem = new DefaultMenuItem("Videos", "fa fa-file-movie-o");

    //Retrieve all the logged in user access permissions...
    this.actionGetLoggedInUserFormsAndFields();

    if (this.formDefinitionsUserCanCreate != null && !this.formDefinitionsUserCanCreate.isEmpty()) {

        //File - New
        DefaultSubMenu fileNewSubMenu = new DefaultSubMenu("New", "fa fa-files-o");

        //Add Each of the Document Types...
        for (FormDefinition formDefinition : this.formDefinitionsUserCanCreate) {

            DefaultMenuItem formDefMenuItem = new DefaultMenuItem(formDefinition.getTitle(), "fa fa-file-text-o");

            formDefMenuItem.setIgnoreAutoUpdate(true);
            formDefMenuItem.setAjax(true);

            formDefMenuItem.setUpdate(":bottom:inventoryDataTable");
            formDefMenuItem.setTarget("_blank");

            formDefMenuItem.setOutcome(Outcome.FORM_CONTAINER);

            //Params...
            formDefMenuItem.setParam(WebParam.FormDefinitionId, formDefinition.getId().toString());
            formDefMenuItem.setParam(WebParam.Title, "New '" + formDefinition.getTitle() + "'");
            formDefMenuItem.setParam(WebParam.CurrentDataViewType,
                    CurrentDataViewType.NewFormFromUserDash.toString());

            fileNewSubMenu.addElement(formDefMenuItem);
        }

        //ADD TO FILE...
        //New
        fileSubMenu.addElement(fileNewSubMenu);
    }

    //ADD TO FILE...
    //Search
    fileSubMenu.addElement(fileSearchItem);

    User loggedInUser = null;
    try{
        loggedInUser = this.getLoggedInUser();
    }
    //
    catch(WebSessionExpiredException webExpiredExcept)
    {
        return;
    }

    //Change Password
    if(loggedInUser.doesUserHaveAdminPermission(AdminPermission.change_own_password))
    {
        fileSubMenu.addElement(new DefaultSeparator());
        fileSubMenu.addElement(fileChangePasswordItem);
    }

    //Add to Help...
    helpSubMenu.addElement(helpDocumentationItem);

    this.topMenuModel.addElement(fileSubMenu);
    this.topMenuModel.addElement(helpSubMenu);
    this.topMenuModel.addElement(refreshSubMenu);
}`
```

10:28:24,077 SEVERE [javax.enterprise.resource.webcontainer.jsf.application](http-/0.0.0.0:443-9) Error Rendering View[/pages/main_page.xhtml]: java.lang.NullPointerException
    at org.primefaces.component.menubar.MenubarRenderer.encodeSubmenuIcon(MenubarRenderer.java:61) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeSubmenu(TieredMenuRenderer.java:165) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeElements(TieredMenuRenderer.java:131) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeMenu(TieredMenuRenderer.java:79) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.menubar.MenubarRenderer.encodeMarkup(MenubarRenderer.java:51) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:113) [primefaces-5.2.3.jar:5.2.3]
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:881) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1786) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.render.Renderer.encodeChildren(Renderer.java:168) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:851) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:84) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:71) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.layout.LayoutUnitRenderer.encodeEnd(LayoutUnitRenderer.java:49) [primefaces-5.2.3.jar:5.2.3]
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:881) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1786) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:439) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:124) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100) [primefaces-5.2.3.jar:5.2.3]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_65]

10:28:24,080 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/fluid].[Prime Faces Servlet]](http-/0.0.0.0:443-9) JBWEB000236: Servlet.service() for servlet Prime Faces Servlet threw exception: java.lang.NullPointerException
    at org.primefaces.component.menubar.MenubarRenderer.encodeSubmenuIcon(MenubarRenderer.java:61) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeSubmenu(TieredMenuRenderer.java:165) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeElements(TieredMenuRenderer.java:131) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeMenu(TieredMenuRenderer.java:79) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.menubar.MenubarRenderer.encodeMarkup(MenubarRenderer.java:51) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:113) [primefaces-5.2.3.jar:5.2.3]
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:881) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1786) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.render.Renderer.encodeChildren(Renderer.java:168) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:851) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:84) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:71) [primefaces-5.2.3.jar:5.2.3]
    at org.primefaces.component.layout.LayoutUnitRenderer.encodeEnd(LayoutUnitRenderer.java:49) [primefaces-5.2.3.jar:5.2.3]
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:881) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1786) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:439) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:124) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139) [jsf-impl-2.1.19-redhat-2.jar:2.1.19-redhat-2]
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594) [jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar:2.1.19.1.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100) [primefaces-5.2.3.jar:5.2.3]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_65]

**Comment by cagataycivici** [comment]
Try DynamicMenuModel instead of DefaultMenuModel. Also please use forum first for questions like these and please format your code next time. Thank you.
