### ISSUE TITLE
Captcha broken when running inside spring webflow's FlowExternalContext

### ISSUE THREAD

**Issue by vchoy** [primefaces/primefaces#351]
https://github.com/svn2github/primefaces/commit/c712ed566bb477d673ed819cc739c5ed0c78cb5a

```
Caused by: java.lang.ClassCastException: org.springframework.faces.webflow.FlowExternalContext cannot be cast to org.primefaces.context.PrimeExternalContext
    at org.primefaces.component.captcha.Captcha.createPostParameters(Captcha.java:188) ~[primefaces-5.2.jar:5.2]
    at org.primefaces.component.captcha.Captcha.validateValue(Captcha.java:147) ~[primefaces-5.2.jar:5.2]
    at javax.faces.component.UIInput.validate(UIInput.java:982) ~[jsf-api-2.2.10.jar:2.2]
    at javax.faces.component.UIInput.executeValidate(UIInput.java:1248) ~[jsf-api-2.2.10.jar:2.2]
    at javax.faces.component.UIInput.processValidators(UIInput.java:712) ~[jsf-api-2.2.10.jar:2.2]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1260) ~[jsf-api-2.2.10.jar:2.2]
    at javax.f
```

**Comment by tandraschko** [comment]
fixed it in trunk - please give it a try. Can't test it as i never user webflow.

**Comment by vchoy** [comment]
Confirming this works. Thank you.
