### ISSUE TITLE
NullPointerException in AutoCompleteRenderer

### ISSUE THREAD

**Issue by Razzhivin** [primefaces/primefaces#358]
Hello!

I create AutoComplete component programmatically use next Java API:

```
public class AutoCompleteHandler extends UIComponentHandler<AutoComplete> {
@Override
public AutoComplete handle(AutoComplete component, Map<String, String> attributes) {
    FacesContext ctx = FacesContext.getCurrentInstance();
    Application application = ctx.getApplication();

    component.setId(attributes.get(InspectionResultConstants.NAME));

    String elExpression = FacesUtils.wrapExpression("addressFinder.getAddressList");
    MethodExpression methodExpression = application.getExpressionFactory().createMethodExpression(ctx.getELContext(), elExpression, List.class, new Class<?>[]{String.class});
    component.setCompleteMethod(methodExpression);

    return component;
}
```

}

My bean which realize method for introducing list of String for AutoComplete Component: 

```
@Named
@ViewScoped
public class AddressFinder implements Serializable {
private String addressValue;
private ArrayList<String> selections = new ArrayList<>();
private String uIComponentName;

public String getAddressValue() {
    return addressValue;
}

public void setAddressValue(String addressValue) {
    this.addressValue = addressValue;
}

public void setUIComponentName(String name) {
    this.uIComponentName = name;
}

public List<String> getAddressList(String searchStr) throws SQLException {
    AddressFinderUtils.recalculateSelections(selections, searchStr);
    Client client = AddressFinderUtils.getClient();
    int phase = selections.size();
    String idexName = AddressFinderUtils.getESIndexNameBySearchPhase(phase, this.uIComponentName);
    if (StringUtils.isEmpty(idexName)) return null;
    String typeName = AddressFinderUtils.getESTypeNameBySearchPhase(phase, this.uIComponentName);
    String esQuery = AddressFinderUtils.getQueryBySearchPashe(phase, selections,  searchStr, this.uIComponentName);


    SearchResponse response = client.prepareSearch(idexName)
            .setTypes(typeName)
            .setExtraSource(esQuery)
            .setFetchSource(true).setFrom(0).setSize(10)
            .execute()
            .actionGet();

    String ESSourceFieldName = AddressFinderUtils.getESSorceFieldNameBySearchPhase(phase, this.uIComponentName);
    if (ESSourceFieldName == null) return null;

    List<String> results = new ArrayList<>();
    String resStr;
    for (SearchHit searchHit : response.getHits()) {
        resStr = searchHit.sourceAsMap().get(ESSourceFieldName).toString();
        results.add(resStr);
    }

    return results;
}

public void onItemSelect(SelectEvent event) {
    selections.add(event.getObject().toString());
}
```

}

When I imput some text into AutoComponent on some view into log I see next  stack trace:

```
17:41:45,822 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-111) java.lang.NullPointerException
at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeSuggestionsAsList(AutoCompleteRenderer.java:516)
at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeSuggestions(AutoCompleteRenderer.java:411)
at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeResults(AutoCompleteRenderer.java:122)
at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeEnd(AutoCompleteRenderer.java:104)
at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582)
at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
at org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:920)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
at javax.faces.component.UIForm.visitTree(UIForm.java:371)
```

In debug mode I look that my method return some List of String it is not null, but into method org.primefaces.component.autocomplete.AutoCompleteRenderer#encodeResults comes UIComponent with suggestions = null. But if  I set break point into method org.primefaces.component.autocomplete.AutoComplete#broadcast I see that invoket and suggestion sets from my method AddressFinder.getAddressList(). I noticed that a instance of  AutoComplete when correctly sets suggesions and instance of  AutoComplete which is supplied to the method encodeResults different.

Primefaces version is 5.2

**Comment by cagataycivici** [comment]
Please use forum for questions like these.
