### ISSUE TITLE
Title not displayed when commandButton/menuItem is disabled. With simple fix from issue#3565, title works for disabled commandButton, but exception for menuItem

### ISSUE THREAD

**Issue by wolf97084** [primefaces/primefaces#3656]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? No (Version 6.2)
- In Version 6.1 it worked.
- Application server: Tomcat 7.0.64
- Affected browsers: IE Edge, Chrome 66.0.3359.170, Firefox 52.7.3 (32-bit)

## 2) Expected behavior
Title of a component (commandButton or menuItem) should be displayed regardless if component is enabled or disabled.

## 3) Actual behavior
1. plain commandButton/menuItem: title not shown on disabled commandButton/menuItem
2. commandButton/menuItem with simple fix from https://github.com/primefaces/primefaces/issues/3565: title will be displayed for disabled command button but project threw classCastException for disabled menuItem

## 4) Steps to reproduce
1. plain commandButton/menuItem:
    A. commandButton: create commandbutton with title and have disabled set to true.
    B. menuItem: create menuItem with title and have disabled set to true.
2. commandButton/menuItem with simple fix from https://github.com/primefaces/primefaces/issues/3565
   A. commandButton: create commandbutton with title and have disabled set to true. Wrapped command button with
 ```
<h:panelGroup id="group" style="display: inline-block;">
<div style="width: fit-content;" title="myTitle"><YOUR_COMPONENT_HERE/></div></h:panelGroup>
<p:tooltip for="group" value="value" />
```
 B. menuItem: create menuItem with title, have disabled set to true and wrap it  with
`<h:panelGroup id="group" style="display: inline-block;"><div style="width: fit-content;" title="myTitle">YOUR_COMPONENT_HERE/></div></h:panelGroup><p:tooltip for="group" value="value" />`

## 5) Sample XHTML
1. Plain commandButton/menuItem:
    A. commandButton: 
```
<p:commandButton id="removeCmd" icon="fa fa-times" 
             actionListener="#{controller.remove()}" 
             update="@form"
             disabled="#{ontroller.commandDisabled()}"                                                          
             style="width: 20px; height:20px;margin-left: 5px;"
             title="#{controller.commandDisabled() ? 'Command disabled due to user privilege' : 'remove selected item'}"
             styleClass="removeCmd"/>
  => title not shown when commandbutton is disabled.
```
  B. menuItem:
```
<p:contextMenu for="tree_table" nodeType="firstLevel" selectionMode="single"
                           style="width:220px">
<p:menuitem value="Add Custom Item" 
			icon="fa fa-plus" 
			update="@form" 
			disabled="#{not empty controller.selectedItemsToAdd or not empty controller.selectedItemsToRemove}"  
			title="#{controller.addCustomItemDisabled ? 'Command disabled.' : 'Add custom item'}"
			onclick="triggerHiddenEvent_customItem(); return false;"/>
other p:menuitem....
</p:contextMenu>
			
...
<p:commandButton id="triggerHiddenEvent_customItem" styleClass="button" action="#{controller.addCustomItem}" style="display:none">
	<p:ajax event="dialogReturn" 
			listener="#{controller.onItemChosen}" 
			update="@form"/>
</p:commandButton>
  => title not shown when menuItem is disabled.

```
2. commandButton/menuItem with Simple fix from https://github.com/primefaces/primefaces/issues/3565
  A. commandButton with fix:
```
<h:panelGroup id="group" style="display: inline-block;">
<div style="width: fit-content;" title="myTitle">
<p:commandButton id="removeCmd" icon="fa fa-times" 
             actionListener="#{controller.remove()}" 
             update="@form"
             disabled="#{ontroller.isCommandDisabled()}"                                                          
             style="width: 20px; height:20px;margin-left: 5px;"
             title="#{controller.isCommandDisabled() ? 'Command disabled due to user privilege' : 'remove selected item'}"
             onstart="PF('bui').show(); PF('bar').show();" 
             oncomplete="PF('bui').hide(); PF('bar').hide();"
             styleClass="removeCmd"/>
</div>
</h:panelGroup>
<p:tooltip for="group" value="value" />
  => title will be displayed with simple fix
```
   B. menuItem with fix:
```
<p:contextMenu for="tree_table" nodeType="firstLevel" selectionMode="single"
                           style="width:220px">
<h:panelGroup id="group" style="display: inline-block;">
<div style="width: fit-content;" title="myTitle">
<p:menuitem value="Add Custom Item" 
			icon="fa fa-plus" 
			update="@form" 
			disabled="#{not empty controller.selectedItemsToAdd or not empty controller.selectedItemsToRemove}"  
			title="#{controller.addCustomItemDisabled ? 'Command disabled.' : 'Add custom item'}"
			onclick="triggerHiddenEvent_customItem(); return false;"/>
</div>
</h:panelGroup>
<p:tooltip for="group" value="value" />
other p:menuitem....
</p:contextMenu>
			
...
<p:commandButton id="triggerHiddenEvent_customItem" styleClass="button" action="#{controller.addCustomItem}" style="display:none">
	<p:ajax event="dialogReturn" 
			listener="#{controller.onItemChosen}" 
			update="@form"/>
</p:commandButton>
=> this one throws ClassCastException
SEVERE: Servlet.service() for servlet [Faces Servlet] in context with path [/cm] threw exception [javax.faces.component.html.HtmlPanelGroup cannot be cast to org.primefaces.model.menu.MenuElement] with root cause
java.lang.ClassCastException: javax.faces.component.html.HtmlPanelGroup cannot be cast to org.primefaces.model.menu.MenuElement at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeElements(TieredMenuRenderer.java:98)
at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeMenu(TieredMenuRenderer.java:79)
at org.primefaces.component.contextmenu.ContextMenuRenderer.encodeMarkup(ContextMenuRenderer.java:66)
at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:117)
 => this one throws ClassCastException
SEVERE: Servlet.service() for servlet [Faces Servlet] in context with path [/cm] threw exception [javax.faces.component.html.HtmlPanelGroup cannot be cast to org.primefaces.model.menu.MenuElement] with root cause
java.lang.ClassCastException: javax.faces.component.html.HtmlPanelGroup cannot be cast to org.primefaces.model.menu.MenuElement at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeElements(TieredMenuRenderer.java:98)
at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeMenu(TieredMenuRenderer.java:79)
at org.primefaces.component.contextmenu.ContextMenuRenderer.encodeMarkup(ContextMenuRenderer.java:66)
at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:117)

```

**Comment by kukel** [comment]
This behaviour comes from the new jquery-ui version. See https://stackoverflow.com/questions/50281355/primefaces-6-2-commandbutton-title-not-working-when-commandbutton-is-disabled. The new behaviour is in my opinion not bad and since you can override it, I would vote to 'close' this as won't fix

**Comment by wolf97084** [comment]
Agreed and thank you, @kukel
