### ISSUE TITLE
 SelectOneMenu: crashes on PrimafeFaces > 6.2 when editable="true"

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#3662]
## 1) Environment
- PrimeFaces version: 6.2.3
- Does it work on the newest released PrimeFaces version? NO
- Application server + version: Glassfish 4.1
- Affected browsers: Chrome, Opera

## 2) Expected behavior

The program don't display any error (AjaxExceptionHandler).

## 3) Actual behavior

In Primefaces 6.1.14, the program work correclty.
After migrating to 6.2 and now to 6.2.3, the program crashes when I display a page that contains a SelectOneMenu widget and a RemoteCommand.

Error Message

```
Message: com.goodyear.tlga.postLabelling.dto.PostLabellingOriginatorUser cannot be cast to java.lang.String 
Stack Trace: java.lang.ClassCastException: com.goodyear.tlga.postLabelling.dto.PostLabellingOriginatorUser cannot be cast to java.lang.String
at com.sun.faces.renderkit.html_basic.MenuRenderer.getConvertedValue(MenuRenderer.java:318)
at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.getConvertedValue(SelectOneMenuRenderer.java:80)
at javax.faces.component.UIInput.getConvertedValue(UIInput.java:1045)
at javax.faces.component.UIInput.validate(UIInput.java:975)
at javax.faces.component.UIInput.executeValidate(UIInput.java:1248)
at javax.faces.component.UIInput.processValidators(UIInput.java:712)
at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
at org.primefaces.component.panel.Panel.processValidators(Panel.java:313)
at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
at org.primefaces.component.panel.Panel.processValidators(Panel.java:313)
at javax.faces.component.UIForm.processValidators(UIForm.java:253)
at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1195)
at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:81)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
at com.goodyear.tlga.web.controller.Log4jFilter.doFilter(Log4jFilter.java:54)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
at java.lang.Thread.run(Thread.java:745)

```
## 4) Steps to reproduce

The program crashes when I first display the page. I can close the Dialog that display the error message and continues to work with the SelectOneMenu without problem. The AjaxException is only throw when I display the page for the first time AND when <p:remoteCommand> is present in XHTML page !

## 5) Sample XHTML

```
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
          xmlns:ui="http://java.sun.com/jsf/facelets"
          xmlns:h="http://java.sun.com/jsf/html"
          xmlns:p="http://primefaces.org/ui"
          xmlns:f="http://java.sun.com/jsf/core"
          xmlns:pe="http://primefaces.org/ui/extensions"
          >
        <h:body>
            <h:form id="formInputActionDialog">
            <p:panel>
                            <p:selectOneMenu
                                    autoWidth="false"
                                    id="cmbTplOriginator" 
                                    value="#{oController.txtOriginator.value}" 
                                    effect="fold" 
                                    editable="true"
                                    required="false"
                                    converter="#{oOriginatorConverter}"
                                    style="width:240px;"
                                    >
                                    <f:selectItems 
                                        value="#{oController.txtOriginator.getUserList()}"
                                        var="originator"
                                        itemLabel="#{originator.humanName}"
                                        itemValue="#{originator}"
                                        />
                                </p:selectOneMenu>

                </p:panel>

                <p:remoteCommand async="true"
                    autoRun="true" 
                    name="LazyLoadingOfPage"
                 />
                
            </h:form>
        </h:body>
    </html>

```
## 6) Sample bean

```
public List<OriginatorUser> getUserList() ...

package com.goodyear.tlga.web.converter;


//import service.goodyear.application.security.model.User;


import com.goodyear.common.exception.TlgaException;
import com.goodyear.tlga.postLabelling.dto.PostLabellingOriginatorUser;
import com.goodyear.tlga.postLabelling.service.PostLabellingService;

import javax.ejb.EJB;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;

@ManagedBean
@ApplicationScoped
public class OriginatorConverter implements Converter
    {

    @EJB
    private PostLabellingService postLabellingService;

    @Override
    public Object getAsObject(FacesContext facesContext, UIComponent uiComponent, String sValue) {

        OriginatorUser oOriginatorUser = null;
        try {
            if (!sValue.isEmpty())
                {
                if (sValue.endsWith(")"))
                    {
                    int iPos = sValue.indexOf("(") + 1;
                    int iEnd = sValue.length() - 1;
                    String sUserid = sValue.substring(iPos, iEnd);
                    iEnd = iPos - 2;
                    String sName = sValue.substring(0,iEnd).trim();
                    oOriginatorUser = new OriginatorUser(sUserid, sName);
                    }
                else
                    {
                    OriginatorUser = postLabellingService.findPostLabellingOriginatorByUserId(sValue);
                    }    
                }
            }
        catch (TlgaException e)
            {
            e.printStackTrace();
            }
        
        return oOriginatorUser;
    }

    @Override
    public String getAsString(FacesContext facesContext, UIComponent uiComponent, Object object)
        {
        OriginatorUser user;
        String sName = "?";
        
        try {
            user = (OriginatorUser) object;
            sName = user.getHumanName();
            }
        catch(Exception ex)
            {
            int i0 = 0;
            }   
        
        return sName;
        }
}

```

```
package com.goodyear.tlga.postLabelling.dto;

import java.io.Serializable;

public class OriginatorUser implements Serializable
    {
    private String sName;
    private String sUserId;

    public String getHumanName()
        {
        String sComposedName = "";
        
        if (sUserId != null)
            {
            sComposedName = getName() + " (" + getUserId() + ")";
            }
        
        return sComposedName;
    }

    public OriginatorUser(String userId, String name)
        {
        if (userId == null) return;
        
        this.sUserId = userId.toUpperCase();
        this.sName = name;
        }

    public OriginatorUser()
        {
        this.sUserId = null;
        this.sName = null;
        }

    public String getName() {
        return sName;
    }

    public String getUserId() {
        return sUserId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        
        OriginatorUser that = (PostLabellingOriginatorUser) o;

        if (that == null) return false;
        
        if (sUserId == null)
            {
            return (that.sUserId == null);
            }

        if (!sUserId.equals(that.sUserId)) return false;

        return true;
    }

    @Override
    public int hashCode()
        {
        if (sUserId == null) return 0;
        
        return sUserId.hashCode();
        }
}

```

**Comment by tandraschko** [comment]
We have a very required question in the issue template
"- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)"

So please test it, AFAIR it's already fixed.

**Comment by tandraschko** [comment]
Also your ticket would be invalid as the example isn't runnable and contains unrequired stuff like EJBs.

**Comment by schlebe** [comment]
ok, I will download last build from GitHub and if error already exists, I will modify my code so that you have a very simple code. I begin now :-)

**Comment by schlebe** [comment]
I have converted my code to PrimeFaces 6.3-SNAPSHOT. I have take some times because RequestContext must be replaced by PrimeFaces.current() !

I have also reduced my XHTML code to

```
<!DOCTYPE html>

<html 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pe="http://primefaces.org/ui/extensions"
    >
<h:head>
</h:head>

<h:body>
    <h:form>
        <p:panel id="inputPanels">
            <h:outputText  
                id="txtTplOriginator"
                styleClass="OutputField" 
                value="TPL-ORIGINATOR"  
                style="width:240px; padding:0px; margin:0px;"
                />

            <p:selectOneMenu
                autoWidth="false"
                id="cmbTplOriginator" 
                value="#{testViewController.getCurrentxUser()}" 
                effect="fold" 
                editable="true"
                required="false"
                converter="#{postLabellingOriginatorConverter}"
                style="width:240px;"
                >

                <f:selectItems 
                    value="#{testViewController.getUserList()}"
                    var="originator"
                    itemLabel="#{originator.humanName}"
                    itemValue="#{originator}"
                    />
            </p:selectOneMenu>
        </p:panel>

    <p:remoteCommand async="true"
        autoRun="true" 
        />

</h:form>
</h:body>
</html>

```
The Controller code is

```
import com.company.tlga.postLabelling.dto.OriginatorUser;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name="testViewController")
@ViewScoped
public class TestViewController
    extends AbstractViewController
    {
    public OriginatorUser getCurrentxUser()
        {
        return new OriginatorUser("ZA28140","SCHLEICH Bernard");
        }

    public List<OriginatorUser> getUserList()
        {
        List<OriginatorUser> list = new ArrayList<OriginatorUser>();
            
        list.add(new OriginatorUser("ZA28140","SCHLEICH Bernard"));
        list.add(new OriginatorUser("ZA28141","TOM Skywalker"));
            
        return list;
        }
    } // END-OF-CLASS

```
The code for OriginatorUser has already been transmitted in previous message.

The code for OriginatorConverter is

```
import com.goodyear.common.exception.TlgaException;
import com.goodyear.tlga.postLabelling.dto.PostLabellingOriginatorUser;
import com.goodyear.tlga.postLabelling.service.PostLabellingService;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;

@ManagedBean
@ApplicationScoped
public class OriginatorConverter implements Converter
    {
    @Override
    public Object getAsObject(FacesContext facesContext, UIComponent uiComponent, String sValue)
        {
        OriginatorUser oOriginatorUser = null;
        try {
            if (!sValue.isEmpty())
                {
                int iPos = sValue.indexOf("(") + 1;
                int iEnd = sValue.length() - 1;
                String sUserid = sValue.substring(iPos, iEnd);
                iEnd = iPos - 2;
                String sName = sValue.substring(0,iEnd).trim();
                oOriginatorUser = new OriginatorUser(sUserid, sName);
                }
            }
        return oOriginatorUser;
        }

    @Override
    public String getAsString(FacesContext facesContext, UIComponent uiComponent, Object object)
        {
        OriginatorUser user;
        String sName = "?";
        
        try {
            user = (OriginatorUser) object;
            sName = user.getHumanName();
            }
        catch(Exception ex)
            {
            int i0 = 0;
            }   
        
        return sName;
        }
}

```

I will add that the error disappears in 2 situations : 
1. if I suppress <p:remoteCommand>
2. if I suppress <h:head> empty bloc

**Comment by tandraschko** [comment]
Deeper analysis or PR is very welcome.

**Comment by schlebe** [comment]
Just for information ...  

I have replaced <p:remoteCommand> by JQuery (see code below) and the application work now correctly. The Primefaces error is already there but I use another technic to run a specific script when page is loaded.

```
<script type="text/javascript">
    jQuery(document).ready(function()
        {
        onLoadDialog();
        });
</script>

```

**Comment by tandraschko** [comment]
It works fine for me, after removing invalid code.

"value" of selectOneMenu must be a ValueExpression, not MethodExpression and it must be writeable, too (but the example works without setter).

> value="#{testViewController.currentxUser}"

If it doesn't work for you, mabye there is something wrong in your application.
I can't help then without a primefaces-test project to replicate.

**Comment by schlebe** [comment]
Hello Tandraschko, I have found what happens and I can explain it for a future correction :-)

First of all, because the message I receive is
Message: com.goodyear.tlga.postLabelling.dto.PostLabellingOriginatorUser cannot be cast to java.lang.String

I have added a ToString() method to PostLabellingOriginatorUser class like this
```
    @Override
    public String toString()
        {
        return "PostLabellingOriginatorUser" +
                "{userid='" + sUserId + "'" +
                ",name='" + sName + "'" + 
                '}';
        }
```
Then I have tested my HTML code using pure JSF tags like this
```
<h:selectOneMenu value="#{oPostLabActionController.panelTpl.txtOriginator.value}">
    <f:converter converterId="postLabellingOriginatorConverter"/>
    <f:selectItems 
        value="#{oPostLabActionController.panelTpl.txtOriginator.userList}"
        var="originator" 
        itemLabel="#{originator.humanName}"
        itemValue="#{originator}"
        />
</h:selectOneMenu>
```
In this case, Web page will be correctly displayed !

After that, I have reduced <p:selectOneMenu> Primefaces widget so it is similar to JSF previous element without changing <f:selectItems> part.
```
<p:selectOneMenu
    value="#{oPostLabActionController.panelTpl.txtOriginator.value}" 
    converter="postLabellingOriginatorConverter"
     >
```
The Web page is then displayed without error.

I have then add each attribute one by one until Web application crashes again.

This crash happens only **when editable attribute is equal to true** !

When crash is displayed, I have followed code
```
<p:selectOneMenu
    value="#{oPostLabActionController.panelTpl.txtOriginator.value}" 
    converter="postLabellingOriginatorConverter"
    required="false"
    autoWidth="false"
    editable="true"
    effect="fold" 
    >
```
Supplementary interesting remarks:

If I replace "postLabellingOriginatorConverter" by "#{postLabellingOriginatorConverter}" the program doesn't crash but doesn't display correct value. Indeed, it display in InputText widget ToString() value and not getHumanName() String value !

I don't understand the difference between defining a converter with and without #{}.

I think that this case is certainly replicatable using editable="true" attribute !

**Comment by melloware** [comment]
@Rapster I think the issue is editable="true" and is related to this: https://github.com/primefaces/primefaces/issues/3791

**Comment by schlebe** [comment]
The answer to my question about difference between "#{converter}" and "converter" is well documented by Balus on [https://stackoverflow.com/questions/27354994/difference-between-converter-entityconverter-and-converter-entityconverter/51436237](https://stackoverflow.com/questions/27354994/difference-between-converter-entityconverter-and-converter-entityconverter/51436237)

**Comment by cnsgithub** [comment]
@schlebe Invalid link -> HTTP 404

**Comment by schlebe** [comment]
Thanks, I have forgotten to fill (url) in my post. Now it is corrected.
