### ISSUE TITLE
cookie value 101Xfn_102Xfn.  Processing will continue, but the flash is unavailable for this request

### ISSUE THREAD

**Issue by surendraMaitrix** [primefaces/primefaces#3674]
Hello Everyone,
I am new to primefaces and having a problem in a project. that catalog is below. i cant understand what is happening . I need its solution as soon as possible.

SEVERE: Form too many keys
java.lang.IllegalStateException: Form too many keys
	at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:526)
	at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:641)
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:371)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:303)
	at org.eclipse.jetty.server.Request.extractParameters(Request.java:257)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:826)

2018-05-17 10:23:38.356:WARN:oejh.HttpParser:qtp2109957412-13: badMessage: **java.lang.IllegalStateException: too much data after closed for HttpChannelOverHttp@4cff0ff{r=1,c=false,a=IDLE,uri=}**
**May 17, 2018 10:23:38 AM com.sun.faces.context.flash.ELFlash$PreviousNextFlashInfoManager decode
SEVERE: JSF1094: Could not decode flash data from incoming cookie value 101Xfn_102Xfn.  Processing will continue, but the flash is unavailable for this request.**
May 17, 2018 10:23:38 AM com.sun.faces.application.view.FaceletViewHandlingStrategy handleRenderException
SEVERE: Error Rendering View[/xxxxxxxxx/xxxx.xhtml]
java.lang.NullPointerException
	at com.sun.faces.context.flash.ELFlash.setCookie(ELFlash.java:974)
	at com.sun.faces.context.flash.ELFlash.doLastPhaseActions(ELFlash.java:666)
	at com.sun.faces.context.flash.ELFlash.doPostPhaseActions(ELFlash.java:601)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:437)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)

**Comment by tandraschko** [comment]
Try the forum or stackoverflow. This is a issue tracker, for primefaces bugs.
This is wheter edirectly PrimeFaces related, nor you provided a example -> invalid.
