### ISSUE TITLE
p:fileUpload: Exception if one or more filenames has a '%' character

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#3916]
This is the exception: 
javax.servlet.ServletException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: ".j"

This is the stacktrace:

Caused by: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: ".j"
at java.net.URLDecoder.decode(URLDecoder.java:194)
at org.primefaces.model.NativeUploadedFile.decode(NativeUploadedFile.java:180)
at org.primefaces.model.NativeUploadedFile.getContentDispositionFileName(NativeUploadedFile.java:156)
at org.primefaces.model.NativeUploadedFile.resolveFilename(NativeUploadedFile.java:114)
at org.primefaces.model.NativeUploadedFile.(NativeUploadedFile.java:45)
at org.primefaces.component.fileupload.NativeFileUploadDecoder.decodeAdvanced(NativeFileUploadDecoder.java:67)
at org.primefaces.component.fileupload.NativeFileUploadDecoder.decode(NativeFileUploadDecoder.java:38)
at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:62)

- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

I found this discussion on stackoverflow that seem related to this behaviour:

https://stackoverflow.com/questions/34633956/any-concerns-about-executing-urldecoder-against-a-url-that-was-not-encoded

1) Environment
- PrimeFaces version: v.6.2.7

- Does it work on the newest released PrimeFaces version? Version?

- Application server + version:

jsf Mojarra 2.2.14
Tomcat 8.5
Java 8u181

- Affected browsers: All

2) Expected behavior

Upload the file or remove the '%' character from filename 

3) Actual behavior

Exception

4) Steps to reproduce

Go to:  https://www.primefaces.org/showcase/ui/file/upload/single.xhtml

Try to upload a jpg file with this filename:   test%.jpg

**Comment by melloware** [comment]
Here is the original ticket where we fixed a bunch of issues with filenaming:  https://github.com/primefaces/primefaces/issues/3034

I don't remember anyone calling out % as a valid file name character but I guess it could be.

**Comment by melloware** [comment]
Also linking #3269 as its related to filename cleansing.
