### ISSUE TITLE
DataTable: TableState ignores SortMode and leads to Exceptions when used together with MultiSort

### ISSUE THREAD

**Issue by PJahrmann** [primefaces/primefaces#4117]
## 1) Environment
- PrimeFaces version: 6.2.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 7
- Affected browsers: All

## 2) Expected behavior

Storing and Restoring TableState together with Multi-Sort-Meta is possible.

## 3) Actual behavior

When using TableState together with MultiSort Mode, it is not possible to render the DataTable correctly. Due to the absence of a "sortMode" variable in the class TableState, an exception is thrown when re-entering the page, if the Multi-Sort-Meta is set. (Because DataTable is in Single-Sort Mode and tries to use "resolveSortField" in loadLazyData(). As a cause of isMultiSort() returns "single" as long as sortMode is not explicitly set to "multiple")

**Exception:**
java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [TestBean.multiSort] on this ManagedType [Entity]
	at org.hibernate.jpa.internal.metamodel.AbstractManagedType.checkNotNull(AbstractManagedType.java:144)
	at org.hibernate.jpa.internal.metamodel.AbstractManagedType.getAttribute(AbstractManagedType.java:130)
	at org.hibernate.jpa.criteria.path.AbstractFromImpl.locateAttributeInternal(AbstractFromImpl.java:133)
	at org.hibernate.jpa.criteria.path.AbstractPathImpl.locateAttribute(AbstractPathImpl.java:221)
	at org.hibernate.jpa.criteria.path.AbstractPathImpl.get(AbstractPathImpl.java:194)
	...
	at org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:1164)
	at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:144)
	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:92)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	...

## 4) Solution

Add sortMode variable in TableState.java and set it within DataTable.restoreTableState().

**TableState.java:**

	private String sortMode;

	public String getSortMode() {
		return sortMode;
	}

	public void setSortMode(String sortMode) {
		this.sortMode = sortMode;
	}

**DataTable.java:**

	public void restoreTableState() {
        	...
        	this.setSortMode(ts.getSortMode());
       	...
	}

**Comment by Rapster** [comment]
Seems you have a solution, please provide a PR then :wink:

**Comment by tandraschko** [comment]
I would like to fix it but no sample -> invalid.
if you still have the problem, please create a new issue with a runnable sample
