### ISSUE TITLE
TextEditor: NPE at decode

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#4303]
## 1) Environment
- PrimeFaces version: 6.2.12
- Did work on PrimeFaces version 6.2.10 (skipped 6.2.11 because of fileUpload issue)
- Application server + version: JBoss EAP 6.4.21
- Affected browsers: all

## 2) Expected behavior
No NPE

## 3) Actual behavior
```
10:38:17,204 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (ajp-localhost.localdomain/127.0.0.1:8009-6) java.lang.NullPointerException
	at org.primefaces.component.texteditor.TextEditor.isAllowBlocks(TextEditor.java:149)
	at org.primefaces.component.texteditor.TextEditorRenderer.decode(TextEditorRenderer.java:53)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:789)
	at javax.faces.component.UIInput.decode(UIInput.java:761)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1183)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:666)
	at javax.faces.component.UIForm.processDecodes(UIForm.java:225)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1178)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1178)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:925)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
```

## 4) Steps to reproduce
Just try to submit a form containing a p:textEditor

## 5) Sample XHTML
```
<h:form>
<p:textEditor value="#{someController.message}" />
<p:commandButton value="Send" actionListener="#{someController.send}" update="@form"/>
</h:form>
```

**Comment by tandraschko** [comment]
ELITE only, probably the defaultValue is missing in the allow* attributes in the XML

**Comment by fcorneli** [comment]
Indeed, PrimeFaces version 6.2.12 has the following within TextEditor:
```
public boolean isAllowBlocks() {
    return (java.lang.Boolean) getStateHelper().eval(PropertyKeys.allowBlocks, null);
}
```
which make the autoboxing go NPE when you don't explicitly set these attributes. And this while the trunk has it correct:
```
public boolean isAllowBlocks() {
    return (Boolean) getStateHelper().eval(PropertyKeys.allowBlocks, true);
}
```
and this for all new Boolean attributes.

**Comment by mertsincan** [comment]
Fixed for 6.2.13.

**Comment by cbjerg** [comment]
When is the 6.2.13 out?

**Comment by schlebe** [comment]
How avoid this issue using last release 6.2.12 ? 
I have download last documentation to see if some ALLOW attributes exist but this is not documented ? Or what I search in <p:textEditor> is not correct.

Before downloading 6.2.12, I have following question:

If I have some pages with some <p:textEditor> can I use 6.2.12 using some workaround ? Which ?

**Comment by tandraschko** [comment]
There is no documentation for the elite releases but it's documented in the taglib. So you IDE should allow code-completion.

You can use it when you set all allow* to true or false (instead of null). Just the "default" mechanism is broken.

**Comment by phillipross** [comment]
thanks @tandraschko 

Specifically, the following attributes are the ones being referred to, and their default values are all "false"

```
allowFormatting
allowBlocks
allowStyles
allowLinks
allowImages
```

**Comment by cbjerg** [comment]
@schlebe 
I've just added them to the Element
<p:textEditor widgetVar="editor" value="#{settingsFacade.description}" placeholder="Add a description" allowBlocks="true" allowFormatting="true" allowLinks="true" allowStyles="true" allowImages="true">

**Comment by schlebe** [comment]
thanks both for your answer. Now, I can try to use last Primefaces release without loosing time to find what is wrong with <p:textEditor>  :-)
