### ISSUE TITLE
javax.enterprise.resource.webcontainer.jsf.context java.lang.NullPointerException with p:ajax listener call

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#4349]
Hello,
Recently I migrated a JEE project from Payara to Wildfly, and since some calls p: ajax cause this exception : 
 [javax.enterprise.resource.webcontainer.jsf.context] (default task-30) java.lang.NullPointerException: java.lang.NullPointerException

## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT 
- Application server   : wildfly-15.0.0.Final
- JSF implementation : Mojarra 2.3.5.SP2

## 2) Actual behavior
` [javax.enterprise.resource.webcontainer.jsf.context] (default task-30) java.lang.NullPointerException: java.lang.NullPointerException
	at com.sun.faces.cdi.CdiUtils.createConverter(CdiUtils.java:125)
	at com.sun.faces.application.ApplicationImpl.createConverter(ApplicationImpl.java:1458)
	at javax.faces.application.ApplicationWrapper.createConverter(ApplicationWrapper.java:425)
	at org.primefaces.util.ComponentUtils.getConverter(ComponentUtils.java:167)
	at org.primefaces.renderkit.InputRenderer.getConvertedValue(InputRenderer.java:34)
	at javax.faces.component.UIInput.getConvertedValue(UIInput.java:1122)
	at javax.faces.component.UIInput.validate(UIInput.java:1030)
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1334)
	at javax.faces.component.UIInput.processValidators(UIInput.java:757)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:632)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1736)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)`

## 5) Sample XHTML

```
 <p:outputLabel for="dataA" value=" value :" />
 <p:inputText id="dataA" value="#{mbean.valueA}"  >
            <p:ajax event="valueChange"  listener="#{mbean.listener('STR')}" />
 </p:inputText>
```

## 6) Sample bean

```
@Named(value = "mBean")
@ViewScoped
public class MBean implements Serializable{
 
    private String valueA;
      
    public MBean() {
    }

    @PostConstruct
    public void init()
    {
        valueA = "";
    }

    public void listener(String str)     
    {
        System.out.println(" Listener OK ");
        
    }

    public String getValueA() {
        return valueA;
    }


    public void setValueA(String str) {
        this.valueA = str;
    }
}

```

I found a temporary solution. it's to return an object when calling the listener:

    public Object listener(String str)     
    {
        System.out.println(" Listener OK ");
        return "" ;  
    }

is it a p:ajax related issue with the event "valueChange" or a bug in Mojarra ?

**I also noticed that primefaces components return the same exception when a primitive is used in value**

thank you in advance for your feedback for this problem.

**Comment by tandraschko** [comment]
Thats a mojarra issue: https://github.com/eclipse-ee4j/mojarra/issues/4500
