### ISSUE TITLE
[Documentation] 2.2 Dependencies

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4381]
![image](https://user-images.githubusercontent.com/15189434/50924026-5b9a7600-141c-11e9-800a-8eea1e9f57e4.png)

java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.CellStyle.setAlignment(Lorg/apache/poi/ss/usermodel/HorizontalAlignment;)V
	at org.primefaces.component.export.ExcelExporter.applyOptions(ExcelExporter.java:301)
	at org.primefaces.component.export.ExcelExporter.export(ExcelExporter.java:81)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:145)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:814)

6.2 pom.xml : found the issue the hard way :(

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.17</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.17</version>
            <scope>provided</scope>
        </dependency>

**Comment by ravihariharan** [comment]
[Documentation] - User guide 2.2 Dependencies - Apache poi #3576
