### ISSUE TITLE
DatePicker: PartialResponseError submitting multiple values

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#4471]
Here is a test case:  
[pf-4470.zip](https://github.com/primefaces/primefaces/files/2791715/pf-4470.zip)

Run the sample and then select a few dates from the multiple Calendar and press the "All" button.

You will get this stack trace:

```
Jan 24, 2019 7:41:10 AM com.sun.faces.application.view.FaceletViewHandlingStrategy handleRenderException
SEVERE: Error Rendering View[/test.xhtml]
javax.faces.FacesException: Value could be either String or java.util.Date
        at org.primefaces.util.CalendarUtils.getValueAsString(CalendarUtils.java:136)
        at org.primefaces.util.CalendarUtils.getValueAsString(CalendarUtils.java:55)
        at org.primefaces.component.calendar.BaseCalendarRenderer.encodeEnd(BaseCalendarRenderer.java:58)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
        at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:583)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at javax.faces.component.UIForm.visitTree(UIForm.java:381)
```

**Comment by mertsincan** [comment]
Does it work without immediate attribute on datepicker?

**Comment by melloware** [comment]
So with immediate=false the error goes away but the values are not accepted and and the multi-calendar dissapears and I get this in the JavaScript Console:
```
Uncaught TypeError: this.viewDate.getMonth is not a function
    at $.(anonymous function).(anonymous function).renderDateView (http://localhost:8080/primefaces-test/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:980:67)
    at $.(anonymous function).(anonymous function).renderDateView (http://localhost:8080/primefaces-test/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:144:25)
    at $.(anonymous function).(anonymous function).renderPanelElements (http://localhost:8080/primefaces-test/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:961:42)
    at $.(anonymous function).(anonymous function).renderPanelElements (http://localhost:8080/primefaces-test/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:144:25)
    at $.(anonymous function).(anonymous function).renderDatePickerPanel (http://localhost:8080/primefaces-test/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:953:48)
    at $.(anonymous function).(anonymous function).renderDatePickerPanel (http://localhost:8080/primefaces-test/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:144:25)
    at $.(anonymous function).(anonymous function)._render (http://localhost:8080/primefaces-test/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:893:18)
    at $.(anonymous function).(anonymous function)._render (http://localhost:8080/primefaces-test/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:144:25)
    at $.(anonymous function).(anonymous function)._create (http://localhost:8080/primefaces-test/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:113:18)
    at $.(anonymous function).(anonymous function)._create (http://localhost:8080/primefaces-test/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=7.0-SNAPSHOT:144:25)
```

![image](https://user-images.githubusercontent.com/4399574/51681716-7f7cc080-1fb3-11e9-9d02-6ff03e867095.png)

The other poster said he had to use this crazy hack to make it work:

![image](https://user-images.githubusercontent.com/4399574/51681750-93282700-1fb3-11e9-97b3-56d99dac9a83.png)

**Comment by GedMarc** [comment]
On value setting also found encodeEnd() didn't handle properly for no value selected with immediate=true, had to wrap.

```
@Override public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
		UICalendar uicalendar = (UICalendar)component;
		String markupValue = "";
		Object submittedValue = uicalendar.getSubmittedValue();

		if(submittedValue == null)
			submittedValue = "";

		ValueExpression ve = uicalendar.getValueExpression("value");
		if (ve != null) {
			Class type = ve.getType(context.getELContext());
			if(type == ArrayList.class) {
				submittedValue = ve.getValue(context.getELContext()).toString();
				markupValue = submittedValue.toString().substring(1, submittedValue.toString().length() - 1);
			}
		}
		else
		{
			try {
				markupValue = CalendarUtils.getValueAsString(context, uicalendar);
			}catch(Exception e)
			{
				Logger.getLogger("DatePickerRenderer").warning("No value bound to this calendar");
			}
		}
		String widgetValue = uicalendar.isTimeOnly() ? CalendarUtils.getTimeOnlyValueAsString(context, uicalendar) : markupValue;

		this.encodeMarkup(context, uicalendar, markupValue);
		this.encodeScript(context, uicalendar, widgetValue);
	}
```

**Comment by mertsincan** [comment]
@melloware, the second issue(JS error) is fixed. Could you please test it?

**Comment by melloware** [comment]
@mertsincan I have confirmed the JS error is no longer displaying if immediate="false" in this scenario.

**Comment by mertsincan** [comment]
Thanks a lot, @melloware ;) Original issue is fixed now. Could @melloware and @GedMarc please test it?

**Comment by melloware** [comment]
@mertsincan So far the fixes look good.  But @GedMarc has been heavily using this component so I will wait until he confirms as well.

**Comment by GedMarc** [comment]
Perhaps my repo is out of date?
Can you confirm the dependency for me please?
```
  <repositories>
        <repository>
            <id>prime-repo</id>
            <name>PrimeFaces Maven Repository</name>
            <url>http://repository.primefaces.org</url>
            <layout>default</layout>
        </repository>
    </repositories>

      <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>7.0.RC1</version>
        </dependency>
```

We have this widget in production ;) We were forced by business to push it in on the day of 6.2.14 release  ;)

**Comment by melloware** [comment]
@GedMarc I think you can do this...

```
<dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>
```
I am not quite sure how jitpack works.  If not if you git clone PF here you can do "mvn clean install" to build 7.0-SNAPSHOT locally.

It looks like JitPack will then force a build of the latest code if you use the above!  So cool.

**Comment by GedMarc** [comment]
Getting much closer!

```
Caused by: javax.el.PropertyNotWritableException: /test.xhtml @43,141 value="#{testView.multidate}": Property [multidate] not writable on type [org.primefaces.test.TestView]
        at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:136)
        at javax.faces.component.UIInput.updateModel(UIInput.java:834)
        ... 44 more
```

I double checked the getters/setters, looks ok to me, maybe just a sanity check on my stuff? I haven't done the best this week

[pfdatepicker.zip](https://github.com/primefaces/primefaces/files/2796248/pfdatepicker.zip)

**Comment by melloware** [comment]
@GedMarc I had to fix this in your code to be bean compliant like this...

```java
	/**
	 * Setter for property 'multi'.
	 *
	 * @param multi Value to set for property 'multi'.
	 */
	public void setMulti(List<Date> multi)
	{
		this.multi = multi;
	}
```

You were returning testView instead of a void method.

**Comment by GedMarc** [comment]
Ah yes I do the CRP builders, not the best week xD

**Comment by mertsincan** [comment]
@melloware, you are so fast 😄

**Comment by GedMarc** [comment]
Standard Inline & Normal & Immediate- Pass
Immediate Inline & Normal & Immediate - Pass
Locale Inline & Normal & Immediate - Pass

Restricted Dates inline & Normal  & Immediate - Fail
Time Zoned Dates Inline & Normal  & Immediate - Fail

----
Outside @form Not Updated - Pass
Inside @form Updated - Pass
-----

I see you guys don't do "broken components", but "bug in components" logging - Should this get logged as new for minDate not taking effect (popup doesn't work, calendar doesn't display)

In the test, all inputs after the millenium calendar pre populate don't function

[pfdatepicker.zip](https://github.com/primefaces/primefaces/files/2796360/pfdatepicker.zip)

![image](https://user-images.githubusercontent.com/5367513/51750203-fef4b780-20b9-11e9-92ab-fd4924787e5b.png)

**Comment by GedMarc** [comment]
Also looks like immediate=false without multiple doesn't function (date4 and after)
But this is really getting much better

**Comment by GedMarc** [comment]
crap wrong issue

**Comment by GedMarc** [comment]
no right issue xD

**Comment by melloware** [comment]
@GedMarc I would open a new issue one for each issue you have.  That way they get tracked as individual issues and not in one big bucket.  As small a reproducible test case for each just showing the issue.

**Comment by GedMarc** [comment]
Then for this bug, this is complete

Thanks guys! See you on the next issue thread!
