### ISSUE TITLE
InputMask: NullPointerException after update v6.2 to v7.0RC1

### ISSUE THREAD

**Issue by mfrenaij** [primefaces/primefaces#4484]
## 1) Environment
- PrimeFaces version: 7.0RC
- Works with version 6.2

## 2) Expected behavior
InputMask should accept values like 'FF', '00' - '99' (not '0A')

## 3) Actual behavior
NullPointerException at org.primefaces.component.inputmask.InputMaskRenderer.translateMaskInfotRegex(InputMaskRenderer.java:79)

## 4) Steps to reproduce
Enter a value e.g. '08' in the inputMask field and press 'Enter'

## 5) Sample XHTML:
    <p:inputMask value="#{myManagedBean.inputString}" maxlength="2" size="2" >
        <p:keyFilter regEx="/[0-9f]/i" />
        <f:ajax/>
    </p:inputMask>

## 6) Sample bean
    private String inputString;

    public void setInputString(String inputString) {
        this.inputString = inputString;
    }

    public String getInputString() {
        return inputString;
    }

Stack trace:
javax.faces.FacesException: java.lang.NullPointerException
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:86)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:650)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at org.primefaces.ultima.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:32)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3701)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.__run(WebAppServletContext.java:3667)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:40012)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2443)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2291)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2269)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1703)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1663)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:644)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:415)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:355)
Caused by: javax.faces.FacesException: java.lang.NullPointerException
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:273)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:55)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:927)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	... 33 more
Caused by: java.lang.NullPointerException
	at org.primefaces.component.inputmask.InputMaskRenderer.translateMaskIntoRegex(InputMaskRenderer.java:79)
	at org.primefaces.component.inputmask.InputMaskRenderer.decode(InputMaskRenderer.java:51)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:832)
	at javax.faces.component.UIInput.decode(UIInput.java:771)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1227)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:676)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:573)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:266)

**Comment by tandraschko** [comment]
@cnsgithub can you check that?

**Comment by cnsgithub** [comment]
@mfrenaij @tandraschko I wonder if you're using this correctly? Where did you specify your `p:inputMask mask` attribute? See https://primefaces.org/showcase/ui/input/inputMask.xhtml.

**Comment by tandraschko** [comment]
yep, probably invalid usage
however we should not throw a NPE then and just skip the validation.

**Comment by cnsgithub** [comment]
The `mask` attribute is required: https://github.com/primefaces/primefaces/blob/d166f951acb0d119fb6d5ef73e0b874dc0bb1194/src/main/resources/META-INF/primefaces-p.taglib.xml#L8923

Therefore we should throw an `InvalidArgumentException` in the first place.

**Comment by tandraschko** [comment]
thats ok for me, too

**Comment by melloware** [comment]
PR submitted. I used FacesException since that seems to be the pattern other components are using for invalid configuration errors.
