### ISSUE TITLE
Client Side Validation: UnsupportedOperationException registering a custom ClientValidationConstraint

### ISSUE THREAD

**Issue by frifle** [primefaces/primefaces#4495]
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1457)
	at org.primefaces.validate.bean.BeanValidationMetadataMapper.registerConstraintMapping(BeanValidationMetadataMapper.java:171)
	at de.frifle.test.playground.validation.ConstraintListener.<init>(ConstraintListener.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:329)

- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
In `BeanValidationMetadataMapper` the Map `CONSTRAINT_MAPPING` containing the client side validators is created using the new `MapBuilder`-Tool which returns an unmodifiable Map. When adding a custom `ClientSideValidator` using 'BeanValidationMetadataMapper.registerConstraintMapping' it tries to put a new entry to the unmodifiable Map which results in above exception.

## 1) Environment
- PrimeFaces version: 
7.0.RC1

- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
No

- Application server + version:
payara any version.

- Affected browsers:
any

## 2) Expected behavior
No exception thrown
...

## 3) Actual behavior
See above: Exception is thrown.
..

## 4) Steps to reproduce
Create a sample bean that registeres a new `ClientSidevalidator`, eg

	@Named
	@ApplicationScoped
	public class ConstraintRegistrator {
	
		@PostConstruct
		public void registerCSV() {
			BeanValidationMetadataMapper.registerConstraintMapping(FrifleCustomConstraint.class, new ClientValidationConstraint() {
				@Override
				public String getValidatorId() {
					// ...
				}
	
				@Override
				public Map<String, Object> getMetadata(ConstraintDescriptor constraintDescriptor) {
					// ...
				}
			});
		}
    }

**Comment by tandraschko** [comment]
for now all MapBuilder are modifiable again, we can decide what to do after the release.

**Comment by tandraschko** [comment]
@Rapster if you would like to introduce a unmodifiable option, please create a issue for 7.1

**Comment by Rapster** [comment]
I'll have a look after release. FYI, we should considerer using a service locator pattern for something like BeanValidationMetadataMapper, making everything static is not the right thing to do.
