### ISSUE TITLE
Add the modifier 'public' to all *Base.java classes

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4757]
Reported By PRO User;
> Error "can not access a member of class org.primefaces" migrating from 6.2 to 7.0. The error stack;
```
INFO: javax.faces.FacesException: java.lang.IllegalAccessException: Class javax.faces.component.UIComponentBase$AttributesMap can not access a member of class org.primefaces.component.picklist.PickListBase with modifiers "public"
javax.faces.FacesException: java.lang.IllegalAccessException: Class javax.faces.component.UIComponentBase$AttributesMap can not access a member of class org.primefaces.component.picklist.PickListBase with modifiers "public"
	at javax.faces.component.UIComponentBase$AttributesMap.get(UIComponentBase.java:2348)
	at org.primefaces.renderkit.InputRenderer.isDisabled(InputRenderer.java:49)
	at org.primefaces.renderkit.InputRenderer.shouldDecode(InputRenderer.java:57)
	at org.primefaces.component.picklist.PickListRenderer.decode(PickListRenderer.java:41)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:787)
	at javax.faces.component.UIInput.decode(UIInput.java:757)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1181)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:662)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1176)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1176)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1176)
	at javax.faces.component.UIForm.processDecodes(UIForm.java:225)
```

**Comment by ravihariharan** [comment]
@mertsincan i had a same issue when using JRE 1.7. When i used JRE 1.8 i did not see this issue.  Do we know the root cause of this issue and if it impact only JRE 1.7 ?
