### ISSUE TITLE
DataTable: NullPointerException with multiViewState=true

### ISSUE THREAD

**Issue by matinh** [primefaces/primefaces#4803]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No (7.0)
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: jetty-9.4.15.v20190215
- Affected browsers: probably all (tested with FireFox 66.0.3 and Chromium 73 on Linux)
- JSF versions: works with MyFaces (2.2 and 2.3) but not with Mojarra (2.2 and 2.3)

## 2) Expected behavior

AJAX update of `<p:datatable>` with `multiViewState="true"` should work.

## 3) Actual behavior

NullPointerException:

    Mai 15, 2019 11:25:40 AM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
    SCHWERWIEGEND: java.lang.NullPointerException
    	at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:125)
    	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:93)
    	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
    	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
    	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:583)
    	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
    	at org.primefaces.component.api.UIData.visitTree(UIData.java:873)
    	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
    	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:404)
    	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:323)

If I remove the `multiViewState="true"`, everything works as expected.

## 4) Steps to reproduce

1. clone https://github.com/matinh/primefaces-test.git using the branch `datatable` with `git clone 'https://github.com/matinh/primefaces-test.git' -b datatable`
1. change directory `cd primefaces-test`
1. run `mvn jetty:run-exploded`
1. goto http://localhost:8080/primefaces-test/
1. Enter a filter in column *Last Name*, e.g. 'h' -> the datatable now only shows a single row
1. uncheck the *Last Name* column below

The datatable doesn't get updated and you get the NPE shown above.

**Comment by melloware** [comment]
Looks like the NPE is on this line of code: https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java#L125

**Comment by matinh** [comment]
Yes it is (see StackTrace), and the reason is column == `null`.

Unfortunately adding a `null`-check fixes the exception, but the example still doesn't work as expected. Instead the corresponding header of the dynamic columns is not rendered, but the body is. Is my example a valid use-case at all? Is it allowed to change dynamic columns like I did in my example?

**Comment by matinh** [comment]
Hm, forget my last comment about partly rendered table. I just saw that I had the wrong scope for the backing-bean in my minimalistic example. I updated the example (please checkout for debugging) and now a simple `null`-check fixes the problem.

I'm still not 100% sure if I'm using the `<p:datatable>` in a way it is meant to be used. Is a column-toggler like I implemented it in the example supported? Or should I better ask this in the forum?

**Comment by melloware** [comment]
@matinh I would submit a PR with your NULL defensive check.  NPE's are never good!

**Comment by matinh** [comment]
Was just working on it. Here it is: PR: https://github.com/primefaces/primefaces/pull/4806
