### ISSUE TITLE
staticMessage: NullPointerException when severity is not set

### ISSUE THREAD

**Issue by kaiwinter** [primefaces/primefaces#4935]
[StaticMessageRenderer](https://github.com/primefaces/primefaces/blob/ba2900cfcd4276e31224f38667561973b36a7ba9/src/main/java/org/primefaces/component/staticmessage/StaticMessageRenderer.java#L41) doesnt't check if severity is set before using it.

## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? - No
- Does it work on the newest sources in GitHub? - Don't think so as there is still no valid setter
- Application server + version: JBoss 7.1
- Affected browsers: Chrome 75.0.3770.100 64 Bit

## 2) Expected behavior
When `severity` is missing in a `p:staticMessage` no exception should be thrown. Maybe a default severity should be used (like a `FacesMessage` uses `SEVERITY_INFO`). What do you think?

## 3) Actual behavior
An exception is thrown when `severity` is missing:
```
Caused by: java.lang.NullPointerException
	at org.primefaces.component.staticmessage.StaticMessageRenderer.encodeEnd(StaticMessageRenderer.java:41)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:458)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:135)
```

## 4) Steps to reproduce
This can stable be reproduced by execution the following XHTML.

## 5) Sample XHTML
```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:p="http://primefaces.org/ui">
   <body>
      <p:staticMessage detail="Hello there!"/>
   </body>
</html>
```

## 6) Sample bean
not necessary

**Comment by tandraschko** [comment]
+1 for Info as default

**Comment by melloware** [comment]
+1 for this I can submit a PR.

**Comment by tandraschko** [comment]
Please see my commit
