### ISSUE TITLE
MultiSelectListbox:NullPointerException

### ISSUE THREAD

**Issue by afd0174** [primefaces/primefaces#4965]
## 1) Environment
- PrimeFaces version: 7.0
- Wildfly 10.1
- Mojarra  2.2.13.SP1
- Affected browsers: All browsers (server-side issue)

## 2) Expected behavior

In PrimeFaces 6.2 (and lower), there is no client side validation performed on the submitted values in the multiSelectListBox.  In this case, SelectItemGroups that do not have child elements attached can be submitted without issue.

## 3) Actual behavior

In PrimeFaces 7.0, there is client side validation in place via the class/method SelectRenderer#doValidateSubmittedValues: 

(https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/renderkit/SelectRenderer.java)

The loop in this method (starting at line 329) assumes that all SelectItemGroup instances have non-null child lists.  When this condition fails, a NullPointerException is thrown.

## 4) Steps to reproduce

The attached test harness class method `MultiSelectListboxTestHarness.generateSomeSelectionsWithChildren()` be used to reproduce the error by replacing the code for the `init` method in the class 'MultiSelectView.java' in the hosted example for MultiSelectListbox (https://www.primefaces.org/showcase/ui/input/multiSelectListbox.xhtml) with the following:

`public void init() { 
  categories = MultiSelectListboxTestHarness.generateSomeSelectionsWithChildren();
}`

## 5) Sample XHTML

See https://www.primefaces.org/showcase/ui/input/multiSelectListbox.xhtml

## 6) Sample bean

See https://www.primefaces.org/showcase/ui/input/multiSelectListbox.xhtml

## 7) Attached code 

```java
import java.util.ArrayList;
import java.util.List;
import javax.faces.model.SelectItem;
import javax.faces.model.SelectItemGroup;

public class MultiSelectListboxTestHarness {
    
   // Creates data that passes PrimeFaces 7.0 validation
    public static List<SelectItem> generateAllSelectionsWithChildren() {
        `List<SelectItem> categories = new ArrayList<>();`
        SelectItemGroup group1 = new SelectItemGroup("Group 1");
        SelectItemGroup group2 = new SelectItemGroup("Group 2");
        SelectItemGroup group3 = new SelectItemGroup("Group 3");
        SelectItemGroup group4 = new SelectItemGroup("Group 4");
         
        SelectItemGroup group11 = new SelectItemGroup("Group 1.1");
        SelectItemGroup group12 = new SelectItemGroup("Group 1.2");
         
        SelectItemGroup group21 = new SelectItemGroup("Group 2.1");
         
        SelectItem option31 = new SelectItem("Option 3.1", "Option 3.1");
        SelectItem option32 = new SelectItem("Option 3.2", "Option 3.2");
        SelectItem option33 = new SelectItem("Option 3.3", "Option 3.3");
        SelectItem option34 = new SelectItem("Option 3.4", "Option 3.4");
         
        SelectItem option41 = new SelectItem("Option 4.1", "Option 4.1");
         
        SelectItem option111 = new SelectItem("Option 1.1.1");
        SelectItem option112 = new SelectItem("Option 1.1.2");
        group11.setSelectItems(new SelectItem[]{option111, option112});
         
        SelectItem option121 = new SelectItem("Option 1.2.1", "Option 1.2.1");
        SelectItem option122 = new SelectItem("Option 1.2.2", "Option 1.2.2");
        SelectItem option123 = new SelectItem("Option 1.2.3", "Option 1.2.3");
        group12.setSelectItems(new SelectItem[]{option121, option122, option123});
         
        SelectItem option211 = new SelectItem("Option 2.1.1", "Option 2.1.1");
        group21.setSelectItems(new SelectItem[]{option211});
         
        group1.setSelectItems(new SelectItem[]{group11, group12});
        group2.setSelectItems(new SelectItem[]{group21});
        group3.setSelectItems(new SelectItem[]{option31, option32, option33, option34});
        group4.setSelectItems(new SelectItem[]{option41});
         
        categories.add(group1);
        categories.add(group2);
        categories.add(group3);
        categories.add(group4);
        
        return categories;
    }

   // Creates data that fails PrimeFaces 7.0 validation
    public static List<SelectItem> generateSomeSelectionsWithChildren() {
        `List<SelectItem> categories = new ArrayList<>();`
        SelectItemGroup group1 = new SelectItemGroup("Group 1");
        SelectItemGroup group2 = new SelectItemGroup("Group 2");
        SelectItemGroup group3 = new SelectItemGroup("Group 3");
        SelectItemGroup group4 = new SelectItemGroup("Group 4");
         
        SelectItemGroup group11 = new SelectItemGroup("Group 1.1");
        SelectItemGroup group12 = new SelectItemGroup("Group 1.2");
         
        SelectItemGroup group21 = new SelectItemGroup("Group 2.1");
         
        SelectItem option31 = new SelectItem("Option 3.1", "Option 3.1");
        SelectItem option32 = new SelectItem("Option 3.2", "Option 3.2");
        SelectItem option33 = new SelectItem("Option 3.3", "Option 3.3");
        SelectItem option34 = new SelectItem("Option 3.4", "Option 3.4");
         
        SelectItem option41 = new SelectItem("Option 4.1", "Option 4.1");
         
        SelectItem option111 = new SelectItem("Option 1.1.1");
        SelectItem option112 = new SelectItem("Option 1.1.2");
        group11.setSelectItems(new SelectItem[]{option111, option112});
         
        SelectItem option121 = new SelectItem("Option 1.2.1", "Option 1.2.1");
        SelectItem option122 = new SelectItem("Option 1.2.2", "Option 1.2.2");
        SelectItem option123 = new SelectItem("Option 1.2.3", "Option 1.2.3");
        group12.setSelectItems(new SelectItem[]{option121, option122, option123});
         
        // Group 2.1 has no children
        // SelectItem option211 = new SelectItem("Option 2.1.1", "Option 2.1.1");
        // group21.setSelectItems(new SelectItem[]{option211});
         
        group1.setSelectItems(new SelectItem[]{group11, group12});
        group2.setSelectItems(new SelectItem[]{group21});
        group3.setSelectItems(new SelectItem[]{option31, option32, option33, option34});
        group4.setSelectItems(new SelectItem[]{option41});
         
        categories.add(group1);
        categories.add(group2);
        categories.add(group3);
        categories.add(group4);
        
        return categories;
    }
}
```

**Comment by tandraschko** [comment]
Please also post a xhtml.

**Comment by afd0174** [comment]
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
 
    <h:head>
        	<title>Test</title>
    </h:head>
    <h:body>
	<h:form>
    		<p:multiSelectListbox value="#{multiSelectView.selection}" effect="slide" header="Categories" showHeaders="true">
        			<f:selectItems value="#{multiSelectView.categories}" />
    		</p:multiSelectListbox>
    		<p:commandButton value="Save" icon="pi pi-check" update="out" style="display:block;margin:10px 0" /> 
    		<h:outputText id="out" value="Value: #{multiSelectView.selection}" style="display:block" />
	</h:form>
    </h:body>
</html>

**Comment by melloware** [comment]
Verified NPE. Working on a fix.

```
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
        at java.util.Arrays.asList(Arrays.java:3800)
        at org.primefaces.renderkit.SelectRenderer.doValidateSubmittedValues(SelectRenderer.java:337)
        at org.primefaces.renderkit.SelectRenderer.doValidateSubmittedValues(SelectRenderer.java:334)
        at org.primefaces.renderkit.SelectRenderer.validateSubmittedValues(SelectRenderer.java:310)
        at org.primefaces.renderkit.SelectOneRenderer.decode(SelectOneRenderer.java:44)
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:858)
```

**Comment by melloware** [comment]
OK PR submitted and tested and it is fixed
