### ISSUE TITLE
NullPointerException 	at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeSuggestionsAsList(AutoCompleteRenderer.java:492)

### ISSUE THREAD

**Issue by githubde** [primefaces/primefaces#512]
NPE at AutoCompleteRenderer.java:492 when using autoComplete comp inside a JSF composite component. This issue is more prevalent when the .xhtml page is secured using AuthenticationFilter.

Using:
primefaces 5.2
javax.faces-2.2.11.jar
Glassfish 4.1
JDK 1.8.0_45

2015-07-11T17:50:28.313-0400|Severe: java.lang.NullPointerException
    at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeSuggestionsAsList(AutoCompleteRenderer.java:492)
    at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeSuggestions(AutoCompleteRenderer.java:393)
    at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeResults(AutoCompleteRenderer.java:123)
    at org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeEnd(AutoCompleteRenderer.java:105)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
    at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582)
    at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:174)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
    at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
    at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322)
    at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:60)
    at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:219)
    at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1004)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:430)
    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:655)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
    at test.AuthFilter.doFilter(AuthFilter.java:45)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
    at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
    at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
    at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
    at java.lang.Thread.run(Thread.java:745)

**Comment by djmj** [comment]
You are sure this is related to autoComplete? I had this error also and the problem was that Glassfish with mojarra swallows other exceptions or throws exceptions that are not really the problem.

Dont know anymore how i resolved it, but we use a lot of autocomplete in composites.

**Comment by cagataycivici** [comment]
The error doesn't seem autoComplete related, we've tried in an composite with no issues. Also line 492 does not seem indicate the method you have issue with;

https://github.com/primefaces/primefaces/blob/5_2/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java

**Comment by cagataycivici** [comment]
If you can identify the root result that confirms issue is on our side, we'll reopen but right now issue is not clear so closing for now.

**Comment by githubde** [comment]
@cagataycivici, In my isolated TestCase project, I have autoComplete working OK on form.xhtml and NOT ok on signup.xhtml.  (I can't attach .zip) The additional code in form.xhtml that makes it work is...

<commonComps:formComp submitButtonText="Submit Now"
        submitButtonAction="#{myBean.doSubmit}" />

## signup.xhtml

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:commonComps="http://xmlns.jcp.org/jsf/composite/commonComps"
    xmlns:userComps="http://xmlns.jcp.org/jsf/composite/userComps">

<h:head>
    <title><h:outputText value="#{msg.welcomeTitle}" /></title>
/h:head

<h:body>

```
<p:autoComplete id="cc" value="#{cc.attrs.countryValue}"
    completeMethod="#{countryACMBean.complete}" var="c"
    itemLabel="#{c.nameEn}" itemValue="#{c}"
    converter="#{countryACConverter}" maxlength="50" size="40"
    required="true" requiredMessage="country is required"
    placeholder="test place holder for country2" />
```

/h:body

</html>

## form.xhtml

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:o="http://omnifaces.org/ui"
    xmlns:of="http://omnifaces.org/functions"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:commonComps="http://xmlns.jcp.org/jsf/composite/commonComps">

<f:loadBundle basename="resources.application" var="msg" />

<h:head>
    <title><h:outputText value="#{msg.welcomeTitle}" /></title>
/h:head

<h:body>

```
<commonComps:formComp submitButtonText="Submit Now"
    submitButtonAction="#{myBean.doSubmit}" />

<p:autoComplete id="cc" value="#{cc.attrs.countryValue}"
    completeMethod="#{countryACMBean.complete}" var="c"
    itemLabel="#{c.nameEn}" itemValue="#{c}" multiple="true"
    converter="#{countryACConverter}" maxlength="50" size="40"
    required="true" requiredMessage="country is required"
    placeholder="test place holder for country FORM3" />
```

/h:body
</html>

In my full project, I have autoComplete working ok inside composite comp on one page and not on another using the same composite comp. But here, no NPE or other error is observed. Sorry the code is not formatting properly.

**Comment by githubde** [comment]
Resolved. The autoComplete list not rendering was due to jquery conflict with jquery included in primefaces jar. Resolved by using primefacs jquery.
