### ISSUE TITLE
Datatable context menu and XML comments

### ISSUE THREAD

**Issue by Lemongrass3110** [primefaces/primefaces#516]
I added a comment after the last menuitem in the context menu of our datatable and suddenly I got an exception.

I am running on primefaces 5.2 from the maven central repository.

Here is the code for the context menu:

```
<p:contextMenu for="items">
    <p:menuitem value="Show" icon="ui-icon-search" actionListener="#{controller.showItem()}" ajax="false"/>
    <p:menuitem value="Change" icon="ui-icon-document" actionListener="#{controller.changeItem()}" ajax="false"/>
    <!-- Print: ui-icon-print -->
</p:contextMenu>
```

Here is the exception that is caused:

```
javax.faces.FacesException: java.lang.ClassCastException: org.apache.myfaces.view.facelets.compiler.UIInstructions incompatible with org.primefaces.model.menu.MenuElement
    at org.apache.myfaces.shared_impl.context.ExceptionHandlerImpl.wrap(ExceptionHandlerImpl.java:241)
    at org.apache.myfaces.shared_impl.context.ExceptionHandlerImpl.handle(ExceptionHandlerImpl.java:156)
    at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:258)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:191)
Caused by: java.lang.ClassCastException: org.apache.myfaces.view.facelets.compiler.UIInstructions incompatible with org.primefaces.model.menu.MenuElement
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeElements(TieredMenuRenderer.java:98)
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeMenu(TieredMenuRenderer.java:79)
    at org.primefaces.component.contextmenu.ContextMenuRenderer.encodeMarkup(ContextMenuRenderer.java:67)
    at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:113)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:535)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:626)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:622)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:622)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:622)
    at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1320)
    at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:263)
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:59)
    at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:59)
    at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:85)
    at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:239)
    ... 29 more
```

**Comment by tandraschko** [comment]
Set:
<context-param>
<param-name>javax.faces.FACELETS_SKIP_COMMENTS</param-name>
<param-value>true</param-value>
</context-param>
