### ISSUE TITLE
FileUpload: Using the new API of PF 7.1-SNAPSHOT, simple single fileUploader throws  ELException: Cannot convert

### ISSUE THREAD

**Issue by Selaron** [primefaces/primefaces#5160]
When trying out the improved new File Upload API introduced in #4305 and following the [documentation ](https://primefaces.github.io/primefaces/7_1/#/components/fileupload?id=simple-file-upload) and [migration guide](https://github.com/primefaces/primefaces/wiki/Migration-Guide#70-to-71) it is suggested I'd use the new `SingeUploadedFile` interface.
The [documentation ](https://primefaces.github.io/primefaces/7_1/#/components/fileupload?id=simple-file-upload) btw. seemes to have a typo here by importing the wrong class `import org.primefaces.model.file.UploadedFile;` for the `FileBean.file` field.

## 1) Environment
- PrimeFaces version: **7.1-SNAPSHOT**
- Does it work on the newest released PrimeFaces version? **Yes, 7.0**
- Does it work on the newest sources in GitHub? **No**
- Application server + version: **Apache Tomcat 9.0.21**
- Affected browsers: **any**

## 2) Expected behavior

I should receive a `SingleUploadedFile` instance in my bean setter `setFile(...)`;

## 3) Actual behavior

An Exception is thrown:

```
Servlet.service() for servlet [Faces Servlet] in context with path [/jsf-owb] threw exception [javax.el.ELException: /testIt.xhtml @13,76 value="#{fileBean.uploadedFile}": Cannot convert [org.primefaces.model.file.UploadedFileWrapper@35853fff] of type [class org.primefaces.model.file.UploadedFileWrapper] to [interface org.primefaces.model.file.SingleUploadedFile]] with root cause
javax.el.ELException: Cannot convert [org.primefaces.model.file.UploadedFileWrapper@35853fff] of type [class org.primefaces.model.file.UploadedFileWrapper] to [interface org.primefaces.model.file.SingleUploadedFile]
	at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:576)
	at org.apache.el.parser.AstValue.setValue(AstValue.java:203)
	at org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:263)
	at org.apache.webbeans.el22.WrappedValueExpression.setValue(WrappedValueExpression.java:93)
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:137)
	at javax.faces.component.UIInput.updateModel(UIInput.java:883)
	at javax.faces.component.UIInput.processUpdates(UIInput.java:797)
	at javax.faces.component.UIForm.processUpdates(UIForm.java:301)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1329)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1329)
	at javax.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:1390)
	at com.sun.faces.lifecycle.UpdateModelValuesPhase.execute(UpdateModelValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:670)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:188)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

## 4) Steps to reproduce

Try upload a single file.

## 5) Sample XHTML

```
<h:form enctype="multipart/form-data">
    <p:fileUpload value="#{fileBean.file}" mode="simple" />
    <p:commandButton value="Submit" ajax="false" action="#{fileBean.doSomething}"/>
</h:form>
```

## 6) Sample bean

```
import org.primefaces.model.file.SingleUploadedFile;
public class FileBean {
    private SingleUploadedFile file;
    //getter-setter

   public void doSomething(){}
}
```

##################################

Of course instead of `SingleUploadedFile` I can use `UploadedFile` or `UploadedFileWrapper` for my `file` field, but this would make me "lose" flawless access to file data and meta data implemented by `SingleUploadedFile` from within an Action method:

```
public interface SingleUploadedFile extends UploadedFile {
    String getFileName();
    InputStream getInputStream() throws IOException;
    byte[] getContent();
    String getContentType();
}
```

I can still access these information on an `UploadedFile` or `UploadedFileWrapper` using the newly introduced consumer pattern as described for [Multiple Uploads](https://primefaces.github.io/primefaces/7_1/#/components/fileupload?id=multiple-uploads) in `simple` mode - but this is not too obvious from documentation for `single` mode:
```
	public void doSomething() {
		FileUploadUtils.consume(uploadedFile, this::consumeFile);
	}

	public void consumeFile(SingleUploadedFile file) {
		String type = file.getContentType();
		byte[] content = file.getContent();
		String name = file.getFileName();
                // go on consuming .. mh tasty!
	}
```

Another work around is simply using the `fileUploadListener` approach that hands me the `SingleUploadedFile`.

**Comment by tandraschko** [comment]
I think we need a seperate wrapper for multi and single

Also we should rename NativeUploadedFile to NativeSingleUploadedFile
And
DefaultSingleUploadedFile to CommonsSingleUploadedFile

**Comment by Rapster** [comment]
I think I made a mistake in the showcase, I should have leave it as `UploadedFile` and then use `FileUploadUtils.consume` method or cast it directly into a `SingleUploadedFile`. I think I mentionned that before, but maybe `UploadedFile` should have a more restricted visibility, `protected`? It'll be less confusing for users and this interface is really meant for internal use of PF.

I don't think we need any more wrappers, but I'll do the refactoring yes

**Comment by tandraschko** [comment]
For me UploadedFile feels like internal, or even should be removed. Not sure here, just feels a bit weird.


So the User should directly use the single or multi model for the valuebinding. Which means that we would also need 2 seperate wrappers.
Otherwise it will always fail when casting/assigning it to the Bean

**Comment by tandraschko** [comment]
I would even go further and do:

- remove the old UploadedFile
- rename SingleUploadedFile to UploadedFile
- renamed MultiUploadedFile to UploadedFiles

**Comment by tandraschko** [comment]
will do a big refactoring now
feels like everything is bit messed up and to cumberstone

**Comment by tandraschko** [comment]
e.g. take http://localhost:8080/showcase/ui/file/upload/single.xhtml
and add 2 files -> upload
it seems that only 1 file received

**Comment by tandraschko** [comment]
Im really quite unhapy with the current status.
everything is weird.

We have 2 modes:

- Basic
   this means we dont use our JS widget and native html technologies are used.
   currently restricted to "single" file upload as "multiple=true" is not applied here.
   This means always 1 file and 1 request.

- Advanced
  this means that our JS is used.
  multiple just says that you can select multiple files at once, which will be added to the list.
  every file is uploaded via a own request.

This means, we can actually never have multiple files uploaded in 1 request. This also means that MultipleUploadedFile doesn't make any sense for me.

**Comment by Rapster** [comment]
I'm on vacation right now, so can't help much but maybe reading #4038 should help you correct your last statement

**Comment by tandraschko** [comment]
oh damn, just one file is displayed but 2 selected....

**Comment by Rapster** [comment]
That is another issue, I opened an issue actually for that and ping Mert but no answers. After some time, I realized it was fixed by web browser itself :/ 

See https://github.com/primefaces/primefaces/issues/4306

**Comment by tandraschko** [comment]
fixed now

the only difference to the old API is, that multiple=true in mode=simple now used the UploadedFiles model to receive all files in the single request
