### ISSUE TITLE
DataExporter: NPE when using format xlsxstream without specifying options

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#5495]
## 1) Environment
- PrimeFaces version: 8.0RC2
- Does it work on the newest released PrimeFaces version? Yes, 7.11
- Does it work on the newest sources in GitHub? No
- Application server + version: Does not matter
- Affected browsers: Does not matter

## 2) Expected behavior

Export should be possible

## 3) Actual behavior

Exporting yields the following exception:

Caused by: java.lang.NullPointerException: null
	at org.primefaces.component.datatable.export.DataTableExcelXStreamExporter.createSheet(DataTableExcelXStreamExporter.java:62)
	at org.primefaces.component.datatable.export.DataTableExcelExporter.doExport(DataTableExcelExporter.java:79)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.visit(DataTableExporter.java:350)
	at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:127)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:910)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.lambda$invoke$0(DataTableExporter.java:369)
	at org.primefaces.util.ComponentUtils.invokeOnClosestIteratorParent(ComponentUtils.java:623)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.invoke(DataTableExporter.java:367)
	at org.primefaces.component.datatable.export.DataTableExporter.export(DataTableExporter.java:313)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:135)

## 4) Steps to reproduce

Export in format xlsxstream without specifying options.

## 5) Sample XHTML

Will send if deemed necessary.

## 6) Sample bean

Will send if deemed necessary.

Cause is a missing null check in `DataTableExcelXStreamExporter.createSheet()`:

```
    @Override
    protected Sheet createSheet(Workbook wb, String sheetName, ExcelOptions options) {
        SXSSFWorkbook workbook = (SXSSFWorkbook) wb;
        SXSSFSheet sheet =  workbook.createSheet(sheetName);
        if (options.isAutoSizeColumn()) {
            sheet.trackAllColumnsForAutoSizing();
        }
        else {
            sheet.untrackAllColumnsForAutoSizing();
        }
        return sheet;
    }

```

I think the correct fix is using the following code here:

`        if (options == null || options.isAutoSizeColumn()) {
`

I hope this information is sufficient,

**Comment by melloware** [comment]
Already fixed. See: https://github.com/primefaces/primefaces/issues/5469

**Comment by stolp** [comment]
My bad, sorry.

**Comment by melloware** [comment]
No problem!
