### ISSUE TITLE
TabView: with DataModel

### ISSUE THREAD

**Issue by PlassJ** [primefaces/primefaces#5517]
## 1) Environment
- PrimeFaces version: 7.11

## 2) Expected behavior
Should be possible to assign an id ("#{car.id}") to the tab.

## 3) Actual behavior
Id will be always be empty and an Exception occurs.

```
Stacktrace:
FATAL [default task-9] resource.webcontainer.jsf.context.log(): Empty id attribute is not allowed
java.lang.IllegalArgumentException: Empty id attribute is not allowed
	at javax.faces.api@2.3.9.SP01//javax.faces.component.UIComponentBase.validateId(UIComponentBase.java:3261)
	at javax.faces.api@2.3.9.SP01//javax.faces.component.UIComponentBase.setId(UIComponentBase.java:271)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.assignUniqueId(ComponentTagHandlerDelegateImpl.java:414)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:156)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:111)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:179)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:111)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:179)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:111)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:55)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.ui.DefineHandler.applyDefinition(DefineHandler.java:65)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:166)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.impl.DefaultFaceletContext$TemplateManager.apply(DefaultFaceletContext.java:372)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.impl.DefaultFaceletContext.includeDefinition(DefaultFaceletContext.java:342)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.ui.InsertHandler.apply(InsertHandler.java:70)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:55)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:179)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:111)
	at javax.faces.api@2.3.9.SP01//javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:55)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:52)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:46)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:271)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:330)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:309)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:162)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:133)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:52)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:46)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:120)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:358)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:78)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.api@2.3.9.SP01//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.api@2.3.9.SP01//javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
```

## 4) Steps to reproduce
https://www.primefaces.org/showcase/ui/panel/tabView.xhtml

## 5) Sample XHTML (Example created from Showcase)
```xml
<h:form id="form">
  <p:tabView value="#{tabbedView.cars}" var="car">
        <p:tab id="#{car.id}" title="Car - #{car.id}">
            .....
        </p:tab>
    </p:tabView>
```

## 6) Sample bean
See Showcase TabbedView class 
..

Thank you

**Comment by melloware** [comment]
@PlassJ Can you post the stacktrace that you get?  Does this happen on form submit?

**Comment by melloware** [comment]
I must not be understanding the issue because I was able to assign an ID to the tabview.
```xml
<p:tabView value="#{tabbedView.cars}" var="car" id="tvDataModel">
```

And I can see that ID in the HTML and in the JS console.

**Comment by PlassJ** [comment]
@melloware Thank you for your fast reply.

If have updated my initial issue report.
It is all about giving the tab an id depending on the var of the tabView

**Comment by melloware** [comment]
@PlassJ thanks for the updated issue!  See the answer from BalusC on why this is not possible what you are trying to do and he offers 3 solutions.

https://stackoverflow.com/questions/6884801/using-id-causes-java-lang-illegalargumentexception-empty-id-attribute

**Comment by PlassJ** [comment]
@melloware Thank you again
