### ISSUE TITLE
Spinner: exception inside datatable summary row

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#5668]
## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version? 8.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version:
- Affected browsers:

## 2) Expected behavior
click on button should not fire exception 
version 7.0 is ok

## 3) Actual behavior

an exception ocurred

java.lang.NullPointerException: java.lang.NullPointerException
	at deployment.siapenweb.war//org.primefaces.component.spinner.SpinnerRenderer.decode(SpinnerRenderer.java:59)
	at javax.faces.api:mojarra-2.2.16@2.2//javax.faces.component.UIComponentBase.decode(UIComponentBase.java:832)
	
## 4) Steps to reproduce

click on 'send' button

sample project: https://github.com/erickdeoliveiraleal/primefaces-test

**Comment by Michael-3007** [comment]
I have a similar problem with PrimeFaces 8.0:

`
java.lang.NullPointerException
	at org.primefaces.component.spinner.SpinnerRenderer.decode(SpinnerRenderer.java:59)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:479)
	at javax.faces.component.UIInput.decode(UIInput.java:371)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1408)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:207)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at org.primefaces.component.panel.Panel.processDecodes(Panel.java:136)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at org.primefaces.component.dashboard.Dashboard.processDecodes(Dashboard.java:137)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at org.primefaces.component.fieldset.Fieldset.processDecodes(Fieldset.java:102)
	at javax.faces.component.UIForm.processDecodes(UIForm.java:154)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at org.primefaces.component.layout.Layout.processDecodes(Layout.java:113)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1402)
	at javax.faces.component.UIViewRoot._processDecodesDefault(UIViewRoot.java:1772)
	at javax.faces.component.UIViewRoot.access$500(UIViewRoot.java:81)
	at javax.faces.component.UIViewRoot$ApplyRequestValuesPhaseProcessor.process(UIViewRoot.java:1863)
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1738)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:942)`

Is it possible to merge your fix to version 8.0?

**Comment by melloware** [comment]
Its up to @mertsincan to get this merged into Elite 8.0.1.  But I can assure you they will not re-release 8.0 so you might want to sign up for an Elite account so you can get 8.0.1 when it comes out.

**Comment by Michael-3007** [comment]
Thank you! I already have an Elite account so I can get 8.0.1 when it comes out.
