### ISSUE TITLE
DataTable rowsPerPageTemplate-ShowAll+ filtering throws NumberFormatException

### ISSUE THREAD

**Issue by tomlux** [primefaces/primefaces#5704]
## 1) Environment
- PrimeFaces version: Primesfaces 8.0
- Application server + version: Wildfly 16
- Affected browsers: all

## 2) Expected behavior

When I select "ShowAll" in DataTable's rows per page drop-down list, all the rows should be filtered.

## 3) Actual behavior

When the "ShowAll" option is selected, an NumberFormatException is thrown during filtering

     java.lang.NumberFormatException: For input string: "*"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:638)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at deployment.test.war//org.primefaces.component.datatable.feature.FilterFeature.encode(FilterFeature.java:106)
        at deployment.test.war//org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:88)
        at javax.faces.api@2.3.9.SP01//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)

## 4) Steps to reproduce

Set the "records per page" to "all" and make some filtering

## 5) Sample XHTML

        <h:form>
            <p:dataTable value="#{dataTableController.rows}" var="row" paginator="true"
                         rowsPerPageTemplate="5,10,{ShowAll|'All'}" rows="5">
                <p:column filterBy="#{row}" filterMatchMode="contains">
                    <h:outputText value="#{row}"/>
                </p:column>
            </p:dataTable>
        </h:form>

## 6) Sample bean

    @Named
    @ApplicationScoped
    public class DataTableController implements Serializable {
        private static final int ROW_COUNT = 15;
        private static final List<String> ROWS = new ArrayList<>(ROW_COUNT);

        static {
            for (int i = 0; i < ROW_COUNT; i++) {
                ROWS.add("Row " + i);
            }
        }

        public List<String> getRows() {
            return ROWS;
        }
    }

**Comment by melloware** [comment]
I can't reproduce your issue: 
[pf-5704.zip](https://github.com/primefaces/primefaces/files/4345118/pf-5704.zip)


You can execute the sample with `mvn jetty:run` command and hit http://localhost:8080/primefaces-test to run the page.

**Comment by tomlux** [comment]
I'm also getting an exception running your zip with "mvn hetty:run".

Here my steps o reproduce:

1. opening http://localhost:8080/primefaces-test/
2. setting column filtering to "2" while leaving the rpp to 5, rows 2+12 are display
3. setting the rpp now to ALL
 -> NumberFormatException
4. setting column filtering to "1"
 -> NumberFormatException


SEVERE: Error Rendering View[/test.xhtml]
    java.lang.NumberFormatException: For input string: "*"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:569)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.primefaces.component.datatable.feature.FilterFeature.encode(FilterFeature.java:106)
        at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:88)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:913)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at javax.faces.component.UIForm.visitTree(UIForm.java:371)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1004)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)

**Comment by melloware** [comment]
Yep now I get the issue.  Thanks for the more explicit instructions.

**Comment by tomlux** [comment]
Just did this fix in your code.

[https___github_com_primefaces_primefaces_issues_5704_DataTable_rowsPerPageTemplate-ShowAll.zip](https://github.com/primefaces/primefaces/files/4347576/https___github_com_primefaces_primefaces_issues_5704_DataTable_rowsPerPageTemplate-ShowAll.zip)

**Comment by tomlux** [comment]
I also saw that after changing to "all", the filter didn't correctly displayed the results.

To fix this, I needed to added an a JS-filter call on the table after the "page"-event

  <p:ajax event="page" oncomplete="PF('tblTest').filter(); return false;"/>

**Comment by melloware** [comment]
These all seem like really buggy behavior with the "ALL" feature.  I didn't even know about this feature seems like it is some undocumented feature in the code.

**Comment by tomlux** [comment]
I just saw that Primefaces8.0.1 is released without this fix.

Should I write a PullRequest to get it in the next release?

**Comment by melloware** [comment]
If you have a proper fix definitely please submit a PR.

**Comment by JHookDev** [comment]
@mertsincan Will this fix be included in an upcoming 8.0.x elite release?

**Comment by irene-hase** [comment]
@mertsincan
 I get the same exception with TreeTable. I use Primeface version 8.0.9. 
 Is there a fix for that?
 
 `11:36:51,370 ERROR [io.undertow.request] (default task-10) UT005023: Exception handling request to...xyz.jsf: java.lang.NumberFormatException: For input string: "*"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.primefaces.component.treetable.TreeTable.updatePaginationData(TreeTable.java:606)
	at org.primefaces.component.treetable.TreeTableRenderer.encodeEnd(TreeTableRenderer.java:194)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)`
