### ISSUE TITLE
Tree: Tree loads the tree model from bean again for each TreeNode

### ISSUE THREAD

**Issue by yennor** [primefaces/primefaces#5755]
## 1) Environment
- PrimeFaces version: 8

## 2) Expected behavior
Tree component should load the tree model from bean only once for each update (render) of the tree component.

## 3) Actual behavior
It seems to load it as many times as there are treenodes in the treemodel.
This can lead to significant higher load times, especially if in some calculations are made in the getter (e.g. Because the data shown in the tree component depend on an other component)

## 4) Steps to reproduce
see
https://github.com/yennor/primefaces-test/tree/tree-value

**Comment by tandraschko** [comment]
please give a bit better description; What is loaded as many times? Which method exactly?

**Comment by yennor** [comment]
sorry, I'm tired. anyway:
`<tree value="{#view.treeRoot}"`

In getTreeRoot() you get the root node with all the other nodes attached.
For every node attached getTreeRoot() gets called again.
In the git repository referenced you can see it nicely, even with counter.

**Comment by melloware** [comment]
@yennor yes this is how JSF works.

Which is why if you look at this page on performance: https://primefaces.github.io/primefaces/8_0/#/core/performance

> Try to avoid logic in getters because they can be called multiple times - especially for the rendered attribute!

You should create your treeRoot model once and then in the getter just return the instance of it don't perform any logic or do it like this...

```java
public TreeNode getTreeRoot() {
    if (treeRoot == null) {
        treeRoot = initiializeTreeRoot();
   }
   return treeRoot;
}
```

it should not be impacting your performance at all if there is no logic in the getter.  You can call a getter 1000 times in a loop if it only returns and instance and Java will do that in milliseconds.

**Comment by yennor** [comment]
ok. But it still doesn't make any sense.
I've just tried it out with the datatable. Even when the datatable has got 50 rows. It doesn't call the getter for the row list 50 times. Only two times.
When the tree component got 50 nodes, it calls the getter for the root node 50 times...
Which just doesn't make any sense. It already got all of the nodes with the first call, it doesn't need to call for each subnode again.

Yes, I can change the logic and create the nodes in the setter of the data the tree component depends on or implement an extra listener. But you won't change my opinion in that that was implemented in a sane way ;-).

**Comment by melloware** [comment]
Well whether it’s implemented incorrectly or not is neither here nor there. You violated one of Joshua Bloch’s cardinal rules of never put logic in setters or getters. Use them as accessors only.  

Your design choice of logic in the getter is what exposed this performance issue. 

Even your example did it correctly by putting the logic in the @Postconstruct method.

**Comment by tandraschko** [comment]
we can check if we can improve it (reducing the Bean calls is good for performance) but as melloware said, it's actually by design that getters are called multiple times.

**Comment by melloware** [comment]
@yennor @tandraschko I took a stack trace...
```
java.lang.Exception: Stack trace
        at java.lang.Thread.dumpStack(Thread.java:1336)
        at org.primefaces.test.TestView.getRootTreeNode(TestView.java:45)
        at org.primefaces.test.TestView$$OwbNormalScopeProxy0.getRootTreeNode(org/primefaces/test/TestView.java)
        at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:94)
        at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
        at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
        at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
        at org.primefaces.component.api.UITree.getValue(UITree.java:153)
        at org.primefaces.component.api.UITree.setRowKey(UITree.java:102)
        at org.primefaces.component.tree.TreeRenderer.encodeTreeNode(TreeRenderer.java:687)
        at org.primefaces.component.tree.TreeRenderer.encodeTreeNodeChildren(TreeRenderer.java:799)
        at org.primefaces.component.tree.TreeRenderer.encodeVerticalTree(TreeRenderer.java:403)
        at org.primefaces.component.tree.TreeRenderer.encodeMarkup(TreeRenderer.java:342)
        at org.primefaces.component.tree.TreeRenderer.encodeEnd(TreeRenderer.java:254)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
```

This stack is printed for each row so the culprit is `org.primefaces.component.tree.TreeRenderer.encodeTreeNode(TreeRenderer.java:687)`

https://github.com/primefaces/primefaces/blob/e4c99061ac949138e6c3de68fb9eed151dbd769d/src/main/java/org/primefaces/component/tree/TreeRenderer.java#L687

Calling `setRowKey` calls UITree setRowKey which has this line in it.
https://github.com/primefaces/primefaces/blob/e4c99061ac949138e6c3de68fb9eed151dbd769d/src/main/java/org/primefaces/component/api/UITree.java#L102-L103

So in setRowKey it has to look up its parent tree.  Not sure if this can be fixed or not considering its using the state of the context to look up the tree.

**Comment by tandraschko** [comment]
51 -> 2 calls
i think thats an good improvemet
this means 49 less calls to the ELResolver, which asks CDI for the bean, which creates new objects + map lookup

**Comment by melloware** [comment]
Nice work @tandraschko !
