### ISSUE TITLE
Media: can't specify a StreamedContent through a method call

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#5902]
Sorry for the brief report, but it's really straight forward.

The same problem described at: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/795
for `pe:documentViewer` exists for `p:media`: I can't specify its `value` attribute to be a `StreamedContent` instance returned by a method call:

    <p:media value="#{myBean.getMyStreamedDocument(myBean.selectedProduct)}" player="pdf" />

causes an exception:

```
[...]
Caused by: javax.el.PropertyNotFoundException: /myFacelet.xhtml @696,133 value="#{bean.getStreamedForm(bean.selectedProduct)}": Property 'getMyStreamedDocument' not found on type com.example.MyBean
	at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:100)
	at org.primefaces.el.ValueExpressionAnalyzer.intercept(ValueExpressionAnalyzer.java:101)
	at org.primefaces.el.ValueExpressionAnalyzer.toValueReference(ValueExpressionAnalyzer.java:114)
	at org.primefaces.el.ValueExpressionAnalyzer.getExpression(ValueExpressionAnalyzer.java:62)
	at org.primefaces.util.DynamicContentSrcBuilder.build(DynamicContentSrcBuilder.java:68)
	at org.primefaces.extensions.component.documentviewer.DocumentViewerRenderer.getDocumentSource(DocumentViewerRenderer.java:144)
	at org.primefaces.extensions.component.documentviewer.DocumentViewerRenderer.generateSrc(DocumentViewerRenderer.java:72)
	... 92 more
Caused by: javax.el.PropertyNotFoundException: Property 'getStreamedCnsRequestForm' not found on type com.example.MyBean
	at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:268)
	at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:221)
	at javax.el.BeanELResolver.property(BeanELResolver.java:355)
	at javax.el.BeanELResolver.getType(BeanELResolver.java:82)
	at com.sun.faces.el.DemuxCompositeELResolver._getType(DemuxCompositeELResolver.java:215)
	at com.sun.faces.el.DemuxCompositeELResolver.getType(DemuxCompositeELResolver.java:242)
	at org.primefaces.el.InterceptingResolver.getType(InterceptingResolver.java:59)
	at org.apache.el.parser.AstValue.getType(AstValue.java:60)
	at org.apache.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:168)
	at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:98)
```

**Comment by melloware** [comment]
I think the problem lies here: `org.primefaces.util.DynamicContentSrcBuilder.build` and that is the same call uses by Primefaces Extensions DocumentViewer.

Specifically on this call.
```java
ValueExpression expression = ValueExpressionAnalyzer.getExpression(
                        context.getELContext(), component.getValueExpression("value"));
```

**Comment by melloware** [comment]
@tandraschko I am going to need your expertise here as I looked at ValueExpressionAnalyzer and don't really know what its doing.  Looks like you have been in this file the most.

**Comment by tandraschko** [comment]
The current code is and was only built to use ValueExpressions.
Also your code will never work for the same reason as 5903, as the VE will be evaluated in the resource request where no facelets params are available anymore.

So we can only support method-calls without params, which is the same as getter call, which is already supported (ValueExpression vs MethodExpression).

If you need to pass a info, you can pass infos to the resource request via f:param on the graphicImage / media.

**Comment by tandraschko** [comment]
@mauromol @melloware i reworked our docu regarding this topic... It took me over 1 hour but i think its worth as its one of the core concepts.
https://primefaces.github.io/primefaces/11_0_0/#/core/dynamiccontent?id=dynamic-content-rendering-via-data-uri-streamfalse-currently-only-supported-by-pgraphicimage

Would be great if you can review + fix spellings and that stuff

**Comment by melloware** [comment]
Done! Nice work.

**Comment by mauromol** [comment]
My suggested fixes in bold:

> ### What happens when the browser requests the URL:
>
>- our ResourceHandler gets the UID from the URL
>- receive**s** the ValueExpression from the session
>- call**s** the ValueExpression via EL API
>- ImageView and therefore DefaultStreamedContent ~~is~~ **are** instantiated the second time
>- the stream from the StreamedContent is ~~now~~ **then** copied to the HTTP response

> ### @ViewScoped support
>
>As the resource is streamed in a second request, which is not bound to any viewstate, @ViewScoped beans are not supported. A common pattern is to pass the information, which is probably stored in your @ViewScoped bean, via request parameters as you can see in the next chapter.
>**Also, parameters declared with `<ui:param>` in the declaring facelet won't be available in the second request.**

[...]

> ### What happens when rendering the p:graphicImage:
>
>- ImageView and therefore DefaultStreamedContent ~~is~~ **are** instantiated
>- the StreamedContent is received via the ValueExpression (#{imageView.image})
>- the stream from the StreamedContent is ~~now~~ **then** converted ~~and~~ into a base64 string and rendered as src attribute

Most importantly: I would insert a reference to this section in all the paragraphs dedicated to the components that use dynamic content rendering: `graphicImage`, `media`, which other?

**Comment by melloware** [comment]
I think the reference was added to all the components see GraphicImage for example here: https://primefaces.github.io/primefaces/11_0_0/#/components/graphicimage?id=getting-started-with-graphicimage
