### ISSUE TITLE
Java 8 Dependency Error on 7.0.14

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#6024]
@mertsincan PrimeFaces-7.0.14 has introduced Java 8 dependency.

The previous version of code primefaces-7.0.9 works fine. Source compare with 7.013 is also good.

Issue only with  PrimeFaces-7.0.14

`java.lang.NoClassDefFoundError: java/time/format/DateTimeParseException
	at org.primefaces.component.clock.ClockRenderer.getValueWithTimeZone(ClockRenderer.java:99)
	at org.primefaces.component.clock.ClockRenderer.encodeScript(ClockRenderer.java:83)
	at org.primefaces.component.clock.ClockRenderer.encodeEnd(ClockRenderer.java:50)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)` 

![image](https://user-images.githubusercontent.com/15189434/84455424-53ef8a00-ac2b-11ea-9903-fc9657fa85ce.png)

**Comment by tandraschko** [comment]
pinged PrimeTek about it. As the community can't fix it, i will close it for now.
