### ISSUE TITLE
ImageCropper v9 - File upload null pointer exception

### ISSUE THREAD

**Issue by GedMarc** [primefaces/primefaces#6077]
Uploaded file fails to read if locally referenced - 

ImageCropperRenderer - Null pointer exception 
```
ExternalContext externalContext = context.getExternalContext();
                        // GitHub #3268 OWASP Path Traversal
                        imagePath = FileUploadUtils.checkPathTraversal(imagePath);

                        String webRoot = externalContext.getRealPath(Constants.EMPTY_STRING);
                        String fileSeparator = Constants.EMPTY_STRING;
                        if (!(webRoot.endsWith("\\") || webRoot.endsWith("/")) &&
                                    !(imagePath.startsWith("\\") || imagePath.startsWith("/"))) {
                            fileSeparator = "/";
                        }
```

I think Line 223+ should read - this returns correctly
```
String webRoot = externalContext.getRealPath(imagePath);
String fileSeparator = System.getProperty("file.separator");
```

**Comment by GedMarc** [comment]
```
ERROR org.primefaces.application.exceptionhandler.PrimeExceptionHandler - null
java.lang.NullPointerException: null
	at org.primefaces.component.imagecropper.ImageCropperRenderer.getConvertedValue(ImageCropperRenderer.java:225) ~[primefaces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIInput.getConvertedValue(UIInput.java:1105) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIInput.validate(UIInput.java:1006) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1317) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIInput.processValidators(UIInput.java:733) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIForm.processValidators(UIForm.java:229) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1310) ~[javax.faces-0.0.0_0-SNAPSHOT.jar:?]
```

Showcase current version on clicking upload on image cropper

**Comment by melloware** [comment]
What OS were you testing under.  I test under Windows but we added a lot of these fixes because Unix users were having issues:
https://github.com/primefaces/primefaces/issues/5861

**Comment by melloware** [comment]
Have you found anymore out in your investigation?  I don't know if this component can blindly write to a disk location for security purposes so we may end up closing this ticket?

**Comment by GedMarc** [comment]
I think close it - I need to do quite a bit more checking, and we don't want a lingering item waiting forever xD
The read-only aspect of JImage/JMod's are going to be something I need to check on for sure
