### ISSUE TITLE
Wizard: NPE guards

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6081]
**Describe the defect**
Forum Post: https://forum.primefaces.org/viewtopic.php?f=3&t=62466

**Reproducer**
[pf-wizard.zip](https://github.com/primefaces/primefaces/files/4832886/pf-wizard.zip)

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Run the tester.
2. Click on 'Next' button a couple of times.
3. See error:

```
Caused by: java.lang.NullPointerException
at org.primefaces.component.wizard.Wizard.processDecodes(Wizard.java:80) [primefaces-8.0.jar:8.0]
at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:590) [jsf-impl-2.2.5-jbossorg-3.jar:]
at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183) [jsf-impl-2.2.5-jbossorg-3.jar:]
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689) [jboss-jsf-api_2.2_spec-2.2.5.jar:2.2.5]
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) [jboss-jsf-api_2.2_spec-2.2.5.jar:2.2.5]
```

**Expected behavior**
NPE's should be guarded against.

**Comment by melloware** [comment]
[pf-wizard.zip](https://github.com/primefaces/primefaces/files/4836601/pf-wizard.zip)
