### ISSUE TITLE
Primeface 8 and Wildfly 18.0.1 - java.lang.InstantiationError: org.primefaces.util.Lazy

### ISSUE THREAD

**Issue by dinbtechit** [primefaces/primefaces#6189]
### Environment:
- Open JDK 11
- Primeface 8
- Wildfly 18.0.1 (JSF 2.3.9)
- Maven
- CentOS 7

### Description
Unable to deploy the war file (which is part of the ear file) due to `java.lang.InstantiationError: org.primefaces.util.Lazy`
Any idea is massively appreciated!!!

### Error
**Full Stack Trace**
```
16:10:00,408 SEVERE [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 32) Critical error during deployment: : java.lang.InstantiationError: org.primefaces.util.Lazy
	at deployment.my-app-ear-3.01.ear.my-app-web-3.01.war//org.primefaces.csp.CspPhaseListener.<init>(CspPhaseListener.java:48)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:222)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.processor.LifecycleConfigProcessor.addPhaseListeners(LifecycleConfigProcessor.java:124)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.processor.LifecycleConfigProcessor.process(LifecycleConfigProcessor.java:96)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.ConfigManager.lambda$initialize$0(ConfigManager.java:294)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:292)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:205)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:217)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)

16:10:00,410 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 32) MSC000001: Failed to start service jboss.deployment.subunit."my-app-ear-3.01.ear"."my-app-web-3.01.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.subunit."my-app-ear-3.01.ear"."my-app-web-3.01.war".undertow-deployment: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:254)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:283)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:217)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
	... 10 more
Caused by: java.lang.InstantiationError: org.primefaces.util.Lazy
	at deployment.my-app-ear-3.01.ear.my-app-web-3.01.war//org.primefaces.csp.CspPhaseListener.<init>(CspPhaseListener.java:48)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:222)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.processor.LifecycleConfigProcessor.addPhaseListeners(LifecycleConfigProcessor.java:124)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.processor.LifecycleConfigProcessor.process(LifecycleConfigProcessor.java:96)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.ConfigManager.lambda$initialize$0(ConfigManager.java:294)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:292)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:205)
	... 21 more

16:10:00,417 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "my-app-ear-3.01.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"my-app-ear-3.01.ear\".\"my-app-web-3.01.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
    Caused by: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
    Caused by: java.lang.InstantiationError: org.primefaces.util.Lazy"}}
16:10:00,419 ERROR [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0021: Deploy of deployment "my-app-ear-3.01.ear" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"my-app-ear-3.01.ear\".\"my-app-web-3.01.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
    Caused by: java.lang.RuntimeException: java.lang.InstantiationError: org.primefaces.util.Lazy
    Caused by: java.lang.InstantiationError: org.primefaces.util.Lazy"}}
```

**Comment by melloware** [comment]
Hmmm this is interesting.  Let me try and reproduce in Wildfly.

**Comment by dinbtechit** [comment]
Thanks! Let me know if you need any thing. 

Primefaces 7 works fine though.

**Comment by melloware** [comment]
Hmmm OK I can't reproduce.

Open JDK 11
Primeface 8
Wildfly 18.0.1 (JSF 2.3.9)
Maven

I am running just with with CSP=true and CSP=false???

Can you do me a favor and in Wildfly delete  your /data /log and /tmp folders in /standalon and restart your wildfly?

**Comment by dinbtechit** [comment]
Is your war file packaged in a ear file? I don't know if that makes any difference. Mine is packaged within a ear file.

I have also tried with CPS=true and false. But that didn't make any difference.

**web.xml** 
``` xml
<context-param>
    <param-name>primefaces.CSP</param-name>
    <param-value>true</param-value>
</context-param>
```

Anyway... let me try deleting data, tmp and log. Stay tuned!

**Comment by melloware** [comment]
Nope mine is  a WAR file not an EAR file.  Do you have two PrimeFaces loaded in your EAR?  Where is PrimeFaces in your EAR inside the WAR or packaged as a lib of the EAR?

**Comment by dinbtechit** [comment]
Deleting data, tmp and logs did not help. I got the same error. 😔

> Nope mine is a WAR file not an EAR file. Do you have two PrimeFaces loaded in your EAR? Where is PrimeFaces in your EAR inside the WAR or packaged as a lib of the EAR?

They are inside my WAR, under WEB-INF/lib/<primefaces libraries>

Here is my full project structure. Below doesn't include the EJB, web services and other modules.

```
my-app-ear-3.01
└── my-app-web-3.01.war
	├── app
	│   ├── *.xhtml                    # My app pages 
	├── appError.xhtml
	├── login.xhtml
	├── META-INF
	│   ├── MANIFEST.MF
	│   └── maven
	│       └── ca.example.app
	│           └── my-app-web
	├── resources
	│   ├── css
	│   │   ├── app.css
	│   │   ├── app-prime.css
	│   │   ├── app-secondary.css
	│   │   ├── ie8.css
	│   │   ├── ie9.css
	│   │   ├── normalize.css
	│   │   └── webflow.css
	│   ├── js
	│   │   ├── common.js
	│   │   ├── jquery-3.4.1.min.js
	│   │   └── webfont.js
	│   └── utils
	│       ├── pageMenu.xhtml
	│       ├── policy.xhtml
	│       └── messages.xhtml
	└── WEB-INF
		├── beans.xml
		├── classes
		│   └── ca
		│       └── example
		├── faces-config.xml
		├── jboss-web.xml
		├── lib
		│   ├── commons-codec-1.10.jar
		│   ├── commons-lang3-3.10.jar
		│   ├── gson-2.8.5.jar
		│   ├── primefaces-8.0.jar
		│   └── primefaces-extensions-8.0.2.jar
		├── templates
		│   ├── app_admin_layout.xhtml
		│   └── app_layout.xhtml
		└── web.xml
```

**Comment by melloware** [comment]
interesting.  Why an EAR if it only contains 1 WAR?  Or is there other stuff you are not including?

**Comment by dinbtechit** [comment]
> interesting. Why an EAR if it only contains 1 WAR? Or is there other stuff you are not including?

there are other stuffs that I have not included.

**Comment by melloware** [comment]
Is there any way you can boil down a small reproducible example for me to deploy?

**Comment by dinbtechit** [comment]
Unfortunately I am not able to reproduce the issue in a brand new project either.  https://github.com/dinbtechit/jsf-demo

I'll investigate this further and get back to  you. Thanks!

**Comment by melloware** [comment]
Thank you. That is the only way I can help debug it so hopefully as you reintroduce 1 thing at a time until it happens.

**Comment by dinbtechit** [comment]
Found the culprit.... It was due to conflicting Primefaces version. My War file was using `primefaces 8.0` while there was another dependency referenced in the project that was using `primefaces 7.0`. (Which was installed as a library within Wildfly Modules, made it a bit tricky to find)

**Comment by melloware** [comment]
That is why I asked "Do you have two PrimeFaces loaded in your EAR?" up above :)  Glad you got it solved!

**Comment by mahatiGH** [comment]
I had a similar issue, maven installs the dependency and when I had tried to 'add framework support' in intellij it had copied in a different version into the TARGET/XXX-SNAPSHOT/WEB-INF/lib. Being not so familiar with how java dependencies work it took me some time to figure it out. I got lucky because I was thinking about deleting ~/.m2/repository or running maven clean install.

**Comment by xaqan** [comment]
asdfs
![coca-cola](https://user-images.githubusercontent.com/15524815/191487741-d0165cc3-5399-4111-a04e-602adf8ec711.png)
