### ISSUE TITLE
OutcomeTargetRenderer does not consider JSF 2.2 flow url parameters

### ISSUE THREAD

**Issue by icordoba** [primefaces/primefaces#627]
I am testing JSF 2.2 flows in a PrimeFaces application and when I replace h:button with p:button the link stops working.
In JSF 2.2 you can specify, for example, the flow_id in the "outcome" of a h:button. This seems not to work in PF . The exception I'm getting is:

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: javax.servlet.ServletException: WELD-001303: No active contexts for scope type javax.faces.flow.FlowScoped
   at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4898)
   at [internal classes]
Caused by: javax.servlet.ServletException: WELD-001303: No active contexts for scope type javax.faces.flow.FlowScoped
   at javax.faces.webapp.FacesServlet.service(FacesServlet.java:230)
   at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1285)
   at [internal classes]
   at com.servengine.servlet.EncodingFilter.doFilter(EncodingFilter.java:44)
   at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
   at [internal classes]
   at com.servengine.servlet.ServengineWebFilter.doFilter(ServengineWebFilter.java:136)
   at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
   ... 1 more
Caused by: org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.faces.flow.FlowScoped
   at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:708)
   ... 7 more

Mor information at:
http://forum.primefaces.org/viewtopic.php?f=3&t=42986&p=134916#p134916

**Comment by tandraschko** [comment]
http://docs.oracle.com/javaee/7/api/javax/faces/flow/FlowHandler.html#FLOW_ID_REQUEST_PARAM_NAME
http://docs.oracle.com/javaee/7/api/javax/faces/flow/FlowHandler.html#TO_FLOW_DOCUMENT_ID_REQUEST_PARAM_NAME

**Comment by tandraschko** [comment]
should be fixed in trunk.
Could you please try it? I don't have a example app.

**Comment by icordoba** [comment]
Hello,
I'm sorry I have never built PrimeFaces from trunk, just used downloaded jars. I'll be pleased to test and report here if I have have a link on how to build it or to download a trunk build from git. Thanks.

**Comment by tandraschko** [comment]
1) checkout maven-jsf-plugin
2) "mvn clean package" in the maven-jsf-plugin dir
3) checkout primefaces
4) "mvn clean package" in the primefaces dir 

the builded primefaces jar is no available in the primefaces dir under the target dir.
