### ISSUE TITLE
OutcomeTargetRenderer: null view params occurs NPE

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6287]
**Describe the defect**
Using Tomcat 9.0 + EmptyToNullStringELResolver (see https://stackoverflow.com/a/33420995/4605161) occurs NPE while trying to encode the outcome URL.

```
java.lang.NullPointerException: null
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at com.sun.faces.context.UrlBuilder.addValuesToParameter(UrlBuilder.java:318)
	at com.sun.faces.context.UrlBuilder.addParameters(UrlBuilder.java:127)
	at com.sun.faces.context.ExternalContextImpl.encodeBookmarkableURL(ExternalContextImpl.java:1059)
	at javax.faces.context.ExternalContextWrapper.encodeBookmarkableURL(ExternalContextWrapper.java:966)
	at com.sun.faces.application.view.MultiViewHandler.getBookmarkableURL(MultiViewHandler.java:408)
	at javax.faces.application.ViewHandlerWrapper.getBookmarkableURL(ViewHandlerWrapper.java:272)
	at javax.faces.application.ViewHandlerWrapper.getBookmarkableURL(ViewHandlerWrapper.java:272)
	at org.primefaces.renderkit.OutcomeTargetRenderer.getTargetURL(OutcomeTargetRenderer.java:201)
	at org.primefaces.component.button.ButtonRenderer.buildOnclick(ButtonRenderer.java:100)
	at org.primefaces.component.button.ButtonRenderer.encodeMarkup(ButtonRenderer.java:58)
	at org.primefaces.component.button.ButtonRenderer.encodeEnd(ButtonRenderer.java:36)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
```
**To Reproduce**
Considering this navigation rule:
```
<navigation-case>
   <from-outcome>addRecord</from-outcome>
   <to-view-id>/pages/record/create.jsf</to-view-id>
   <redirect>
      <view-param>
         <name>trfId</name>
         <value>#{transferContext.trfId}</value>
      </view-param>
      <view-param>
         <name>klaId</name>
         <value>#{transferContext.klaId}</value>
      </view-param>
   </redirect>
</navigation-case>
```

One of these values is null and will later on occur NPE. Basically, I'll have a params map with key klaId and values of size 1 being null. I don't think the value should be added if the parsed value is null. See `OutcomeTargetRenderer#evaluateValueExpressions`:
```java
protected List<String> evaluateValueExpressions(FacesContext context, List<String> values) {
        // note that we have to create a new List here, because if we
        // change any value on the given List, it will be changed in the
        // NavigationCase too and the EL expression won't be evaluated again
        List<String> target = new ArrayList<>(values.size());
        for (String value : values) {
            if (isExpression(value)) {
                // evaluate the ValueExpression
                value = context.getApplication().evaluateExpressionGet(context, value, String.class);
            }
            target.add(value);
        }
        return target;
    }
```

**Expected behavior**
If the parsed el is null, it shouldn't be present in param values map

**Comment by melloware** [comment]
Agreed. A NULL value should not be added.
