### ISSUE TITLE
FileDownload: classic (non-ajax) FileDownload failes due to class-not-found-exception

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6291]
**Environment:**
 - PF Version: 9.0-SNAPSHOT
 - Tomcat 9.x

**To Reproduce**

1. Start current Showcase with PrimeFaces 9.0-SNAPSHOT
2. open http://localhost:8080/showcase_war_exploded/ui/file/download.xhtml
3. click to "Download"

This causes:
```
	java.lang.NoClassDefFoundError: org/apache/commons/io/output/StringBuilderWriter
		at org.primefaces.component.filedownload.FileDownloadActionListener.regularDownload(FileDownloadActionListener.java:118)
		at org.primefaces.component.filedownload.FileDownloadActionListener.processAction(FileDownloadActionListener.java:83)
		at javax.faces.event.ActionEvent.processListener(ActionEvent.java:72)
		at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:490)
		at javax.faces.component.UICommand.broadcast(UICommand.java:211)
		at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:847)
		at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1396)
		at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:58)
		at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
		at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
		at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:73)
		at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
```

Is there something wrong with shading?

**Comment by melloware** [comment]
Hmmm weird I just pulled down the latest showcase and both the AJAX and non-AJAX work fine for me?

**Comment by christophs78** [comment]
I´ll cross-check this tomorrow on my workstation. (On my notebook i currently don´t find a way to get rid of this issue.)
Which Java-version and which application-server/version do you use?
(Tried with Java 8 and 14 (AdoptOpenJDK (HotSpot)) on Tomcat 9.0.35)

**Comment by christophs78** [comment]
Same issue on my workstation. (Tomcat 9.0.12 and Java8)
