### ISSUE TITLE
DataTable: h:inputFile inside p:dataTable causes javax.servlet.ServletException: UT010016: Not a multi part request when submitted by ajax

### ISSUE THREAD

**Issue by BryanV91** [primefaces/primefaces#6351]
**Describe the defect**

I currently have a requirement where we need a tag `h:inputFile` in every row of a `p:dataTable`, when I try to submit the whole `h:form` with `enctype="multipart/form-data"` through AJAX I'm getting this exception:

`javax.faces.FacesException: javax.servlet.ServletException: UT010016: Not a multi part request`

- I can't use the `p:fileUpload` component, it is way too big to be inside of a `<td />`
- AJAX is mandatory, so I can't swap to the non-ajax version
- I already know that I can't send a file with a `p:commandLink` through AJAX and that's why I'm using `h:inputFile` + `f:ajax`

Workaround:

Using selectors to process all inputs except the `h:inputFile` works if the `h:inputFile` component is outside of the `p:dataTable,` but it is not working when it is inside of the `p:dataTable` because the parent component is still processing its childs.

**Environment:**
 - PF Version: _8.0_
 - JSF + 2.2: _Mojarra 2.2.9_
 - Affected browsers: _ALL_

**To Reproduce**

1. Copy & paste examples
2. Click submit links
3. See error

**Expected behavior**

`p:dataTable` should ignore all its childs with the selector that has been set to be ignored.

**Example XHTML**

If I click Submit (ignore) h:inputFile should be ignored and all the other components should be processed, but exception is thrown.

If I click Submit (process) all h:inputFile are not processed and all other components are processed, finally no exception is thrown.

```html
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui" xmlns:jsf="http://xmlns.jcp.org/jsf" xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core" xmlns:o="http://omnifaces.org/ui">
<h:head id="head">
</h:head>
<h:body id="body">
	<h:form id="form" enctype="multipart/form-data">
		<p:dataTable id="table" value="#{[1,2,3,4,5]}">
			<f:facet name="header">
				Table
			</f:facet>
			<p:column id="input">
				<p:inputText id="text" styleClass="process"></p:inputText>
			</p:column>
			<p:column id="col" headerText="Column">
				<h:inputFile id="file" value="#{testBean.file}" pt:class="ignore">
					<f:ajax listener="#{testBean.handleFileUpload}" render="@form" />
				</h:inputFile>
			</p:column>
		</p:dataTable>
		<p:commandLink process="@(.process)" update="@(.process)">
			Submit (process)
		</p:commandLink>
		<p:commandLink process="@(#form :not(.ignore))" update="@(#form :not(.ignore))">
			Submit (ignore)
		</p:commandLink>
	</h:form>
</h:body>
</html>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestBean implements Serializable {

        private Part file;

        public void handleFileUpload(AjaxBehaviorEvent event) {
		System.out.println("file size: " + file.getSize());
		System.out.println("file type: " + file.getContentType());
		System.out.println("file info: " + file.getHeader("Content-Disposition"));
	}

       // getters + setters

}
```

**Comment by tandraschko** [comment]
Does f:ajax or p:ajax in a Inputfile works outside of a datatable?

**Comment by BryanV91** [comment]
Yes f:ajax works outside of the datatable.

**Comment by BryanV91** [comment]
> Yes f:ajax works outside of the datatable

It works when I choose the h:inputFile + f:ajax not to be processed.

**Comment by BryanV91** [comment]
Sorry for the misclick, it's too late here. I will be providing an example with h:inputFile + f:ajax outside of the datatable in a few hours.

**Comment by melloware** [comment]
@BryanV91 A runnable example would be great using [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.

**Comment by BryanV91** [comment]
@melloware 

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/5287174/primefaces-test-master.zip)

Page `page.xhtml` contains the p:dataTable and the h:inputFile. 

The submission works if I do this (selecting only the inputs that I want):

```
<p:commandLink process="@(.process)" update="@(.process)">Submit (process)</p:commandLink>
```

Expected behaviour (process everything except `h:inputFile):`

```
<p:commandLink process="@(#form :not(.ignore))" update="@(#form :not(.ignore))">Submit (ignore)</p:commandLink>
```

`p:dataTable` + `process="@(#form :not(.ignore))"` is somehow not ignoring child components with the custom selector.

**Comment by melloware** [comment]
OK I had to fix your example to make it work for me:
[pf-6351.zip](https://github.com/primefaces/primefaces/files/5288387/pf-6351.zip)

I get different behavior betweeen Mojarra and MyFaces:
`mvn clean jetty:run -Pmojarra23`

`mvn clean jetty:run -Pmyfaces23`

On Mojarra I get:
```
Sep 27, 2020 9:59:23 AM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
        at org.eclipse.jetty.server.Request.getParts(Request.java:2365)
        at com.sun.faces.renderkit.html_basic.FileRenderer.decode(FileRenderer.java:91)
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:832)
        at javax.faces.component.UIInput.decode(UIInput.java:773)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1227)
        at javax.faces.component.UIInput.processDecodes(UIInput.java:678)
        at org.primefaces.component.api.UIData.process(UIData.java:451)
        at org.primefaces.component.datatable.DataTable.processChildren(DataTable.java:1171)
        at org.primefaces.component.api.UIData.processPhase(UIData.java:400)
        at org.primefaces.component.api.UIData.processDecodes(UIData.java:357)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:573)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:913)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at javax.faces.component.UIForm.visitTree(UIForm.java:371)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:266)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
```

With MyFaces I don't get any errors but I don't know if I am getting the behavior you want.
Can you test with `mvn clean jetty:run -Pmyfaces23` and let me know?

**Comment by BryanV91** [comment]
Ok just tested and I can confirm that exception is not thrown with `jetty:run -Pmyfaces23`.

Exception only occurs with `jetty:run -Pmojarra23`.

Stacktrace:

```
sep 27, 2020 7:59:34 PM com.sun.faces.context.PartialViewContextImpl processPartial
INFORMACIÓN: javax.faces.FacesException: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
javax.faces.FacesException: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
	at com.sun.faces.renderkit.html_basic.FileRenderer.decode(FileRenderer.java:78)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
	at javax.faces.component.UIInput.decode(UIInput.java:798)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:886)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:692)
	at org.primefaces.component.api.UIData.process(UIData.java:451)
	at org.primefaces.component.datatable.DataTable.processChildren(DataTable.java:1171)
	at org.primefaces.component.api.UIData.processPhase(UIData.java:400)
	at org.primefaces.component.api.UIData.processDecodes(UIData.java:357)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:913)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1008)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:55)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1402)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
	at org.eclipse.jetty.server.Request.getParts(Request.java:2365)
	at com.sun.faces.renderkit.html_basic.FileRenderer.decode(FileRenderer.java:67)
	... 62 more

sep 27, 2020 7:59:34 PM com.sun.faces.lifecycle.ApplyRequestValuesPhase execute
ADVERTENCIA: javax.faces.FacesException: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
javax.faces.FacesException: javax.faces.FacesException: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:268)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1008)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:55)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1402)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.faces.FacesException: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
	at com.sun.faces.renderkit.html_basic.FileRenderer.decode(FileRenderer.java:78)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
	at javax.faces.component.UIInput.decode(UIInput.java:798)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:886)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:692)
	at org.primefaces.component.api.UIData.process(UIData.java:451)
	at org.primefaces.component.datatable.DataTable.processChildren(DataTable.java:1171)
	at org.primefaces.component.api.UIData.processPhase(UIData.java:400)
	at org.primefaces.component.api.UIData.processDecodes(UIData.java:357)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:913)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
	... 45 more
Caused by: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
	at org.eclipse.jetty.server.Request.getParts(Request.java:2365)
	at com.sun.faces.renderkit.html_basic.FileRenderer.decode(FileRenderer.java:67)
	... 62 more

sep 27, 2020 7:59:34 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
GRAVE: javax.servlet.ServletException: Unsupported Content-Type [application/x-www-form-urlencoded; charset=UTF-8], expected [multipart/form-data]
	at org.eclipse.jetty.server.Request.getParts(Request.java:2365)
	at com.sun.faces.renderkit.html_basic.FileRenderer.decode(FileRenderer.java:67)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
	at javax.faces.component.UIInput.decode(UIInput.java:798)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:886)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:692)
	at org.primefaces.component.api.UIData.process(UIData.java:451)
	at org.primefaces.component.datatable.DataTable.processChildren(DataTable.java:1171)
	at org.primefaces.component.api.UIData.processPhase(UIData.java:400)
	at org.primefaces.component.api.UIData.processDecodes(UIData.java:357)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:913)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1008)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:55)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1402)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
```

So is not related to PrimeFaces at all?

**Comment by melloware** [comment]
Well I will leave that up to @tandraschko but we have seen this a lot where Mojarra bugs are not present in MyFaces.  MyFaces is more actively developed and is much more robust and has higher performance than Mojarra.

But to me this feels like a Mojarra bug.

**Comment by tandraschko** [comment]
The example doesnt contain a DataTable, so not related to DataTable?

**Comment by melloware** [comment]
Oh he has 2 pages 1 test.xhtml and 1 page.xhtml.  The page.xhtml in my download is functional and uses the DataTable.

**Comment by tandraschko** [comment]
but even index.xhtml throws the exception?

**Comment by tandraschko** [comment]
Ok, i think PrimeFaces just ignores the enctype. AFAIR i tried to implement it in the past but never did. Thats the reason why the exception occurs and is correct.

Now i check the DataTable example.

**Comment by melloware** [comment]
Yes for me test.xhtml was throwing the exception as well.

**Comment by melloware** [comment]
Looks like these are the issue:

https://github.com/eclipse-ee4j/mojarra/issues/3782

https://github.com/eclipse-ee4j/mojarra/issues/2931

In fact it looks like Mojarra has lots of issues with this: https://github.com/eclipse-ee4j/mojarra/issues?q=is%3Aissue+enctype+is%3Aclosed+sort%3Aupdated-desc

They are marked closed but it seems to still be a problem in 2.3.14

**Comment by tandraschko** [comment]
I would say that both mojarra and PF is doing correct here.
1) p:ajax doenst support upload and therefore the enctype is ignored (would be a new feature request)
2) the whole DataTable is processed (see javax.faces.partial.execute post param), therefore all rows and inputFiles are processed. Therefore its fine that Mojarra throws a exception as the servlet Part cant be acessed.
It would be nicer if Mojarra would ignore != form-data requests in theier renderer #decode method.  (small enhancement in Mojarra!)

I dont know why MyFaces doesnt throw a exception here, it should be, too.

**Comment by tandraschko** [comment]
I think this ticket is just a missunderstanding of PF selectors and DatTable as still the whole DataTable is processed.

**Comment by tandraschko** [comment]
@melloware could you try to find out why the file-inputs are not processed with MyFaces / HtmlInputFileRendererBase#decode not called?

I think thats the last key to understand the problem for 100%. Nevertheless i think the current exception is ok if you see my last 2 posts, just MyFaces should also throw one.

**Comment by BryanV91** [comment]
With:

```
<p:commandLink id="ignore-file-link" process="@(#form :not(.ignore))" update="@(#form :not(.ignore))">
    Submit (ignore)
</p:commandLink>
```

Result:

`javax.faces.partial.execute: form:table form:table_head form:table:input form:table:col form:table_data form:table:0:text form:table:1:text form:table:2:text form:table:3:text form:process-inputs-link form:ignore-file-link j_id1:javax.faces.ViewState:0`

<h:inputFile id="file" /> is not present. But exception is thrown.

So my missunderstanding could be that eventhough I'm not selecting the h:inputFile, the whole p:dataTable is still being processed?

**Comment by tandraschko** [comment]
form:table is the whole DataTable ;)

**Comment by BryanV91** [comment]
```
<h:commandButton id="hcommandBtn-file" value="CommandButton File">
    <f:ajax execute="file, table"></f:ajax>
</h:commandButton>
```

`javax.faces.partial.execute: form:hcommandBtn-file file, form:table`


This is not throwing the exception at all.

**Comment by tandraschko** [comment]
because f:ajax uses the enctype defined in the form - as i already said.

**Comment by tandraschko** [comment]
created 2 sucessor tasks for this ticket.
You can workaround your problem with overriding the Mojarra inputFileRenderer and skip decode when the current request != multipart

maybe melloware can assist.
