### ISSUE TITLE
File Upload: NPE

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6428]
Regularly, every few days, we have the following type of entries in our log which are related to the file upload widget.
However, we have no user reports and no reproducible case. Obviously there is an NPE. Would be great if you could have a look into and fix it.
Thanks in advance.

```
[#|2020-10-08T16:39:55.192+0200|SEVERE|Payara 5.2020.4|org.primefaces.application.exceptionhandler.PrimeExceptionHandler|_ThreadID=692;_ThreadName=http-thread-pool::http-listener-1(6);_TimeMillis=1602167995192;_LevelValue=1000;|
  java.lang.NullPointerException
        at org.primefaces.model.file.NativeUploadedFile.resolveFilename(NativeUploadedFile.java:113)
        at org.primefaces.model.file.NativeUploadedFile.<init>(NativeUploadedFile.java:53)
        at org.primefaces.component.fileupload.NativeFileUploadDecoder.createUploadedFile(NativeFileUploadDecoder.java:60)
        at org.primefaces.component.fileupload.NativeFileUploadDecoder.createUploadedFile(NativeFileUploadDecoder.java:38)
        at org.primefaces.component.fileupload.AbstractFileUploadDecoder.decodeAdvanced(AbstractFileUploadDecoder.java:82)
        at org.primefaces.component.fileupload.AbstractFileUploadDecoder.decode(AbstractFileUploadDecoder.java:50)
        at org.primefaces.component.fileupload.AutoFileUploadDecoder.decode(AutoFileUploadDecoder.java:49)
        at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:59)
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
        at javax.faces.component.UIInput.decode(UIInput.java:798)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:886)
        at javax.faces.component.UIInput.processDecodes(UIInput.java:692)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:881)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:881)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:881)
        at javax.faces.component.UIForm.processDecodes(UIForm.java:196)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:881)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:881)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:881)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:881)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:881)
        at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1010)
        at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:55)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.bfabric.filter.LoginFilter.doFilter(LoginFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
|#]
```

**Comment by tandraschko** [comment]
added some null checks, not sure if other NPEs will follow 
As we dont have a reproducer, i will close it for now.

**Comment by wal-jan** [comment]
There are more NPEs. <p:fileUpload **mode=simple auto=true** _fileLimit=x sizeLimit=y allowTypes=z_ .../> sends empty parts if fileLimit, sizeLimit or allowTypes are violated. NPEs occur with both UPLOADER=native and UPLOADER=commons

[PF-6428-commons.zip](https://github.com/primefaces/primefaces/files/6856978/PF-6428-commons.zip)
[PF-6428-native.zip](https://github.com/primefaces/primefaces/files/6856979/PF-6428-native.zip)

**Comment by melloware** [comment]
@wal-jan can you open a new issue with these in it?
