### ISSUE TITLE
Sorted DataTable throws NullPointerException

### ISSUE THREAD

**Issue by dfme** [primefaces/primefaces#645]
We are using a `<p:dataTable` within our Primefaces 5.0 application.
We currently wanted to upgrade to use 5.2 but we are hindered with the following issue:
Since Primefaces 5.1 the `BeanPropertyComparator` throws a `NullPointerException` when the component is being rendered during an ajax call.
After doing some analysis we have come to the conclusion that the initialisation of the `ValueExpression` being used for sorting has changed in the `SortFeature` class. In 5.0 there is the following code snippet:

```
ValueExpression tableSortByVE = table.getValueExpression("sortBy");
        if (tableSortByVE != null) {
            sortByVE = tableSortByVE;

            UIColumn sortColumn = table.getSortColumn();
            if (sortColumn != null && sortColumn.isDynamic()) {
                ((DynamicColumn) sortColumn).applyStatelessModel();
            }
        } else {
            sortByVE = createValueExpression(context, table.getVar(),
                    table.getSortBy());
        }
```

Therefore the `ValueExpression` is definately created and passed to the `BeanPropertyComparator`
In 5.1 and 5.2 however the passage has changed and there is no if / else code block anymore. Therefore the `sortByVE` is `null` and passed to the `BeanPropertyComparator` which causes the NPE.

For us this looks like regression bug.

Snippet of the `<p:dataTable` definition:

```
<p:dataTable var="doc" value="#{chunk.chunkDocs}"
                                    filteredValue="#{ppMessageBean.filteredChunkDocs}"
                                    sortBy="archivoid" paginator="true" rows="30"
                                    paginatorPosition="bottom" style="margin-top:10px;">
```

Complete Stacktrace:

```
Aug 20, 2015 12:00:25 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SCHWERWIEGEND: java.lang.NullPointerException
    at org.primefaces.model.BeanPropertyComparator.compare(BeanPropertyComparator.java:58)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
    at java.util.TimSort.sort(TimSort.java:230)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.ArrayList.sort(ArrayList.java:1454)
    at java.util.Collections.sort(Collections.java:175)
    at org.primefaces.component.datatable.feature.SortFeature.singleSort(SortFeature.java:148)
    at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:109)
    at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:83)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
    at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:88)
    at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:71)
    at org.primefaces.component.panel.PanelRenderer.encodeContent(PanelRenderer.java:206)
    at org.primefaces.component.panel.PanelRenderer.encodeMarkup(PanelRenderer.java:123)
    at org.primefaces.component.panel.PanelRenderer.encodeEnd(PanelRenderer.java:58)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
    at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:88)
    at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:71)
    at org.primefaces.component.outputpanel.OutputPanelRenderer.encodeEnd(OutputPanelRenderer.java:38)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1864)
    at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:599)
    at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1690)
    at com.sun.faces.facelets.component.UIRepeat.visitChildren(UIRepeat.java:856)
    at com.sun.faces.facelets.component.UIRepeat.visitTree(UIRepeat.java:759)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1701)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1701)
    at javax.faces.component.UIForm.visitTree(UIForm.java:371)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1701)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1701)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1701)
    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1701)
    at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:406)
    at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:325)
    at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:60)
    at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1004)
    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1857)
    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:435)
    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:301)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
```

**Comment by cagataycivici** [comment]
This was a documented changed from 5.0 to 5.1 and finally removed in 5.2. You need to have a expression for sortBy all times. Please review;

https://github.com/primefaces/primefaces/wiki/Migration-Guide
