### ISSUE TITLE
DatePicker: showSeconds should be automatically set when pattern is used

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6459]
Currently, it is required to use showSeconds="true" in order to show the seconds in the widget. Example:

```
 <p:datePicker
            value="#{workflowStep.startDateTime}"
            pattern="yyyy-MM-dd HH:mm:ss"
            showSeconds="true"
            showTime="true" />

```

It would be good if this is not required anymore whenever the attribute pattern is used. The necessity to show seconds can be derived from the pattern. This reduces potential inconsistencies.

**Comment by melloware** [comment]
Same here if the pattern has an "s" in it is shows seconds.
```java
if (datepicker.isShowSecondsWithoutDefault() == null) {
            datepicker.setShowSeconds(pattern.contains("s"));
        }
```

**Comment by tuerker** [comment]
i had quick view on the corresponding method encodeMarkup. then the only reason why this is not applied must be that the if condition datepicker.isShowSecondsWithoutDefault() is not null anymore when this place is reached.

**Comment by melloware** [comment]
I think I see this bug still investigating.

**Comment by tuerker** [comment]
so could it be that datepicker.isShowSecondsWithoutDefault is somehow set to a default that is not null, e.g., empty string?

**Comment by tuerker** [comment]
thanks in advance.

**Comment by tuerker** [comment]
great. thanks.

**Comment by tuerker** [comment]
it looks like that this fix unfortunately broke something else. when there is no pattern, it delivers NPE.

**Comment by tuerker** [comment]
this is exactly what your reproducer also states now:

```

HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException
URI:	/primefaces-test/test.xhtml
STATUS:	500
MESSAGE:	javax.servlet.ServletException: javax.servlet.ServletException
SERVLET:	Faces Servlet
CAUSED BY:	javax.servlet.ServletException: javax.servlet.ServletException
CAUSED BY:	javax.servlet.ServletException
CAUSED BY:	java.lang.NullPointerException
Caused by:
javax.servlet.ServletException: javax.servlet.ServletException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1418)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:572)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	... 12 more
Caused by: java.lang.NullPointerException
	at org.primefaces.component.datepicker.DatePickerRenderer.encodeMarkup(DatePickerRenderer.java:124)
	at org.primefaces.component.calendar.BaseCalendarRenderer.encodeEnd(BaseCalendarRenderer.java:89)
	at org.primefaces.component.datepicker.DatePickerRenderer.encodeEnd(DatePickerRenderer.java:63)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
```

**Comment by tuerker** [comment]
```
        if (datepicker.isShowSecondsWithoutDefault() == null) {
            datepicker.setShowSeconds(pattern.contains("s"));
        }
```

should be 

```
        if (pattern != null && datepicker.isShowSecondsWithoutDefault() == null) {
            datepicker.setShowSeconds(pattern.contains("s"));
        }
```

**Comment by melloware** [comment]
No I just fixed it correctly.
```java
String pattern = datepicker.getPattern() == null ? datepicker.calculatePattern() : datepicker.getPattern();
```

**Comment by tuerker** [comment]
yes that is working now.
