### ISSUE TITLE
FileUpload: Requires Nashorn Engine

### ISSUE THREAD

**Issue by commodis** [primefaces/primefaces#6461]
**Describe the defect**
The FileUpload component requires the Nashorn Engine.
With [JEP 372](https://openjdk.java.net/jeps/372) this engine was removed from the JDK 15.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _MyFaces 2.3.1_
 - Affected browsers: _Chrome, but this seems server-side_

**To Reproduce**
1. Install JDK 15
2. Upload WAR on Wildfly 19+
3. upload a `txt.file`

```log
13:06:59,538 WARNING [org.primefaces.util.FileUploadUtils] (default task-17) The type of the uploaded file test.txt could not be validated: javax.script.ScriptException: java.lang.NullPointerException: JavaScript ScriptEngine not available via the context ClassLoader or the extension ClassLoader.
	at org.primefaces.util.FileUploadUtils.isValidFileName(FileUploadUtils.java:176)
	at org.primefaces.util.FileUploadUtils.isValidType(FileUploadUtils.java:143)
	at org.primefaces.util.FileUploadUtils.isValidFile(FileUploadUtils.java:297)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decodeAdvanced(NativeFileUploadDecoder.java:101)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decode(NativeFileUploadDecoder.java:53)
	at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:59)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIInput.decode(UIInput.java:798)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:886)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIInput.processDecodes(UIInput.java:692)
	at com.sun.jsf-impl@2.3.9.SP08//com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
	at com.sun.jsf-impl@2.3.9.SP08//com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIComponent.visitTree(UIComponent.java:1456)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.jsf-impl@2.3.9.SP08//com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
	at com.sun.jsf-impl@2.3.9.SP08//com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.api@3.0.0.SP02//javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:228)
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
	at javax.faces.api@3.0.0.SP02//javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1008)
	at com.sun.jsf-impl@2.3.9.SP08//com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:55)
	at com.sun.jsf-impl@2.3.9.SP08//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.jsf-impl@2.3.9.SP08//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.api@3.0.0.SP02//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.api@3.0.0.SP02//javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.core@2.1.0.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
	at io.undertow.core@2.1.0.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: JavaScript ScriptEngine not available via the context ClassLoader or the extension ClassLoader.
	... 81 more
```

**Expected behavior**
Working file upload if the nashorn type validator is not present or an output for a workaround like `remove allowTypes on JDK 15+`

**Example XHTML**
```html
<h:form
    enctype="multipart/form-data"
>
    <p:fileUpload
        mode="advanced"
        auto="true"
        allowTypes="/(\.|\/)txt$/"
    />
</h:form>
```

P.S.

It does work without `allowTypes`

```html
<h:form
    enctype="multipart/form-data"
>
    <p:fileUpload
        mode="advanced"
        auto="true"
    />
</h:form>
```

**Comment by tandraschko** [comment]
yeah, we knew that this would be a problem in the future.

**Comment by melloware** [comment]
Yep I think we should research how to detect if Nashhorn is available and also how we can use a JS Engine in JDK15+ if a user does put one on the classpath.

**Comment by tandraschko** [comment]
i think we should remove the JS stuff and add a second attribute for a server-side allowTypes regex

**Comment by melloware** [comment]
Hmmm two attributes seems like a nightmare for users knowing JS and Java Regex patterns no?  

So the code is currently doing the right thing by detecting Nashhorn or Rhino JS engine the only problem is its throwing an Exception if not found.   i think we should remove this exception and just log a WARNING so people using JDK15+ can keep using this for PF 9.  

We can always discuss options for PF 10?

**Comment by tandraschko** [comment]
not validating on the server side might be a secure thing.

**Comment by melloware** [comment]
Good point. @commodis can you add this to your PF app and see if it works.
```xml
<dependency>
  <groupId>org.mozilla</groupId>
  <artifactId>rhino</artifactId>
  <version>1.7.13</version>
</dependency>
```

it should detect the Rhino JS engine since its pluggable and validate using Rhino on JDK15+ right now.  We might not need to do anything except update our documentation?

**Comment by tandraschko** [comment]
adding a fat JS engine dependency because of a small regex? -1 as real solution

**Comment by melloware** [comment]
well I wanted to see if it just worked first as a solution to get people using PF 8.0 or 7.0 on JDK15+ an option right now.

**Comment by commodis** [comment]
Thanks for the suggestion, I will try this tomorrow!

**Comment by Rapster** [comment]
Why using `allowTypes` over [input#accept](https://www.w3schools.com/tags/att_input_accept.asp)? That way, no need of js engine

**Comment by melloware** [comment]
Accept is only for the client dialog to help filter own what the browser shows you like..

> accept | null | String | Filters files in native file browser dialog.

Whereas the AllowTypes allows you to check for Mime Content Type as well.

So accept could be ".pic" with  `allowTypes="/(\.|\/)(gif|jpe?g|png)$/"` so that would force the browser dialog to only allow picking *.pic files but those files having a Content type of GIF, JPG, JPEF, or PNG.  So those two fields serve two different purposes.

**Comment by Rapster** [comment]
Not sure I follow... [input#accept](https://www.w3schools.com/tags/att_input_accept.asp) gives a lot of flexibility:

- file_extension: Specify the file extension(s) (e.g: .gif, .jpg, .png, .doc) the user can pick from
- audio/*: The user can pick all sound files
- video/*: The user can pick all video files
- image/*: The user can pick all image files
- media_type: A valid media type, with no parameters. Look at IANA Media Types for a complete list of standard media types


Ohh I get it `FileUpload#allowTypes` is used for client validation! But still, if you configure accept attribute, how allowTypes becomes useful? 

The way I see it, we are using Nashorn just because of a simple js regex which is originally executed on a web-browser, but we want also to execute  it on server side for security reasons I'm guessing. It's a lot of headaches for not much since you can easily bypass it by renaming the file extension. The only true check is using Tika

**Comment by melloware** [comment]
Yeah my PR I just replaced Nashhorn with Regex checking on the Java side.  

the reason this was introduced was for security: https://github.com/primefaces/primefaces/issues/2791

In case someone bypassed client side script with a Form Post.

**Comment by Rapster** [comment]
It's good you managed to get rid of Nashorn, but I still think allowTypes is more or less useless, even though there is this check on server side, any good hacker will be able to bypass it. As I said, only Tika will be able to give you a clear answer whether it's a valid file or not... To keep things simple, we should have one attribute, it's still confusing for me to have accept and allowTypes

**Comment by tandraschko** [comment]
AFAIR allowTypes is used by complex upload Widget.
Later i added accept for simple upload

**Comment by commodis** [comment]
> Good point. @commodis can you add this to your PF app and see if it works.
> 
> ```
> <dependency>
>   <groupId>org.mozilla</groupId>
>   <artifactId>rhino</artifactId>
>   <version>1.7.13</version>
> </dependency>
> ```
> 
> it should detect the Rhino JS engine since its pluggable and validate using Rhino on JDK15+ right now. We might not need to do anything except update our documentation?

I just tried adding the Rhino Depependency to the maven `pom.xml`. Even though it is located at `/WEB-INF/lib/rhino-1.7.13.jar` the class loader does not pick the library up. Hence probably the same exception as in the first post was thrown.

**Comment by melloware** [comment]
@commodis Ah I see why Rhino in code has to be loaded like..
```java
        ScriptEngine engine = m.getEngineByName("rhino");
```

And we are loading Nashhorn like this...
```java
        ScriptEngine engine = m.getEngineByName("javascript");
```

I was hoping Rhino would plug itself in but it does not its by name.  Sorry!

**Comment by Rapster** [comment]
Looking at `FileUploadUtilsTest#isValidContentTypeCheck`, am I missing something or this UT is wrong?:

```java
        when(fileUpload.getAccept()).thenReturn("image/png");
        Assertions.assertTrue(FileUploadUtils.isValidType(appContext, fileUpload, createFile("test.TIF", "image/tif", tif)));
        Assertions.assertTrue(FileUploadUtils.isValidType(appContext, fileUpload, createFile("test.mp4", "application/music", mp4)));

```

**Comment by melloware** [comment]
The line right above it turns off type checking so they are both true.
```java
when(fileUpload.isValidateContentType()).thenReturn(false);
```
Then it runs tests with it turned on..
```java
when(fileUpload.isValidateContentType()).thenReturn(true);
```

**Comment by melloware** [comment]
To my personal taste this is why i don't like muddled tests that test multiple things in 1 test.  I prefer 1 test 1 result with clear Arrange Act Assert steps like...
```java
 @Test
    public void convertJavaScriptRegex_CaseInsensitive() {
        // Arrange
        String jsRegex = "/\\.(gif|png|jpe?g)$/i";

        // Act
        String result = FileUploadUtils.convertJavaScriptRegex(jsRegex);

        // Assert
        assertEquals("\\.(gif|png|jpe?g)$", result);
    }
```

If your test you were confused about was written
```java
// Arrange
when(fileUpload.isValidateContentType()).thenReturn(false);
when(fileUpload.getAccept()).thenReturn("image/png");

//Act
boolean result = FileUploadUtils.isValidType(appContext, fileUpload, createFile("test.TIF", "image/tif", tif));

//Assert
Assertions.assertTrue(result);
```

It would read cleaner and you would see it more clearly.  Just my two cents.

**Comment by Rapster** [comment]
I understand what you're saying but still, basically it says "fileupload only accepts image/png kind of file, and passing a TIF file is still okay" but that's wrong, it should fail. Now I think of it, it's because allowTypes is not defined, but you have to admit that is very confusing. `FileUploadUtils#isValidFileName` and `FileUploadUtils#isValidFileContent` should be package visibility and not private to test these individually (arf they're also static...)

**Comment by melloware** [comment]
Yes I agree with you it is confusing, and each method should be tested standalone for the function that it does.

**Comment by c-koell** [comment]
Is it possible to backboard this to the 8.x branch ? We are on 8.0.10 and we see this exception on java 17 now.

**Comment by julioAzocar** [comment]
solucion se actualiza primefaces de 8.0 a 11.0.0 y no arrojo mas error

**Comment by matsandreassen** [comment]
I'd also like this to be backported to 8.x as we're not quite ready to move on to 11.

**Comment by tandraschko** [comment]
Please see: https://github.com/primefaces/primefaces#community--elite--pro

**Comment by jasonex7** [comment]
> > Good point. @commodis can you add this to your PF app and see if it works.
> > ```
> > <dependency>
> >   <groupId>org.mozilla</groupId>
> >   <artifactId>rhino</artifactId>
> >   <version>1.7.13</version>
> > </dependency>
> > ```
> >   
> > it should detect the Rhino JS engine since its pluggable and validate using Rhino on JDK15+ right now. We might not need to do anything except update our documentation?
> 
> I just tried adding the Rhino Depependency to the maven `pom.xml`. Even though it is located at `/WEB-INF/lib/rhino-1.7.13.jar` the class loader does not pick the library up. Hence probably the same exception as in the first post was thrown.

To anyone trying to workaround this problem in PrimeFaces 8.x with Java 15+, the correct dependency you have to add to your pom.xml is the following:

```xml
<dependency>
    <groupId>org.mozilla</groupId>
    <artifactId>rhino-engine</artifactId>
    <version>1.7.14</version>
</dependency>
```

That dependency has the corresponding SPI file in META-INF/services path.

**Comment by matsandreassen** [comment]
I tried adding _rhino-engine_ 1.7.14 in my 8.0.19 application, but even though it has the SPI file, I still get 

> 13:59:51.195 [http-nio-8081-exec-2] WARN  org.primefaces.util.FileUploadUtils - The type of the uploaded file file123.bin could not be validated
javax.script.ScriptException: java.lang.NullPointerException: JavaScript ScriptEngine not available via the context ClassLoader or the extension ClassLoader.
	at org.primefaces.util.FileUploadUtils.isValidFileName(FileUploadUtils.java:168)

**Comment by jasonex7** [comment]
rhino-engine maven dependency adds two jar files: rhino-engine-1.7.14.jar and rhino-1.7.14.jar. Could you check if those were aggregated to your generated deployment? I had no problem with PrimeFaces 8.0.0 and 8.0.4

**Comment by marcelocaser** [comment]
With you use JDK14 or previous version, pay attention in message: "Warning: Nashorn engine is planned to be removed from a future JDK release"

**Comment by redddcyclone** [comment]
@jasonex7 that helped, thanks. I'm using JDK 17, PrimeFaces 8.0

**Comment by melloware** [comment]
@redddcyclone you might want to consider upgrading your PF.  Tons of bug fixes and security fixes since 8.0 and it also gets rid of this Rhino Nashhorn requirement.

**Comment by redddcyclone** [comment]
@melloware I wish I could, but I'm managing a project that depends heavily on the aristo theme, which was removed in version 10. I'll be reworking it soon, but for now the latest version I can use is 8.0... but thanks for the suggestion anyway

**Comment by redddcyclone** [comment]
@melloware 

Wow, thank you! Actually, I tried downloading aristo.jar from https://repository.primefaces.org/org/primefaces/themes/aristo/1.0.1 and using with PF 10.0 but it broke a lot of things, so I though the theme would ultimately not be compatible at all. But following the steps on this discussion made it work well! There are some things out of place but I can easily fix it with CSS.

Thanks a lot!

**Comment by melloware** [comment]
yeah the CSS is older so its not perfect but it gets you off of PF 8.0
