### ISSUE TITLE
Chips: allow arbitrary collection type such as TreeSet

### ISSUE THREAD

**Issue by svenhaag** [primefaces/primefaces#6657]
Currently only `List<String>` can be used for the Chips components value. Therefore the entries are eventually redundant and unsorted.

Please also support other types of collections, so that e.g. a `TreeSet` can be used to have unique and sorted entries.

**Example XHTML**
```xml
<p:chips value="#{bean.chips}" />
```

**Example Bean**
```java
@Getter
@Setter
private Collection<String> chips = new TreeSet<>();
```

**Comment by Rapster** [comment]
Please follow the "new feature" template, otherwise will be closed as invalid

**Comment by melloware** [comment]
I could be wrong but when I try to switch Chips to Collection instead of List I get this error:
```
javax.el.ELException: Cannot convert [[One, Two, Three]] of type [class java.util.ArrayList] to [interface java.util.Set]
	at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:577)
	at org.apache.el.parser.AstValue.setValue(AstValue.java:203)
	at org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:263)
	at org.apache.webbeans.el22.WrappedValueExpression.setValue(WrappedValueExpression.java:93)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.setValue(ContextAwareTagValueExpression.java:146)
	at javax.faces.component.UIInput.updateModel(UIInput.java:429)
	at javax.faces.component.UIInput.processUpdates(UIInput.java:347)
	at javax.faces.component.UIForm.processUpdates(UIForm.java:264)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1506)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1506)
	at javax.faces.component.UIViewRoot._processUpdatesDefault(UIViewRoot.java:1777)
	at javax.faces.component.UIViewRoot.access$700(UIViewRoot.java:81)
	at javax.faces.component.UIViewRoot$UpdateModelPhaseProcessor.process(UIViewRoot.java:1915)
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1738)
	at javax.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:989)
	at org.apache.myfaces.lifecycle.UpdateModelValuesExecutor.execute(UpdateModelValuesExecutor.java:38)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
```

It seems like Set is not supported in the EL coerceToType??  I found this post from BalusC about it: https://stackoverflow.com/questions/7711703/displaying-objects-from-a-set-collection-in-datatable-jsf-does-not-work

but maybe I am missing something.

**Comment by Rapster** [comment]
Well, I don't think you can explicitely specify a Set through EL. Anyway, here the requirement is to enlarge the support of `Collection` and not make it specific to `List` (see `ChipsRenderer#encodeMarkup`). Basically, we'll have to use introspection for this

**Comment by melloware** [comment]
I just submitted this PR: https://github.com/primefaces/primefaces/pull/6658

Which makes it more like AutoComplete but it seems like the submission never even gets to the ChipsRenderer because of the EL Expression issue.  My Integration test fails. when I try and use set.

However @svenhaag I did make it so even if you use `List` and the `unique=true` it ensures the List is unique.  I updated my Integration Test accordingly too.

**Comment by svenhaag** [comment]
@melloware unique acts via JavaScript. I think this could be omitted when relying on the JAVA based collection ;).

**Comment by melloware** [comment]
Please see PR: https://github.com/primefaces/primefaces/pull/6658

We make the Server side List unique if unique="true".  Its the same code as done in AutoComplete with multiple.

And as I have said JSF will not allow the value to be a Set only a List it seems.

**Comment by Rapster** [comment]
Oh yeah my bad, I thought we were creating a temporary ArrayList... Regarding, your last point, read the 2nd paragraph (and yet, it's based on DataTable), but in general nothing prevents to have a Set as value (except EL expressions)
