### ISSUE TITLE
TreeTable: Error after migration to PF 10 from PF 8.

### ISSUE THREAD

**Issue by BorisYellnikov** [primefaces/primefaces#6971]
**Describe the defect**
After migration from PF 8 to 10 i have error in my composite component.

lut 10, 2021 10:50:23 AM com.sun.faces.application.view.FaceletViewHandlingStrategy handleRenderException
SEVERE: Error Rendering View[/content/webSiteEditor.xhtml]
javax.el.ELException: /resources/aik/treeTableDataModelEditor.xhtml @35,38 value="#{cc.attrs.value}": Cannot convert [org.primefaces.model.menu.DefaultMenuModel@707b1475] of type [class org.primefaces.model.menu.DefaultMenuModel] to [interface org.primefaces.model.TreeNode]
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:77)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:170)
	at org.primefaces.component.api.UITree.getValue(UITree.java:157)
	at org.primefaces.component.api.UITree.visitTree(UITree.java:813)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:150)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.facelets.component.UIRepeat.visitTree(UIRepeat.java:693)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:940)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:347)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.saveView(FaceletPartialStateManagementStrategy.java:464)
	at com.sun.faces.application.StateManagerImpl.saveView(StateManagerImpl.java:64)
	at javax.faces.application.StateManager.getViewState(StateManager.java:561)
	at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:506)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1101)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javax.el.ELException: Cannot convert [org.primefaces.model.menu.DefaultMenuModel@707b1475] of type [class org.primefaces.model.menu.DefaultMenuModel] to [interface org.primefaces.model.TreeNode]
	at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:576)
	at org.apache.el.ExpressionFactoryImpl.coerceToType(ExpressionFactoryImpl.java:47)
	at javax.el.ELContext.convertToType(ELContext.java:304)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:192)
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.ContextualCompositeValueExpression.getValue(ContextualCompositeValueExpression.java:117)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
	... 72 more

lut 10, 2021 10:50:23 AM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: javax.el.ELException: Cannot convert [org.primefaces.model.menu.DefaultMenuModel@707b1475] of type [class org.primefaces.model.menu.DefaultMenuModel] to [interface org.primefaces.model.TreeNode]
	at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:576)
	at org.apache.el.ExpressionFactoryImpl.coerceToType(ExpressionFactoryImpl.java:47)
	at javax.el.ELContext.convertToType(ELContext.java:304)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:192)
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.ContextualCompositeValueExpression.getValue(ContextualCompositeValueExpression.java:117)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:170)
	at org.primefaces.component.api.UITree.getValue(UITree.java:157)
	at org.primefaces.component.api.UITree.visitTree(UITree.java:813)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:150)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.facelets.component.UIRepeat.visitTree(UIRepeat.java:693)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:940)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:347)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.saveView(FaceletPartialStateManagementStrategy.java:464)
	at com.sun.faces.application.StateManagerImpl.saveView(StateManagerImpl.java:64)
	at javax.faces.application.StateManager.getViewState(StateManager.java:561)
	at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:506)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1101)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Reproducer**
https://github.com/primefaces/primefaces.git

**Environment:**
 - PF Version: 10
 - JSF + version: jakarta 2.3.13

**Example XHTML**
```<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:aik="http://aik.cms.component.com"
      xmlns:aikCmsWidget="http://java.sun.com/jsf/composite/aik/widget"
      xmlns:aikCms="http://java.sun.com/jsf/composite/aik"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:p="http://primefaces.org/ui">

<cc:interface componentType="treeTableDataModelEditor" displayName="treeTableDataModelEditor" shortDescription="Tree table data model editor">
	<cc:attribute name="value" default="#{aikDefaultModelsBean.rootTreeNode}"></cc:attribute>
	<cc:attribute name="headerText" default="Tree table model editor"></cc:attribute>
	<cc:attribute name="onNodeSelect" method-signature="void onNodeSelect(org.primefaces.event.NodeSelectEvent)"></cc:attribute>
	<cc:attribute name="onNodeExpand" default="#{aikDefaultModelsBean.onNodeExpand}" method-signature="void onNodeSelect(org.primefaces.event.NodeExpandEvent)"></cc:attribute>
	<cc:attribute name="onNodeCollapse" default="#{aikDefaultModelsBean.onNodeCollapse}" method-signature="void onNodeSelect(org.primefaces.event.NodeCollapseEvent)"></cc:attribute>
	<cc:attribute name="onNodeUnselect" default="#{aikDefaultModelsBean.onNodeUnselect}" method-signature="void onNodeSelect(org.primefaces.event.NodeUnselectEvent)"></cc:attribute>
</cc:interface>

<cc:implementation>

	<p:contextMenu for="aikTreeTableId">
		 <p:menuitem value="#{msgs.aikAddRootNode}" action="#{cc.addRootNode}" update="aikTreeTableId"></p:menuitem>
		 <p:menuitem value="#{msgs.aikAddNode}" icon="pi pi-search" action="#{cc.addNode}" update="aikTreeTableId"/>
         <p:menuitem value="#{msgs.aikDeleteSelectedNode}" icon="pi pi-times" action="#{cc.deleteSelectedNode}" update="aikTreeTableId"/>
	</p:contextMenu>
	
	<p:treeTable id="aikTreeTableId" value="#{cc.attrs.value}" var="doc" selectionMode="single" selection="#{cc.selectedNode}" 
				 editable="true" editMode="cell">
		<p:ajax event="expand"   listener="#{cc.onNodeExpand}" />
        <p:ajax event="collapse" listener="#{cc.onNodeCollapse}" />
        <p:ajax event="select"   listener="#{cc.onNodeSelect}" />
        <p:ajax event="unselect" listener="#{cc.onNodeUnselect}"/>
        <p:ajax event="rowEdit" listener="#{cc.onRowEdit}"  />
        <p:ajax event="rowEditCancel" listener="#{cc.onRowCancel}"  />
        
		<f:facet name="header">
			<h:outputText value="#{cc.attrs.headerText}"></h:outputText>
		</f:facet>
		
		<p:column headerText="#{msgs.aikData}">
			 <p:cellEditor>
                <f:facet name="output"><h:outputText value="#{doc.data}" /></f:facet>
                <f:facet name="input"><p:inputText value="#{doc.data}" style="width:100%"/></f:facet>
            </p:cellEditor>
		</p:column>
		
		<p:column headerText="#{msgs.aikType}">
			<p:cellEditor>
				<f:facet name="output"><h:outputText value="#{doc.type}"></h:outputText></f:facet>
				<f:facet name="input"><p:inputText value="#{doc.type}"></p:inputText></f:facet>
			</p:cellEditor>
		</p:column>
		
		<p:column headerText="#{msgs.aikIcon}">
			<aikCms:piSelector value="#{doc.icon}"></aikCms:piSelector>
		</p:column>
		
		<p:column headerText="#{msgs.aikExpandedIcon}">
			<aikCms:piSelector value="#{doc.expandedIcon}"></aikCms:piSelector>
		</p:column>
		
		<p:column headerText="#{msgs.aikCollapseIcon}">
			<aikCms:piSelector value="#{doc.collapseIcon}"></aikCms:piSelector>	
		</p:column>
		
		<p:column headerText="#{msgs.aikStyleClass}">
			<p:cellEditor>
				<f:facet name="output"><h:outputText value="#{doc.styleClass}"></h:outputText></f:facet>
				<f:facet name="input"><p:inputText value="#{doc.styleClass}"></p:inputText></f:facet>
			</p:cellEditor>
		</p:column>
        
	</p:treeTable>
	
</cc:implementation>

</html>
```

**Comment by tandraschko** [comment]
TreeTable does not support DefaultMenuModel, also you didnt provide a reproducer.

**Comment by BorisYellnikov** [comment]
The problem is it works in PF 8 and earlier versions of PF, and I don't use as a value DefaultMenuModel but TreeNode.

**Comment by tandraschko** [comment]
Your exception says something different. we cant still help you without a reproducer.

**Comment by tandraschko** [comment]
will close it for now, please come back if you have a reproducer (a forked primefaces-test project)
