### ISSUE TITLE
Datepicker: LocalDateTime with showTime="false" throws converter error

### ISSUE THREAD

**Issue by undermensch** [primefaces/primefaces#7216]
Datepicker with value=LocalDateTime with showTime="false" throws converter error

 PF Version: 10.0.0
 Mojarra 2.2
 Affected browsers:  ALL

1. Create a Datepicker with a LocalDateTime as a value
2. Set showTime="false"
3. Submit Value
4. BaseCalendarRenderer will create a converter exception since the submitted value has no time

**Expected behavior**
Value successfully converts to LocalDateTime with a default time (LocalTime.MIN, etc). A use case would be adding an event to the schedule with all day option where it would be desirable to hide/disregard the time without having to change the backing value type.

**Comment by melloware** [comment]
if you don't want time why not use `LocalDate` which is more correct?

**Comment by undermensch** [comment]
If I use the p:schedule component with ScheduleEvent which uses LocalDateTime for start and end of event and if I give users the option of selecting all day or specifying times, it's better to use LocalDateTime. I don't want to show time if the user selects all day event, but I want the option of times if the user does not select all day. What would be the purpose of a showTime attribute? If I use LocalDate, this attribute would not be necessary, because time would not be shown....

**Comment by melloware** [comment]
its trying to give smart defaults for expected behavior.  So just override the converter with your own like this...

```xml
<p:datePicker value="#{yourlocalDateTime}" showTime="false"/>
   <f:convertDateTime pattern = "dd-mm-yyyy" type="localDateTime" />
<p:datePicker>
```

**Comment by undermensch** [comment]
That example just results in another converter exception. I did get it to work by creating my own custom converter. I feel this should work out of the box, without my having to create a custom converter; however, if this is the expected behavior, then I guess this would be more of a feature request.... Thanks.

**Comment by melloware** [comment]
Agreed this should probably work.

**Comment by melloware** [comment]
Reproducer:
[pf-7216.zip](https://github.com/primefaces/primefaces/files/6289765/pf-7216.zip)

**Comment by wal-jan** [comment]
After some debugging I got to this Ecxeption: 
```
java.time.format.DateTimeParseException: Text '04/06/2021' could not be parsed: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO,Europe/Berlin resolved to 2021-04-06 of type java.time.format.Parsed
	at java.base/java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:2023)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1958)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
	at org.primefaces.component.calendar.BaseCalendarRenderer.convertToJava8DateTimeAPI(BaseCalendarRenderer.java:236)
	at org.primefaces.component.calendar.BaseCalendarRenderer.getConvertedValue(BaseCalendarRenderer.java:164)
	at org.primefaces.component.datepicker.DatePickerRenderer.getConvertedValue(DatePickerRenderer.java:315)
	at javax.faces.component.UIInput.getConvertedValue(UIInput.java:1067)
	at javax.faces.component.UIInput.validate(UIInput.java:981)
	at org.primefaces.component.datepicker.DatePicker.validate(DatePicker.java:100)
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1270)
	at javax.faces.component.UIInput.processValidators(UIInput.java:714)
	at javax.faces.component.UIForm.processValidators(UIForm.java:253)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1195)
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1443)
        ...
Caused by: java.time.DateTimeException: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO,Europe/Berlin resolved to 2021-04-06 of type java.time.format.Parsed
	at java.base/java.time.LocalDateTime.from(LocalDateTime.java:463)
	at java.base/java.time.format.Parsed.query(Parsed.java:241)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	... 56 more
Caused by: java.time.DateTimeException: Unable to obtain LocalTime from TemporalAccessor: {},ISO,Europe/Berlin resolved to 2021-04-06 of type java.time.format.Parsed
	at java.base/java.time.LocalTime.from(LocalTime.java:433)
	at java.base/java.time.LocalDateTime.from(LocalDateTime.java:459)
	... 58 more
```
I suggest the following change
```
--- a/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java
+++ b/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java
@@ -26,6 +26,7 @@
 import java.io.IOException;
 import java.text.ParseException;
 import java.text.SimpleDateFormat;
+import java.time.DateTimeException;
 import java.time.LocalDate;
 import java.time.LocalDateTime;
 import java.time.LocalTime;
@@ -50,6 +51,7 @@
 import javax.faces.convert.ConverterException;
 
 import org.primefaces.component.api.UICalendar;
+import org.primefaces.component.datepicker.DatePicker;
 import org.primefaces.el.ValueExpressionAnalyzer;
 import org.primefaces.renderkit.InputRenderer;
 import org.primefaces.util.*;
@@ -231,7 +233,15 @@
                     .withResolverStyle(resolveResolverStyle(calendar.getResolverStyle()));
 
             try {
-                return LocalDateTime.parse(submittedValue, formatter);
+                try {
+                    return LocalDateTime.parse(submittedValue, formatter);
+                } catch (DateTimeParseException e) {
+                    // in case of missing time part try via LocalDate.class
+                    if (e.getCause() instanceof DateTimeException && e.getCause().getCause() instanceof DateTimeException &&
+                            e.getCause().getCause().getMessage().contains(" LocalTime "))
+                        return LocalDate.parse(submittedValue, formatter).atStartOfDay();
+                    throw e;
+                }
             }
             catch (DateTimeParseException e) {
                 throw createConverterException(context, calendar, submittedValue, formatter.format(LocalDateTime.now()));
```
But maybe there is a better solution to check for this special case.

**Comment by melloware** [comment]
@christophs78 what do you think?

**Comment by christophs78** [comment]
I don´t think we should add code like this to PrimeFaces. Hacks like this may be added to custom projects but not to an universal library like PrimeFaces.
If someone like´s to do a PR IMO the right place should be to add a few if´s to https://github.com/primefaces/primefaces/blob/10.0.0/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java#L163.
Pseudo-code: 
```
if type == LocalDateTime && "false".equals(showTime) then
    ....
else 
     exisiting code
end if 
```

**Comment by melloware** [comment]
OK I think I fixed it in the cleanest spot.
