### ISSUE TITLE
[BUG] [5.2] ClassCastException - selectonemenu with implicit downcast 

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#749]
Forum url: http://forum.primefaces.org/viewtopic.php?f=3&t=38422
Primefaces: 5.0 / 5.2
Mojarra: 2.2.4 / 2.2.9
Glassfish 4.0 / 4.1
# Code
## Bean

```
private final int[] values = new int[] {1, 2};
private byte selValue;

// getter and setter
```
## Markup:

```
<h:form>
    <h:selectOneMenu label="Test" value="#{testBean.selValue}">
            <f:selectItems value="#{testBean.values}"/>
    </h:selectOneMenu>
</h:form>
```
# Exception

_5.0_

Replacing `h:selectOneMenu` by primefaces equivalent `p:selectOneMenu` results in "ClassCastException"

```
javax.faces.convert.ConverterException: test: Conversion of '1' to String not possible.
    at javax.faces.convert.ByteConverter.getAsString(ByteConverter.java:154)
    at org.primefaces.renderkit.InputRenderer.getOptionAsString(InputRenderer.java:148)
```

_5.2_ 

```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Byte
    at javax.faces.convert.ByteConverter.getAsString(Unknown Source)
    at org.primefaces.renderkit.InputRenderer.getOptionAsString(InputRenderer.java:148)
    at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.encodeOption(SelectOneMenuRenderer.java:360)
```
# Workaround

use `h:selectOneMenu` instead of `p:selectOneMenu`

**Comment by cnsgithub** [comment]
Hi, I think the main issue here is the selValue, since the values are int and value is byte, i kinda would expect some strange things to happen anyway. Why don't you just use a getter/setter with int and to the conversion to byte yourself. Just tested and it works, and its not really an ugly workaround

```
   private byte selValue;

    public int getSelValue() {
        //convert manually
    }
    public void setSelValue(int selValue) {
        //convert manually
    }

//if you need the byte getter/setter for other purposes you still can add it

```

**Comment by tandraschko** [comment]
Works fine for me.
