### ISSUE TITLE
DatePicker: crashes with NPE when converting from p:calendar

### ISSUE THREAD

**Issue by ozziej** [primefaces/primefaces#7615]
**Describe the defect**
When migrating from PF8.0 to PF10.0.4 changing p:calendar to p:datePicker causes Null Pointer Exceptions if the referenced object is null. (which is not terribly surprising, but this code works on p:calendar, and I cannot see an easy way around this.)

**Environment:**
 - PF Version: 10.0.4
 - JSF + version: JSF 2.3, WildFly 24.0.0_Final
 - Affected browsers: ALL

**To Reproduce**
1. Create a Controller with an object (such as a User object that is NULL initially, as would be the case when editing a user from a table at the point at which the table is rendered, the user object will be null as no user is selected)
2. Create a form with the user details, such as userId, email address, date of birth in a dialog that will be opened on selecting the user
3. Change p:calendar to p:datePicker
4. NPE

**Expected behavior**
No NPE

**Example XHTML**
```html
<h:form id="frmTest">
  <p:calendar id="dateOfBirth" value="#{userController.selectedUser.dateOfBirth}"/> 
</h:form>
```
vs
```html
<h:form id="frmTest">
  <p:datePicker id="dateOfBirth" value="#{userController.selectedUser.dateOfBirth}"/> 
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class UserController implements Serializable {
    private Users selectedUser;

   //at this point selectedUser is null (as would be the case with a table where nothing is selected)
    public Users getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(Users selectedUser) {
        this.selectedUser = selectedUser;
    }
}
```
The above code works PERFECTLY with p:calendar, but p:datePicker crashes:

SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-65) Error Rendering View[/secured/otherusers.xhtml]: javax.el.PropertyNotFoundException: /secured/edituserdialog.xhtml @82,86 value="#{userController.selectedUser.dateOfBirth}": Target Unreachable, 'null' returned null
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:64)
	at deployment.ProjectName-1..0.war//org.primefaces.component.api.UICalendar.getTypeFromValueByValueExpression(UICalendar.java:356)
	at deployment.ProjectName-1.0.war//org.primefaces.component.datepicker.DatePickerRenderer.encodeEnd(DatePickerRenderer.java:59)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.api@3.0.0.SP04//javax.faces.render.Renderer.encodeChildren(Renderer.java:152)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at deployment.ProjectName-1.0.war//org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:72)
	at deployment.ProjectName-1.0.war//org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:59)
	at deployment.ProjectName-1.0.war//org.primefaces.component.dialog.DialogRenderer.encodeContent(DialogRenderer.java:195)
	at deployment.ProjectName-1.0.war//org.primefaces.component.dialog.DialogRenderer.encodeMarkup(DialogRenderer.java:118)
	at deployment.ProjectName-1.0.war//org.primefaces.component.dialog.DialogRenderer.encodeEnd(DialogRenderer.java:47)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:286)
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)

**Comment by melloware** [comment]
I actually think it should not have worked in Calendar and the above error is correct?

**Comment by ozziej** [comment]
Yes, as I mentioned, it probably **should** give an NPE error, but when using p:calendar it doesn't, but using p:datePicker, it does.

**Comment by ozziej** [comment]
So, I re-created the issue, using the example at :
https://www.primefaces.org/showcase/ui/data/datatable/crud.xhtml

The example here gets around the issue by using a rendered attribute on the container.
<p:outputPanel rendered="#{not empty crudView.selectedProduct}">
...
                            <div class="p-field p-col">
                                <p:outputLabel for="creationTime">Creation Time</p:outputLabel>
                                <p:calendar id="creationTime" value="#{crudView.selectedProduct.creationTime}"/>
                            </div>
</p:outputPanel>
I added creationTime to the product class.

If you use p:calendar and **remove** this : rendered="#{not empty crudView.selectedProduct}"
Everything still works (i.e. no NPE)

However, changing p:calendar to p:datePicker = NPE

I've attached the sample project (with some minor changes to the example)
To replicate the issue.
[SampleProject.zip](https://github.com/primefaces/primefaces/files/6860700/SampleProject.zip)

Remove the following from the outputPanel
rendered="#{not empty crudView.selectedProduct}"

This will cause the NPE on the p:datePicker line.

Change p:datePicker to p:calendar

There will not be a NPE

**Comment by melloware** [comment]
i think maybe you are misunderstanding me. I am saying this is NOT a bug in DatePicker..  You have...
```
value="#{userController.selectedUser.dateOfBirth}": Target Unreachable, 'null' returned null
```

So that means your `selectedUser` is null and thus `dateOfBirth` cannot be reached.  The error is clear JSF EL error and correct.  Why the Calendar does not have this error I am not sure but I believe the DatePicker is doing the right thing and this is the correct error.

@tandraschko any thoughts on this?

**Comment by ozziej** [comment]
@melloware I'm understanding completely, and I agree that its "doing the right thing" however, this ONLY occurs with the date picker.
So, all other elements e.g. <p:inputText value="#{userController.selectedUser.surname}"/> for example do NOT produce a NPE. its ONLY the p:datePicker element.

So, what I'm perhaps saying, is that yes, the datePicker is "doing the right thing" by throwing an NPE, however, its COMPLETELY inconsistent with ALL other elements (including p:calendar, p:inputText, p:selectOneRadio etc , etc)
(You can verify this by running the example)

So, either ALL elements should throw a NPE (which they don't) or p:datePicker should behave as the other elements do and NOT throw a NPE.

**Comment by melloware** [comment]
Understood.

**Comment by tandraschko** [comment]
currently expected as we need to extract the type of the binding.
maybe #getExpectedType works better in all cases compared to #getType

**Comment by melloware** [comment]
You can follow my PR here for comments: https://github.com/primefaces/primefaces/pull/7619

**Comment by tandraschko** [comment]
@melloware you can change this code to only catch PropertyNotFoundException? can you test it?

**Comment by melloware** [comment]
sure

**Comment by melloware** [comment]
Tested locally now I am letting the whole Integration Test suite run.
