### ISSUE TITLE
FileUpload: Simple auto upload throws exception while size limit is reached

### ISSUE THREAD

**Issue by garcia-jj** [primefaces/primefaces#7616]
I tried to use the simple file upload component with auto=true, and an error occurs while I sent a file that reaches the max upload size.  Debugging the code I see that field `part` inside `NativeUploadedFile` class is null.

**Reproducer**
Clone repository https://github.com/garcia-jj/primefaces-upload-issue in order to reproduce that issue. The page http://127.0.0.10:8080/primefaces-test/basic.xhtml contains the test case.

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _e.g. Wildfly 21, Mojarra
 - Affected browsers: tested on Chorme and Firefox, but I guess this is not a browser issue

**To Reproduce**
1. Go to 'http://127.0.0.10:8080/primefaces-test/basic.xhtml'
2. Click on '+ Choose' button, then select a file with size greater than 1kb.
4. See error on logs. A NullPointerException will occurs.
```
Jul 21, 2021 3:35:56 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.NullPointerException: Cannot invoke "javax.servlet.http.Part.getSize()" because "this.part" is null
        at org.primefaces.model.file.NativeUploadedFile.getSize(NativeUploadedFile.java:70)
        at org.primefaces.model.file.UploadedFileWrapper.getSize(UploadedFileWrapper.java:74)
        at org.primefaces.util.FileUploadUtils.tryValidateFile(FileUploadUtils.java:299)
        at org.primefaces.component.fileupload.FileUpload.validateValue(FileUpload.java:85)
```

**Expected behavior**
The file upload sucessfully.

**Example XHTML**
```html
<p:growl id="messages" showDetail="true"/>

<div class="card">
    <h5>Single</h5>
    <h:form>
        <p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" auto="true"
                      process="@this" update="messages"
                      sizeLimit="1"
                      listener="#{fileUploadView.handleFileUpload}"/>
    </h:form>
</div>

<div class="card">
    <h5>Multiple</h5>
    <h:form>
        <p:fileUpload value="#{fileUploadView.files}" mode="simple" skinSimple="true" multiple="true"
                      auto="true"
                      sizeLimit="1"
                      process="@this" update="messages"
                      listener="#{fileUploadView.handleFilesUpload}"/>
    </h:form>
</div>
```

**Example Bean**
```java
@Named
@RequestScoped
public class FileUploadView {

	private UploadedFile file;
	private UploadedFiles files;

	public UploadedFile getFile() {
		return file;
	}

	public void setFile(UploadedFile file) {
		this.file = file;
	}

	public UploadedFiles getFiles() {
		return files;
	}

	public void setFiles(UploadedFiles files) {
		this.files = files;
	}

	public void handleFileUpload(FileUploadEvent event) {
		FacesMessage message = new FacesMessage("Successful", event.getFile().getFileName() + " is uploaded.");
		FacesContext.getCurrentInstance().addMessage(null, message);
	}

	public void handleFilesUpload(FilesUploadEvent event) {
		for (UploadedFile f : event.getFiles().getFiles()) {
			FacesMessage message = new FacesMessage("Successful", f.getFileName() + " is uploaded.");
			FacesContext.getCurrentInstance().addMessage(null, message);
		}
	}
}
```

Thank U

**Comment by melloware** [comment]
Thanks for the reproducer!  I modified your example slightly to print out an invalid size message.
```xml
			<p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" auto="true"
						  process="@this" update="messages"
						  sizeLimit="1000" invalidSizeMessage="File Size has exceeded 1KB!"
						  listener="#{fileUploadView.handleFileUpload}"/>
```

**Comment by melloware** [comment]
PR Submitted please review.

**Comment by garcia-jj** [comment]
Great job. Thank U

**Comment by melloware** [comment]
@wal-jan is going to take a shot at a more comprehensive fix.
