### ISSUE TITLE
Datatable throws ListDataModel cast exception

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#7737]
I think there was a bug introduced somewhere due to #7391, because this didn't happen for us on 10.0.5 and suddenly appeared on 10.0.6. The problem happens when selecting rows in a filtered datatable with lazy model.

```
Caused by: java.lang.ClassCastException: class pl...DataModel cannot be cast to class java.util.List (pl...DataModel is in unnamed module of loader 'deployment...-web-1.war' @3428e777; java.util.List is in module java.base of loader 'bootstrap')
	at javax.faces.api@3.0.0.SP04//javax.faces.model.ListDataModel.setWrappedData(ListDataModel.java:200)
	at deployment...-web-1.war//org.primefaces.model.SelectableDataModelWrapper.<init>(SelectableDataModelWrapper.java:31)
	at deployment...-web-1.war//org.primefaces.component.datatable.DataTable.updateValue(DataTable.java:306)
	at deployment...-web-1.war//org.primefaces.component.datatable.feature.SelectionFeature.decode(SelectionFeature.java:55)
	at deployment...-web-1.war//org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:65)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
	at deployment...-web-1.war//org.primefaces.component.api.UIData.processDecodes(UIData.java:109)
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
	at deployment...-web-1.war//org.primefaces.component.api.UIData.visitTree(UIData.java:683)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at deployment...-web-1.war//org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:931)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
```
(lazy data model descendant class name and deployment name redacted)

In the old code this part of SelectionFeature
```
        if (isFiltered) {
            table.updateValue(originalValue);
        }
```
 called this part of UIData:
```
    public void setValue(Object value) {
        setDataModel(null);
        getStateHelper().put(PropertyKeys.value, value);

    }
```
and it worked. Now it calls the code you see in the stack trace. That code expects originalValue to be a list, while it gets a LazyDataModel from datatable's getValue().

**Comment by tandraschko** [comment]
please provide a reproducer

**Comment by morvael** [comment]
The old method called setValue directly:
```
        if (isFiltered) {
            table.setValue(originalValue);
        }
```

And the new one uses new updateValue:
```
        if (isFiltered) {
            table.updateValue(originalValue);
        }
```
which is
```
    public void updateValue(Object value) {
        Object originalValue = getValue();
        if (originalValue instanceof SelectableDataModel) {
            setValue(new SelectableDataModelWrapper((SelectableDataModel) originalValue, value));
        }
        else {
            setValue(value);
        }
    }
```
and it wants value to be list.

I'll try to prepare a reproducer.

**Comment by morvael** [comment]
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7030742/primefaces-test-master.zip)

Enter something into filter input to filter a value and click on the row to select it. You should get:
![Screenshot 2021-08-23 at 10-57-09 PrimeFaces Test](https://user-images.githubusercontent.com/1133953/130419932-8c2b4103-9b5d-49a0-85f2-2c8ef1472e9f.png)

**Comment by morvael** [comment]
I think this bug will make many people around the world using datatable with lazy & filter & selection (doesn't seem to be very uncommon scenario) quite unhappy with 10.0.6.

**Comment by morvael** [comment]
I think that it's easy to miss this exception without custom exception handler that shows some "behind the scenes" exceptions to the user. Apart from that the component seems to work (see how the footer changes while selecting one or more items). So I don't know the ramifications of this bug.

**Comment by morvael** [comment]
But it's definitely wrong to assume DataTable.getValue always returns a List, it can also return a LazyDataModel.

**Comment by tandraschko** [comment]
it seems to work fine with 11.0.0-SNAPSHOT, right?

**Comment by morvael** [comment]
Seems like I can't find that jar, so no way to test.

**Comment by tandraschko** [comment]
scroll down and check the readme here: https://github.com/primefaces/primefaces

**Comment by morvael** [comment]
There is no 11.0.0-SNAPSHOT there, and master-SNAPSHOT looks like 6_1?

**Comment by tandraschko** [comment]
master-SNAPSHOT = 11.0.0-SNAPSHOT

**Comment by tandraschko** [comment]
otherwise you can always checkout PF master and just do a mvn install -DskipTests

**Comment by morvael** [comment]
Then why do I get master-6_1-g9cdffab-6065 with master-SNAPSHOT? Anyway, I provided a reproducer for 10.0.6 :)

**Comment by tandraschko** [comment]
i dont know, i dont use jitpack

this is the community issue tracker and I can only fix it for 11.0
therefor i would like to know if it works there, so we can identifiy it as elite only and ping PrimeTek.

**Comment by morvael** [comment]
This is the content of https://jitpack.io/com/github/primefaces/primefaces/master-SNAPSHOT/maven-metadata.xml
![Screenshot at 2021-08-23 12-06-05](https://user-images.githubusercontent.com/1133953/130429737-1870731a-7e81-41df-b7b7-6b7356846fe4.png)

I guess that's another issue that could be raised...

**Comment by morvael** [comment]
I think I have already suggested elite needs an issue tracker too. Because otherwise we end up with some catch 22 situation.

**Comment by tandraschko** [comment]
created a issue for the jitpack issue

i cant replicate it with a snapshot, however i dont know if i make something wrong

@sqores @mertsincan 
can you have a look? i really suggest to release 11.0 as 10.1 and get rid of all that datatable issues easily.

i will also ping PrimeTek in the team chat and likely close that issue then, thats only elite.

**Comment by christophs78** [comment]
i´ll add explizit integrationtests for the combination of DataTable + Lazy + Filter + Selection
@morvael : do you use single or multiselect?

**Comment by morvael** [comment]
Multiselect (as in the reproducer).

**Comment by buunsal** [comment]
@morvael I tested with 10.0.6 and 11.0.0-SNAPSHOT. Yes it doesn't work with 10.0.6 and it works with 11.0.0-SNAPSHOT. I'll try to fix it for the next elite version.

**Comment by buunsal** [comment]
Source of the issue is this fixes: https://github.com/primefaces/primefaces/issues/7336
And fixed with this: https://github.com/primefaces/primefaces/issues/7368

**Comment by MassiveTM** [comment]
I have the same problem with Primefaces 10.0.6 - Datatable with Filter and Selection, without Lazy.

` <p:commandButton action="#{bck.editAction}" process="@this" partialSubmit="true" global="true"
			 styleClass="button iconButton" icon="icon-pencil-1">
		<f:setPropertyActionListener target="#{bck.selected}" value="#{row}" />
</p:commandButton> `

When i try to select the row , the setPropertyActionListener is passing a null value :( Any idea?

**Comment by melloware** [comment]
@MassiveTM then yours is a different problem because this is specific to Lazy.    You will need to create a PrimeFaces Test reproducer so we can see your issue.   You can use this as a starting point since this is a Selection example: https://github.com/KCampos-GandG/primefaces-test.git

The user above's issue was his Selection object was not `Serializable`. If you can reproduce please open a new ticket.
