### ISSUE TITLE
DataExporter: Exception when exporting DataTable with single column and header facet

### ISSUE THREAD

**Issue by firsthour** [primefaces/primefaces#7802]
**Describe the defect**
Exception thrown when a DataTable with a header and a single exportable column:
```
java.lang.IllegalArgumentException: Merged region A1 must contain 2 or more cells
	at org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:403)
	at org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:368)
	at org.primefaces.component.datatable.export.DataTableExcelExporter.addTableFacets(DataTableExcelExporter.java:205)
	at org.primefaces.component.datatable.export.DataTableExcelExporter.exportTable(DataTableExcelExporter.java:401)
	at org.primefaces.component.datatable.export.DataTableExcelExporter.doExport(DataTableExcelExporter.java:87)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.visit(DataTableExporter.java:357)
```

I discovered this when trying to create a simple, reproduceable setup for a different error we're seeing. We have a complex datatable framework with p:columns and data exporters, and the new feature of the header facet being put in row 1 is creating issues for us. I'm still working on that issue though.

**Environment:**
 - PF Version: _10.0.6_
 - POI: _4.1.2_

**To Reproduce**
1. Export table
2. See error

**Expected behavior**
The table should export successfully.

**Example XHTML**
```
<h:form>
	<p:dataTable
		id="dt"
		var="row"
		value="#{testController.rows}">
		<f:facet name="header">
			<p:outputLabel value="Test" />
		</f:facet>
		<p:column headerText="Column 1">
			<h:outputText value="#{row.col1}" />
		</p:column>
	</p:dataTable>
	<p:commandButton value="XLS">
		<p:dataExporter
			type="xlsx"
			target="dt"
			fileName="output" />
	</p:commandButton>
</h:form>
```

**Example Bean**
```
@Named
@ViewScoped
public class TestController implements Serializable {
	private static final long serialVersionUID = 1L;
	
	public List<Row> getRows() {
		Row row1 = new Row();
		row1.setCol1("r1c1");
		
		Row row2 = new Row();
		row2.setCol1("r2c1");
		
		return Arrays.asList(row1, row2);
	}
	
	public static class Row {
		private String col1;
		
		public String getCol1() {
			return col1;
		}
		
		public void setCol1(String col1) {
			this.col1 = col1;
		}
	}
}
```

**Comment by melloware** [comment]
I will investigate.

**Comment by melloware** [comment]
OK PR submitted. The error makes perfect sense POI does not allow you to merge a single cell since its not really a merge at that point!
