### ISSUE TITLE
FileDownload: "Error in streaming dynamic resource" with ViewScoped and ajax="true"

### ISSUE THREAD

**Issue by firsthour** [primefaces/primefaces#7844]
**Describe the defect**
When trying to serve a file from a ViewScoped CDI bean and ajax="true" on the button, I get an "Error in streaming dynamic resource" message and the download fails. Here's the exception:

```
org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.faces.view.ViewScoped
at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647)
at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:94)
at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
at org.jboss.weld.module.web.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
at org.jboss.weld.module.web.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
at org.jboss.as.jsf.injection.weld.ForwardingELResolver.getValue(ForwardingELResolver.java:46)
at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:136)
at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:156)
at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:184)
at com.sun.el.parser.AstIdentifier.getValue(AstIdentifier.java:91)
at com.sun.el.parser.AstValue.getBase(AstValue.java:125)
at com.sun.el.parser.AstValue.getValue(AstValue.java:173)
at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:183)
at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
at org.primefaces.application.resource.StreamedContentHandler.handle(StreamedContentHandler.java:60)
```

**Environment:**
 - PF Version: _10.0.6_
 - JSF + version: _Mojarra 2.3.14.SP04_
 - Weld: _3.1.7 (SP1)_
 - Wildfly: _Full 24.0.1.Final_
 - Affected browsers: _Chrome and Firefox_

**To Reproduce**
1. Click button
2. See error
3. Switch to ajax="false" or CDI @RequestScoped
4. Works fine

**Expected behavior**
The browser should download the file as expected.

**Example XHTML**
```
<h:form>
	<p:commandButton value="Submit">
		<p:fileDownload value="#{testController.file}" />
	</p:commandButton>
</h:form>
```

**Example Bean**
```
import java.io.Serializable;

import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

@Named
@ViewScoped
public class TestController implements Serializable {
	private static final long serialVersionUID = 1L;
	
	public StreamedContent getFile() {
		return DefaultStreamedContent.builder()
			.contentType("image/jpg")
			.name("logo.jpg")
			.stream(() -> FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/images/logo.jpg"))
			.build();
	}
}
```

**Comment by melloware** [comment]
hmmm to me this feels like a Jboss error not so much a PF error?

**Comment by tandraschko** [comment]
A resource request doesnt have a attached View or viewstate, thats by design

**Comment by melloware** [comment]
What is weird is without Jboss here is a reproducer.
[pf-7844.zip](https://github.com/primefaces/primefaces/files/7188017/pf-7844.zip)

It works with Mojarra and MyFaces downloading the file but I see this error in the console...
```
[INFO] Started Jetty Server
[WARNING] handleException /primefaces-test/javax.faces.resource/dynamiccontent.properties.xhtml java.io.IOException: Error in streaming dynamic resource
```

**Comment by tandraschko** [comment]
Weird but my last statement is true
Does Filedownload not use the resource request? Why is there one then?

**Comment by firsthour** [comment]
> It works with Mojarra and MyFaces downloading the file but I see this error in the console...

Did the browser actually offer you the correct file or was it a stack trace html disguised as a .jpg?

I guess I'm confused where to go from here, to be honest.

**Comment by melloware** [comment]
You are right its called `logo.jpg` but the file contains this...

```
html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 java.io.IOException: Error in streaming dynamic resource</title>
</head>
<body><h2>HTTP ERROR 500 java.io.IOException: Error in streaming dynamic resource</h2>
<table>
<tr><th>URI:</th><td>/primefaces-test/javax.faces.resource/dynamiccontent.properties.xhtml</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>java.io.IOException: Error in streaming dynamic resource</td></tr>
<tr><th>SERVLET:</th><td>Faces Servlet</td></tr>
<tr><th>CAUSED BY:</th><td>java.io.IOException: Error in streaming dynamic resource</td></tr>
<tr><th>CAUSED BY:</th><td>javax.el.ELException: Error reading [file] on type [org.primefaces.test.TestView$$OwbNormalScopeProxy0]</td></tr>
<tr><th>CAUSED BY:</th><td>javax.enterprise.context.ContextNotActiveException: WebBeans context with scope type annotation @ViewScoped does not exist within current thread</td></tr>
</table>
<h3>Caused by:</h3><pre>java.io.IOException: Error in streaming dynamic resource
	at org.primefaces.application.resource.StreamedContentHandler.handle(StreamedContentHandler.java:126)
	at org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:98)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:704)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
```

So @tandraschko is correct your scenario should not work.
