### ISSUE TITLE
Error message starting Primefaces webapp in Tomee V8.08 LinkageError Jsf23WidgetVarSearchKeywordResolver

### ISSUE THREAD

**Issue by stuart1975** [primefaces/primefaces#8041]
Hello,
I am trying to migrate  primefaces app V10.0.0 from tomcat V9 to tomee plus V8.08
Starting in webapp tomee plus 8.08 resulted in getting the following error message:

nov 02, 2021 8:28:39 DA TARDE org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class [org.apache.myfaces.webapp.StartupServletContextListener]
**java.lang.LinkageError: loader constraint violation for class org/primefaces/expression/impl/Jsf23WidgetVarSearchKeywordResolver: when selecting overriding method "org.primefaces.expression.impl.Jsf23WidgetVarSearchKeywordResolver.resolve(Ljavax/faces/component/search/SearchKeywordContext;Ljavax/faces/component/UIComponent;Ljava/lang/String;)V"** the class loader (instance of org/apache/tomee/catalina/TomEEWebappClassLoader) of the selected method's type org/primefaces/expression/impl/Jsf23WidgetVarSearchKeywordResolver, and the class loader (instance of java/net/URLClassLoader) for its super type javax/faces/component/search/SearchKeywordResolver have different Class objects for the type javax/faces/component/UIComponent used in the signature
	at org.primefaces.util.Jsf23Helper.addSearchKeywordResolvers(Jsf23Helper.java:37)
	at org.primefaces.webapp.PostConstructApplicationEventListener.processEvent(PostConstructApplicationEventListener.java:55)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:40)
	at org.apache.myfaces.application.ApplicationImpl._traverseListenerList(ApplicationImpl.java:2595)
	at org.apache.myfaces.application.ApplicationImpl.access$000(ApplicationImpl.java:129)
	at org.apache.myfaces.application.ApplicationImpl$SystemListenerEntry.publish(ApplicationImpl.java:2781)
	at org.apache.myfaces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:610)
	at org.apache.myfaces.webapp.AbstractFacesInitializer._dispatchApplicationEvent(AbstractFacesInitializer.java:330)
	at org.apache.myfaces.webapp.AbstractFacesInitializer.initFaces(AbstractFacesInitializer.java:195)
	at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:121)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)

**Comment by tandraschko** [comment]
Can you try a clean project or normal Tomee 8.0.8? Works fine for us

**Comment by tandraschko** [comment]
Im sure its a setup problem, maybe you still have ee jars in your war or something
Please use discord or forum to get help

**Comment by stuart1975** [comment]
After you said a setup problem. I checked for double artificats. In tomee plus myfaces is already included. I don't know why but it is. I have marked myfaces artifact in pom.xml with scope provided and this problem disappeared.

**Comment by tandraschko** [comment]
Because Tomcat != Tomee
