### ISSUE TITLE
Core: UploadedFileCleanerListener.class - Error configuring application listener

### ISSUE THREAD

**Issue by schicho** [primefaces/primefaces#8072]
I tried version 10.0.0 and 11.0.0-RC2

**Describe the defect**

Including the latest Primefaces in my Maven project. Deployment on TomCat 10.0.10 errors with: 

```
11-Nov-2021 18:24:06.998 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [org.primefaces.webapp.UploadedFileCleanerListener]
	java.lang.NoClassDefFoundError: javax/servlet/ServletRequestListener
```

I found releated issues:

https://forum.primefaces.org/viewtopic.php?t=69092

and 

#7976 with #7977 which supposedly fixes the issue. Yet I tried the newest RC with the fix and the same error still occurs. 

**Environment:**
 - PF Version: _10.0.0_ and _11.0.0.RC2_
 - Mojarra 3.0.1
 - TomCat 10.0.10
 - Weld 4.0.2
 - Affected browsers:  _ALL_

**To Reproduce**
1. Simply create a project and add primefaces.jar to the WEB-INF/lib
2. Start tomcat application server
3. web application is not served
4. See SEVERE error in logs

<details>
<summary> Full log </summary>

11-Nov-2021 18:24:05.764 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.10]
11-Nov-2021 18:24:05.775 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/tomcat/apache-tomcat-10.0.10/webapps/primefaces.war]
11-Nov-2021 18:24:06.998 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [org.primefaces.webapp.UploadedFileCleanerListener]
	java.lang.NoClassDefFoundError: javax/servlet/ServletRequestListener
		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
		at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
		at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2516)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:872)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1408)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1252)
		at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:539)
		at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:520)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
		at org.jboss.weld.environment.tomcat.ForwardingInstanceManager.newInstance(ForwardingInstanceManager.java:26)
		at org.jboss.weld.environment.tomcat.WeldForwardingInstanceManager.newInstance(WeldForwardingInstanceManager.java:71)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4640)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1027)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2001)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:828)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:478)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1708)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:320)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:886)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:567)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
	Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletRequestListener
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1444)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1252)
		... 53 more
11-Nov-2021 18:24:06.999 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Skipped installing application listeners due to previous error(s)
11-Nov-2021 18:24:06.999 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
11-Nov-2021 18:24:07.010 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/sep-einfuehrung-schicho-1.0-SNAPSHOT] startup failed due to previous errors

</details>

**Comment by tandraschko** [comment]
Tomcat 10 is jakarta.servlet? Then you need the jakarta qualifier

**Comment by tandraschko** [comment]
```
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>11.0.0-RC2</version>
    <classifier>jakarta</classifier>
</dependency>
```

**Comment by schicho** [comment]
Excuse my ignorance, I am quite new to this technology.

I must have completely overlooked this and started following the wrong route to find the solution. I didn't know this additional tag existed.

Thank you for your help.
