### ISSUE TITLE
AutoComplete: add support for generic collections, not just List

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#8129]
**Describe the defect**
Using `p:autoComplete` with multiple=true and value="{bean.collection}"
throws the following error:

```
10:00:23,212 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-1) java.lang.ClassCastException: class java.util.LinkedHashSet cannot be cast to class java.util.List (java.util.LinkedHashSet and java.util.List are in module java.base of loader 'bootstrap')
	at deployment.ex.war//org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeMultipleMarkup(AutoCompleteRenderer.java:363)
	at deployment.ex.war//org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeMarkup(AutoCompleteRenderer.java:149)
	at deployment.ex.war//org.primefaces.component.autocomplete.AutoCompleteRenderer.encodeEnd(AutoCompleteRenderer.java:129)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
```

**Environment:**
 - PF Version: _11.0.0-RC2_
 - JSF + version: _e.g. Mojarra 2.2.20
 - Affected browsers: _ALL_

**To Reproduce**
1. Use `p:autoComplete` with `multiple=true` and `value="{bean.collection}"` (and use a collection type of `Set`)

**Expected behavior**
The `p:autoComplete` might be used with any collection type (and should not be limited to `List`). At least `Set` should be supported.

**Comment by tandraschko** [comment]
enhancement as it was never supported

**Comment by melloware** [comment]
@nimo23 did you want to work on a PR for this one?

**Comment by nimo23** [comment]
I think, it's not really required. We can easily turn a set to a list manually  (e.g. `new ArrayList<>(mySet);`) and use this list for `p:autoComplete`.
