### ISSUE TITLE
Submenu: exception with comments

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#8206]
JSF comments within `p:menuitem` like shown below:
```html
<p:submenu label="xxx">
    <p:menuitem .../>
    <!--
        COMMENTING OUT SOME MENUITEM
    -->
</p:submenu>
```
gives us the following exception:
```
12:19:12,405 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-63) Error Rendering View[/user/group.xhtml]: java.lang.ClassCastException: com.sun.faces.facelets.compiler.UIInstructions cannot be cast to org.primefaces.model.menu.MenuElement
	at org.primefaces.component.menu.MenuRenderer.encodeElements(MenuRenderer.java:97)
	at org.primefaces.component.menu.MenuRenderer.encodeSubmenu(MenuRenderer.java:165)
	at org.primefaces.component.menu.MenuRenderer.encodeElements(MenuRenderer.java:119)
	at org.primefaces.component.menu.MenuRenderer.encodeMarkup(MenuRenderer.java:86)
	at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:42)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:286)
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:152)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:155)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
```

This should not happen I guess. A simple `instanceof` check should fix this.

**Environment:**
 - PrimeFaces 10.0.7
 - JSF + version: Mojarra 2.3.14.SP04 (WildFly)

**Comment by tandraschko** [comment]
Please try 11.0

**Comment by Rapster** [comment]
See also https://github.com/primefaces/primefaces/issues/2143
