### ISSUE TITLE
Tree: better handle null children

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#8210]
While trying out to migrate from 10 to 11, we stumbled upon the following NPE:
```
java.lang.NullPointerException
	at org.primefaces.component.api.UITree.visitNode(UITree.java:996)
	at org.primefaces.component.api.UITree.visitNodes(UITree.java:971)
	at org.primefaces.component.api.UITree.visitTree(UITree.java:870)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:908)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:150)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at org.primefaces.component.resetinput.ResetInputActionListener.processAction(ResetInputActionListener.java:82)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:72)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:490)
	at javax.faces.component.UICommand.broadcast(UICommand.java:211)
	at javax.faces.component.UIData.broadcast(UIData.java:1127)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:847)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1396)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:58)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
```
Don't know exactly why this is happening, but this did not occur on the 10.0.x series.

**Comment by tandraschko** [comment]
we need a reproducer as stated in the issue template, otherwise we cant fix.

**Comment by fcorneli** [comment]
Pinpointing this one will not be easy. It happens somewhere within: p:dialog -> custom JSF composite -> p:tabView -> p:tab -> p:scrollPanel -> p:tree
Fun fun fun...

**Comment by tandraschko** [comment]
You can atleast debug whats null

**Comment by christophs78** [comment]
https://github.com/primefaces/primefaces/blob/11.0.0/primefaces/src/main/java/org/primefaces/component/api/UITree.java#L996
getChildren() null?

@fcorneli can you please put a breakpoint into this line and validate your usecase?

**Comment by tandraschko** [comment]
i added some checks for null children
if the issue persist, provide a reproducer or we will just close it as invalid

**Comment by TEAMS-HRM** [comment]
I got the same error after upgraded to PF 11.0 , I couldn't reproduce it in simple application but on debug I found  the function root.get() in line 971 return null.
So I have to return to PF 10.0

**Comment by jepsar** [comment]
The milestone for this issue is 12.

**Comment by fcorneli** [comment]
The way we solved it in our project is to simply always provide a `TreeNode` value, even if it's empty.

**Comment by tandraschko** [comment]
this should fix it

**Comment by brivalin** [comment]
I'm facing this issue in my project, and would like to know if the commit will be added in Elite patches ?

**Comment by tandraschko** [comment]
Please read: https://github.com/primefaces/primefaces/blob/master/README.md#community--elite--pro
