### ISSUE TITLE
DataExporter: Updating apache.poi to 5.1.0 breaks xls export

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8268]
Updating apache.poi from 5.0.0 to 5.1.0 breaks xls export.

Following error is thrown:
```
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<clinit>(SXSSFWorkbook.java:109)
	at org.primefaces.component.datatable.export.DataTableExcelXStreamExporter.createWorkBook(DataTableExcelXStreamExporter.java:48)
	at org.primefaces.component.datatable.export.DataTableExcelExporter.preExport(DataTableExcelExporter.java:66)
	at org.primefaces.component.datatable.export.DataTableExporter.export(DataTableExporter.java:206)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:159)
```

Is this a PF or apach.doi issue?

reproducer: [p-dataexporter.zip](https://github.com/primefaces/primefaces/files/7854595/p-dataexporter.zip)

**Comment by tandraschko** [comment]
https://poi.apache.org/components/logging.html

poi requires log4j in 5.1

**Comment by melloware** [comment]
No its your code.  You CAN NOT exclude this:

```xml
          <exclusion>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
          </exclusion>
```

We do in Primefaces Core because we only need POI to compile but if you want it to run you need that dependency.

**Comment by melloware** [comment]
See: https://github.com/primefaces/primefaces/issues/8167

**Comment by tuerker** [comment]
many thanks for the quick response!
