### ISSUE TITLE
TreeTable: Swapping nodes with Collections.swap causes NPE

### ISSUE THREAD

**Issue by newk5** [primefaces/primefaces#8330]
**Describe the defect**
If you swap items inside TreeNode#getChildren with Collections.swap, it causes an NPE with mojarra when the update="treeID" is triggered. With MyFaces NPE is only  thrown with quarkus for some reason, with jetty it doesn't throw an NPE but it doesn't seem to work either. @FlipWarthog has noticed that this is because TreeNodeChildren#.set clears the parent node  for some reason

```
java.lang.NullPointerException: Cannot invoke "org.primefaces.model.TreeNode.getRowKey()" because the return value of "org.primefaces.model.TreeNode.getParent()" is null
    at org.primefaces.component.treetable.TreeTableRenderer.encodeNode(TreeTableRenderer.java:528)
    at org.primefaces.component.treetable.TreeTableRenderer.encodeNodeChildren(TreeTableRenderer.java:849)
    at org.primefaces.component.treetable.TreeTableRenderer.encodeNodeChildren(TreeTableRenderer.java:836)
    at org.primefaces.component.treetable.TreeTableRenderer.encodeTbody(TreeTableRenderer.java:514)
    at org.primefaces.component.treetable.TreeTableRenderer.encodeRegularMarkup(TreeTableRenderer.java:386)
    at org.primefaces.component.treetable.TreeTableRenderer.encodeMarkup(TreeTableRenderer.java:262)
    at org.primefaces.component.treetable.TreeTableRenderer.render(TreeTableRenderer.java:145)
    at org.primefaces.component.treetable.TreeTableRenderer.encodeEnd(TreeTableRenderer.java:138)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:649)
    at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:530)
```

**Reproducer**
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/7935585/primefaces-test.zip)

**Environment:**
 - PF Version: _11.0_
 - JSF + version: all profiles on the primefaces-test project
 - Affected browsers: _ALL_

**To Reproduce**
1. Run with mojarra
2. Click on 'Move up' button on the last row

**Comment by FlipWarthog** [comment]
Adding some additional info here based on the discussion in the PrimeLand Discord. The specific code causing the issue has been (mostly) unchanged since it was added [back in 2013](https://github.com/primefaces/primefaces/commit/ae6ab661569b37cedac1fe3280b2ddd8be79a428).

A workaround was found by using `TreeNodeChildren.setSibling` rather than `TreeNodeChildren.set` (which wipes out the parent value). See [this commit](https://github.com/primefaces/primefaces/commit/783868cf7895d06e751732439e6a866fd2889794).

Looking at these methods, they are practically identical with the exception of the parent field being cleared. The main problem is `set` is defined in `List` and therefore leveraged in the Collections util, whereas `setSibiling` is specific to `TreeNodeList`.

**Comment by melloware** [comment]
So do we have a solution to this issue?

**Comment by FlipWarthog** [comment]
I'm not 100% sure and haven't looked much into it since my original analysis, since there's a workaround.

An option would be to remove `setSibling` entirely and modify `set` to do the exact same thing (e.g. remove the call the null out the parent). That would definitely fix this issue but I'm not sure what kind of downstream impacts it might have, because I can't figure out why they're different in the first place.

That being said, I think we've got a good handful of integration tests around Tree so I can put in a draft PR and see what it does.

**Comment by FlipWarthog** [comment]
Okay, PR submitted and the build passed. I also retested with the reproducer attached to this issue and it works as well.

**Comment by melloware** [comment]
Yep let's switch it out of draft.  The integration tests pass and we know it fixes this use case
