### ISSUE TITLE
DataTable: JPALazyDataModel should ignore globalFilter

### ISSUE THREAD

**Issue by ElliotBu** [primefaces/primefaces#8507]
**Describe the defect**
I have a DataTable which is using the OOTB Functionality of JpaLazyDataModel and dynamic columns. The Datatable uses Default Filtering and Column Filtering. The load of the page is with error but as soon as I start using the column filtering I receive the Exception below. of course I don't have a property "globalFilter" in my Entity and even if I add the property "globalFilter" as @Transient to my Entity it ends up that the column cannot be found in the table exception. 

![image](https://user-images.githubusercontent.com/100536591/156267939-8662a034-6773-427f-ad9a-fac4a2b5d276.png)

```text
java.lang.IllegalArgumentException: Cannot find field globalFilter in de.dwh.model.table.InternalContact
	at org.primefaces.util.LangUtils.getField(LangUtils.java:548)
	at org.primefaces.util.LangUtils.getFieldRecursive(LangUtils.java:520)
	at org.primefaces.model.JpaLazyDataModel.applyFilters(JpaLazyDataModel.java:153)
	at org.primefaces.model.JpaLazyDataModel.count(JpaLazyDataModel.java:111)
	at org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:467)
	at org.primefaces.component.datatable.feature.FilterFeature.encode(FilterFeature.java:126)
	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:80)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:615)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:701)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:319)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:228)
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1101)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:155)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1540)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:297)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:81)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.primefaces.poseidon.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at de.fw.core.filter.NoCacheFilter.doFilter(NoCacheFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:215)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:119)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:611)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:550)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:75)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:114)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:199)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:439)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
```

**Reproducer**
there is no chance to provide an reproducer, because the Database is located in a VPN and the issue only occurs if the JPALazyDataModel is feeding the table.

**Environment:**
 - PF Version: 11.0.1
 - JSF 2.3 GlassFish 5.1
 - Firefox and Chrome

**Expected behavior**
Filtering the data in regards to entered filter

**Example XHTML**
```html
<h:form id="frmTest">
    <p:dataTable 
        id="dtaInternalContact"  
        value="#{iNCOController.items}" 
        var="row"
        widgetVar="widInternalContact" 
        selectionMode="multiple"
        liveScroll="false"
        scrollable="true"
        scrollHeight="630"
        selection="#{iNCOController.selectedItems}"
        filteredValue="#{iNCOController.filteredItems}"
        sortBy="#{objectController.getDefaultSortMeta('dtaInternalContact')}"
        sortMode="multiple"
        allowUnsorting="true" 
        paginator="true" 
        paginatorPosition="bottom"
        paginatorAlwaysVisible="true"
        paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
        currentPageReportTemplate="{totalRecords} record(s)"
        rows="100"
        rowsPerPageTemplate="100,200,300,400,500"  
        rowKey="#{row.internalContactPk}"
        resizableColumns="true" 
        liveResize="true" 
        draggableColumns="true"
        reflow="true"
        showGridlines="true"
        rowStyleClass="#{row.activeFlag ? '' : 'row_inactive'}"
        styleClass="ui-datatable-striped ui-datatable-sm">
					
        <f:facet name="header">
            <div class="table-header">
                <span class="table-header-pagename">#{iNCOController.viewCaption}</span>
                <span class="ui-input-icon-left filter-container">
                    <i class="pi pi-search"></i>
                    <p:inputText id="globalFilter" onkeyup="PF('widInternalContact').filter()" placeholder="Search"/>
                </span>
            </div>
        </f:facet>

        <p:ajax event="rowSelect"    update=":frmInternalContact:tbToolbar" />
        <p:ajax event="rowUnselect"  update=":frmInternalContact:tbToolbar" />
        <p:ajax event="rowDblselect" oncomplete="editInternalContact()" />

        <p:columns value="#{iNCOController.mainTableColumns}"
                           var="column" 
                           headerText="#{column.header}"
                           field="#{column.property}"
                           styleClass="#{column.adjust}"
                           style="width:#{column.width}" 
                           visible="#{column.visible}" 
                           filterable="#{column.filterable}"
                           filterMatchMode="#{column.type eq 'boolean' or column.type eq 'deleted' or column.type eq 'state' ? 'equals' : 'contains'}"
                           sortable="#{column.sortable}">
            <f:facet name="filter">
                <p:selectOneMenu onchange="PF('widInternalContact').filter()" rendered="#{column.type eq 'boolean'}">
                    <f:converter converterId="javax.faces.Boolean" />
                    <f:selectItem itemLabel="All" itemValue="" />
                    <f:selectItem itemLabel="True" itemValue="true" />
                    <f:selectItem itemLabel="False" itemValue="false" />
                    </p:selectOneMenu>
                <p:selectOneMenu onchange="PF('widInternalContact').filter()" rendered="#{column.type eq 'state'}">
                    <f:converter converterId="javax.faces.Boolean" />
                    <f:selectItem itemLabel="All" itemValue="" />
                    <f:selectItem itemLabel="Contact" itemValue="false" />
                    <f:selectItem itemLabel="List" itemValue="true" />
                </p:selectOneMenu>		
            </f:facet>
            <h:outputText  rendered="#{column.type eq 'string'}"   value="#{row[column.property]}" />
            <h:outputText  rendered="#{column.type eq 'datetime'}" value="#{row[column.property]}"><f:convertDateTime locale="#{parameterSessionController.localeCode}" type="localDateTime" dateStyle="medium" timeStyle="short"/></h:outputText>
            <p:outputLabel rendered="#{column.type eq 'boolean' and row[column.property]}"><i class="pi pi-check-circle" /></p:outputLabel>
            <p:outputLabel rendered="#{column.type eq 'state' and row[column.property] eq true}"><i class="pi pi-list" /></p:outputLabel>
            <p:outputLabel rendered="#{column.type eq 'state' and row[column.property] eq false}"><i class="pi pi-user" /></p:outputLabel>
        </p:columns>
    </p:dataTable>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class INCOController extends AbstractController implements Serializable {
    private static final long serialVersionUID = 1L;
    
    @PersistenceContext(unitName = "dwh")
    EntityManager em;
    
    @Resource
    UserTransaction ut;
    
    private JpaLazyDataModel<InternalContact>    items;
    private List<InternalContact>                filteredItems;
    private List<InternalContact>                selectedItems;
    private InternalContact                      selectedItem;
    private List<ColumnModel>                    mainTableColumns = new ArrayList<ColumnModel>();
    private Boolean                              showDeleted = false;

    public INCOController () {
    }
    
    @PostConstruct
    public void InitController () {
        sessionUser = param.getSessionUser();
        mainTableColumns = ControllerUtils.getColumnModel(mainTableColumns, getControllerName(), "dtaInternalContact");
        items = new JpaLazyDataModel<InternalContact>(InternalContact.class, () -> em, "internalContactPk");
    }
}
```

**Comment by tandraschko** [comment]
will be ignored now
globalFilter must be implemented by the user, like mentioned in the docs: https://primefaces.github.io/primefaces/12_0_0/#/components/datatable?id=lazy-loading

**Comment by ElliotBu** [comment]
> will be ignored now globalFilter must be implemented by the user, like mentioned in the docs: https://primefaces.github.io/primefaces/12_0_0/#/components/datatable?id=lazy-loading

I was reading this document, but it doesn't solve the issue. the function applyGlobalFilters is implemented in your class of JpaLazyDataModel and of course it is empty, because the user can override it. If I'm not overriding the function the class is ending in an exception that the globalFilter property is not in my entity and I will end up in the same exception if I'm overiding the function applyGlobaFilter because the function is not manipulating the JPQL Statement the CriteriaBuilder is creating.

Please advise of how to proceed.?

Thank you and Regards
Christian

**Comment by tandraschko** [comment]
my first commit solves your issue
the second is to allow users to access FilterMeta in applyGlobalFilters

**Comment by ElliotBu** [comment]
Ok, found your change in GitHub and added em to my overriding class and works.

Thank you
Christian
