### ISSUE TITLE
addCallbackParam is not working with pojos

### ISSUE THREAD

**Issue by ybendek** [primefaces/primefaces#871]
RequestContext.getCurrentInstance().addCallbackParam() works perfect with PF5.2 but now in PF5.3 when you try to use POJO Bean as a parameter, an exception throws :

Grave: java.lang.ClassCastException: com.unitas.view.dvo.reports.GraphHistoryContentDVO cannot be cast to org.primefaces.json.JSONObject
    at org.primefaces.context.PrimePartialResponseWriter.encodeCallbackParams(PrimePartialResponseWriter.java:93)
    at org.primefaces.context.PrimePartialResponseWriter.endDocument(PrimePartialResponseWriter.java:191)
    at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:618)
    at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:415)
    at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:60)
    at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:516)
    at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
    at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
    at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
    at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
    at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:343)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:279)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
    at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
    at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
    at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
    at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
    at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
    at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
    at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
    at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
    at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
    at java.lang.Thread.run(Thread.java:745)

Grave:  at org.primefaces.context.PrimePartialResponseWriter.encodeCallbackParams(PrimePartialResponseWriter.java:93)
Grave:  at org.primefaces.context.PrimePartialResponseWriter.endDocument(PrimePartialResponseWriter.java:191)
Grave:  at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:618)
Grave:  at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:415)
Grave:  at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:60)
Grave:  at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:516)
Grave:  at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
Grave:  at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
Grave:  at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
Grave:  at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
Grave:  at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
Grave:  at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
Grave:  at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
Grave:  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:343)
Grave:  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
Grave:  at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
Grave:  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
Grave:  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
Grave:  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:279)
Grave:  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
Grave:  at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
Grave:  at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
Grave:  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
Grave:  at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
Grave:  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
Grave:  at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
Grave:  at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
Grave:  at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
Grave:  at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
Grave:  at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
Grave:  at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
Grave:  at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
Grave:  at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
Grave:  at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
Grave:  at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
Grave:  at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
Grave:  at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
Grave:  at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
Grave:  at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
Grave:  at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
Grave:  at java.lang.Thread.run(Thread.java:745)
Grave: com.unitas.view.dvo.reports.GraphHistoryContentDVO cannot be cast to org.primefaces.json.JSONObject
java.lang.ClassCastException: com.unitas.view.dvo.reports.GraphHistoryContentDVO cannot be cast to org.primefaces.json.JSONObject
    at org.primefaces.context.PrimePartialResponseWriter.encodeCallbackParams(PrimePartialResponseWriter.java:93)
    at org.primefaces.context.PrimePartialResponseWriter.endDocument(PrimePartialResponseWriter.java:191)
    at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:618)
    at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:415)
    at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:60)
    at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:516)
    at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
    at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
    at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
    at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
    at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:343)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:279)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
    at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
    at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
    at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
    at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
    at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
    at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
    at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
    at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
    at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
    at java.lang.Thread.run(Thread.java:745)

**Comment by tandraschko** [comment]
Fixed in trunk, please give it a try.

**Comment by ybendek** [comment]
thanks... how is supposed to be tested?  I'm using pf with maven repositories and only 5.3 is available, could give me some guidelines?

**Comment by tandraschko** [comment]
Search/google how to build PrimeFaces from source.
