### ISSUE TITLE
SearchExpressions: Failure to evaluate RowIndex

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8905]
### Describe the bug

Without an `@` in the search expression this evaluates correctly inside a DataTable column

```xml
<!-- 1. case: update using full path without search expression features -->
<p:commandButton value="Form Id" update="frmTest:myTable:#{rowIndex}:someBlockInAnotherColumn" />
```

However using `@form` for the same expression fails...
```xml
<!-- 2. case: update using search expression features with @form-->
<p:commandButton value="Form Id" update="@form:myTable:#{rowIndex}:someBlockInAnotherColumn" />
```

**StackTrace:**
```
javax.faces.FacesException: Cannot find component for subexpression "0" from component with id "frmTest:myTable" in full expression "@form:myTable:0:someBlockInAnotherColumn" referenced from "frmTest:myTable:0:j_idt11".
	at org.primefaces.expression.SearchExpressionFacade.resolveClientIdsByExpressionChain(SearchExpressionFacade.java:694)
	at org.primefaces.expression.SearchExpressionFacade.resolveClientIds(SearchExpressionFacade.java:206)
	at org.primefaces.util.AjaxRequestBuilder.addExpressions(AjaxRequestBuilder.java:164)
	at org.primefaces.util.AjaxRequestBuilder.update(AjaxRequestBuilder.java:157)
	at org.primefaces.renderkit.CoreRenderer.preConfiguredAjaxRequestBuilder(CoreRenderer.java:455)
	at org.primefaces.renderkit.CoreRenderer.buildAjaxRequest(CoreRenderer.java:476)
	at org.primefaces.renderkit.CoreRenderer.buildAjaxRequest(CoreRenderer.java:472)
	at org.primefaces.component.commandbutton.CommandButtonRenderer.buildRequest(CommandButtonRenderer.java:148)
	at org.primefaces.component.commandbutton.CommandButtonRenderer.encodeMarkup(CommandButtonRenderer.java:78)
	at org.primefaces.component.commandbutton.CommandButtonRenderer.encodeEnd(CommandButtonRenderer.java:63)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at org.primefaces.component.column.Column.renderChildren(Column.java:90)
	at org.primefaces.component.datatable.DataTableRenderer.encodeCell(DataTableRenderer.java:1356)
	at org.primefaces.component.datatable.DataTableRenderer.encodeRow(DataTableRenderer.java:1272)
	at org.primefaces.component.datatable.DataTableRenderer.encodeRows(DataTableRenderer.java:1179)
	at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:1119)
	at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:1072)
	at org.primefaces.component.datatable.DataTableRenderer.encodeRegularTable(DataTableRenderer.java:401)
	at org.primefaces.component.datatable.DataTableRenderer.encodeMarkup(DataTableRenderer.java:331)
	at org.primefaces.component.datatable.DataTableRenderer.render(DataTableRenderer.java:106)
	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:97)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
```

### Reproducer

[search-expressions.zip](https://github.com/primefaces/primefaces/files/8933803/search-expressions.zip)

### Expected behavior

The search expression should work.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

ALL

### JSF implementation

All

### JSF version

2.3

### Browser(s)

ALL

**Comment by tandraschko** [comment]
i will mark this as enhancement as this was not supported by JSF 2.3 either
we will need to fix this first in MF / Mojarra
then we should finally switch to SearchExpressionAPI if JSF 2.3+

**Comment by tandraschko** [comment]
quite hard to implement - also need to do it in 3 places
it would be great if someone could try to provide PRs or sponsor it

**Comment by melloware** [comment]
I looked at this and I came to the same conclusion it's not easy to implement.  Not sure it's worth the effort when there are other ways to do the same selection.

**Comment by melloware** [comment]
Going to close this for now.
