### ISSUE TITLE
Datatable. Error: "is configured for single selection while multiple rows have been selected"

### ISSUE THREAD

**Issue by trubnikow** [primefaces/primefaces#8932]
### Describe the bug

If rowkey has comma in value then expires this error by select:
Caused by: java.lang.IllegalArgumentException: DataTable 'xxx' is configured for single selection while multiple rows have been selected
	at org.primefaces.component.datatable.feature.SelectionFeature.decodeSingleSelection(SelectionFeature.java:127)
	at org.primefaces.component.datatable.feature.SelectionFeature.decodeSelection(SelectionFeature.java:87)
	at org.primefaces.component.datatable.feature.SelectionFeature.decode(SelectionFeature.java:70)
	at org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:74)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:832)

This work in PF 8.x and don't work in PF 10+
Cause is:
    _@Override
    public void decode(FacesContext context, DataTable table) {
        String clientId = table.getClientId(context);
        Map<String, String> params = context.getExternalContext().getRequestParameterMap();
        Object originalValue = table.getValue();
        boolean isFiltered = table.isFilteringCurrentlyActive();

        String selection = params.get(clientId + "_selection");
        Set<String> rowKeys = Collections.emptySet();

        **if (LangUtils.isNotBlank(selection)) {
            rowKeys = LangUtils.newLinkedHashSet(selection.split(","));
        }**_

mfg

### PrimeFaces version

11.0.0

**Comment by tandraschko** [comment]
Please provide a forked primefaces-test reproducer

**Comment by melloware** [comment]
Related/Duplicate: https://github.com/primefaces/primefaces/issues/5946

Related/Duplicate: https://github.com/primefaces/primefaces/issues/7105

**Comment by tandraschko** [comment]
yeah
in theory it should work with single selection but our decision is that rowKey must not contain a comma
so actually wont fix

do we have a fat hint somewhere about that in the docs?

**Comment by melloware** [comment]
No but i will add one: https://primefaces.github.io/primefaces/11_0_0/#/components/datatable?id=rowkey

**Comment by tandraschko** [comment]
+1
and then lets just close it here

**Comment by trubnikow** [comment]
Thanks for Info.
Adding in Doku is a good idea
