### ISSUE TITLE
Error message starting Primefaces webapp in Payara 5 (with useBundledJsf property) LinkageError Jsf23WidgetVarSearchKeywordResolver Component: Title

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#9080]
Hey everyone,
if Payara 5 is started with the setting "useBundledJsf" so that the JSF version 2.2.20 in the deployment bundle can be loaded, the following exception occurs during deployment:

`  Critical error during deployment: 
java.lang.LinkageError: loader constraint violation: when resolving overridden method "org.primefaces.expression.impl.Jsf23WidgetVarSearchKeywordResolver.resolve(Ljavax/faces/component/search/SearchKeywordContext;Ljavax/faces/component/UIComponent;Ljava/lang/String;)V" the class loader (instance of org/glassfish/web/loader/WebappClassLoader) of the current class, org/primefaces/expression/impl/Jsf23WidgetVarSearchKeywordResolver, and its superclass loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoader), have different Class objects for the type javax/faces/component/UIComponent used in the signature
	at org.primefaces.util.Jsf23Helper.addSearchKeywordResolvers(Jsf23Helper.java:29)
	at org.primefaces.webapp.PostConstructApplicationEventListener.processEvent(PostConstructApplicationEventListener.java:47)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:108)
	at com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2169)
	at com.sun.faces.application.ApplicationImpl.invokeListenersFor(ApplicationImpl.java:2142)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:294)
	at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:739)
	at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:739)
	at com.sun.faces.config.ConfigManager.publishPostConfigEvent(ConfigManager.java:704)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:270)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5175)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:681)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5753)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:619)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:958)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:941)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:694)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1871)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1623)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)`

_payara-web.xml:_
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE payara-web-app PUBLIC "-//Payara.fish//DTD Payara Server 4 Servlet 3.0//EN" "https://docs.payara.fish/schemas/payara-web-app_4.dtd">
<payara-web-app error-url="">
    <class-loader delegate="false"/>
    <property name="useBundledJsf" value="true" />
</payara-web-app>
```

Is it a bug in the Payara server, or does Primefaces read wrong parameters?

Payara itself also specifies the correct Mojarra version when booting up the context:
`[jsf.config.listener.version] [javax.enterprise.resource.webcontainer.jsf.config] Mojarra 2.2.20`

Steven

- Payara 5
- JavaEE 8
- Primefaces 11
- Windows 10
- javax.faces 2.2.20

**Comment by tandraschko** [comment]
Primefaces reads the JSF version by lookup specific classes, which are only available in this JSF version 
In think 2.3 API is still available via classloader in your case
We could change the meachism to detect it but thats quite hard and there is no official API to receive the current deployed JSF version
also it just doesnt make sense to manually put JSF 2.2 in a 2.3 server.
So its a wontfix from our side

Payara should in theory hide all 2.3 classes in the classes then if you set useBundledJsf
