### ISSUE TITLE
InputNumber: decimalPlaces not defaulting correctly on numeric types with null value

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#9093]
### Describe the bug

If the value is `null` the type of the bound value should be checked

https://github.com/primefaces/primefaces/blob/fcced6df36579bc34f09b03b683f31fdee8f0ce3/primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java#L393-L395

### Reproducer

Bind to an `Integer` type of which the value is `null`

### Expected behavior

`decimalPlaces` should be 0 instead of 2, because the value is of type `Integer` although the value is `null`.

### PrimeFaces edition

Community

### PrimeFaces version

12

**Comment by melloware** [comment]
This has been discussed in the past with @tuerker see conversation: https://github.com/primefaces/primefaces/issues/6590#issuecomment-738021193

**Comment by melloware** [comment]
Let me know if you figure this out.  I couldn't figure it out since NULL has no type.

**Comment by jepsar** [comment]
I'll take care of it. Should not be too hard. I just haven't found the time yet.

**Comment by MatthiasScherrerFGCZ** [comment]
@jepsar   
The current build gives an NPE in our application as the type seems to resolve to null.

```
java.lang.NullPointerException
	at org.primefaces.component.inputnumber.InputNumberRenderer.isIntegral(InputNumberRenderer.java:409)
	at org.primefaces.component.inputnumber.InputNumberRenderer.encodeInput(InputNumberRenderer.java:189)
	at org.primefaces.component.inputnumber.InputNumberRenderer.encodeMarkup(InputNumberRenderer.java:143)
	at org.primefaces.component.inputnumber.InputNumberRenderer.encodeEnd(InputNumberRenderer.java:122)

```

By changing the following lines it works:
```
Class<?> type = valueExpression.getType(context.getELContext());
        return type.isAssignableFrom(Long.class)
                || type.isAssignableFrom(Integer.class)
                || type.isAssignableFrom(Short.class)
                || type.isAssignableFrom(BigInteger.class)
                || type.isAssignableFrom(Byte.class);

to

Class<?> type = valueExpression.getType(context.getELContext());
return type != null && (type.isAssignableFrom(Long.class)
            || type.isAssignableFrom(Integer.class)
            || type.isAssignableFrom(Short.class)
            || type.isAssignableFrom(BigInteger.class)
            || type.isAssignableFrom(Byte.class));
```

**Comment by tandraschko** [comment]
fixed it, please check

**Comment by MatthiasScherrerFGCZ** [comment]
@tandraschko   
Thanks. It fixed the problem.

**Comment by fcorneli** [comment]
I'm afraid that the fix is not sufficient to cover all cases. On some `null` values, even the type cannot be inferred. For example `value="#{cc.attrs.value.blablabla.whatever.woopsy}"`. Here `valueExpression.getType(...)` cannot go _deep_ if `blablabla` yields already a `null` and hence it will explode with a `PropertyNotFoundException`. The following patch fixes this issue.
```patch
diff --git a/primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java b/primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
index 3854ae3a6..fd046b70f 100644
--- a/primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
+++ b/primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
@@ -26,6 +26,7 @@ package org.primefaces.component.inputnumber;
 import java.io.IOException;
 import java.math.BigDecimal;
 import java.math.BigInteger;
+import javax.el.PropertyNotFoundException;
 
 import javax.el.ValueExpression;
 import javax.faces.FacesException;
@@ -407,7 +408,13 @@ public class InputNumberRenderer extends InputRenderer {
             return false;
         }
 
-        Class<?> type = valueExpression.getType(context.getELContext());
+        Class<?> type;
+        try {
+            type = valueExpression.getType(context.getELContext());
+        }
+        catch (PropertyNotFoundException e) {
+            type = null;
+        }
         if (type == null) {
             return false;
         }
```

**Comment by tandraschko** [comment]
please try again ;)

**Comment by fcorneli** [comment]
@tandraschko works as expected, thanks.
