### ISSUE TITLE
TreeTableExporter: `var` exposes different value during exporting between `selectionOnly` and others

### ISSUE THREAD

**Issue by maruTA-bis5** [primefaces/primefaces#9310]
### Describe the bug

TreeTableExporter exposes `var` variable during exporting, but different behavior when `selectionOnly="true"`.

|export mode|`var` value|
|---|---|
|Standard (`pageOnly="false" selectionOnly="false"`)|`T`|
|Page Only|`T`|
|Selection Only|`TreeNode<T>`|

### Reproducer

1. Clone https://github.com/maruTA-bis5/primefaces.git and checkout `treetable-exposed-var` branch
2. Run showcase following `Run from sources` steps in primefaces-showcase/README.md
3. Go to http://localhost:8080/showcase/ui/data/dataexporter/treetable.xhtml
4. Select one or more rows
5. Click any of `Selection Only` export button
6. This exception occurred
```
javax.el.PropertyNotFoundException: Property [name] not found on type [org.primefaces.model.DefaultTreeNode]
        at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:257)
        at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:209)
        at javax.el.BeanELResolver.property(BeanELResolver.java:330)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:89)
        at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
        at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
        at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:93)
        at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:356)
        at javax.faces.component.UIOutput.getValue(UIOutput.java:67)
        at org.primefaces.component.export.Exporter.exportValue(Exporter.java:91)
        at org.primefaces.component.export.TableExporter.exportColumn(TableExporter.java:63)
        at org.primefaces.component.treetable.export.TreeTableExcelExporter.addColumnValue(TreeTableExcelExporter.java:214)
        at org.primefaces.component.treetable.export.TreeTableExcelExporter.exportCells(TreeTableExcelExporter.java:114)
        at org.primefaces.component.treetable.export.TreeTableExporter.exportRow(TreeTableExporter.java:146)
        at org.primefaces.component.treetable.export.TreeTableExporter.exportSelectionOnly(TreeTableExporter.java:168)
        at org.primefaces.component.treetable.export.TreeTableExcelExporter.exportTable(TreeTableExcelExporter.java:339)
        at org.primefaces.component.treetable.export.TreeTableExcelExporter.doExport(TreeTableExcelExporter.java:82)
        at org.primefaces.component.treetable.export.TreeTableExporter$ExportVisitCallback.visit(TreeTableExporter.java:235)
        at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
        at org.primefaces.component.api.UITree.visitTree(UITree.java:855)
        at javax.faces.component.UIForm.visitTree(UIForm.java:357)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
        at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
        at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
        at org.primefaces.component.treetable.export.TreeTableExporter$ExportVisitCallback.export(TreeTableExporter.java:251)
        at org.primefaces.component.treetable.export.TreeTableExporter.export(TreeTableExporter.java:203)
        at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:171)
```

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0, 12.0.0, master(c18baa3ed00e8c964fddc88743daae4ca1bb5868)

### Theme

Saga

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

Temurin-11.0.12+7

**Comment by melloware** [comment]
Thanks for the report.

**Comment by melloware** [comment]
Reproducer was a big help!
