### ISSUE TITLE
DataTable: JpaLazyDataModel ConverterException for numeric columns when filtering by non-numeric

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#9320]
### Describe the bug

Numeric JPA columns (Long, BigDecimal, etc) cause `JpaLazyDataModel` to throw a `ConverterException` if non-numeric values are add to the filters for those columns.

### Reproducer

https://github.com/FlipWarthog/primefaces-test/tree/hibernate

Running this reproducer using `mvn clean jetty:run -Pmojarra23`, open the test page and filter either "Number Col" or "Decimal Col" with "abc" to get the following result:

```
SEVERE: javax.faces.convert.ConverterException: frmTest:tblJpa: 'abc' must be a number consisting of one or more digits.
        at javax.faces.convert.LongConverter.getAsObject(LongConverter.java:95)
        at org.primefaces.model.JpaLazyDataModel.convertToType(JpaLazyDataModel.java:326)
        at org.primefaces.model.JpaLazyDataModel.applyFilters(JpaLazyDataModel.java:163)
        at org.primefaces.model.JpaLazyDataModel.count(JpaLazyDataModel.java:120)
        at org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:509)
        at org.primefaces.component.datatable.feature.FilterFeature.encode(FilterFeature.java:135)
        at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:85)
```

```
SEVERE: javax.faces.convert.ConverterException: frmTest:tblJpa: 'abc' must be a signed decimal number.
        at javax.faces.convert.BigDecimalConverter.getAsObject(BigDecimalConverter.java:96)
        at org.primefaces.model.JpaLazyDataModel.convertToType(JpaLazyDataModel.java:326)
        at org.primefaces.model.JpaLazyDataModel.applyFilters(JpaLazyDataModel.java:163)
        at org.primefaces.model.JpaLazyDataModel.count(JpaLazyDataModel.java:120)
        at org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:509)
        at org.primefaces.component.datatable.feature.FilterFeature.encode(FilterFeature.java:135)
        at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:85)
```

### Expected behavior

I'm assuming we might want a little more graceful interaction here; using a normal DataTable bound to a collection, filtering a number columns with non-numeric values just filters out all records (no match) rather than failing.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

Arya

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Chrome latest

**Comment by FlipWarthog** [comment]
The workaround I'm currently using leverages `inputNumber` in a filter facet:
```xml
<f:facet name="filter">
   <p:inputNumber onkeypress="PF('tableWidgetVar').filter()" />
</f:facet>
```
