### ISSUE TITLE
java.lang.IllegalStateException: Could not find backup for factory javax.faces.context.PartialViewContextFactory

### ISSUE THREAD

**Issue by rabiter** [primefaces/primefaces#9364]
Hello,

We found this exception in a server log, it occurs from time to time. According to the stacktrace it always happens in PrimeFaces$Ajax.update(..). Do you have any idea what might cause it?

```
Caused by: java.lang.IllegalStateException: Could not find backup for factory javax.faces.context.PartialViewContextFactory. 
    at javax.faces.FactoryFinderInstance.notNullFactory(FactoryFinderInstance.java:532)
    at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:209)
    at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:279)
    at com.sun.faces.context.FacesContextImpl.getPartialViewContext(FacesContextImpl.java:171)
    at javax.faces.context.FacesContextWrapper.getPartialViewContext(FacesContextWrapper.java:381)
    at org.primefaces.PrimeFaces$Ajax.update(PrimeFaces.java:377)
    at com.my.company.presentation.core.view.jsf.FacesUtils.updateComponent(FacesUtils.java:528)
    at com.my.company.presentation.core.view.jsf.FacesUtils.updateComponent(FacesUtils.java:520)
    at com.my.company.presentation.core.view.jsf.menubar.ImaMenuBar.updateComponents(ImaMenuBar.java:124)
    at com.my.company.presentation.documentdetails.controller.DetailsManager.resetMenu(DetailsManager.java:1623)
    at com.my.company.presentation.documentdetails.controller.DetailsManager.resetPresentation(DetailsManager.java:1617)
    at com.my.company.presentation.documentdetails.controller.DetailsManager.eventFired(DetailsManager.java:1095)
    at com.my.company.business.common.entity.EventsMediator.fireEvent(EventsMediator.java:146)
    at com.my.company.business.common.entity.EventsMediator.fireEvent(EventsMediator.java:90)
    at com.my.company.business.common.entity.EventsMediator$Proxy$_$$_WeldClientProxy.fireEvent(Unknown Source)
    at com.my.company.cache.service.util.scopes.SessionSystemServiceBean.onSystemStateOutdated(SessionSystemServiceBean.java:39)
    at com.my.company.cache.service.util.AbstractSystemServiceBean.lambda$new$0(AbstractSystemServiceBean.java:38)
    at com.my.company.cache.service.util.SystemStateHolder.checkSystemState(SystemStateHolder.java:48)
    at com.my.company.cache.service.util.AbstractSystemServiceBean.checkSystemState(AbstractSystemServiceBean.java:43)
    at com.my.company.cache.service.util.scopes.SessionSystemServiceBean$Proxy$_$$_WeldClientProxy.checkSystemState(Unknown Source)
    at com.my.company.cache.service.SystemStateService.checkSystemState(SystemStateService.java:25)
    at sun.reflect.GeneratedMethodAccessor438.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
    at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79)
    at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89)
    at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102)
    at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
    at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:254)
```

Thank you!

### PrimeFaces edition

Community

### PrimeFaces version

8.0.7

### JSF implementation

Mojarra

### JSF version

2.3.9

### Java version

unknown

**Comment by melloware** [comment]
Please  provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

It looks like you are using Mojarra 2.3.9 which is quite old have you tried 2.3.18?

**Comment by melloware** [comment]
I did find this: https://stackoverflow.com/questions/31187989/wildfly-8-seam2-redirect-javax-faces-context-partialviewcontextfactory

**Comment by Rapster** [comment]
Yup, after reading it, maybe this can help: https://www.beyondjava.net/modify-jsf-library-load-order (must be due to your environnement)

FYI, I can see in omnifaces "ordering after others" is used

**Comment by melloware** [comment]
Going to close for now until we can get a reproducer.

**Comment by rabiter** [comment]
> I did find this: https://stackoverflow.com/questions/31187989/wildfly-8-seam2-redirect-javax-faces-context-partialviewcontextfactory

Thank you! This is very likely exactly the case we have faced with.

**Comment by rabiter** [comment]
> Maybe this can help: https://www.beyondjava.net/modify-jsf-library-load-order
> 
> FYI, I can see in omnifaces "ordering after others" is used

Thank you for a hint!
