### ISSUE TITLE
DataTable with <p:columns> : EL still evaluated despite rendered="false"

### ISSUE THREAD

**Issue by tomtomlehero** [primefaces/primefaces#9474]
### Describe the bug

Hello,

With Primefaces 12.0.0, I have the following issue with dataTable:

The view code is :

```
  <h:panelGroup rendered="#{controler.rendered}">

    <p:dataTable value="#{controler.countries}" var="row">
      <p:columns var="columnHeader" value="#{controler.columns}">
        <f:facet name="header">
          <h:outputText value="#{columnHeader}" />
        </f:facet>
        <h:outputText value="#{row}" />
      </p:columns>
    </p:dataTable>

  </h:panelGroup>

```

The controller code is :

```
  public boolean isRendered() {
    return false;
  }

  public List<String> getCountries() {
    return Arrays.asList("Argentina", "Australia", "Brazil", "Canada", "Germany", "France", "India", "Italy", "Japan", "Russia", "Spain",
        "United Kingdom");
  }

  public List<String> getColumns() {

    if (!isRendered()) {
      log.error("You should never read this");
    }
    return Arrays.asList("Countries");
  }

```

When displaying the view, I can read in the logs : "You should never read this".
To my understanding, none of the content of the outer panelGroup should be evaluated when the rendering is set to false.
In the real project, having the getColumns() method called when it should not leads to NullPointerException because of uninitialized variables.

Any idea how we could avoid getting the method called ?

Many thanks for your help.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

MyFaces

### JSF version

3.0

### Java version

11

**Comment by tandraschko** [comment]
i dont think we can fix it and AFAIR we already discussed something similar
we reset dynamic columns when saving state and this is not related if the component was rendered or not

`p:columns value` is something like a static model, whereas `value` of dataTable is more dynamic

**Comment by tomtomlehero** [comment]
To complete, I specify that : 
 - We reproduce with the PRO version 12.0.2.
 - With the former configuration of JSF 2.1 / Primefaces 8, it was not the case.

**Comment by melloware** [comment]
Can you provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project so we can debug?

**Comment by tomtomlehero** [comment]
Hello Melloware

Here's a fork of Primefaces-Test which reproduces the described behavior:
https://github.com/tomtomlehero/primefaces-test-9474

if you run and display the home page:
http://localhost:8080/primefaces-test/

you'll see the log : " You should never read this"
which shows that the code inside the outer PanelGroup is executed even though it's not rendered.

Thank you

**Comment by melloware** [comment]
Thank you!

**Comment by melloware** [comment]
@tandraschko is right here is the stack trace and it looks like its visit tree calling the save state.  I would think it would skip unrendered components on visit?

```
 at org.primefaces.test.TestView.getColumns(TestView.java:46)
        at org.primefaces.test.TestView$$OwbNormalScopeProxy0.getColumns(org/primefaces/test/TestView.java)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:91)
        at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
        at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
        at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:93)
        at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:356)
        at javax.faces.component.UIData.getValue(UIData.java:2229)
        at org.primefaces.component.api.UIData.getDataModel(UIData.java:634)
        at org.primefaces.component.api.UIData.setRowModel(UIData.java:425)
        at org.primefaces.component.api.UIData.setRowIndexWithoutRowStatePreserved(UIData.java:418)
        at org.primefaces.component.api.UIData.setRowIndex(UIData.java:478)
        at org.primefaces.component.api.ColumnAware.lambda$resetDynamicColumns$6(ColumnAware.java:374)
        at org.primefaces.component.api.ColumnAware.forEachColumn(ColumnAware.java:95)
        at org.primefaces.component.api.ColumnAware.forEachColumn(ColumnAware.java:55)
        at org.primefaces.component.api.ColumnAware.resetDynamicColumns(ColumnAware.java:372)
        at org.primefaces.component.datatable.DataTable.saveState(DataTable.java:1011)
        at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy$1.visit(DefaultFaceletsStateManagementStrategy.java:1056)
        at org.apache.myfaces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:140)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:715)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
        at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
        at javax.faces.component.UIForm.visitTree(UIForm.java:357)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
        at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
        at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
        at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.saveStateOnMapVisitTree(DefaultFaceletsStateManagementStrategy.java:981)
        at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.saveView(DefaultFaceletsStateManagementStrategy.java:769)
        at org.apache.myfaces.application.StateManagerImpl.saveView(StateManagerImpl.java:213)
        at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1975)
        at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:315)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
      
```

**Comment by melloware** [comment]
I think this is similar to BalusC answer here: https://github.com/eclipse-ee4j/mojarra/issues/5181

> Unfortunately, this is expected. The resetValues=true must also visit unrendered components.
> 
> Imagine a master-detail with dialog. Dialog is initially unrendered. Dialog contains input components. These input components could potentially hold old values from a previous attempt. These definitely also need to be resetted. Regardless of whether they are rendered or are in an ui:repeat.
> 
> If you have a bean with a potentially non-existing property which could potentially throw PropertyNotFoundException when rendered, then you'd better use `<c:if test="#{false}">` instead of `<x:someComponent rendered="#{false}">` to prevent it from ending in the component tree.

**Comment by melloware** [comment]
Unfortunately I don't think we can fix this.
