### ISSUE TITLE
Jakarta: master build throws NoClassDefFoundError at startup

### ISSUE THREAD

**Issue by schoeso** [primefaces/primefaces#9657]
### Describe the bug

Starting Wildfly 27 web app with primefaces-jakarta throws a NoClassDefFoundError for a **javax** class. Seems that there is a wrong dependency,

`Cause: Class 'org.primefaces.component.accordionpanel.AccordionPanelRenderer' is missing a runtime dependency: java.lang.NoClassDefFoundError: javax/el/PropertyNotFoundException

2023-01-13 08:28:49,620 ERROR [stderr] (ServerService Thread Pool -- 109) 	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:246)

2023-01-13 08:28:49,620 ERROR [stderr] (ServerService Thread Pool -- 109) 	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:191)

2023-01-13 08:28:49,621 ERROR [stderr] (ServerService Thread Pool -- 109) 	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.config.processor.RenderKitConfigProcessor.addRenderers(RenderKitConfigProcessor.java:285)

2023-01-13 08:28:49,621 ERROR [stderr] (ServerService Thread Pool -- 109) 	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.config.processor.RenderKitConfigProcessor.process(RenderKitConfigProcessor.java:162)

2023-01-13 08:28:49,621 ERROR [stderr] (ServerService Thread Pool -- 109) 	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.config.ConfigManager.lambda$initialize$1(ConfigManager.java:295)

2023-01-13 08:28:49,621 ERROR [stderr] (ServerService Thread Pool -- 109) 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)

2023-01-13 08:28:49,621 ERROR [stderr] (ServerService Thread Pool -- 109) 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
...
2023-01-13 08:28:49,623 ERROR [stderr] (ServerService Thread Pool -- 109) Caused by: java.lang.NoClassDefFoundError: javax/el/PropertyNotFoundException

2023-01-13 08:28:49,623 ERROR [stderr] (ServerService Thread Pool -- 109) 	at java.base/java.lang.Class.forName0(Native Method)

2023-01-13 08:28:49,623 ERROR [stderr] (ServerService Thread Pool -- 109) 	at java.base/java.lang.Class.forName(Class.java:467)
...
`

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by tandraschko** [comment]
yeah
it seems if you unpack primefaces-13.0.0-SNAPSHOT-jakarta.jar and scan "javax" in .classes, its somehow not shaded
would be great if anyone could dig into

**Comment by tandraschko** [comment]
seems like only javax.el and javax.persistene is affected

**Comment by melloware** [comment]
Hmm is 12.0.0 affected?  If not it's probably some maven plug-in update in 13.0?

**Comment by melloware** [comment]
I don't know if JD-GUI decompiler is showing me the right thing but the 12.0.0 Community JAR seems to have tons of `javax` classes and not `jakarta`?    I am hoping its just JDGUI showing it to me wrong.

**Comment by tandraschko** [comment]
i just did it via notepad++ and search files
you also see some stuff like javax.xml but that doesnt matter

seems like javax.faces and others are shaded correclty, just persistence and el not

**Comment by tandraschko** [comment]
i wonder if we could add some basic integration tests for jakarta?
just a simple view, datatable, some inputs

So that the startup is tested and some basic features

**Comment by melloware** [comment]
OK I am working on a fix.   But I think and IT of some sort would be good.

**Comment by melloware** [comment]
OK got to the bottom of it and ran over and over and used Notepad++ and now I only see the `javax.xml` as the only one left.  Letting the build run now.

I had to do the following:

1. For some reason sorting the imports fixed the `javax.el` issue  I have no idea why other than a bug in the Transformer.
2. I had to make `javax.validation` string a class.getPackage read because it was used in so many constants it would replace one constant but not anything that the constant was appended to.  It was easier to just use the class.getPackage().

**Comment by melloware** [comment]
@schoeso can you pull `master` and try again with my latest changes?

**Comment by tandraschko** [comment]
seems like still the same for me
  G %jakarta/faces/application/Application I getExpressionFactory ()Ljavax/el/ExpressionFactory; K L

**Comment by melloware** [comment]
hmm

**Comment by melloware** [comment]
When I run the build and then extract the Jakarta JAR I search all classes for `javax`

![image](https://user-images.githubusercontent.com/4399574/212393398-a80618c9-a0a9-4e00-bf0b-5132e9f7f611.png)

BarcodeHandler - has javax.xml so that is OK
PrimeEnvironment - OK its finding the javax string for detecting JSF22
JsonObject - I can't tell but it doesn't look to be anything.

**Comment by melloware** [comment]
Ahhh I have to search for `javax` not `javax.`

**Comment by melloware** [comment]
OK well in its current state its down to two classes not being updated JpaLazyDataModel and PrimeApplicationContext.

**Comment by melloware** [comment]
I opened a ticket here: https://github.com/yupiik/maven-shade-transformers/issues/8

**Comment by melloware** [comment]
OK @schoeso can you try again.  I think everything is actually shading correctly now?  When I decompile the code all I see are Jakarta package spaces.

**Comment by schoeso** [comment]
@melloware  Hi, yes it works fine. Great!
