### ISSUE TITLE
BeanValidation Transformation: ignore disabled inputs

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#9708]
### Description

Right now, Bean Validation contraints are checked also for disabled and readonly inputs. It's a waste of CPU time (and, in my app, DB calls).

### Describe the solution you would like

Either:

- skip disabled/readonly inputs by default (in BeanValidationInputMetadataTransformer), or
- add a context param to control the behavior

### Additional context

I can work on this, just let me know which road should I take.

**Comment by tandraschko** [comment]
i dont understand why there are DB calls for disabled inputs?

**Comment by melloware** [comment]
@NicolaIsotta I would start out with a  [PrimeFaces Test](https://github.com/primefaces/primefaces-test) reproducer so we can see the problem.  right now I agree with @tandraschko I don't quite understand where the performance bottleneck is to help.    once I see the problem maybe I can offer some suggestions how to possible fix!

**Comment by NicolaIsotta** [comment]
Here's an idea of why I noticed this; in some pages, I use inputText for output only this way:
```xhtml
<p:inputText disabled="true" value="#{myBean.calculate('someParam')"/>
```
And the value of the input comes from the db, a web service call  or some other expensive operation:
```java
public String calculate(String param) {
    String value = doSomeHeavyCalculation(param);
    System.out.println("Did some heavy calculation");
    return value;
}
```
and, in some cases, the result of `doSomeHeavyCalculation` cannot be cached.
In these cases, if primefaces.TRANSFORM_METADATA is enabled, I'll find doubled log strings in tmy logs, because BeanValidationInputMetadataTransformer calls the method to check for constraints, even if the input is disabled or readonly.

**Comment by jepsar** [comment]
Why do you use an input text for that?

**Comment by tandraschko** [comment]
can you post a screen of your debugger how the transformer calls #calculate?

**Comment by jepsar** [comment]
Why not do a bit of styling on a span?

**Comment by NicolaIsotta** [comment]
> can you post a screen of your debugger how the transformer calls #calculate?
<details><summary>here it is</summary>
<tt>at it.emmeduei.chTell.util.Decodifiche.decodificaCliente(Decodifiche.java:214)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at jakarta.el.BeanELResolver.invoke(BeanELResolver.java:165)
at jakarta.el.CompositeELResolver.invoke(CompositeELResolver.java:79)
at org.primefaces.el.InterceptingResolver.invoke(InterceptingResolver.java:93)
at org.apache.el.parser.AstValue.getValue(AstValue.java:159)
at org.apache.el.parser.AstDeferredExpression.getValue(AstDeferredExpression.java:42)
at org.apache.el.parser.AstCompositeExpression.getValue(AstCompositeExpression.java:48)
at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
at org.primefaces.el.ValueExpressionAnalyzer.intercept(ValueExpressionAnalyzer.java:144)
at org.primefaces.el.ValueExpressionAnalyzer.toValueReference(ValueExpressionAnalyzer.java:154)
at org.primefaces.el.ValueExpressionAnalyzer.getReference(ValueExpressionAnalyzer.java:51)
at org.primefaces.el.ValueExpressionAnalyzer.getReference(ValueExpressionAnalyzer.java:40)
at org.primefaces.metadata.BeanValidationMetadataExtractor.extractPropertyDescriptor(BeanValidationMetadataExtractor.java:79)
at org.primefaces.metadata.BeanValidationMetadataExtractor.extractConstraintDescriptors(BeanValidationMetadataExtractor.java:66)
at org.primefaces.metadata.BeanValidationMetadataExtractor.extractDefaultConstraintDescriptors(BeanValidationMetadataExtractor.java:60)
at org.primefaces.metadata.transformer.impl.BeanValidationInputMetadataTransformer.transformInput(BeanValidationInputMetadataTransformer.java:67)
at org.primefaces.metadata.transformer.AbstractInputMetadataTransformer.transform(AbstractInputMetadataTransformer.java:43)
at org.primefaces.metadata.transformer.MetadataTransformerExecutor.execute(MetadataTransformerExecutor.java:72)
at org.primefaces.metadata.transformer.MetadataTransformerExecutor.processEvent(MetadataTransformerExecutor.java:52)
at jakarta.faces.event.SystemEvent.processListener(SystemEvent.java:124)
at jakarta.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:109)
at com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:243)
at com.sun.faces.application.applicationimpl.Events.invokeListenersFor(Events.java:222)
at com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:108)
at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:118)
at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:110)
at jakarta.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:660)
at jakarta.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:660)
at jakarta.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:660)
at jakarta.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:525)
at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1432)
at jakarta.faces.render.Renderer.encodeChildren(Renderer.java:146)
at jakarta.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:557)
at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1435)
at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1438)
at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1438)
at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:162)
at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:151)
at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
at ch.jsoft.ebanking.filter.AuthFilter.doFilter(AuthFilter.java:62)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
at ch.jsoft.ebanking.filter.LogUserNameFilter.doFilter(LogUserNameFilter.java:32)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:118)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessToExtension(FacesViewsForwardingFilter.java:187)
at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:144)
at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:130)
at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:86)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:834)
</tt>
</details>

**Comment by NicolaIsotta** [comment]
> Why not do a bit of styling on a span?
> 
> ```
> <span class="ui-inputfield ui-inputtext ui-widget ui-corner-all ui-state-disabled">YOUR TEXT</span>
> ```
> 
> .. and add a class to style it with `display: inline-block`

I already fixed this on my side by overriding BeanValidationInputMetadataTransformer. I just wanted to share this possible enhancement with the community.

My idea was adding a context param to make the transformer work like `p:outputLabel` with `indicateRequired="autoSkipDisabled"`
https://github.com/primefaces/primefaces/blob/d88bad27876ccca963fbc6a7a857b92f30355d4b/primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java#L122-L130

**Comment by tandraschko** [comment]
Yeah
We can always skip static disabled Inputs (disabled=true, but not disabled=someEL)

**Comment by melloware** [comment]
@NicolaIsotta can you submit a PR please for us to review?

**Comment by NicolaIsotta** [comment]
> @NicolaIsotta can you submit a PR please for us to review?

Will do.
