### ISSUE TITLE
JpaLazyDataModel: Regression Issue for #9320

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#9756]
### Describe the bug

#9320 was fixed in 12.0.1, after updating to 12.0.3 the issue is back. I believe the refactoring to fix #9594 removed the original fix.

### Reproducer

Reproducers attached to original issues.

### Expected behavior

See original issues.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.3

### Theme

All

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Chrome latest

**Comment by FlipWarthog** [comment]
Note: the invalid behavior is the same as before the original issue was fixed, but the exception itself is different: NumberFormatException (now) vs. ConverterException (before).

**Comment by FlipWarthog** [comment]
@tandraschko Confirmed your fix; I see the INFO log and the exception is no longer bubbled up.

LOG:
```
INFO: Could not convert 'abc' to class java.lang.Long via org.primefaces.convert.LongConverter
javax.faces.convert.ConverterException: frmTest:tblJpa: 'abc' must be a number consisting of one or more digits.
        at javax.faces.convert.LongConverter.getAsObject(LongConverter.java:95)
        at org.primefaces.model.JpaLazyDataModel.convertToType(JpaLazyDataModel.java:390)
```
