### ISSUE TITLE
ComponentTraversalUtils: Revised code break when primefaces extensions are used

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#9843]
### Describe the bug

dear @Rapster this PR 

https://github.com/primefaces/primefaces/pull/9779

breaks my application. After this PR, i am getting the following error:

```
java.lang.NoSuchMethodError: org.primefaces.util.ComponentTraversalUtils.closestForm(Ljavax/faces/context/FacesContext;Ljavax/faces/component/UIComponent;)Ljavax/faces/component/UIForm;
	at org.primefaces.extensions.component.timer.TimerRenderer.encodeScript(TimerRenderer.java:94)
	at org.primefaces.extensions.component.timer.TimerRenderer.encodeEnd(TimerRenderer.java:75)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:286)
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:152)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278)
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278)
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:151)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
```

It looks like that your revisions affect some primefaces extensions, namely at least the timer.
This error goes back to your change of the method

ComponentTraversalUtils.closestForm

where the argument context was dropped.

Would be great if you could do the needed adaptations also in the affected PF extensions code.

Many thanks in advance.

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
Yep this API is what is used in PFE: `final UIForm form = ComponentTraversalUtils.closestForm(context, timer);`

It looks like @Rapster refactoredit as `context` was not needed but you are using PFE 12 with PF 13 which is never gauranteed to work.  the PFE and PF versions stay in sync for compatability.
