### ISSUE TITLE
Datepicker: ClassCastException when using a converter

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#9889]
### Describe the bug

The issue happens when:

- the value is not a Date but something else (eg. an Integer) and an appropriate converter is defined
- an invalid value is submitted

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10932589/primefaces-test.zip)

1. `mvn install`
2. `mvn jetty:run`
3. navigate to http://localhost:8080/primefaces-test/test.xhtml
4. change something in the datepicker to make it invalid (eg replace a number with a letter)
5. click the button

Result:
```
java.lang.ClassCastException: class java.time.LocalDate cannot be cast to class java.util.Optional (java.time.LocalDate and java.util.Optional are in module java.base of loader 'bootstrap')
    at org.primefaces.test.OptionalConverter.getAsString(OptionalConverter.java:16)
    at org.primefaces.util.CalendarUtils.getValue(CalendarUtils.java:290)
    at org.primefaces.util.CalendarUtils.getValueAsString(CalendarUtils.java:281)
    at org.primefaces.util.CalendarUtils.getValueAsString(CalendarUtils.java:248)
    at org.primefaces.component.datepicker.DatePickerRenderer.encodeScript(DatePickerRenderer.java:167)
    at org.primefaces.component.calendar.BaseCalendarRenderer.encodeEnd(BaseCalendarRenderer.java:87)
    at org.primefaces.component.datepicker.DatePickerRenderer.encodeEnd(DatePickerRenderer.java:92)
    ...
```

### Expected behavior

No exception

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

Eclipse Adoptium jdk-11.0.17.8-hotspot

**Comment by NicolaIsotta** [comment]
I think I found the reason (getValueAsString/getValue methods in CalendarUtils should have the possibility to ignore the converter). I will work on a PR tomorrow.
