### ISSUE TITLE
DataTable: LazyDataModel not working with SelectionMode single on PF12

### ISSUE THREAD

**Issue by ron-hoppe** [primefaces/primefaces#9893]
### Describe the bug

I am facing a issue when trying to use a lazy DataTable together with single selection in PF12.0.

     java.lang.IllegalArgumentException: DataTable 'form:LAUFTable' is configured for single selection while multiple rows have been selected
        at org.primefaces.component.datatable.feature.SelectionFeature.decodeSingleSelection(SelectionFeature.java:131)
        at org.primefaces.component.datatable.feature.SelectionFeature.decodeSelection(SelectionFeature.java:91)
        at org.primefaces.component.datatable.feature.SelectionFeature.decode(SelectionFeature.java:74)
        at org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:71)
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
        at org.primefaces.component.api.UIData.processDecodes(UIData.java:140)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:715)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIForm.visitTree(UIForm.java:355)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1008)
        at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:55)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at applicationbeans.ClickjackingPreventionFilter.doFilter(ClickjackingPreventionFilter.java:31)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:167)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:201)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)
]]

### Reproducer

This is my Implementation of the LazyDataModel:

    public class LazyModel_LAUF_KOPF extends LazyDataModel<LAUF_KOPF> implements Serializable {
    private ModelOracleDB model;
    List<LAUF_KOPF> datasource;
   
    public LazyModel_LAUF_KOPF(ModelOracleDB model){
        this.model= model;
        datasource= this.model.list_LAUF_KOPF();
    }
    
    @Override
    public LAUF_KOPF getRowData(String rowKey) {
        if(rowKey != null){
            for(LAUF_KOPF lauf : datasource) {
                if(lauf.getId().toString().equals(rowKey))
                    return lauf;
            }
        }
        return null;
    }
 
    @Override
    public String getRowKey(LAUF_KOPF lauf) {
        return lauf.getId().toString();
    }
    
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return (int) datasource.stream()
                .filter(o -> filter(FacesContext.getCurrentInstance(), filterBy.values(), o))
                .count();
    }

    @Override
    public List<LAUF_KOPF> load(int offset, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {
        // apply offset & filters
        List<LAUF_KOPF> workschedule= datasource.stream()
                .filter(o -> filter(FacesContext.getCurrentInstance(), filterBy.values(), o))
                .collect(Collectors.toList());

        // sort
        List<Comparator<LAUF_KOPF>> comparators = new ArrayList<>();
        if (!sortBy.isEmpty()) {
            comparators = sortBy.values().stream()
                    .map(o -> new LazySorter_LAUF_KOPF(o.getField(), o.getOrder()))
                    .collect(Collectors.toList());
        }else{
            comparators.add(new LazySorter_LAUF_KOPF("id.DATUM_ANLEGE", SortOrder.DESCENDING));
        }
        Comparator<LAUF_KOPF> cp = ComparatorUtils.chainedComparator(comparators); // from apache
        workschedule.sort(cp);
        List<LAUF_KOPF> data =workschedule.stream().skip(offset).limit(pageSize).collect(Collectors.toList());
        return data;
    }
    }

On the JSF Side the p:datatable is implemented like this:

     <p:dataTable var="item" 
                         value="#{OperationCardView.lazymodel}" 
                         paginator="true" 
                         rows="5"
                         paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport}{NextPageLink} {LastPageLink}"
                         rowsPerPageTemplate="5,10,15" 
                         selectionMode="single" 
                         id="LAUFTable"
                         widgetVar="Wtable"
                         selection="#{OperationCardView.LAUF_KOPF}"
                         lazy="true">

The corresponding bean looks like the following:

    @Named("OperationCardView")
    @SessionScoped
    public class OperationCardView implements Serializable {
       private static final long serialVersionUID = 1L;

       private LazyDataModel<LAUF_KOPF> lazymodel;
       private LAUF_KOPF LAUF_KOPF=null;
    
       @PostConstruct
       public void initialize() {
           this.lazymodel = new LazyModel_LAUF_KOPF(model);
       }
    
       public LazyDataModel<LAUF_KOPF> getLazymodel() {
           return this.lazymodel;
       }
    
       public LAUF_KOPF getLAUF_KOPF(){
           return LAUF_KOPF;
       }

       public void setLAUF_KOPF(LAUF_KOPF LAUF_KOPF) {
           this.LAUF_KOPF = LAUF_KOPF;
       }

### Expected behavior

I would expect that a single Row can be selected without the error and is saved into #{OperationCardView.LAUF_KOPF}

### PrimeFaces edition

Community

### PrimeFaces version

12.0

### Theme

sam

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by tandraschko** [comment]
does it work on 13.0-SNAPSHOT and did you check the migration guide?

**Comment by ron-hoppe** [comment]
I looked into the migration guide on this link:
https://primefaces.github.io/primefaces/10_0_0/#/../migrationguide/13_0_0

It does not mention any changes on the dataTable component, so I did not try the 13.0-SNAPSHOT.

**Comment by ron-hoppe** [comment]
Is there any workaround? 

From what I could research so far the error originates from this peace of code in the SelectionFeature class:

    @Override
    public void decode(FacesContext context, DataTable table) {
        String clientId = table.getClientId(context);
        Map params = context.getExternalContext().getRequestParameterMap();
        Object originalValue = table.getValue();
        boolean isFiltered = table.isFilteringCurrentlyActive();

        String selection = params.get(clientId + "_selection");
        Set rowKeys = Collections.emptySet();

        if (LangUtils.isNotBlank(selection)) {
            rowKeys = LangUtils.newLinkedHashSet(selection.split(","));
        }

        if (isFiltered) {
            table.setValue(null);
        }

        decodeSelection(context, table, rowKeys);

        if (isFiltered) {
            table.setValue(originalValue);
        }

        if (table.isMultiViewState()) {
            DataTableState ts = table.getMultiViewState(true);
            ts.setSelectedRowKeys(table.getSelectedRowKeys());
        }
    }

    public void decodeSelection(FacesContext context, DataTable table, Set rowKeys) {
        table.setSelection(null);
        table.setSelectedRowKeys(null);

        if (table.isSingleSelectionMode()) {
            if (rowKeys.size() > 1) {
                throw new IllegalArgumentException("DataTable '" + table.getClientId(context)
                        + "' is configured for single selection while multiple rows have been selected");
            }

            if (!rowKeys.isEmpty()) {
                decodeSingleSelection(context, table, rowKeys.iterator().next());
            }
        }
        else {
            decodeMultipleSelection(context, table, rowKeys);
        }
    }

The "decode" method passes a Set to the "decodeSelection" method containing more than one entry. Therefore the error is thrown. The Set is filled in the first place with the RequestParameterMap which contains to many items of the structure (clientId + "_selection"). Maybe there is a way to reduce the map in order to have only one entry and therefore avoid having this error.

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by ron-hoppe** [comment]
I implemented the problem in the PrimeFaces Test project. I could not reproduce the error in this project. It musst have something to do with the setup of my project. My pom looks very different to the one of the test project, so I will try to find the answer there

**Comment by tandraschko** [comment]
then we will close it for now

**Comment by ron-hoppe** [comment]
Finally I could solve the problem. I tried Primefaces 10 and 11 and both had the same error. The error occured only on my project though, while the test project keeped working. After spending about 20 hours on this issue I found out, that the reason was the object Type my LazyDataModel<ObjectType> was managing. Whenever I managed Objects with the Annotation @Entity containing a @EmbeddedId I implemented the methods getRowData and get getRowKey like this:

    @Override
    public ORDER getRowData(String rowKey) {
        for(ORDER order: datasource){
            if(order.getId().toString().equals(rowKey)){
                return order;
            }
        }
        return null;
    }

    @Override
    public String getRowKey(ORDER order) {
        return order.getId().toString();
    }

This way the selection would not work and would throw the error message described in the beginning.
As a workaround I changed the methods like the following:

    @Override
    public ORDER getRowData(String rowKey) {
        for(ORDER order: datasource){
            if(order.getObjectID().equals(rowKey)){
                return order;
            }
        }
        return null;
    }

    @Override
    public String getRowKey(ORDER order) {
        return order.getObjectID();
    }

With ObjectID defined as a part of the Entity like the following:

     public class ORDER implements Serializable {
         private static final long serialVersionUID = 1L;

         @EmbeddedId ORDER_ID id;

         @Transient
         private String ObjectID;

         public String getObjectID() {
             return id.YEAR+id.NUMBER;
         }
    }

The reason this issue did not appear in the test project was that I just did not try to reproduce the issue this a entity containing a EmbeddedId. I just used objects of a simple class.
